### ISSUE TITLE
Declarative Base, Mapped vs mapped_column, inconsistent nullable default values. 

### ISSUE THREAD

**Issue by thomas-brandstaetter** [sqlalchemy/sqlalchemy#10085]
### Describe the bug

A column typed with `Mapped` defaults to `nullable=False` which is not consistent with the SQL-Standard. The Standard-SQL behaviour is only achieved, when type-hints are omitted.  

Attached code results to following output

    python tests/playground/sa_test.py
    tests/playground/sa_test.py:55 <module>
        insp_class.columns: <ColumnCollection({
            'tid': Column('tid', Integer(), table=<test>, primary_key=True, nullable=False),
            'b': Column('b', Integer(), table=<test>),
            'a': Column('a', Integer(), table=<test>, nullable=False),
            'c': Column('c', Integer(), table=<test>, nullable=False),
        })> (ColumnCollection) len=4

As you can see only column test.b is correctly defined. 

[sa_test.py.zip](https://github.com/sqlalchemy/sqlalchemy/files/12002529/sa_test.py.zip)

### SQLAlchemy Version in Use

2.0.18

### DBAPI (i.e. the database driver)

psycopg

### Database Vendor and Major Version

PostgreSQL 15.3

### Python Version

3.11.4

### Operating system

macOS 13.4.1 

### To Reproduce

```python
from sqlalchemy import create_engine, Integer, text, inspect
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, sessionmaker

sql_create = """
CREATE TABLE IF NOT EXISTS test (
tid SERIAL PRIMARY KEY,
a INTEGER,
b INTEGER,
c INTEGER
);
"""

DATABASE_SCHEME = "postgresql"
DATABASE_DRIVER = "psycopg"
DATABASE_HOST = "xxx"
DATABASE_USER = "xxx"
DATABASE_PORT = "xxx"
DATABASE_DB = "xxx"

SQLALCHEMY_DATABASE_URI = f'{DATABASE_SCHEME}+{DATABASE_DRIVER}://{DATABASE_USER}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_DB}'  # noqa

engine = create_engine(SQLALCHEMY_DATABASE_URI)
Session = sessionmaker(bind=engine)


class ModelBase(DeclarativeBase):
    pass


class Test(ModelBase):
    __tablename__ = 'test'

    tid = mapped_column(Integer, primary_key=True, autoincrement=True)
    a: Mapped[int]
    b = mapped_column(Integer)
    c: Mapped[int] = mapped_column(Integer)


with Session() as session:
    session.execute(text(sql_create))
    session.commit()


new_test = Test()
with Session() as session:
    session.add(new_test)
    session.commit()


insp_class = inspect(Test)

from devtools import debug as dbg

dbg(insp_class.columns)
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
``` 

### Additional context

python tests/playground/sa_test.py
tests/playground/sa_test.py:55 <module>
    insp_class.columns: <ColumnCollection({
        'tid': Column('tid', Integer(), table=<test>, primary_key=True, nullable=False),
        'b': Column('b', Integer(), table=<test>),
        'a': Column('a', Integer(), table=<test>, nullable=False),
        'c': Column('c', Integer(), table=<test>, nullable=False),
    })> (ColumnCollection) len=4

**Comment by zzzeek** [comment]
hi there -


`A column typed with Mapped defaults to nullable=False which is not consistent with the SQL-Standard.`

This is by design and the behavior of `Mapped[str]` defaulting to nullable=False is [documented here](https://docs.sqlalchemy.org/en/20/orm/declarative_tables.html#mapped-column-derives-the-datatype-and-nullability-from-the-mapped-annotation).   

I dont understand what the advantage to nullable would be if you have a mapping like:

```py
class Thing:
   col: Mapped[int]
```

if "col" were nullable, then `col` could be None and the above type annotation is wrong.


I don't understand the citing of the "SQL standard", the SQL standard does not concern object relational mapping tools.

Note I don't download and run zip files (dont know what `devtools` is either) so if there's some more elaborate issue happening let me know.
