### ISSUE TITLE
Make greenlet optional

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10197]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/10194

this is a new version of #6136, for 2.1.

we can lose the very complicated string of Python version information in setup.cfg and leave installation of greenlet up to using the `pip install sqlalchemy[asyncio]` target.   importing `sqlalchemy.ext.asyncio` without greenlet installed should have a very informative error that includes this target in the message and a link to errors.rst.

**Comment by zzzeek** [comment]
cc @CaselIT

**Comment by CaselIT** [comment]
Makes sense.

**Comment by CaselIT** [comment]
given that https://github.com/python-greenlet/greenlet/issues/350 is fixed are we still go on this?

**Comment by zzzeek** [comment]
deifnitely, because people building out container images etc. dont always want greenlet present

**Comment by andersk** [comment]
Another reason we want greenlet to be optional is that it crashes uWSGI just by existing: https://github.com/python-greenlet/greenlet/issues/330

That’s fixed in the current alpha release but not in stable. And anyway it’s pretty concerning to have a package installed that so invasively changes how Python works that such a bug is even possible, without its functionality being explicitly requested.

**Comment by zzzeek** [comment]
> Another reason we want greenlet to be optional is that it crashes uWSGI just by existing: [python-greenlet/greenlet#330](https://github.com/python-greenlet/greenlet/issues/330)

the repro cases there show it being imported, so if it werent imported, there shouldn't be a problem.  There are actually ways to make Python packages automatically set themselves up with .pth files but greenlet I dont think would be doing this.

**Comment by zzzeek** [comment]
> Another reason we want greenlet to be optional is that it crashes uWSGI just by existing: [python-greenlet/greenlet#330](https://github.com/python-greenlet/greenlet/issues/330)
> 
> That’s fixed in the current alpha release but not in stable. And anyway it’s pretty concerning to have a package installed that so invasively changes how Python works that such a bug is even possible, without its functionality being explicitly requested.

in fact uwsgi directly declares greenlet as a dependency: https://github.com/unbit/uwsgi/blob/21366abc98e8e15c4586d054a880587bee511d2f/setup.py#L123   which here follows from the gevent plugin at https://github.com/unbit/uwsgi/blob/master/buildconf/gevent.ini which follows from the "all" plugin at https://github.com/unbit/uwsgi/blob/master/buildconf/all.ini .

so greenlet is a first class, explicit but probably optional dependency of uwsgi

**Comment by andersk** [comment]
> in fact uwsgi directly declares greenlet as a dependency:

@zzzeek You’re looking at the unreleased 3.x branch of uWSGI. The stable branch declares [no dependencies](https://github.com/unbit/uwsgi/blob/uwsgi-2.0/setup.py).

> if it werent imported, there shouldn't be a problem

SQLAlchemy imports `greenlet` unconditionally in order to test whether it’s there.

https://github.com/sqlalchemy/sqlalchemy/blob/a52103c44f3989d53edf4c76abb92afd3ca724c9/lib/sqlalchemy/util/concurrency.py#L14-L22

**Comment by zzzeek** [comment]
> 
> SQLAlchemy imports `greenlet` unconditionally in order to test whether it’s there.
> 
> https://github.com/sqlalchemy/sqlalchemy/blob/a52103c44f3989d53edf4c76abb92afd3ca724c9/lib/sqlalchemy/util/concurrency.py#L14-L22

ahha!  *That* I do not like!   I will set a task to change this in 2.1.
