### ISSUE TITLE
Oracle async support

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10679]
Oracle has a new branch at https://github.com/oracle/python-oracledb/tree/asyncio-support using real non-blocking in their thin client.  we need to prototype against this to make sure we can work with what they are doing, and then prepare a real patch.

we can of course build off of the new `connectors/asyncio.py` and while we can start in the 2.1 branch, it should be backportable to 2.0 as we have the asyncio connector in 2.0 as well.

with this dialect we will then have asyncio support for 100% of our backends.

Issue with some more information: https://github.com/oracle/python-oracledb/issues/258

**Comment by CaselIT** [comment]
Nice. That was expected since the new python only thin mode was added.

This dialect can have the same behaviour of the psycopg one that includes both sync amd async version under the same name

From a quick look at some samples it's also similar to psycopg in api, meaning that's pep 249 but with asyncio

**Comment by CaselIT** [comment]
Hi @anthony-tuininga 

Just a couple of questions

Do you have a rough timeline for releasing the asyncio support in the normal oracledb releases?

Have you already done some work to add support for the async version in sqlalchemy or were you planning on working on it?

Thanks!

**Comment by anthony-tuininga** [comment]
@CaselIT, depending on feedback and testing results I'd like to release it this year yet -- initial feedback is positive so far! As for working on the async version in sqlalchemy, I am unfamiliar with the sqlalchemy codebase. I am certainly willing to assist whoever takes the lead on it, though!

**Comment by cjbj** [comment]
@CaselIT @zzzeek FYI we are thinking of doing the python-oracledb 2.0 release (with the asyncio support) in a couple of weeks.

**Comment by anthony-tuininga** [comment]
python-oracledb 2.0.0 was just released with asyncio support. Let us know if there are any changes that are needed to get this support into SQLAlchemy.

**Comment by zzzeek** [comment]
> python-oracledb 2.0.0 was just released with asyncio support. Let us know if there are any changes that are needed to get this support into SQLAlchemy.

OK, as you may have surmised, have not had a chance to try it, but I'm pretty confident it will work fine with SQLAlchemy as we can accommodate pretty much anything at this point.

**Comment by CaselIT** [comment]
I've started looking into it.
The error when thick mode is selected and async is used does not seem overly clear:
```py
import asyncio
import oracledb


async def run():
    conn = await oracledb.connect_async(
        user="scott", password="tiger", service_name="XEPDB1", host="127.0.0.1"
    )
    with conn.cursor() as cursor:
        await cursor.execute("select 42 from dual")
        print(await cursor.fetchall())

oracledb.init_oracle_client()
asyncio.run(run())
```
```
oracledb.exceptions.ProgrammingError: DPY-2019: python-oracledb thick mode cannot be used because a thin mode connection has already been created
```

**Comment by CaselIT** [comment]
@cjbj @anthony-tuininga sqlalchemy has a mutext on async driver to prevent concurrent execution.
From some quick test it seems that oracledb already has one interanlly, since the following is correctly serialized.

Am I correct?

```py
import asyncio
import time
import oracledb


async def run():
    conn = await oracledb.connect_async(
        user="scott", password="tiger", service_name="XEPDB1", host="127.0.0.1"
    )

    await conn.execute(
        """
CREATE OR REPLACE FUNCTION my_sleep(i NUMBER)
RETURN NUMBER IS
BEGIN
    DBMS_SESSION.sleep(i);
    RETURN i;
END;"""
    )
    s = time.time()
    print(
        await asyncio.gather(
            conn.fetchall("SELECT my_sleep(2) FROM dual"),
            conn.fetchall("SELECT my_sleep(4) FROM dual"),
            conn.fetchall("SELECT my_sleep(1) FROM dual"),
        )
    )
    e = time.time()
    print(e - s)

asyncio.run(run())
```

the above prints here 7.2 that's the sum of 3 sleeps

**Comment by CaselIT** [comment]
Another question. I noticed that the same function to read the LOBs can be used in both sync and asnyc https://github.com/sqlalchemy/sqlalchemy/blob/99da5ebab36da61b7bfa0b868f50974d6a4c4655/lib/sqlalchemy/dialects/oracle/cx_oracle.py#L816-L820 , since the `read()` co-routine is awaited by oracledb here https://github.com/oracle/python-oracledb/blob/9645d4f9b3fb196925ac364e6dec3ab953fca222/src/oracledb/impl/thin/messages.pyx#L1362-L1379

It this the best approach?

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Add oracledb_async driver support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5032

**Comment by CaselIT** [comment]
@zzzeek a first implementation should be finished.

My current thinking is that this could be released as part of the 2.0 series, with a limitation of not supporting server side cursors, meaning that everything works apart from `stream` and `strem_scalars`.

Since the oracle dialect currently has no support for server side cursor I think this change is too big for 2.0 and we can work on improving the dialect for 2.1 to fully support server side cursors.

What do you think?

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Add oracledb_async driver support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5081

**Comment by CaselIT** [comment]
The dialect was merged, but @anthony-tuininga it would be great if you could reply to these two question I had:
- https://github.com/sqlalchemy/sqlalchemy/issues/10679#issuecomment-1866975196
- https://github.com/sqlalchemy/sqlalchemy/issues/10679#issuecomment-1867041340

thanks!

**Comment by anthony-tuininga** [comment]
To answer the first question: yes, there is an internal mutex in the oracledb driver to prevent concurrent execution, so don't need one in SQLAlchemy.

To answer the second question: there is some overhead in having an async function go through the event loop and many converter functions don't require an await -- so it seemed reasonable to me to allow a converter function to be either a synchronous or asynchronous function and have the driver differentiate between them at runtime. If you have further comments I'd like to hear them!

**Comment by CaselIT** [comment]
Ok, thank you @anthony-tuininga .

One other thing I noticed is that a cursor supports the standard`with` protocol, not the `async with` one that seems common to other drivers.
It's not an problem for sqlalchemy, but maybe support for `async with` could be added for convenience?

**Comment by CaselIT** [comment]
>  I could certainly add the async with support as well if you think that would be advantageous?

as mentioned for sqlalchemy is the same, since for every async lib it uses a proxy cursor class that wraps the real one and that uses the `with` since from the api prospective is exactly the same as a pep 249 cursor.

I just mentioned it since oracledb async is the 7th (if I'm not forgetting some) async lib sqlalchemy supports and all 6 before did use `async with` for the cursors, so if interoperability with the other is an objective that may be useful.
Then again there is no pep 249 for async drivers so every one does things its own way.

Thanks for the support. The async oracledb is out in the 2.0.25 that was published yesterday on pypi

**Comment by anthony-tuininga** [comment]
You're welcome. And based on that information I'll go ahead and add the `async with` support even though it strictly speaking is not needed. Thanks for getting the async support for oracledb in SQLAlchemy!

**Comment by anthony-tuininga** [comment]
And this has now been [done](https://github.com/oracle/python-oracledb/commit/1c0ab31c30e82993dafd79de5d71f73a8ff1ad23).

**Comment by CaselIT** [comment]
great thanks!
