### ISSUE TITLE
MetaData.__init__() got an unexpected keyword argument 'bind' when trying to create DB 

### ISSUE THREAD

**Issue by badinplaid737** [sqlalchemy/sqlalchemy#10759]
### Describe the bug

Using Jupyter notebooks 7.0.6 iPython 8.15.0 I get error messages when with all codes that attempt to call sql magic functions with either %sql or %%sql upon trying to create a db in the same folder that the Jupyter notebook resides, and connect sql magic functions to that db I get the first error message that is indicated subsequent messages will reference $DATABASE_URL not set 

### SQLAlchemy Version in Use

2.0.12

### DBAPI (i.e. the database driver)

sqlite3

### Database Vendor and Major Version

SQLite

### Python Version

3.11.6

### Operating system

OSX 14.2

### To Reproduce

```python
con = sqlite3.connect('chatdata.db')
%load_ext sql
%sql sqlite:///chatdata.db
```

### Error

```
MetaData.__init__() got an unexpected keyword argument 'bind'
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])``` 

### Additional context

I have same issue with windows 11 x-64 also running Jupyter Notebooks 7.0.6 Python 3.6.11 and same version of ipython and get the same issue

**Comment by zzzeek** [comment]
hi -

the code shown is not SQLAlchemy code, that looks like sqilte3 driver code directly.

the stack trace is from SQLAlchemy and it's because [the MetaData object no longer accepts bind](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#implicit-and-connectionless-execution-bound-metadata-removed).  The code you have which is doing this is not shown in your message however you'd want to migrate  off this pattern.

if you need assistance with code please open a [discussion](https://github.com/sqlalchemy/sqlalchemy/discussions)
