### ISSUE TITLE
Method '_with_collation' is abstract in class 'TypeEngine' but is not overridden in child class

### ISSUE THREAD

**Issue by sbrunner** [sqlalchemy/sqlalchemy#11823]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

With user type defined like that:
```python
from sqlalchemy.types import UserDefinedType


class TsVector(UserDefinedType): 
    """A custom type for PostgreSQL's tsvector type."""

    cache_ok = True

    def get_col_spec(self) -> str:
        return "TSVECTOR"

    @property
    def python_type(self) -> type[Any]:
        return dict
```
I get the error:
`[abstract-method(pylint), TsVector] Method '_with_collation' is abstract in class 'TypeEngine' but is not overridden in child class 'TsVector'`

### To Reproduce

```python
I run mypy with prospector
```

### Error

```
[abstract-method(pylint), TsVector] Method '_with_collation' is abstract in class 'TypeEngine' but is not overridden in child class 'TsVector'
``` 

### Versions

- OS: Ubuntu 24.04
- Python: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
- SQLAlchemy: 2.0.32
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc):
prospector 1.10.3
mypy 1.10.0 (compiled: yes)
pylint 2.17.7
astroid 2.15.8

### Additional context

I think that this function
https://github.com/sqlalchemy/sqlalchemy/commit/35c178c405c44798810ceac540faf8385b4632c4#diff-11f1fd0f775da0862d27dad23b5f9a801df9ea8ade1b55fbd0e84bd888fe4f4dR758
Should not raise NotImplementedError because it interferes with type checking, or with `UserDefinedType` we should get an implementation of this method (not exhaustive :-) ).

**Comment by CaselIT** [comment]
Hi,

Sadly for some unfortunate reason the typing tool decided not implemented error = abstract.
The best solution is likely to use `if not TYPE_CHECKING` here

**Comment by zzzeek** [comment]
hi -

we support mypy and pyright for type checking, and this is not a typing error, this looks like another one of pylint's frivolous rules and I'd just disable this rule in pylint.

this passes mypy and pyright without issue

```py
from sqlalchemy.types import UserDefinedType
from typing import Any


class TsVector(UserDefinedType[dict[str, str]]):
    """A custom type for PostgreSQL's tsvector type."""

    cache_ok = True

    def get_col_spec(self) -> str:
        return "TSVECTOR"

    @property
    def python_type(self) -> type[Any]:
        return dict
```

**Comment by zzzeek** [comment]
> I think that this function
https://github.com/sqlalchemy/sqlalchemy/commit/35c178c405c44798810ceac540faf8385b4632c4#diff-11f1fd0f775da0862d27dad23b5f9a801df9ea8ade1b55fbd0e84bd888fe4f4dR758
Should not raise NotImplementedError because it interferes with type checking, or with UserDefinedType we should get an implementation of this method (not exhaustive :-) ).

There is no implementation of the method for UserDefinedType.  this is an optional method that is private.    The class is not even abstract.  pylint is wrong on many levels here

**Comment by CaselIT** [comment]
oh missed it was pylint.

**Comment by sbrunner** [comment]
@zzzeek Many thanks for your analyses, just one note

> There is no implementation of the method for UserDefinedType. this is an optional method that is private. The class is not even abstract. pylint is wrong on many levels here

When I read the Python documentation, https://docs.python.org/3/library/exceptions.html#NotImplementedError, I don't think that PyLint is so wrong, It's true that PyLint sees if the class or the method is abstract, but finally, it's strange to have a method on an object that only raise `NotImplementedError`.

That's it to share my personal impression, I will ignore this PyLint error, then relay no issue to me if you entirely ignore my comment :-)

CU and many thanks for this great lib :-)

**Comment by CaselIT** [comment]
I don't think `NotImplementedError` is used in that way in actual code.

Or at least the fact that a method raises it does should not require a subclass to overload it, that's what `abstractmethod` is for.

**Comment by zzzeek** [comment]
the doc's wording is, "abstract methods should raise this exception **when** they require derived classes to override the method".   it does not state anything about "when" being **compile time** or **runtime**.   We are using it as a **runtime** directive.    if someone wants compile time abstract methods, that's what [abc](https://docs.python.org/3/library/abc.html) is for.     

so in this case, "when" would not occur unless you happened to use this type in a collation expression.    This is in fact a more performant way of doing duck typing.   if the method were not present at all, then from a duck typing perspective, we would need to 1. check that the method is there using `hasattr()` 2. call the method if present or 3. raise an error at the caller level if hasattr returns false.  this is a silly way to do this when you are already in a controlled class hierarchy and can just have the method there, ready to let you know "not implemented!" if the class happens to be used in this particular context.    If we didn't use 1/2/3 above and just let the method not be present, then a. typing definitely **would** fail, because we're calling a method that doesnt exist on the TypeEngine class and b. the user will get an error "FooBar object has no attribute _with_collation", which provides much less context than a method that exists and just states "hey this class doesnt support this feature".

But put all of that aside and disagree with all of that, there is still the basic fact that pylint is assuming that `UserDefinedType` is abstract based on the presence of a method that raises `NotImplementedError`, but **is assuming that TsVector is not**.  How does it know that?     There's no requirement in abstract classes that a subclass of an abstract class can't also be abstract.

**Comment by sbrunner** [comment]
Thanks for the clear explain :-)
