### ISSUE TITLE
Add an officially supported query compilation function

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#2886]
**Migrated issue, originally created by Alex Grönholm ([@agronholm](https://github.com/agronholm))**

Often, when my queries are not accepted by the backend (ProgrammingError) I want to look at the generated SQL and tinker with it, executing it directly on the backend until I figure out what's wrong. Trouble is, when I print the query with str(query), it gives me the non-interpolated version of the query (ie. with the placeholders not filled in). Many people have been asking for a way to get a compiled version of the query, which could be copypasted directly to psql or whatever.

SQLACodegen also requires a method for compiling expressions, given a dialect.
I've used an adapted version of this: http://stackoverflow.com/a/5698357/242021
However, the 0.8.3 update broke it. One of my tests is now giving me:

    AttributeError: Neither 'Label' object nor 'Comparator' object has an attribute 'table'

That's one more reason why I'm requesting an official compiling method that won't break with micro version updates of SQLAlchemy.

**Comment by zzzeek** [comment]
I'm not sure what the problem is here.  What's wrong with:

   print (query.statement.compile(session.connection(), compile_kwargs={"literal_binds": True}))

?

that's the same as what you'd do with Core.    The recipe I have above is trying to make use of the Session that's in the Query for some more contextual information but that does not agree with my longer term plans for what we're doing with the `Query` object.     

the original request here, "does not break" is definitely suited by the above line, query.statement is not going away.

**Comment by zzzeek** [comment]
it's been documented at https://docs.sqlalchemy.org/en/latest/faq/sqlexpressions.html#how-do-i-render-sql-expressions-as-strings-possibly-with-bound-parameters-inlined for some time as well
