### ISSUE TITLE
Support for calling Stored Procedures (not functions)

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#2972]
**Migrated issue, originally created by Ronny Pfannschmidt ([@RonnyPfannschmidt](https://github.com/RonnyPfannschmidt))**

oracle stored procedures cant be invoked by a select, instead one must call them in a anonymous block

a way to either access those via the dbapi.callproc method or generating the fit sql would be nice

currently i work around by compiling to a block on oracle and a select on postgresql
i didnt examine other databases

**Comment by zzzeek** [comment]
just like #1635 , SQLAlchemy is of limited use for the case of calling stored procedures because these are just function calls, there's nothing "relational" going on and SQLAlchemy's expressiveness doesn't really apply.    stored procedure calls are again very database/DBAPI specific (out parameters, callproc(), multiple result sets) and the typical way to solve this problem for an app that is using them is to just use the raw cursor.     So again, a full blown stored procedure API that also comes along with multiple result set support would be great but I don't see it happening unless someone really wanted to make it happen.

**Comment by SuiOni** [comment]
I was following the discussion. 
I see that calling a stored procedure can be done easily with a direct access to the cursor.
My question would be if there is a possibility to define them similar to the rest of the model. 
So that e.g. alembic can auto generate them and has pissibly a DAG of in which order to create them?
Thanks a ton!

**Comment by zzzeek** [comment]
> I was following the discussion.
> I see that calling a stored procedure can be done easily with a direct access to the cursor.
> My question would be if there is a possibility to define them similar to the rest of the model.
> So that e.g. alembic can auto generate them and has pissibly a DAG of in which order to create them?
> Thanks a ton!

stored procedures for Alembic are an external affair.  check out https://github.com/olirice/alembic_utils which I believe supports this.
