### ISSUE TITLE
clarify server-side vs. client-side isolation level, as there's no way to retrieve the AUTOCOMMIT setting from a connection w/o using default

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3357]
**Migrated issue, originally created by Timothy Cardenas ([@trcarden](https://github.com/trcarden))**

Simply create a engine with isolation_level set to autocommit, connect, and compare the return value from get_isolation_level from the value returned from the psycopg2 connection. They do not match.

Example:

```
url='postgresql+psycopg2://me:pass@host/db'
engine = create_engine(
            url,
            encoding='utf8',
            pool_size=5,
            poolclass=QueuePool,
            isolation_level="AUTOCOMMIT"
        )

with engine.connect() as connection:
  print(connection.get_isolation_level())  # => READ COMMITED
  print(connection.connection.isolation_level)  # => 0 (psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)
```

**Comment by zzzeek** [comment]
so rereading this the only thing I can see that would be a worthy feature, but there is no demand for it, is the ability to set isolation levels while still in autocommit.   as you noted and also from so questions like https://stackoverflow.com/questions/24706867/whats-the-point-of-using-high-isolation-level-when-in-autocommit-mode , serializability is potentially important even with single statements.    this would indicate the need for a new isolation API feature as I'm not certain all DBAPIs support varied isolation level and autocommit at the same time.  I would propose this as either a series of composed isolation levels like "SERIALIZABLE_AUTOCOMMIT" or as a separate execution_option dbapi_autocommit=True.        

I will just add that as a separate issue as the focus of the issue here is  a bit confusing.  there are no plans to work on this unless there were some demand for it.
