### ISSUE TITLE
`icontains`, `istartswith`, `iendswith`

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3482]
**Migrated issue, originally created by jvanasco ([@jvanasco](https://github.com/jvanasco))**

discussed previously in 
* https://groups.google.com/forum/#!searchin/sqlalchemy/icontains/sqlalchemy/MUyt8zYaP0c/ht4fGR9q9w8J
* https://groups.google.com/forum/#!searchin/sqlalchemy/icontains/sqlalchemy/331XoToT4lk/RPjIYNTkSEIJ

I tried doing this myself, but don't know enough of the internals to get this done on my own.

it looks like these need to be modified

* sqlalchemy/sql/default_comparator.py
* sqlalchemy/sql/operators.py

but not sure about

* sqlalchemy/sql/compiler.py

there are probably more files.

if someone can get one working, I can do the rest and build out tests.

**Comment by dodoru** [comment]
in  SQLAlchemy==1.2.5,

`startswith` execute query `LIKE  %%`, so it has already been case-insensitive.

**Comment by zzzeek** [comment]
this depends on collation and database in use.   try it on Postgresql.

**Comment by matiasrebori** [comment]
@zzzeek @CaselIT i developed a naive solution of icontains, but im traying to understand how sqlalchemy works in order to make a correct solution, im unsing ilike as example, as i understand the flow goes this way, 
- the ilike method is found in operators.py `def ilike(self, other, escape=None):`
- it calls operate with ilike_op `return self.operate(ilike_op, other, escape=escape)`
- this is the part i dont understand, definition of ilike_op is
```python
@comparison_op
def ilike_op(a, b, escape=None):
    print('ilike_op')
    return a.ilike(b, escape=escape)
```
`return a.ilike(b, escape=escape)` it seems to be calling ilike method again and i lose the track of the calls here
- at some point it enters in the operate method and calls `_boolean_compare` found in default_comparator.py with an ilike operator as argument, i printed the argument from my console `op argument  = <function ilike_op at 0x000001E35DEFA050>
`
- then `_boolean_compare` calls and returns the `BinaryExpression` class that generates an SQL Statement

### My naive solution
my naive solution in the meantime is as follows in operators.py, but i want to understand the above so i can make a correct solution for icontains, and later add istartswith and iendswith
```python
    def icontains(self,other, escape=None):
        other = f'%{other}%'
        return self.operate(ilike_op, other, escape=escape)
```

**Comment by zzzeek** [comment]
consult the implementations in the compiler for visit_startswith_op_binary(), visit_not_startswith_op_binary(), visit_endswith_op_binary(), visit_not_endswith_op_binary() to see how the concatenations for those work.

**Comment by matiasrebori** [comment]
thanks, this helps a lot, with this i will be able to develop a solution.

**Comment by Nikita-Filonov** [comment]
`icontains` might be something like this?

```
func.lower(column).contains(value.lower())
```

I do not know what perfomance it will have

**Comment by CaselIT** [comment]
If a db backend supports ilike I'm guessing this will perform worse (unless the optimizer somehow understands the purpose and switches to ilike)

**Comment by sqla-tester** [comment]
**Matias Martinez Rebori** has proposed a fix for this issue in the **main** branch:

**icontains,istartswith,iendswith operators** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4068

**Comment by sqla-tester** [comment]
**Matias Martinez Rebori** has proposed a fix for this issue in the **main** branch:

**implement icontains, istartswith, iendswith operators** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4068
