### ISSUE TITLE
naming convention should not fire off on reflected constraints; Alembic will also need adjustment

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3818]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

per #3817, alembic has a brittle reliance on naming conventions being applied at reflection time.  We'd like to set up https://gerrit.sqlalchemy.org/#/c/209/ so that this isn't automatic but Alembic will also need to work around this.

**Comment by zzzeek** [comment]
so the change here is a big deal and it only applies to sqlite, for a case that is mostly going away and which has many ways to work around it.

Here's the test case that "fails":


```py
from sqlalchemy import *

m = MetaData()

q = Table(
    'q', m, Column('id', Integer, primary_key=True)
)
t = Table(
    't', m,
    Column('id', Integer, ForeignKey('q.id')),
    Column('x', Boolean(create_constraint=True))
)

e = create_engine("sqlite://", echo=True)

m.create_all(e)


print(inspect(e).get_check_constraints('t'))

m2 = MetaData(naming_convention={
    "ck": "%(constraint_name)s"})
t2 = Table('t', m2, autoload_with=e)
```

why is that?  because there's a naming convention for the CHECK constraint when we reflect it, which we do need to have in order to create a round trip for that convention.     But the question is, why is this constraint unnamed?   The DB was not created with a name for that constraint, and that's the issue, it should have been created this way:

```py
from sqlalchemy import *

m = MetaData(naming_convention={
    "ck": "%(constraint_name)s"})

q = Table(
    'q', m, Column('id', Integer, primary_key=True)
)
t = Table(
    't', m,
    Column('id', Integer, ForeignKey('q.id')),
    Column('x', Boolean(create_constraint=True, name='bb'))
)

e = create_engine("sqlite://", echo=True)

m.create_all(e)


print(inspect(e).get_check_constraints('t'))

m2 = MetaData(naming_convention={
    "ck": "%(constraint_name)s"})
t2 = Table('t', m2, autoload_with=e)



```

so that the CHECK constraint generated by the boolean is named.

Boolean and Enum don't generate this CHECK constraint by default anymore anyway, so this shouldn't really come up unless someone is really trying to roll with explicitly unnamed constraints, then trying to reflect it by adding in a naming convention.    changing the behavior would suggest some entirely different flow here and I think it's a lot of risk and complexity to get into it, the [docs](https://alembic.sqlalchemy.org/en/latest/naming.html) recommend having a naming convention up front.
