### ISSUE TITLE
descriptive error message when attempting to repurpose an instrumented attribute

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3858]
**Migrated issue, originally created by Mehdi GMIRA ([@mehdigmira](https://github.com/mehdigmira))**

Hey,

Here is the test case:

```python
from sqlalchemy import Column, DateTime, String, Integer, ForeignKey, func, Table, create_engine
from sqlalchemy.orm import relationship, backref, sessionmaker, joinedload, contains_eager
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
engine = create_engine('sqlite://', echo=False)


class Student(Base):
    __tablename__ = 'student'
    id = Column(Integer, primary_key=True)
    name = Column(String)


Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)
Session = sessionmaker(engine)
session = Session()


session.add(Student(name='foo'))

session.commit()


class Myclass(object):
    column = Student.name

    def test(self):
        print session.query(Student.id, Student.name).filter(self.__class__.column == 'foo').all()  # does not raise
        print session.query(Student.id, Student.name).filter(self.column == 'foo').all()  # raises error


my_class = Myclass()

my_class.test()
```

The error that is raised is: 

```python
AttributeError: 'Myclass' object has no attribute '_sa_instance_state'
```

**Comment by RamonWill** [comment]
Hi SQLAlchemy team,

I have looked into the above issue and have the below question

_Using the following [link](https://groups.google.com/forum/#!topic/sqlalchemy/P46hdGe8K6o) as reference:_ Is it reasonable and clearer to change the error message to "'Myclass' instance is not a mapped object in the database"? Since it would have to be an instance of a object or a descriptor for the database in the first place.

**My understanding of the issue from debugging the code**
After debugging the code i found that the error is raised by the following [line](https://github.com/sqlalchemy/sqlalchemy/blob/3dc9a4a2392d033f9d1bd79dd6b6ecea6281a61c/lib/sqlalchemy/orm/attributes.py#L328) specifically where instance_state(instance). 

instance_state() uses the operator.attrgetter method to see if the object in question has the attribute "_sa_instance_state". If the object doesn't have the attribute an the error is raised. In this particular issue it was raised for the reasons @zzzeek stated.

Kind Regards,

Ramon

**Comment by zzzeek** [comment]
hey there -

there's an existing exception that does the messaging automatically.   In a case like this we simply need to raise sqlalchemy.orm.exc.UnmappedInstanceError(instance), taking into account we want to use util.raise_() so that the "cause" can be linked, and the messaging is already there.

**Comment by sqla-tester** [comment]
**RamonWill** has proposed a fix for this issue in the **master** branch:

**Raise UnmappedInstanceError if the attribute of a database object is an unmapped object.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2119
