### ISSUE TITLE
Metadata reflection slow with large schemas

### ISSUE THREAD

**Issue by flewellyn** [sqlalchemy/sqlalchemy#4379]
Using SQLAlchemy 1.2.14, I attempted to reflect a schema from a customer which contained several thousand tables, and noticed this was very slow.  Using echo="debug" as an option on the engine, I noticed that the SQLAlchem reflection code is iteratively querying the database for table metadata, instead of issuing one query.

I believe this is sub-optimal, and performance would be greatly enhanced if the SQLAlchemy reflection code issued one query to the backend instead of iterating over the table list.  

Example times: MS SQL Server database with 3,300 tables: 15 minutes.
PostgreSQL database with 694 tables: 4 minutes.
PostgreSQL database with 18,000+ tables: 45 minutes.

**Comment by zzzeek** [comment]
also note that the MySQL database relies upon "SHOW CREATE TABLE", which cannot be batched amongst many tables.  So a performance enhancement here would also need to be conditional based on whether or not a dialect can provide it.   Being able to pass all the desired table names to the dialect from the inspector would also require significant changes to the entire architecture between dialect and inspector, and would need to work exactly as it does now for dialects that can't support such a performance feature including third party.

**Comment by zzzeek** [comment]
note that part of my skepticism over the "one query" claim is that table reflection loads all kinds of objects, not just columns, but also indexes, constraints, for Postgresql it has to load enums and domains, all of these things have their own individual queries that themselves often have hard-to-optimize elements such as LEFT OUTER JOINs and things like that.  If all of this were to be put into *one* query, it is very possible that "one" query would be very un-optimized and slow, not to mention extremely difficult to maintain.

My mistake here is that the issue here states two separate things, and I failed to separate those things immediately. One is, "it's too slow to reflect 18000 tables".  The other is, "please write everything into one giant query".   

More realistically, an optimization here would be first off that if we do want to reflect N tables, we at least do batching, that is, methods like dialect.get_columns() would gain the ability to do their work for a list of table/schemaname combinations.    The reflection of N tables would involve M calls to get_columns(), get_indexes(), get_foreign_keys(), etc.  where M is a portion of N.  We would use batching, and not one huge result, so that results can be streamed out before the full set of tablenames is available, which also gives the chance to preserve memory within the process.   

However, another problem is that table reflection right now sticks all the Table objects into one MetaData() object, and again a MetaData() with 18000 table objects all at once would often be memory intensive, slowing everything down just because of the swapping that would go on.   But this comes down to what the original use case is for reflecting 18000 tables at once - though I'm assuming it's something "streaming" in nature, like writing them out to a file or something like that.  creating ORM mapping to 18000 tables at once would probably take down a server with 500G of ram.   But since we don't know amongst these 18K Table objects which ones might need to refer to each other, it's not worth it to change this right now.

The way this can work is dialects gain methods:

get_multi_columns()
get_multi_foreign_keys()
get_multi_indexes()
get_multi_unique_constraints()
get_multi_check_constraints()
get_multi_table_comments()
get_multi_pk_constraint()

(see how many separate queries there are?)

Any dialect can choose not to implement any or only some of these, as the DefaultDialect will implement them in terms of iterating through the existing single-table versions.   Dialects that *do* implement them should conserve code duplication by re-expressing their existing get_columns(), get_foreign_keys(), etc. in terms of the multiple versioned method (there's no way we want queries like [these](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/base.py#L2875) maintained in *two* separate places).

Finally, the way metadata.reflect() works as well as Table would need to be reorganized so that reflect() can call upon multiple table names at once.  I think reflect() should create Table objects with each name ahead of time like it does now, but then we would need to change around Table._autoload() so that MetaData can pass the list of Table objects to an inspector.reflect_multi() method which does what it needs, that is metadata.reflect() would not pass "autoload_with" to each Table.

These changes allow the reflection of multiple tables to become more efficient in steps, first that we reorganize the code just to expect a stream of Table objects, then we allow dialects to set up multi-versions of each of their reflection methods one at a time.    The architectural refactor to allow this could happen sooner than later.   optimization of individual dialects can happen later over time.

Also of course these inspector methods are public so that developers can get the listing of columns for hundreds of tables at once.

**Comment by flewellyn** [comment]
Forgive me, I came across as far crankier than I should have in my initial posting.

I have the most experience with PostgreSQL, and with that system I would be able to do it in M queries as you said, with the system catalog queries.  I think MS SQL would work the same querying against sys tables.  I had no idea vis a vis MySQL; never used it in any real capacity.

Given the issues you describe, this looks like a much harder problem than I imagined, and I can indeed see how iteratively issuing queries was the simplest way to handle things.  That said, the optimizations you describe would definitely be very useful.

18,000 tables was, and is, very much an outlier case; I used it mostly for stress-testing the reflection code.  I wouldn't expect a database of that complexity as a normal case!  However, I have seen several thousand (low thousand) table databases in production in a few cases.

I guess my question is, what might be done to improve performance for reflection in the meantime?

**Comment by zzzeek** [comment]
The architectural changes I described are pretty straightforward.  the thing that made this seem daunting was the "one" query part where all the separate things like constraints and indexes would need to be  merged together; there's no reason that needs to be done.    the solution would be, if we have 1000 tables, instead of 1000 get columns queries, 1000 get indexes queries, 1000 get constraint queries, etc., we have one query for each of those.  so the 1000-table reflection (which is pretty realistic as a use case) would involve about eight or nine queries for each of those different things.    

so to make it happen quickly, adding the availability of those "bulk" methods, adding a new method to Inspector that does what reflecttable() does, except for a list of table names and then calls into the bulk methods, organizing metadata.reflect() to create a list of Table() objects up front and send them to inspector.bulk_reflecttable(), would be what is needed to start.  then we can go into the target dialects and change methods as needed to work in terms of get_multi_xyz(); the get_columns() methods of SQL Server and Postgresql would serve your use case right now.

i've milestoned this at 1.4 since 1.3 is in betas now but if you were highly motivated to make this happen sooner it can be released sooner, as we have very good test coverage of reflection at this point.

**Comment by zzzeek** [comment]
this is a nice to have and I'd welcome contributions on this but I have no timeline for working on this myself

**Comment by lululukas** [comment]
I appreciate the amount of work that would have to go into this, just chiming in that it would def be a very nice to have 😄

**Comment by sumau** [comment]
As a workaround until the solution above is implemented, how about:
- creating empty metadata
- using engine.table_names(schema=…) or inspector.get_table_names() to get the names of the table for a specific schema
- add the tables to the metadata **without** specifying autoload=True, autoload_with=engine
I tested this with 1000 tables and performance increased by 10 times

Are there any issues with my suggestion I have not considered?

**Comment by zzzeek** [comment]
What you've described would add 1000 Table objects without any columns or constraints in them.  if that's all you need, you're good - this would be good basically for emitting DROP TABLE statements for tables that have no foreign key dependencies.  The example at https://github.com/sqlalchemy/sqlalchemy/wiki/DropEverything does this and also handles the foreign key constraints.   I'm not sure what other use case there is for 1000 Table objects that are just names with no columns or constraints.

**Comment by SahooAshis** [comment]
Just a question.

If a table key is already present in db.Model.metadata.tables object and later I did some changes in the table. If the method db.Model.metadata.reflect() is defined to run at some time-interval will it capture the changes made or it will ignore that table as it is already present?

**Comment by zzzeek** [comment]
it ignores already present unless you use the flag extend_existing=True, however, it only adds new columns, it wont change anything that's present already.

**Comment by zzzeek** [comment]
oh ok it might replace existing columns also, that were reflected.  see https://docs.sqlalchemy.org/en/14/core/metadata.html?highlight=autoload_replace#sqlalchemy.schema.Table.params.autoload_replace .

**Comment by sqla-tester** [comment]
**Federico Caselli** referenced this issue:

**Added a new multi-table reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3167

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Added a new multi-table reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3167

**Comment by PaleNeutron** [comment]
Same problem, reflecting about 1500 tables in Oracle database takes more than 20 min.

**Comment by zzzeek** [comment]
well are you in for a treat!   once we get 2.0 out

**Comment by CaselIT** [comment]
The reworked reflection is now merged in main.

Could you test this and report back if it's faster as expected? 

Thanks!

**Comment by ps-clarson** [comment]
Hi! I was having the same slowness issue with a db reflection script I wrote leveraging sqlalchemy 1.4.6, the get_columns() call was the primary offender.

My database reflection script took 43 minutes to run on sqlalchemy 1.4.6.

I pulled down main (2.0.0b1) and installed it, ran my script and it completed in 4 minutes.

That's a huge performance improvement, good stuff! When can we expect 2.0 to be released? 😉

**Comment by zzzeek** [comment]
how big is that database b.c. 4 minutes is still a long time.     trying to get 2.0 betas by end of year hopefully sooner

**Comment by ps-clarson** [comment]
Hard for me to say exactly how large the database is. It has ~600 schemas most of which have ~150 tables.

My script is only processing 2 of those schemas for a total of 530 tables. My script might not be the best way to benchmark this change because it's running some custom queries in addition to using sqlalchemy for reflection. Just wanted to give y'all a data point.

Let me know if you would like more info.

**Comment by CaselIT** [comment]
Thanks for testing it!
