### ISSUE TITLE
wildcard loader options are not documented for columns, other features missing

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4390]
in https://docs.sqlalchemy.org/en/latest/changelog/migration_09.html#class-specific-wildcards we talk about the new wildcard feature, but that's not the main docs.  There's a little bit of wildcard mentioned at https://docs.sqlalchemy.org/en/latest/orm/loading_relationships.html?highlight=wildcard#wildcard-loading-strategies.  But nothing for columns at https://docs.sqlalchemy.org/en/latest/orm/loading_columns.html - there's "load_only()" which is what uses wildcards behind the scenes, but it should be mentioned.  but then what gets really weird is, what's this?  https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/strategy_options.py#L495  "dot-star" ?  what's that ?   I don't even know what it does and I implemented it. no docs anywhere for that?  that's kind of a problem b.c i dont even know what it does.

**Comment by jvanasco** [comment]
The `.*` is now line 919-920 https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/strategy_options.py#L919-L920 ; (via comparison to a 2018 revision tag when this issue was opened https://github.com/sqlalchemy/sqlalchemy/blob/4332b970c9ec0b32170b1206b965fa7eb5d62a3f/lib/sqlalchemy/orm/strategy_options.py )

I have no idea what this is. @zzzeek any ideas yet?  if so, i can elaborate your comments into a PR.

**Comment by zzzeek** [comment]
I commented the line out and no tests failed

**Comment by zzzeek** [comment]
mmm it is tested though in a few places such as here:

https://github.com/sqlalchemy/sqlalchemy/blob/master/test/orm/test_default_strategies.py#L428

test doesnt fail without it though so lets see why that is

**Comment by zzzeek** [comment]
because these are the same

```py
>>> ".*".split(".")
['', '*']
>>> "*".split(".")
['*']

```

**Comment by jvanasco** [comment]
There are no user-facing docs in sqlalchemy or sqlalchemyorg that reference this, so IMHO it would be safe to deprecate from an undocumented standpoint.

maybe it was in there because some internal codepaths were previously generating ".*", and the prefix needed to be removed. i don't see anything creating that now, though I'm nowhere as familiar with this as you.

**Comment by zzzeek** [comment]
so, AFAICT it's a syntax that's supported but doesnt actually matter, the tests in test_default_strategies can be changed to "*" from ".*" and there appears to be no change

**Comment by zzzeek** [comment]
sure we can warn on that, regular warning, not a 2.0 one.  i dont think anyone is using it since it was not documented.

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **master** branch:

**Fixes: #4390** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3105

**Comment by jvanasco** [comment]
Only these tests fail with the new warning:

* test.orm.test_default_strategies.DefaultStrategyOptionsTest.test_joined_path_wildcards
* test.orm.test_default_strategies.DefaultStrategyOptionsTest.test_subquery_path_wildcards
* test.orm.test_deferred.InheritanceTest.test_defer_on_wildcard_subclass
* test.orm.test_default_strategies.DefaultStrategyOptionsTest.test_joined_path_wildcards
* test.orm.test_default_strategies.DefaultStrategyOptionsTest.test_subquery_path_wildcards
* test.orm.test_deferred.InheritanceTest.test_defer_on_wildcard_subclass

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **rel_1_4** branch:

**Fixes: #4390** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3293
