### ISSUE TITLE
Better exception than "AttributeError: mapper" when passing an invalid thing to Query.join

### ISSUE THREAD

**Issue by dtantsur** [sqlalchemy/sqlalchemy#4428]
I do realize that it's mostly an RTFM issue that is obvious for an experience SQLAlchemy user. But I'm not one, and I got stuck with this for quite some time, so I wonder something can be improved here.

I got derailed from the correct `Query.join` usage after hitting bug #4427, and ended up with:
```
>>> session.query(B).join(B.a_id)
...
  File "/home/dtantsur/Projects/temp/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2244, in _join
    right_entity = onclause.property.mapper
  File "/home/dtantsur/Projects/temp/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 853, in __getattr__
    return self._fallback_getattr(key)
  File "/home/dtantsur/Projects/temp/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 831, in _fallback_getattr
    raise AttributeError(key)
AttributeError: mapper
```
The same thing with
```
>>> session.query(B).join(A, B.a_id)
```
Now, it does not sound completely unreasonable to me to use a foreign key as a hint for JOIN, but that's not the point here. I wonder if the exception can be caught and the error message be something
```
Expected a mapped object, such as a model or a statement, got a Column.
```

**Comment by zzzeek** [comment]
that is reasonable considering that query.join() accepts such a grab-bag of junk as arguments, I can accept PRs for this.

**Comment by ParthS007** [comment]
@zzzeek I want to work on this. Can you please point me to the file where I need to do changes?
Thanks

**Comment by zzzeek** [comment]
for this one we are looking inside of:   https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/query.py#L2229

the following test program should raise an ArgumentError that explains that the "onclause" is not the right kind of argument:
```

from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    bs = relationship("B")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))


s = Session()
print(s.query(B).join(B.a_id))
```

right now it says this:

```
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 923, in _fallback_getattr
    raise AttributeError(key)
AttributeError: entity

```

**Comment by ParthS007** [comment]
@zzzeek What is the type of `onclause` that is to be expected?

**Comment by zzzeek** [comment]
the parameter accepts a variety of arguments and is fairly complicated (there is a plan to simplify this in the future but it's a long way off).   if you run a test suite like test/orm/test_joins.py, all the valid use cases for the parameters here are exercised.   the various forms of usage are documented at https://docs.sqlalchemy.org/en/latest/orm/query.html?highlight=query%20join#sqlalchemy.orm.query.Query.join .

**Comment by RamonWill** [comment]
Hi @zzzeek,

I can look into this issue ill make a PR at some point today.

Kind Regards,

Ramon

**Comment by zzzeek** [comment]
hi @RamonWill  -

current master is using a very different system of parsing arguments for things like query.join() so it's possible this is already working and just needs a test.

**Comment by zzzeek** [comment]
wow it doesn't.   unfortunately the way this works in 1.4 is completely different from 1.3

**Comment by RamonWill** [comment]
Hi Mike,

From the debugging i could see that the _legacy_join is used in the [context.py file](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/context.py#L1293) 

I was planning to add the below and it doesn't break the existing tests and i have created a test for this. Does this look okay?
I am actually a few commits behind so will need to rebase and check again but this is the gist of what i was thinking.
```diff
            if isinstance(onclause, interfaces.PropComparator):
                # descriptor/property given (or determined); this tells us
                # explicitly what the expected "left" side of the join is.
                if right is None:
                    if of_type:
                        right = of_type
+                    elif isinstance(onclause.property, properties.ColumnProperty):
+                       raise sa_exc.ArgumentError(
+                           "Expected mapped entity or "
+                            "selectable/table as join target"
+                       )
                    else:
                        right = onclause.property.entity
```

Would appreciate your thoughts and guidance on this.

Kind Regards,
Ramon

**Comment by zzzeek** [comment]
OK that's pretty good and I think at the moment we have to do something like that.

in 1.4, there are essentially two levels of accommodation for user input.

the first one is the coercions layer, which takes place immediately when you call upon query.join() for example.   The fact that a "Class.attrname" can be passed here was difficult for me to accommodate, and that awkwardness is part of why this issue continues to persist in 1.4 even though I wrote this whole big system to parse things correctly.    I have a proof of concept here that would adjust the class relationships to catch this at the coercions layer, but this would be a big change I'd have to work through.

the second level is in the compilation phase, where the code you've worked on above is now accommodating the arguments that coercions has given us, and now we unwrap it and see that it's still wrong.   There are a bunch of other cases within the join mechanics where this can happen.

The big deal here is that in 1.4, this second level of argument checking happens only when we *compile* the query.  in 1.3, all of the work that happens in context.py occurs immediately within our up-front query.join() call.

in any case, the approach you have above could also be backported to 1.3 as it works upon logic that is roughly present in 1.3 as well, just in a different file.   I don't think it's that important we backport right now because 1.4 betas are definitely getting closer.

Even if i do merge the coercions rework I have here, the check you are doing is still useful.

So that said, yes, let's do your check, however let's reorganize it so that we "beg forgiveness" rather than "ask permission", and by that I mean:

```
diff --git a/lib/sqlalchemy/orm/context.py b/lib/sqlalchemy/orm/context.py
index 55a6b4cd2..e89804bf9 100644
--- a/lib/sqlalchemy/orm/context.py
+++ b/lib/sqlalchemy/orm/context.py
@@ -1292,7 +1292,15 @@ class ORMSelectCompileState(ORMCompileState, SelectState):
                     if of_type:
                         right = of_type
                     else:
-                        right = onclause.property.entity
+                        right = onclause.property
+
+                        try:
+                            right = right.entity
+                        except AttributeError:
+                            raise sa_exc.ArgumentError(
+                                "Join target %s does not refer to a "
+                                "mapped entity" % right
+                            )
 
                 left = onclause._parententity
 

```

**Comment by RamonWill** [comment]
Hi Mike,

Okay noted, thank you for the background information as well as advice on improving the code.

I will make the adjustments and send through a PR with the test and changelog also

Thanks,
Ramon

**Comment by sqla-tester** [comment]
**RamonWill** has proposed a fix for this issue in the **rel_1_3** branch:

**Provide more detailed error message for Query.join()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2192
