### ISSUE TITLE
Cast applies an anonymous alias

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#4449]
Cast renders an anonymous alias contrary to the [documentation](https://docs.sqlalchemy.org/en/latest/core/sqlelement.html#sqlalchemy.sql.expression.cast)

The example used in the documantation
```py
from sqlalchemy import cast, Numeric, select

stmt = select([
            cast(product_table.c.unit_price, Numeric(10, 4))
        ])
```
renders as
```sql
SELECT CAST(product_table.unit_price AS NUMERIC(10, 4)) AS anon_1 FROM product_table
```
instead of
```sql
SELECT CAST(unit_price AS NUMERIC(10, 4)) FROM product
```

I've tried sqlalchemy version 1.2.7 and 1.2.16 and both return the same result

**Comment by zzzeek** [comment]
SELECT renders an anonymous alias for all expressions that don't have a name, originally so that they can be correctly targeted in the result set.  The modern result set implementation can probably get by without that behavior as it no longer relies upon names, however, that's a much more fundamental change beyond cast().

is the issue here strictly that the documentation is inaccurate?

**Comment by CaselIT** [comment]
It's a bit surprising here since I had not realized that all expression without names render as anonymous.
A way to avoid it would be great, but since that would require a large change, at least a note in the documentation would be great.

I'm using postgres that implicitly aliases the cast with the column name, so that's probably why I was surprised by the behavior of sqlalchemy. Other databases do not do this

**Comment by zzzeek** [comment]
it could be suggested that our own cast() would attempt to suggest this name for the alias name.  I tried to mock that up but apparently there's no codepath at the moment where an object can state that it needs a label, e.g. "expr AS label", but that this label is not the so-called "anonymous" label.    this makes sense because the way things work now, a column either is implicitly named (e.g. a table-bound column or explicitly created label) or we are giving it our own anonymous name.   In both cases, SQLAlchemy doesn't itself generate a conflicting name, which is the problem the whole system is looking to avoid ( which again, is because historically, the whole result set required things be addressable by name, which is not strictly necessary now).    That is, if cast(x AS foo) always rendered as "cast(x AS foo) AS x", now code which attempts to cast "x" in two different ways would have a naming conflict whereas before it would not.      

I did mock it up here with some extra flags and noticed I can generate this:

```
SELECT CAST(tab.q AS VARCHAR) AS q, CAST(tab.q AS FLOAT) AS q 
FROM tab

```
I went to see what PG does if I do this, and it generates the result with the same name twice:

```
test=# select cast(x as varchar), cast(x as float) from foo;
 x | x 
---+---
(0 rows)

```

as you mentioned, this is not what other DBs do.

I think this is something that could maybe be made to act more like postgresql, but im not really sure it's worth it, as these naming things issues cause subtle problems when we change things.     the column name can be generated as you want if you use .label() explciitly, so at the moment I vote we just update the docs and maybe add a note, cast() is like any other anonymous expression.

**Comment by CaselIT** [comment]
I agree that postgres is a bit strange in this case.

In the future I think it could be useful if there was a way to disable disable the anonymous label generation, letting the database name the result set columns.

BTW Thanks for the quick answer 😉

**Comment by zzzeek** [comment]
> I agree that postgres is a bit strange in this case.
> 
> In the future I think it could be useful if there was a way to disable disable the anonymous label generation, letting the database name the result set columns.

as I said I don't think it's worth it, seeing that you can use label() if you really need it to act that way.  What is your use case for it to behave this way?

**Comment by CaselIT** [comment]
Nice, thanks for the update!
