### ISSUE TITLE
why I can`t get cursor using mysqldb?

### ISSUE THREAD

**Issue by vimiPonyai** [sqlalchemy/sqlalchemy#4495]
Hi all, I try to hack the execute method while executing SQL.
If i use pymysql, I works well by using:
`execute_method = engine.__dict__['dialect'].__dict__['dbapi'].__dict__['cursors'].__dict__['Cursor'].__dict__['execute']`
I can get the execute method so I can hack successfully.

but while I use mysqldb, I does not work.
and say
`KeyError: 'cursors'`
is it not found cursors for mysqldb?

thanks in advance.

**Comment by vimiPonyai** [comment]
found in 
`engine.__dict__['dialect'].__dict__['identifier_preparer'].__dict__['dialect'].__dict__['dbapi'].__dict__['cursors'].__dict__['BaseCursor'].__dict__['execute']`

**Comment by zzzeek** [comment]
if you want to work with cursors, please use the documented approach at:

https://docs.sqlalchemy.org/en/latest/core/connections.html#working-with-raw-dbapi-connections

**Comment by zzzeek** [comment]
otherwise, to inject behavior for execute, please use one of the following event hooks:

https://docs.sqlalchemy.org/en/latest/core/events.html?highlight=do_execute#sqlalchemy.events.DialectEvents.do_execute
https://docs.sqlalchemy.org/en/latest/core/events.html?highlight=do_execute#sqlalchemy.events.DialectEvents.do_execute_no_params
https://docs.sqlalchemy.org/en/latest/core/events.html?highlight=do_execute#sqlalchemy.events.DialectEvents.do_executemany
https://docs.sqlalchemy.org/en/latest/core/events.html?highlight=before_cursor_execute#sqlalchemy.events.ConnectionEvents.before_cursor_execute

**Comment by vimiPonyai** [comment]
> otherwise, to inject behavior for execute, please use one of the following event hooks:
> 
> https://docs.sqlalchemy.org/en/latest/core/events.html?highlight=do_execute#sqlalchemy.events.DialectEvents.do_execute
> https://docs.sqlalchemy.org/en/latest/core/events.html?highlight=do_execute#sqlalchemy.events.DialectEvents.do_execute_no_params
> https://docs.sqlalchemy.org/en/latest/core/events.html?highlight=do_execute#sqlalchemy.events.DialectEvents.do_executemany
> https://docs.sqlalchemy.org/en/latest/core/events.html?highlight=before_cursor_execute#sqlalchemy.events.ConnectionEvents.before_cursor_execute

I love you, very love you. 
And also amazing the code what you write.
thanks your reply.
