### ISSUE TITLE
Drop relationship after session commit

### ISSUE THREAD

**Issue by comtihon** [sqlalchemy/sqlalchemy#4513]
Hi, 
I don't quite understand, why my previosly loaded objects dissapear from relationship after session commit.
I load them like this:
```
query.options(contains_eager(Parent.children, alias=children_subquery)
```
My model:
```
class Parent(db.Model):
  children = relationship('Child', lazy='raise')
```
I did it on purpose, as my subquery is quite complex to be accessed via subquery (and requires additional data). So objects are loaded by demand.
Actually, everything worked, till I've added db.session.commit().
Current scenario:
1. load Parent objects with Children attached
2. insert some more empty Parent objects via db.session.add & db.session.commit
3. try to access Parent.children <--- here comes the lazy load error, but it shouldn't, as this data was loaded on step 1.

I've found an ugly workaround - I insert objects on step 2 via `Parent.__table__.insert`. But I don't like it.

Is there a way to add objects to session without previously loaded objects invalidation?

**Comment by zzzeek** [comment]
> Hi,
> I don't quite understand, why my previosly loaded objects dissapear from relationship after session commit.

when the session commits a transaction, its default behavior is to expire all object attributes, so that when the next transaction begins, all the state is loaded with whatever the current state of the database is; note that when you commit a database transaction and start a new one, you're now open to the whole world of changes that could have happened concurrently with your commit or before you called begin again.   

this behavior, while it prevents a different sort of confusion where users wonder why they updated their object in transaction A, and then in transaction B, and then they wonder why they don't see B's changes in A, is necessarily kind of heavy-handed to the more common use case where someone wants to commit their transaction, then keep working with the data they have without worrying about other transactions.   This latter use case works transparently as well with the default behavior, *except* that if you look at the SQL being emitted, you see a lot more than you'd like, and especially if you seek to detach your objects from the Session or prevent lazy loads with lazy="raise", it's going to fail quite badly.    Since these are optimization cases, that means they are non-default vs. the "works every time for non-optimized use" case.

So to work with optimizing that you don't have to re-emit SQL all over again after commit() and you don't care about concurrent transaction state, you simply turn the flag off.  It is called [expire_on_commit](https://docs.sqlalchemy.org/en/latest/orm/session_api.html?highlight=expire_on_commit#sqlalchemy.orm.session.Session.params.expire_on_commit) and it is discussed in detail at: https://docs.sqlalchemy.org/en/latest/orm/session_basics.html#committing  .

**Comment by zzzeek** [comment]
okey doke feel free to continue discussion.

**Comment by comtihon** [comment]
Thanks for the answer!
