### ISSUE TITLE
ResultProxy

### ISSUE THREAD

**Issue by john-bodley** [sqlalchemy/sqlalchemy#4523]
Per this issue in [pydruid](https://github.com/druid-io/pydruid/issues/151) which implements the Druid SQLAlchemy dialect I was wondering how the ResultProxy is supposed to behave when the result set returns no rows and Druid SQL API provides no description associated with the empty result set. 

This is problematic as per the SQLAlchemy [documentation](
https://docs.sqlalchemy.org/en/latest/core/connections.html#sqlalchemy.engine.ResultProxy._soft_close) the `_soft_close` method is called automatically when the `cursor.description` is `None` meaning that queries of the form:

```
>>> from sqlalchemy.engine import create_engine

>>> engine = create_engine('druid://localhost:8082/druid/v2/sql')
>>> result = engine.execute("SELECT SUM(x) FROM foo WHERE bar IS NULL")
>>> result.fetchall()
...
AttributeError: 'NoneType' object has no attribute 'fetchall'
```
error due to the cursor being closed due to the missing description. 

I was wondering whether there were other dialects which didn't define a description for an empty result set associated with a SELECT statement or how one should configure their dialect to circumvent the issue of a missing description.

**Comment by zzzeek** [comment]
so " no rows" is not the same as "no result".   A SELECT statement that returns zero rows because it doesnt match any in its WHERE clause would produce a cursor that when fetchall() is called, returns an empty sequence (e.g. python list), however it would still have cursor.description indicating the rows that would be returned.   you can test this on any database like SQLite:

```
>>> import sqlite3
>>> conn = sqlite3.connect(":memory:")
>>> cursor = conn.cursor()
>>> cursor.execute("select 1 where 1=0")
<sqlite3.Cursor object at 0x7fcc3b1c3e30>
>>> cursor.description
(('1', None, None, None, None, None, None),)

```

if druid has a SQL API, it should be fixed to support returning to the client the columns that were requested.  ideally it includes datatype and all that but as you can see above SQLite returns a very minimal record.  

also see [cursor.description](https://www.python.org/dev/peps/pep-0249/#description) in pep 249.

**Comment by john-bodley** [comment]
Thanks @zzzeek for the quick response and explanation.
