### ISSUE TITLE
Please clarify the warning in the Numeric documentation

### ISSUE THREAD

**Issue by bryankaplan** [sqlalchemy/sqlalchemy#4532]
The documentation for `Numeric` [includes](https://github.com/sqlalchemy/sqlalchemy/blob/2160b7e65220cebf2a6d8a026b6b4fd4c5d9163f/lib/sqlalchemy/sql/sqltypes.py#L554-L557) the following warning:

> Note that the ``cdecimal`` and ``decimal`` libraries are **not
> compatible with each other**, so patching ``cdecimal`` at the
> global level is the only way it can be used effectively with
> various DBAPIs that hardcode to import the ``decimal`` library.

Does this mean that:
* It is dangerous for a single running process to import both the old 
  python's `decimal` and `cdecimal,` and for both to be used in attempts to read
  and write to and from the same database using `Numeric` via sqlalchemy
* It is dangerous for one codebase using the old python's `decimal` and
  a separate codebase using `cdecimal`, running in separate processes, to both
  read and write to and from the same database using `Numeric` via sqlalchemy
* All of the above
* None of the above; something entirely different

Additionally, could you please elaborate on the nature of the danger involved
in whichever above scenario(s) are correct?

**Comment by zzzeek** [comment]
> The documentation for `Numeric` [includes](https://github.com/sqlalchemy/sqlalchemy/blob/2160b7e65220cebf2a6d8a026b6b4fd4c5d9163f/lib/sqlalchemy/sql/sqltypes.py#L554-L557) the following warning:

are you on python 2.7 or python 3.x ?   the notes about cdecimal are ancient as python 3 now bundles the full cdecimal library as "decimal".     I doubt people usually patch "cdecimal" in their Python 2 applications anymore.   I couldn't even get it to pip install smoothly, had to run python setup.py install on the source distro.   just taking the docs out is likely the best thing to do here.


> 
> > Note that the `cdecimal` and `decimal` libraries are **not
> > compatible with each other**, so patching `cdecimal` at the
> > global level is the only way it can be used effectively with
> > various DBAPIs that hardcode to import the `decimal` library.
> 
> Does this mean that:
> 
>     * It is dangerous for a single running process to import both the old
>       python's `decimal` and `cdecimal,` and for both to be used in attempts to read
>       and write to and from the same database using `Numeric` via sqlalchemy

It usally means it raises errors if you try to do any kind of math with a cdecimal.Decimal and a decimal.Decimal.   But it is also a little "dangerous" because the two types don't raise an error when you try to compare them to each other, they just return the wrong result (see below).   so that's not good.


> 
>     * It is dangerous for one codebase using the old python's `decimal` and
>       a separate codebase using `cdecimal`, running in separate processes, to both
>       read and write to and from the same database using `Numeric` via sqlalchemy

absolutely not.    "decimal.Decimal" and "cdecimal.Decimal" are Python objects that are not exposed to the database at all.  It's no different than if one process is reading/writing numbers using a Python interpreter and the other one is doing it using node.js.

> 
>     * All of the above
> 
>     * None of the above; something entirely different
> 
> 
> Additionally, could you please elaborate on the nature of the danger involved
> in whichever above scenario(s) are correct?

here is the danger (noting that "pip install cdecimal" doesn't even seem t work anymore, I had to download it directly for some reason):

```
>>> import cdecimal
>>> import decimal
>>> cdecimal.Decimal("1") + decimal.Decimal("1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'cdecimal.Decimal' and 'Decimal'
>>> cdecimal.Decimal("1") > decimal.Decimal("1")
True
>>> cdecimal.Decimal("1") == decimal.Decimal("1")
False
>>> cdecimal.Decimal("1") < decimal.Decimal("1")
False

```

hence if your DBAPI has "import decimal" inside of it, you load some rows and they have decimal.Decimal() objects in them, then you plug some cdecimal.Decimal() objects into it, the ORM won't compare the values correctly, and any kind of math you do will raise errors.

So the advice is, if you want to use cdecimal (which you absolutely do not need to and if you are unsure of what it means, then just dont use it), make sure your DBAPI is not able to import the regular "decimal" library.

**Comment by bryankaplan** [comment]
Thank you, @zzzeek. That was really helpful. You covered everything I was looking to understand.
