### ISSUE TITLE
__eq__ in Column class to be able to compare columns(Feature request)

### ISSUE THREAD

**Issue by datadidit** [sqlalchemy/sqlalchemy#4554]
Would it be possible to add a `__eq__` method to the [Column](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/schema.py#L1013) class. 

This would allow users to compare automapped models colums to in a SQLAlchemy model:

```python
def get_automapped_model(table_name, engine):
    ''' Method for retrieving automapped model by table name '''
    METADATA.reflect(engine, only=[table_name])
    base = automap_base(metadata=METADATA)
    base.prepare()

    return base.classes[table_name]


def add_columns_to_table(model=PlayerIntl, engine=_ENGINE_PHIL_DATA):
    '''
    # https://stackoverflow.com/questions/7300948/add-column-to-sqlalchemy-table
    # TODO: Do this through alembic when you get a second
    :return:
    '''
    table_name = model.__table__.name
    automapped_model = get_automapped_model(table_name, engine)
    missing_columns = []
    for column in automapped_model.__table__.columns:
        print type(column)
        for model_col in model.__table__.columns:
            print type(model_col)
            print "Comparing {0} to {1}".format(model_col, column)
```

**Comment by zzzeek** [comment]
hi there-

the `Column` class already has an `__eq__` method, this is intrinsic to the entire working of SQLAlchemy Core.  it produces a `BooleanExpression` construct.   Intro to this concept is at https://docs.sqlalchemy.org/en/latest/core/tutorial.html#operators .   it is not used for the purpose of comparing the structure of columns however.

The comment in your code example points to the correct long-term approach for schema comparison which is to use Alembic.    You can however continue to compare the Column objects manually as you are doing, or use the [inspector](https://docs.sqlalchemy.org/en/latest/core/reflection.html?highlight=inspector#fine-grained-reflection-with-inspector) too.

**Comment by zzzeek** [comment]
actually the last few paragraphs of the previous section, https://docs.sqlalchemy.org/en/latest/core/tutorial.html#selecting .

**Comment by datadidit** [comment]
@zzzeek Thanks for all your help. So I guess the thing I'm having trouble with is when I compare an `automapped` models column to a hand typed models column via

```
        for model_col in automapped_model.__table__.columns:
            if model_col == column:
                found_match = True
```

I don't find matches. When I do the rudimentary comparison just looking at the column names:

```
        for model_col in automapped_model.__table__.columns:
            if model_col.name == column.name:
                found_match = True
```
I do find matches. Yes this is a basic match and ideally I'd use `alembic` which I plan to go through the docs eventually. But shouldn't I also be able to just compare the two columns this way as well. Simple name matching was okay for me for now. But I'm guessing if I do something similar to [this](https://stackoverflow.com/questions/39043003/comparing-sqlalchemy-object-instances-for-equality-of-attributes) and remove the `_sa_instance` I'd be able to compare the dicts.

**Comment by zzzeek** [comment]
> @zzzeek Thanks for all your help. So I guess the thing I'm having trouble with is when I compare an `automapped` models column to a hand typed models column via
> 
> ```
>         for model_col in automapped_model.__table__.columns:
>             if model_col == column:
>                 found_match = True
> ```
> 
> I don't find matches. When I do the rudimentary comparison just looking at the column names:
> 
> ```
>         for model_col in automapped_model.__table__.columns:
>             if model_col.name == column.name:
>                 found_match = True
> ```
> 
> I do find matches. 

this is, as I referred above to the documentation, due to the behavior of `__eq__()` in SQLAlchemy.


Yes this is a basic match and ideally I'd use `alembic` which I plan to go through the docs eventually. 

> But shouldn't I also be able to just compare the two columns this way as well. 

no, you shouldn't.  this is not how `Column` objects work.   If SQLAlchemy didn't override `__eq__()` on them to produce expression behavior, then `__eq__()` would act as the Python default, comparing the two objects on identity alone.  The request to "compare" two Column objects at the schema level can mean any number of things.  What if both columns have the same datatype and name, but one was autoloaded from a different table than the other one? do they "compare" equally?   What if they are from the *same* table, but in different schemas, or two different databases, do they "compare" equally?  What if they are the same everything but one is from an Oracle database and the other from SQLite?  Do they "compare" equally?   What if one has a default generator on it and the other does not?   do they "compare"equally?   I could really go on all day with things that are linked to Column objects that may or may not be considered to be "equal", so your best bet is to write your own "compare()" function that compares exactly what you want.


> Simple name matching was okay for me for now. 

OK so that means your problem is solved for now.   When you have a new problem, come back to the mailing list and that one can be solved as well.

> But I'm guessing if I do something similar to [this](https://stackoverflow.com/questions/39043003/comparing-sqlalchemy-object-instances-for-equality-of-attributes) and remove the `_sa_instance` from the copied dictionary I'd be able to compare the dicts.

that approach is pretty bad, deepcopy is intensely error prone, slow, and uses tons of memory.   Id never compare two objects generically that way.  to compare two objects you first test that each are of the same class (or a subclass, depending on how you see it working), then you compare the **specific attributes that you care about, explicitly**.   Open-ended comparisons that try to guess everything are slow, hacky, and error prone.

**Comment by datadidit** [comment]
@zzzeek thanks again for the help. Not going down the `__dict__` approach just stood out when I was googling around for this problem.
