### ISSUE TITLE
Info attribute on hybrid_property

### ISSUE THREAD

**Issue by ErnaOudman** [sqlalchemy/sqlalchemy#4555]
The Column class of sqlalchemy has the option to populate the info attribute with a dictionary. Also when using the column_property function, it's possible to parse this info dictionary.

So the following works:
```python
class Address(Base):
	__tablename__ = "something"
	
	street = Column(
		String(20),
		info={"displayname": 'Street name'}
	)
	
	number = Column(
		Integer,
		info={"displayname": 'House number'}
	)
	
	address = column_property(
		func.concat(name, '', func.cast(number, String)),
		info={"displayname": 'Address'}
	)
```
	
Then I have some properties which I want to transform into hybrid_properties. As I'm looping over them, I'm not using hybrid_property as a decorator. So I want to do the following:

```python
	attributes = {}
	
	for key, value in items.items():
		fget = partial(item['fget'])
		fset = partial(item['fset'])
		expr = partial(item['expr'])
		info = item['info']
		attributes[key] = hybrid_property(fget=fget, fset=fset, expr=expr, info=info)	
```
	
This works without the info keyword for hybrid_property. 

Standard, the info attribute of a hybrid_property is an empty dictionary, but gives an 'unexpected keyword' error for 'info'. From the source code this is completely clear.
	
But when creating a hybrid_property, it get's an info attribute. But this is an empty dictionary. And it doesn't seem possible to change it or add an info dictionary.
I was wondering if there is a reason for this. Or is it something that could be added? Or maybe I miss how it could actually be added.

**Comment by zzzeek** [comment]
hi there -

Historically, having `.info` on hybrid was tricky because the `@hybrid_attribute` maintains class-based and instance-based getter behavior - it used to return the underlying expression object directly at the class level, meaning an `.info` that was local to the hybrid would not be accessible.  To fix this, the hybrid object itself was made to be accessible from the mapper as well, by requesting `mapper.attrs['my_hybrid']`.    

In current releases, in the majority of cases the `@hybrid_attribute` when invoked at the class level wraps the underlying SQL expression in a `QueryableAttribute` that is specific to the hybrid,which allows you to access and manipulate the `.info` dictionary directly:
```

from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.hybrid import hybrid_property

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String, info={"foo": "bar"})

    @hybrid_property
    def data_hyb(self):
        return self.data

    @data_hyb.expression
    def data_hyb(cls):
        return cls.data

A.data_hyb.info['foo'] = 'bar'
print(A.data_hyb.info)

```

As the `@hybrid_property` delivers a decorator-oriented constructor (that is, its `__init__` method is a callable which has to follow the [decorator convention](https://docs.python.org/3/reference/compound_stmts.html#function-definitions), it's not possible for `.info` to be part of its constructor unless the API were changed to allow for two levels of construction.

**Comment by zzzeek** [comment]
also as part of my example I intended to illustrate how to get at the `.info` for the `Column` via the hybrid, that looks like:

`print(A.data_hyb.expression.info)
`

that is, they are two separate dictionaries.

**Comment by ErnaOudman** [comment]
Thanks for your elaborated answer. Clear why it's not possible and also not necessary.

**Comment by zzzeek** [comment]
you're welcome!
