### ISSUE TITLE
MSSQL where clause defaults to N-prefix on py3

### ISSUE THREAD

**Issue by villebro** [sqlalchemy/sqlalchemy#4561]
With the addition of unicode support in SQLAlchemy 1.3 for MSSQL, it appears all strings are interpreted as unicode on Python 3. I believe in the majority of cases N-prefixing should not be applied, but rather only when the column type is `UnicodeText`. The example below is for Python 3.7.2 on `master` branch:

```python
from sqlalchemy.sql import column, table, select
from sqlalchemy.types import UnicodeText

mssql_engine = sa.create_engine('mssql+pyodbc://uid:pwd@localhost')

col = column('col')
unicode_col = column('unicode_col', type_=UnicodeText())
tbl = table('tbl')

s = select([col]).select_from(tbl).where(col == 'abc').where(unicode_col == 'abc')
print(s.compile(mssql_engine, compile_kwargs={"literal_binds": True}))
```

# Expected behavior
```sql
SELECT col 
FROM tbl 
WHERE col = 'abc' AND unicode_col = N'abc'
```

# Actual behavior
```sql
SELECT col 
FROM tbl 
WHERE col = N'abc' AND unicode_col = N'abc'
```

**Comment by zzzeek** [comment]
well, the thing is, the datatype of 'abc' *is* `Unicode` because you're in Python 3.  so, I'm not really sure what to do here, but you certainly can set the type yourself to String:

    col == literal('foo', type_=String)

**Comment by zzzeek** [comment]
as well as, the type is correctly inferred from the expression, that is, if you do this:

    col = column('col', String)

the "N" goes away, because the comparison figures out that it's a String and not Unicode comparison.    which seems like everything is doing the right thing.

**Comment by zzzeek** [comment]
also...unicode support was not "added" in 1.3, maybe the "N" thing is what you're referring towards

**Comment by zzzeek** [comment]
oh its #4442 which is also your issue

**Comment by villebro** [comment]
Yes, I was referring to the N-thing. I believe users coming from <1.3 will expect `NoneType` to default to non-N-prefixed where clauses, i.e. same behavior as `String`. But I can work with `type_=String`, no sweat, thanks.

**Comment by zzzeek** [comment]
yeah I think there's a minor surprise there but when we see str in python 3, it can easily have unicode chars inside of it and we don't want to be checking, so I think this behavior is more correct.   it shouldn't impact standard SQL operations against columns that have datatypes.

**Comment by villebro** [comment]
Not sure how MSSQL handles N prefixed ascii-only strings when dealing with indexes, but it may cause trouble in that area. But if not then it probably just a minor cosmetic detail.

**Comment by zzzeek** [comment]
the N prefixed strings don't work well with indexes but I don't see how one would normally be getting N prefixed strings because in Core everything is usually typed.  in your case, making a lot of use of text(), that's a thing to consider, but text() allows typing to be set up for parameters as well, you probably should not rely on implicit typing because it wont work for things like large numeric / floating values either.

**Comment by ianthetechie** [comment]
I recently made a post to the mailing list and SO (https://stackoverflow.com/questions/55098426/strings-used-in-query-always-sent-with-nvarchar-syntax-even-if-the-underlying-c) about this same issue.

We are using the ORM, not core in our case and the ORM just passes a Python `str` to the underlying driver, and at least one of the underlying ODBC drivers and pymssql both prefix unicode strings with N because they don't have the context to do otherwise.

N prefixed strings will have problems with more than indexes by the way. Any sort of comparison of an NVARCHAR literal to a VARCHAR column results in the entire column being upcasted, which is not a trivial operation on tables with a large number of rows.
