### ISSUE TITLE
issue with composite keys and declarative classes

### ISSUE THREAD

**Issue by silky** [sqlalchemy/sqlalchemy#4597]
versions:

```
(sql-alc-bug) 01:16 PM noon ∈ sql-alc-bug 🌷 python -c 'import sqlalchemy as s; print(s.__version__)'
1.3.3
(sql-alc-bug) 01:16 PM noon ∈ sql-alc-bug 🌷 python --version                                        
Python 3.6.2 :: Continuum Analytics, Inc.
```

the following code fails:

```
from sqlalchemy import (
    Column
    , Integer
    , String
    , ForeignKeyConstraint
    , create_engine
    )
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Order(Base):
    __tablename__ = "order"

    id   = Column(Integer, primary_key=True)
    name = Column(String(50), primary_key=True)

    
class Location(Base):
    __abstract__ = True
    
    id   = Column(Integer, primary_key=True)
    name = Column(String(50))
    
    order_id   = Column(Integer)
    order_name = Column(String(50))


class Thing(Base):
    __tablename__ = "thing"
    id   = Column(Integer, primary_key=True)
    ab   = Column(Integer, primary_key=True)

    
class WhateverLocation(Location):
    __tablename__ = "whateverlocation"

    thing_id = Column(Integer)
    thing_ab = Column(Integer)

    fk1 = ForeignKeyConstraint( [thing_id, thing_ab]
                        , [Thing.id, Thing.ab]
                        )
    
    fk2 = ForeignKeyConstraint( ["order_id", "order_name"]
                        , [Order.id, Order.name]
                        )
    
    # __table_args__ = ( fk1, fk2 )
    
    

fkcs = list(Base.metadata.tables["whateverlocation"].foreign_key_constraints)
assert len(fkcs) == 2
```

to fix it, just uncomment the magical `__table_args__` line.

the point is, there's something odd happening when we define an FK relationship based on keys in a parent class.

i think for the sqlalchemy experts this might be an easy fix, but it's been a struggle for me to figure out why this is happening (spent a few hours glancing around the code!)

i'm happy enough with the workaround if setting the `__table_args__` magic, but it's probably good to fix.

thanks!

fwiw: it seems like whatever happens when `__table_args__` is set, is a much nicer codepath; as i was able to solve the problem in ~1 min, because it gave error messages, into of  silently dropping the constraints!

**Comment by zzzeek** [comment]
this is #2700 for now see the workaround recipe given, or just put those columns on the superclass

**Comment by zzzeek** [comment]
oh wait you have `__tablename__` in there, so this is not a bug.

**Comment by zzzeek** [comment]
> 
> to fix it, just uncomment the magical `__table_args__` line.

this is not magical, this [is documented](https://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/table_config.html?highlight=__table_args__#table-configuration)  Declarative knows nothing about fk1 and fk2 otherwise as these are not attributes is scans for.

> 
> the point is, there's something odd happening when we define an FK relationship based on keys in a parent class.

looking closely, it appears you might be trying to point out the difference between the two FKs.  Since one of them uses the actual `Column` objects, and not just their string name, it auto-attaches itself to the `Table`.  But for the second one you've given the `ForeignKeyConstraint` only string names so it can't do this.

> 
> i think for the sqlalchemy experts this might be an easy fix, but it's been a struggle for me to figure out why this is happening (spent a few hours glancing around the code!)
> 
> i'm happy enough with the workaround if setting the `__table_args__` magic, but it's probably good to fix.

that's the correct usage.   There is no "fk = ForeignKeyConstraint` pattern in declarative.     A quick scan through https://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/index.html just to see the basic patterns might be helpful here.

**Comment by silky** [comment]
@zzzeek ; 

several comments.

1) note that infact declarative _does_ work out that fk1 and fk2 have been defined; observe that 1 fk constraint is made, even though no-one references fk2

2) we tried to use:

```
    
    fk2 = ForeignKeyConstraint( [Location.order_id, Location.order_name]
                        , [Order.id, Order.name]
                        )
    
```

but that fails whether you use `__table_args__` or otherwise!

happy for other suggestions on how to solve this. thanks for pointing me to the documentation for `__table_args__`, though! maybe the real bug is why FKs are made _without_ using table_args??

**Comment by zzzeek** [comment]
> @zzzeek , thanks for the prompt response!
> 
> several comments.
> 
>     1. note that infact declarative _does_ work out that fk1 and fk2 have been defined; observe that 1 fk constraint is made, even though no-one references fk2

as i said, declarative is not doing this.  The ForeignKeyConstraint is, when you put the "thing_id, thing_ab" Column objects directly into it.   Declarative saw the "fk1" and "fk2" attributes and it fully skipped them, trust me.

> 
>     2. we tried to use:
> 
> 
> ```
>     
>     fk2 = ForeignKeyConstraint( [Location.order_id, Location.order_name]
>                         , [Order.id, Order.name]
>                         )
>     
> ```
> 
> but that fails whether you use `__table_args__` or otherwise!

because Location.order_id and Location.order_name are not part of any Table object because that declarative class is abstract.

> 
> happy for other suggestions on how to solve this. 

Use the documented API.... ?    I'm not sure what the problem is.

> thanks for pointing me to the documentation for `__table_args__`, though! maybe the real bug is why FKs are made _without_ using table_args??

because you gave it Column objects which it used to attach itself to the Table.       This use is not well documented for ForeignKeyConstraint which is documented as normally taking string column names, since that works in a wider range of scenarios.   But all the Constraint objects automatically associate themselves with a Table if they are given Table-bound Column objects.

**Comment by silky** [comment]
so helpful!

**Comment by silky** [comment]
finding this issue was quite frustrating and time consuming; reporting it took some effort, and having this kind of rude/aggressive conversation is not a nice feeling.

**Comment by zzzeek** [comment]
I'm sorry I was not trying to be rude, I was a little puzzled why you asked how we can solve this problem after I thought I pretty clearly explained how to solve this.     I've been answering thousands of these questions for about 13 years and while some have gotten heated, I wasn't trying to be aggressive on this one, I will have some colleagues review what I wrote here to try to help me see it, sorry.

**Comment by auvipy** [comment]
From a maintainer perspective IMHO it doesn't seem to be rude to be that rude to me, some times I also feel the same @zzzeek

**Comment by dianaclarke** [comment]
Kudos @silky for providing a stand-alone executable that demonstrates the issue you are facing. I was quickly able to pip install sqlalchemy into a virtualenv and run your snippet without issue. The lack of stand-alone examples is a recurring frustration for maintainers, so I applaud your efforts and I'm sure @zzzeek appreciates them too.

I think it's clear from @zzzeek's responses that he took the time to understand the intent behind the code snippet you provided, and tried to point you in the right direction. He did that for free (at the expense of family and paid work), and faster than one would expect in a corporate environment. And you're right: he probably does know best – I would follow any advice he has the time to give you.

That said, this line: "Use the documented API.... ? I'm not sure what the problem is" would probably have upset me too. That feedback has been sent to @zzzeek. I don't think it was particularly harsh (and for sure not meant to be), but code reviews etc always feel more raw in the moment.

And yes, I would be frustrated too. Hooking up SQLAlchemy correctly is getting in the way of building the thing you want to build. The fun stuff. Same reason I hate setting up a new development environment. Hoops I have to jump through to get to the fun. Could be worse though... at least someone else built the ORM...

When the dust settles at work, perhaps you could submit a pull request to clarify the docs you struggled with?
