### ISSUE TITLE
Emit subquery that doesn't use EXISTS with .has()

### ISSUE THREAD

**Issue by taion** [sqlalchemy/sqlalchemy#4607]
Apologies in advance if this would be better-suited for the mailing list rather than the issue tracker.

As documented, when using `.has()`, a subquery with `EXISTS` is always generated. However, to the best of my understanding, in some cases, this is not ideal.

Specifically, when the relevant foreign key is non-nullable, instead of emitting:

```sql
SELECT
  ...
FROM
  children
WHERE
  EXISTS (
    SELECT
      1
    FROM
      parents
    WHERE
      size > 3
      AND parents.id = children.parent_id
  )
```

We can obtain the same result with something like:

```sql
SELECT
  ...
FROM
  children
WHERE
  (
    SELECT
      size > 3
    FROM
      parents
    WHERE
      parents.id = children.parent_id
  )
```

Against PostgreSQL, at least, the latter seems to be more performant than the former – the query plan looks equivalent to what would happen with a join, while the former involves some expensive scans. Currently it's possible to obtain such queries by writing a subquery by hand.

It would be nice if `.has()` automatically worked in this manner.

But it's very possible that I'm just misunderstanding something here, or if this would break the contract that `.has()` is supposed to have! Apologies if so.

**Comment by zzzeek** [comment]
Hi there -

Re: mailing list, yes I sort of like things to start on the mailing list, but github has apparently an immense gravitational pull so it seems to be moving here where I label things just as "question".

In this case, this seems like a feature request for SQL optimization.    There isn't a generic "has()" SQL expression element right now which means it cannot render different SQL for different databases, and the SQL you have above seems like something that isn't going to work on most other databases, because it appears to be interpreting the results of a subquery as a boolean.   That's explicitly what the "EXISTS" is meant to do.

Also, very sophisticated databases like Postgresql are supposed to be able to optimize small things like this on their own.   Have you tested against many PG versions including the latest 11.2 series ?   Can you share query plans with Postgresql developers?

Perhaps a way to handle this would be a new construct called something like "SelectBoolean", which explicitly means, "return a WHERE clause that represents True if the given select returns rows", and then *that* comes out as an EXISTS in most cases.    

I can accept PRs for the above idea but someone would need to do the work to determine which backends the above SQL works with, if it even works for older versions of PostgreSQL like the 8.x series which we still support.

**Comment by zzzeek** [comment]
Tried to see if maybe EXISTS can be used differently, but on Oracle which is where we look to get the lowest common denominator for SQL syntax, nothing works:
```
-- what we do now, OK
SQL> SELECT 1 FROM DUAL WHERE EXISTS (SELECT 1 FROM foo WHERE data > 3);

no rows selected

-- everything else, nope
SQL> SELECT 1 FROM DUAL WHERE EXISTS (select data > 3 FROM foo);
SELECT 1 FROM DUAL WHERE EXISTS (select data > 3 FROM foo)
                                             *
ERROR at line 1:
ORA-00923: FROM keyword not found where expected


SQL> SELECT 1 FROM DUAL WHERE (SELECT data > 3 FROM foo);
SELECT 1 FROM DUAL WHERE (SELECT data > 3 FROM foo)
                                      *
ERROR at line 1:
ORA-00936: missing expression


SQL> SELECT 1 FROM DUAL WHERE (EXISTS data > 3 FROM foo);
SELECT 1 FROM DUAL WHERE (EXISTS data > 3 FROM foo)
                          *
ERROR at line 1:
ORA-00906: missing left parenthesis


SQL> SELECT 1 FROM DUAL WHERE (EXISTS SELECT data > 3 FROM foo);
SELECT 1 FROM DUAL WHERE (EXISTS SELECT data > 3 FROM foo)
                          *
ERROR at line 1:
ORA-00906: missing left parenthesis


SQL> SELECT 1 FROM DUAL WHERE EXISTS (SELECT data > 3 FROM foo);
SELECT 1 FROM DUAL WHERE EXISTS (SELECT data > 3 FROM foo)
                                             *
ERROR at line 1:
ORA-00923: FROM keyword not found where expected



```

**Comment by zzzeek** [comment]
hey there.

looking at this again, I think before we get into this we would need a lot more detail on exactly what the performance differences are.    Per https://www.percona.com/blog/2020/04/16/sql-optimizations-in-postgresql-in-vs-exists-vs-any-all-vs-join/ , if I'm skimming this correctly ( :)  ) there should not be any difference between the various syntaxes, where here it might be nice to try using the PG ANY() operator even.  PG has the smartest SQL optimizer out there and for the performance case I'd need to see the dataset being tested and the plans and also what PG version this is against; if PG had an optimizer issue in pg9 or 10 that is solved in 12 we shouldn't be doing this.

in any case this is kind of an esoteric use case that has a workaround, so it's not really a 1.4 deliverable, as 1.4 is already enormous and we don't want to make any more behavioral changes that aren't absolutely necessary at this point.

I'd like to learn a lot more about it before building out a new "selectboolean" kind of thing, this seemed easy to me when I commented but like everything, it's more code which needs a lot of tests and ongoing maintenance.

**Comment by taion** [comment]
Right, I'm not sure either. This was against 9.6 at the time, and the service in question now runs against PostgreSQL 12. This only came up for for a single query, too, and hasn't come up in other cases that seemed similar at a glance.

At any rate, I've also left the company where I hit this performance case at all, so I don't have the means to meaningfully reproduce this any more. I'm CCing @sloria who might care – this showed up in the context of some complex permissioning filters... there might still be a FIXME in the codebase pointing at this issue.

**Comment by zzzeek** [comment]
I think for now we don't have a real action plan here and not really anyone asking for improvements here.  The EXISTS thing is not great but I don't at the moment have an actionable improvement to make.
