### ISSUE TITLE
consider better control of the xid with 2pc, gather use cases for this API and determine the best course of action

### ISSUE THREAD

**Issue by braincore** [sqlalchemy/sqlalchemy#4608]
Currently, calling `sess.prepare()` will automatically generate an `xid` for the `PREPARE TRANSACTION` statement. I would like to use an `xid` generated by my application.

The reason is that I'd like to pass the `xid` to the transaction manager with confirmation prior to `PREPARE` so that there's no chance of the `xid` being untracked (application crashes in between `PREPARE` and sending the `xid`).

Also, as a side note, is there an easy way to extract the `xid` from a session?
```
for k, v in sess.transaction._connections.items():
    print('xid', v[1].xid)
```

**Comment by zzzeek** [comment]
Hi there -

thanks for the clear question.

There are reasons that what you describe is not very simple.   First off, the "xid" passed to prepare() is specific to PostgreSQL.   On Oracle, the xid has to be generated at the begin().  So the API only allows for xid at the level of begin_twophase().   The xid can be passed at this level when using [the connection object](https://docs.sqlalchemy.org/en/latest/core/connections.html?highlight=begin_twophase#sqlalchemy.engine.Connection.begin_twophase).

Next, the Session itself does not manage just one Connection/Transaction, it is intended to manage any number of connections/transactions simultaneously.   So if it were to allow the xid to be specified, this xid would be shared among all the prepared transactions across all the databases it talks to which could even be of different vendors.   That is *probably* still a desirable effect, but again the Oracle dialect has it's own XID generation scheme which suggests we might not be able to assume xids don't have more formatting requirements that are backend specific, which suggests this API (that is, pass an xid to the Session somehow) is not really sufficient for the "specify an XID use case".

In the bigger scheme, the Session's normal use case does not include an explicit call to begin(), as begin() only applies to the "autocommit" use case which will be going away eventually.

So the best I can see for this use case is that `Session` needs a method by which xid can be passed only before any connections have started a transaction:

    sesssion.set_next_xid(xid)   

Above, the xid will be used on the next SessionTransaction for all begin_twophase() calls.   If the SessionTransaction has any connections already procured from any engines, the above call raises an error.    The xid is assigned to the current SessionTransaction only.

Additionally, set_next_id() can accept individual Engine objects so that it can match these xids to engines:

   session.set_next_xid(xid, some_bind)

Above, set_next_xid() raises an error if some_bind already has a transaction in play, or if some_bind is not an engine registered as a bind within the session.

I can accept PRs for the above feature that include complete tests in test/orm/test_transaction.py

All of that said, there are ways to pass the xid in now that don't involve sending the xid through the Session.     There are probably ways to inject it using events, while this could maintain the Session creational pattern it would be otherwise a little involved.  However, for your use case I would think if you are seeking this level of transaction control you might be better off doing this at the Connection level directly using the [joining a Session into an external transaction](https://docs.sqlalchemy.org/en/latest/orm/session_transaction.html#joining-a-session-into-an-external-transaction-such-as-for-test-suites), at least that will get you what you want right now:

```
with engine.connect() as conn:
    with conn.begin_twophase(xid=my_xid) as trans:
        sess = Session(conn)    

        # work with session
        sess.commit()   # won't actually commit
   # commits here outside the block

```

so above, the xid is available as trans.xid.    

So for visibility into the SessionTransaction, that would be nice to have but we don't have that right now.   There would need to be a public API that includes tests in order for this to be available in a forwards compatible way.     Again this is something I am open towards API proposals and pull requests for proposals that are approved.

**Comment by zzzeek** [comment]
one wrinkle with the "SessionTransaction visibility API" is that the API of Connection / Transaction might be changing fairly dramatically in 2.0 where there would not necessarily be a separate Transaction object, not sure yet.

**Comment by braincore** [comment]
Sorry for the delay. Just to get a hang of things, I'm trying the "joining a Session into an external transaction" approach. One hiccup is when calling `conn.close()` it issues a `ROLLBACK PREPARED` statement likely because it knows it's a 2pc and has issued a `PREPARE` call; I haven't delved deep into the actual implementation yet.

That problem along with your pseudo-code makes me wonder whether we have a different understanding of what should go on. Modifying what you wrote above, here's my approach:

```
notify_2pc_tx_mgr_of_new_xid(my_xid)
with engine.connect() as conn:
    with conn.begin_twophase(xid=my_xid) as trans:
        sess = Session(conn)    

        # work with session
        sess.commit()   # won't actually commit
        trans.prepare()  # prepare for commit
# at this point, conn can return to the pool, and transaction/session can be closed.
# now that the xid is fully detached from the connection/transaction/session
notify_2pc_tx_mgr_to_commit(my_xid)
# from here, the 2pc_tx_mgr (running on a different server) can run `COMMIT PREPARED`.
```

Does the above match your understanding of the flow? On my brief usage and examination of the code, SA appears to assumes that the session that calls `PREPARE TRANSACTION` is also the one to call `COMMIT/ROLLBACK PREPARED` which is the root of the behavior mismatch. I noticed this same behavior with `horizontal_shard.ShardedSession` as well.

I'd expect my approach to be the common case and the default behavior of SA w.r.t. 2pc to be somewhat misleading. But then again, I'm new to transaction managers. Thoughts?

**Comment by zzzeek** [comment]
> Sorry for the delay. Just to get a hang of things, I'm trying the "joining a Session into an external transaction" approach. One hiccup is when calling `conn.close()`, it issues a `ROLLBACK PREPARED` statement likely because it knows it's a 2pc and has issued a `PREPARE` call; I haven't delved deep into the actual implementation yet.> 
> That problem along with your pseudocode makes me wonder whether we have a different understanding of what should go on. Modifying what you wrote above, here's my approach:
> 
> ```
> notify_2pc_tx_mgr_of_new_xid(my_xid)
> with engine.connect() as conn:
>     with conn.begin_twophase(xid=my_xid) as trans:
>         sess = Session(conn)    
> 
>         # work with session
>         sess.commit()   # won't actually commit
>         trans.prepare()  # prepare for commit
> # at this point, conn can return to the pool, and transaction/session can be closed.

OK this is a whole different use case, of which a certain variety of it was implemented a long time ago in terms of a connection being lost in the middle of 2pc, however, it didn't have any intent to support leaving the transaction open outside the scope of a valid connection.    At the time, it was not clear how popular 2pc would be or how far along support for 2pc in databases and Python drivers would be;   Postgresql was able to do 2pc although with extremely aggressive locking that makes it nightmarish to test, MySQL could do it, Oracle could do it, and SQL Server could almost do it with a few little glitches we couldn't figure out, but let's leave it open.

Jump ten years later.    MySQL's 2pc is still not as usable as PGs and it sees zero use, Oracle's 2pc was always unusable as well and then cx_Oracle dropped support for a key function we needed to be able to use it so we've had to drop support completely for now, and SQL Server's 2pc has continued to never really be usable nor has anyone asked for it.   The APIs we have for two phase that sort of hint at what you want to do above remain completely undocumented and nobody has ever even brought it up.

Then, someone came along and opened issue #4608.    And we're here!

So let me ease your concerns by saying, I think the best way you can do this right now is just to call PREPARE and COMMIT PREPARED yourself, or you can use psycopg2's API as well.   It looks like our API was modeled after psycopg2, or the other way around, but they added one little helper function `connection.reset()` which is what we don't implement nicely (but you can get this effect using invalidate()).   Below are three examples, using string SQL, using psycopg2's API, and finally using the SQLAlchemy tpc API that has this one hacky invalidate() step.

**example 1 - emit strings for PREPARE / COMMIT PREPARED**

```

from sqlalchemy import create_engine
from sqlalchemy.orm import Session

engine = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
with engine.begin() as conn:
    conn.execute("DROP TABLE IF EXISTS foo")
    conn.execute("CREATE TABLE foo (id integer)")

sess = Session(engine)

sess.execute("INSERT INTO foo (id) VALUES (1)")
sess.execute("PREPARE TRANSACTION '12345'")

sess.close()

# ... later ...

sess = Session(engine)
sess.execute("ROLLBACK")  # work around psycopg2's implicit transaction
sess.execute("COMMIT PREPARED '12345'")
sess.close()


with engine.connect() as conn:
    print(conn.execute("select id from foo").fetchall())
```

```
** example 2, same thing but use psycopg2's API **

from sqlalchemy import create_engine
from sqlalchemy.orm import Session

engine = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
with engine.begin() as conn:
    conn.execute("DROP TABLE IF EXISTS foo")
    conn.execute("CREATE TABLE foo (id integer)")

sess = Session(engine)

sess.connection().connection.tpc_begin('12345')
sess.execute("INSERT INTO foo (id) VALUES (1)")
sess.connection().connection.tpc_prepare()
sess.connection().connection.reset()

sess.close()

# ... later ...

sess = Session(engine)
sess.connection().connection.tpc_commit('12345')
sess.close()


with engine.connect() as conn:
    print(conn.execute("select id from foo").fetchall())
```
** example 3, use SQLAlchemy's API **

```

from sqlalchemy import create_engine
from sqlalchemy.orm import Session

engine = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
with engine.begin() as conn:
    conn.execute("DROP TABLE IF EXISTS foo")
    conn.execute("CREATE TABLE foo (id integer)")

conn = engine.connect()
trans = conn.begin_twophase(xid='12345')
sess = Session(conn)

sess.execute("INSERT INTO foo (id) VALUES (1)")

sess.commit()   # won't actually commit
trans.prepare()  # prepare for commit

conn.invalidate()  # closes the connection.   this is where we would call psycopg2.reset()

# ... later ...

conn = engine.connect()
conn.commit_prepared('12345', recover=True)



with engine.connect() as conn:
    print(conn.execute("select id from foo").fetchall())
```

> 
> Does the above match your understanding of the flow? In my brief usage and examination of the code, SA appears to assumes that the session that calls `PREPARE TRANSACTION` is also the one to call `COMMIT/ROLLBACK PREPARED`, which is the root of the behavior mismatch. I noticed this same behavior with `horizontal_shard.ShardedSession` as well.

What I'm going to do, since no DBAPI supports this API at all and there is a huge rewrite of how engines/connections work in SQLAlchemy 2.0, is take out the entire 2pc thing for now and document just for Postgresql that one can use the psycopg2 API directly.  None of this stuff works on any other backend.

> 
> I'd expect my approach to be the common case and the default behavior of SA w.r.t. 2pc to be somewhat misleading. But then again, I'm new to transaction managers. Thoughts?

the common case was coordination of a single prepare() across multiple database engines so that there would not be a partial commit.  Leaving the xid open in the DB engine with no active connection was never the intent of the API.

**Comment by zzzeek** [comment]
I'm not really sure how one uses the 2pc "leave the transaction by itself" feature in practice; the database only allows for a certain configured number of prepared transactions at once, and if no applications attend to them, they stay forever, keeping everything they are using locked.  How do you accommodate for that? Do you have aggressive cronjobs looking for failed transactions ?   Just from my limited testing the prepared transactions in PG are kind of a nightmare to deal with.

**Comment by braincore** [comment]
Thanks for those snippets! I have it all working using example 3. I'm going to do some performance testing, but sounds like there's a non-trivial chance those results will be abysmal. Can't wait to find out!

There are two assumptions that lead to my approach:
1. If a prepared transaction isn't committed, it'll hold locks potentially indefinitely. That's terrible and can grind the DB to a halt. Sounds like we agree.
2. In a typical web application, there's a web server tier that connects to the database tier, i.e. web servers are database clients. Web servers are built to be stateless and are spun up and spun down regularly; processes on web servers are often killed rather than cleanly wound down.

Taking the two together, what's going to happen if you have web servers be solely responsible for `COMMIT PREPARED` after `PREPARE TRANSACTION`? Over time, you'll have inopportune failures that'll grow the number of prepared transactions that may only have partially committed which ties up locks and invalidates application-level data integrity.

Given this architecture, you can either:
1. Make web servers stateful and have them persist transactions to disk in case of reboot. This is very unfavorable in modern architectures.
2. Introduce a separate transaction manager that's stateful and ensures that all transactions are committed quickly and reliably even in the event of server failures. It's very much event based, and not an aggressive cronjob :) except on process restarts.

Within bucket #2, you can do my approach which is to introduce a thin transaction manager that's only used for important cross-shard queries (minimizing performance concerns). The other approach is to introduce a DB-proxy layer. Web clients speak to this proxy layer via a proprietary API (or maybe SQL could be used), but the proxy is stateful and is responsible for all communication with the DB backends. The current SA interface is more amenable to this second approach.

**Comment by braincore** [comment]
By the way, do you have any indication that 2pc uses more locks than what's ordinarily being used by the non-2pc transaction? Is it simply a matter of the duration those locks are held?

**Comment by zzzeek** [comment]
> By the way, do you have any indication that 2pc uses more locks than what's ordinarily being used by the non-2pc transaction? Is it simply a matter of the duration those locks are held?

it doesn't use more locks than normal, to my knowledge, it's just those locks are sitting there permanently so even restarting your application is not sufficient if it is crashing due to locks.

**Comment by zzzeek** [comment]
there was something in your earlier comment that led me to my notion that our 2pc API is insufficent, when you said:  "# at this point, conn can return to the pool, and transaction/session can be closed. #"

but your original stated use case is that you only wanted to control the XID in case the application crashed.

The big thing we are missing is an intuitive way of intentionally returning a connection to the pool while leaving the prepared trans sitting in the database.     I'm talking to the zope.transaction people and they don't support this use case either which suggests I might have jumped too fast here.

do you actually intend to leave the prepared trans in the DB for another process to pick up *intentionally* ?  or is your use case strictly one of when the application crashes ?  because if the latter, our API is still mostly fine except for control of the xid thing.

**Comment by braincore** [comment]
I see & agree with how you're leaning. For testing/development purposes, I became focused on funneling all 2pc through the transaction manager. But really, there's nothing wrong with keeping the COMMIT PREPARED on the web server for the happy path as long as the transaction manager has a record for recovery purposes.

For PG, the requests I have are then:
1. The original request to have the application specify xid.
2. For the session to know to issue `ROLLBACK` unless `prepare()` has been called at which point it should use `ROLLBACK PREPARED`.

Thanks for the help and sorry for the bit of circuitousness.

**Comment by zzzeek** [comment]
AFAIK #2 is already the case provided ?   or have you observed that it doesn't do that? 

another thought I have here is that if you have a Session that does not specify "twophase", is there a way to have it begin a two phase trans on an ad hoc basis in any case.   right now of course I lean on the "use an external connection" use case but that's a bit inconvenient.

**Comment by zzzeek** [comment]
mmm it seems to know during rollback if the prepare happened or not: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/base.py#L2494

**Comment by braincore** [comment]
Sorry for dropping off. I've been meaning to do a minimal repro but haven't found the time as it all started as a quick experiment to migrate to v1.4.

**Comment by zzzeek** [comment]
it doesn't seem like there's anything to do here.    can be reopened if we can get specific action items.
