### ISSUE TITLE
question: "partial"/semi-calculated primary key?

### ISSUE THREAD

**Issue by herbygillot** [sqlalchemy/sqlalchemy#4630]
Suppose I have a DB table where I desire the combination of two columns, `id` and `version`, to be treated as the primary key.

What would be the best way to approach setting up a mapped object in SQLAlchemy such that the object itself uses only `id` as its primary key identity, with `version` being automatically looked up (for the max version present, for example)?  And perhaps automatically calculating the value for `version` on object creation (ie., incrementing from the value of the highest currently present in the db)?

I very much appreciated the versioning examples included in the SQLAlchemy wiki and examples directory, but I'm still for the most part unclear about the above.

**Comment by zzzeek** [comment]
> Suppose I have a DB table where I desire the combination of two columns, `id` and `version`, to be treated as the primary key.
> 
> What would be the best way to approach setting up a mapped object in SQLAlchemy such that the object itself uses only `id` as its primary key identity, 

the primary key of the mapping can vary independently of the primary key on the Table metadata by using the "primary_key" argument to mapper(), which in declarative is under __mapper_args__, e.g.   

```
class Foo(Base)
    # ...
    id = Column(...)
   version = Column(...)
   __mapper_args__ = {"primary_key": id}

```

> with `version` being automatically looked up (for the max version present, for example)? 

you  need to augment Query with a before_compile() event which adds the "max" criteria as a correlated subquery: https://github.com/sqlalchemy/sqlalchemy/wiki/FilteredQuery   warning, correlated subquery on every row does not perform well.  Prefer to use the history table pattern (e.g. archive the previous row into a separate table) if you only need to look up the most recent version of things.

>  And perhaps automatically calculating the value for `version` on object creation (ie., incrementing from the value of the highest currently present in the db)?

Not clear what you refer towards as object "creation", usually the "version" refers to new versions of the *same* object.  When an object is "created" in Python, it's considered "transient", there is no database context present.   The new max version_id can be looked up using either the before_insert() or before_update() events ( https://docs.sqlalchemy.org/en/13/orm/events.html?highlight=before_insert#sqlalchemy.orm.events.MapperEvents.before_insert ) depending on what exactly you want to do.   But this also this assumes you are setting the integer primary key up front, not relying upon autoincrement, as you will need the "id" to be available before an INSERT proceeds (unless you start at version 1 for an INSERT and are incrementing on UPDATE, it's not clear) in order to perform your query in order to get the next version id.

**Comment by herbygillot** [comment]
As always @zzzeek, I am most appreciative of your always deeply insightful and very prompt responses.  Thank you for pointing me in the right direction.  I like the idea of a custom Query object as it makes it easier for me to set intent on the query (like `query(Someobj, include_deleted=True).at_version(35)`), but the `before_compile` definitely makes sense as the point where the actual action should happen.

**Comment by zzzeek** [comment]
ok closing this for now.
