### ISSUE TITLE
Differences beetween calling Stored Procedure for Sybase with SQL Alchemy and raw SQL

### ISSUE THREAD

**Issue by pwalaszkowski** [sqlalchemy/sqlalchemy#4671]
Hi Guys,

I've stucked with very weird thing. I want to execute some stored procedures throught SQL Alchemy. So first i've prepared my engine:

```
from sqlalchemy import create_engine
from sqlalchemy.orm import create_session
from sqlalchemy import text
from configuration import Configuration

class SybaseDatabase:
def __init__(self, driver="Adaptive+Server+Enterprise"): 
self.engine = create_engine("sybase+pyodbc://{}:{}@{}/{}?driver={}&port={}". format(Configuration.DB_USER, Configuration.DB_PASSWORD, Configuration.DB_HOST.split(":")[0], Configuration.DB_NAME, driver, Configuration.DB_HOST.split(":")[1]), echo=True) `

        self.engine.dialect.identifier_preparer.initial_quote = ""
        self.engine.dialect.identifier_preparer.final_quote = ""
        self.session = create_session(self.engine, autocommit=True)`

    def get_session(self):
        """
        Retrieves current session.
        :return: current session.
        """
        return self.session

    def close_session(self):
        """
        Closes all open sessions.
        """
        self.session.close_all()

    def execute_query(self, query, commit=True):
        """
        Executes query passes as a parameter.
        :param query: passed query to be executed.
        :param commit: if True session will be committed
        :return query execution results
        """
        if commit:
            self.session.begin()
            results = self.session.execute(text(query))
            self.session.commit()
        else:
            results = self.session.execute(text(query))
        return results

    def execute_query_from_file(self, sql_file):
        
        Executes query passed from file.
        :param sql_file: file containing query to be executed
        :return: query execution results
        """
        with open(sql_file) as file:
            query = file.read().strip()
        self.session.begin()
        results = self.session.execute(query)
        self.session.commit()
        return results

    def __del__(self):
        self.session.close_all()
```

Then i'm just trying to execute prepared queries with calling a stored procedure. 
First i calling it throught from pure SQL tool and it works well.  
Then i do the same using Python and SQL Alchemy by putting the path in 
def execute_query(self, query, commit=True): method.

Unfortunately by some ways it doesn't work my SP return me error codes which are defined in it.
I am printing out the SQL (echo=True) and grab this SQL and put in into SQL tool and it works fine.

Any leads? I make approach with SQL Alchemy and simple pyodbc and cursor solution, both not works for me.

Thanks

**Comment by zzzeek** [comment]
hi there -

for stored procedures, it is best to use the DBAPI interface directly, which is documented for this case at: https://docs.sqlalchemy.org/en/13/core/connections.html#calling-stored-procedures.  the DBAPI has a method "callproc" that is usually required for procedures.  

Since stored procedure calls are very specific to how the database interface works and how it deals with parameters, an application that is making use of a procedure is already very specific to that target database and likely the driver so it's much more straightforward just to work with what the DBAPI gives you.     SQLAlchemy could build a big interface around all of this but it would more likely get in the way of things rather than helping, since the SP use case is both extremely different on all the target databases and additionally is not very SQL-ish in any case.

On top of all of that, the Sybase dialect is *really* tenuous, the main DBAPI hasn't had a release in about eight years, we tried having continuous test coverage for Sybase but it was too difficult to keep Sybase running , so the dialect here is almost unmaintained.

**Comment by zzzeek** [comment]
hope this helps feel free to reopen for more questions thanks!
