### ISSUE TITLE
High memory footprint when using relationship

### ISSUE THREAD

**Issue by dima-starosud** [sqlalchemy/sqlalchemy#4672]
Using `sqlalchemy-1.3.3`, `Python 3.5.5`.
In our project we use inheritance to allow separated customization. We have 10 main models (we call them *customizable*), which are inherited from for each client.
Here is [the script](https://github.com/sqlalchemy/sqlalchemy/files/3167001/main.txt) which I used to measure memory consumption. It has following interface `python main.txt R C`. It adds `R` relationships to base class and inherits from it `C` times.
When I played with it for me it looked like each replication of a relationship `rel` (e.g. `Y1.rel`, `Y2.rel`) used 10KB.

```
root@dcb1a462de97:/service# python main.txt 1 0
1615841
root@dcb1a462de97:/service# python main.txt 1 10
1791973
root@dcb1a462de97:/service# python main.txt 1 100
3152911
```

Currently we have 500 clients. Each customizable model has ~15 non-custom relationships (which are replicated for all clients):
```
root@dcb1a462de97:/service# python main.txt 15 500
67315250
```
And this number multiplied by number of customizable models gives us almost 700MB.
It's an issue for us.
Is there a way to reduce this?

**Comment by zzzeek** [comment]
Can you clarify how many actual relationship() objects are created for "15 500" ?  does that mean you have 7500 relationship objects in a single process?

**Comment by dima-starosud** [comment]
`python main.txt 15 500` will create only 15 relationship. It basically will do:
```
class Y(Base):
    r_1  = relationship(...)
    r_2  = relationship(...)
    ...
    r_15 = relationship(...)

class Y1(Y):
    __mapper_args__ = ...

class Y2(Y):
    __mapper_args__ = ...

...

class Y500(Y):
    __mapper_args__ = ...
```

**Comment by zzzeek** [comment]
so you are working with 500 polymorphic identities, which are dynamically created.   So that's not a branch that the ORM has been optimized for.  Polymorphic identities weren't intended to be used at that scale, however, I can't say how things would be different if you simply had 500 separate mappers in any case.    

does your test improve at all if you put some gc.collect() in there ?

additionally, when you say "500 clients", you mean multi-tenant customers ?    I'd be very concerned about scaling the complexity of the program in-memory in proportion to the number of tenants, whether its 50 or 5000 you will hit a vertical limit in any case.  that is, this is vertically scaled.

**Comment by zzzeek** [comment]
this is how you can see the per-class instrumentation for each relationship:

```
diff --git a/lib/sqlalchemy/orm/attributes.py b/lib/sqlalchemy/orm/attributes.py
index f37928cc1e..71976714bb 100644
--- a/lib/sqlalchemy/orm/attributes.py
+++ b/lib/sqlalchemy/orm/attributes.py
@@ -766,6 +766,8 @@ class ScalarAttributeImpl(AttributeImpl):
         super(ScalarAttributeImpl, self).__init__(*arg, **kw)
         self._replace_token = self._append_token = Event(self, OP_REPLACE)
         self._remove_token = Event(self, OP_REMOVE)
+        if self.uses_objects:
+            print("yup %s %s" % (arg[0], arg[1]))
 
     def delete(self, state, dict_):
         if self.dispatch._active_history:

```

AttributeImpl is using `__slots__` as are the `Event` objects, everything here is fairly slim.   an alternative archicture would be that instrumentation would be only present on the basemost class, Y, for these attributes, and then as they receive get/set events they would respond based on the parent class present.  However this decisionmaking would be complex and performance intensive, so most of what you see in mappings is highly optimized for speed, not so much memory, which means figuring out as much as possible up front for re-use.     memory use would only get worse as SQLAlchemy adds more kinds of caching.     

As this example illustrates single-table inheritance, it's not clear what kinds of "customizations" you're dealing with;  often, it's schema level customizations but that doesn't apply here since this is just one table.  Would need to see exactly the nature of these "customizations" for further insight.     Short of that, sharding out the application to separate processes / servers based on a modulus of the "client" would be how to scale this more immediately, but the overall use case is not clear yet.

**Comment by dima-starosud** [comment]
Customization is not an issue. It's just a good use case for polymorphic mappers.
Let me try to explain this issue from scratch using the code. So there is class `Y` and 500 child classes:

    class Y(Base):
        __tablename__ = 'y'
        id = Column(Integer, primary_key=True)
        kind = Column(Integer, nullable=False)

        __mapper_args__ = {'polymorphic_on': kind}

        r_1_id = Column(Integer, ForeignKey(X.id), nullable=False)
        r_1 = relationship(X, foreign_keys=r_1_id)


    class Y1(Y):
        __mapper_args__ = {'polymorphic_identity': 1}

    ...

    class Y500(Y):
        __mapper_args__ = {'polymorphic_identity': 500}


Adding one more relationship to class `Y`

    class Y(Base):
        ...
        r_2_id = Column(Integer, ForeignKey(X.id), nullable=False)
        r_2 = relationship(X, foreign_keys=r_2_id)

increases memory footprint by almost 5MB (note children are not touched).
You can reproduce this issue using script I provided:

    root@dcb1a462de97:/service# python main.txt 1 500
    9166189
    root@dcb1a462de97:/service# python main.txt 2 500
    13546700

**Comment by zzzeek** [comment]
Hi there -

I ran your script and also evaluated what the source of the memory use is, and as mentioned above, it's because SQLAlchemy creates attrbute-tracking objects for each relationship upon each subclass.    

in searching for a way to provide support, I took your question "Is there a way to reduce this?" at face value.   The answer I can give you for the near term is, don't make 500 mapped classes.  This was why I was trying to evaluate your use case and see if there's a better way you might achieve what you need to do.    if the question really meant, "is there way for SQLAlchemy to use significantly less memory for 500 classes", the answer right now is unfortunately no, as I mentioned, there's already been a significant improvement in this area which [redudced the memory taken up by SQLAlchemy ORM internals by 50%](https://docs.sqlalchemy.org/en/13/changelog/migration_10.html?highlight=__slots__#significant-improvements-in-structural-memory-use).   As mentioned above, the basic architectural issue that each of the mapped subclasses sets up its own instrumentation objects is the source of most of the problem, and to change that would require that the single descriptor do lots more runtime work for every attribute operation, which would be a significant impact on performance at a critical level.   

This is not to say that there aren't some more big memory wins hiding here but as there has already been significant effort in this area it's unclear if it's worthwhile to prioritize this right now, unless people want to spend some time looking into it further.

**Comment by dima-starosud** [comment]
Thank you @zzzeek for such a detailed explanation.
We will try another approach for customization then.

**Comment by zzzeek** [comment]
OK, sorry i could not be of more help at the moment.
