### ISSUE TITLE
remove util.dependency_for; use module cross-assignment

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4689]
dependency_for is going to make type annotations difficult and is also as we see in #4656 they break type annotations also.   As we see in https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1244/ we can go back to using cross-module assignment, let's see if this is feasible.  I remember that there might have been some situations where nothing except dependency_for() worked, but let's give it another try.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Remove dependency_for utility function** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1773

**Comment by CaselIT** [comment]
Ok so neuron imports RelationshipProperty from properties, instead of orm directly.
Maybe the internal packages of sqlalchemy should me marked as private in the doc, meaning that users should not import directly from them.

I guess we can manually add it in the `__init__` or use a `def __getattr__(name)` in the `properties` module that imports it on demand

Also py27 fails the test with import error but py3 has success :\

**Comment by zzzeek** [comment]
you'd want to rename the files as "_properties.py" ?     for the moment, I think we need to support the various import paths that have been out there for a long time.

**Comment by zzzeek** [comment]
noting that they are likely in the docs, because it's very difficult to control the module that's displayed when you do sphinx docstrings

**Comment by CaselIT** [comment]
Without using imports in functions py27 does not seem to work, but I'll try having another look at it.
Also `__getattr__` at the module level is nice, but sadly only 3.7+ https://www.python.org/dev/peps/pep-0562/

> you'd want to rename the files as "_properties.py" ? for the moment, I think we need to support the various import paths that have been out there for a long time.

No have a warning like this warning https://pandas.pydata.org/pandas-docs/stable/reference/index.html#api

**Comment by CaselIT** [comment]
So py3 import (or at least py3.7) seems to allow partially imported modules, so cyclic reference error happen only if a partial module is used while loading another module, like if extending a class from the partial module. If it's only referenced inside function/methods it works.

I can try to solve this together with #4656, by using imports inside the function, with a decorator that ensures that the required modules are imported, so that they become noop, and we avoid thread safety problems.
