### ISSUE TITLE
module 'time' has no attribute 'clock' in python3.8b1

### ISSUE THREAD

**Issue by NewUserHa** [sqlalchemy/sqlalchemy#4731]
`use time.perf_counter instead`

**Comment by zzzeek** [comment]
hi there -

from your PR I can see that you've located this function in the compat.py module.    However, this function does not appear to be used, at least based on a grep, and if so, is likely from some very old performance-related tests that have long since been rewritten to use profiling.

So as is usually the case I require additional information, have you encountered some use case where this function was actually used?  Or have you located this function based on a code inspection only ?   course of action for the moment would appear to be to simply remove it.

**Comment by NewUserHa** [comment]
that's not my PR.
that issue content is copied from traceback.
it used just some simple functions from sqlalchemy but I don't have a complete example code of it

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Remove unused "time_func"** https://gerrit.sqlalchemy.org/1319

**Comment by zzzeek** [comment]
The functions in compat.py are not public API.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Remove unused "time_func"** https://gerrit.sqlalchemy.org/1320

**Comment by zzzeek** [comment]
the time_func was no longer used as of 07130c7a8b5c58e744c27c7b1 which was #2379
