### ISSUE TITLE
correctly detect "NO ACTION", "RESTRICT", do not include "NO ACTION" in reflection results, add tests

### ISSUE THREAD

**Issue by saletnik** [sqlalchemy/sqlalchemy#4741]
Bug in 

https://github.com/sqlalchemy/sqlalchemy/blob/1ed2f1621510b48a6c46bedf3dd579c56bd89ccb/lib/sqlalchemy/dialects/mysql/reflection.py#L426

there is no such action as "NOACTION"
should be

> kw["on"] = "RESTRICT|CASCADE|SET NULL|NO ACTION"

**Comment by zzzeek** [comment]
Hi there -

Looking more closely here, this issue is not that simple.

The "NOACTION" typo here has been that way for 12 years and has had no impact, which is for two reasons, nobody actually uses "NO ACTION" as it is essentially the default, and even if they did, that it is reflected back as nothing is still "correct", since it's the default.

MySQL's "NO ACTION" is also equivalent to their own "RESTRICT".   Some versions of MariaDB/ MySQL don't report "RESTRICT" in "SHOW CREATE TABLE" in any case, I'm testing it now and it seems to only be coming back as of MySQL 8.0, MySQL 5.7 isn't reporting it and neither is MariaDB 10.3.   

So ironically, the fact that we don't reflect "NO ACTION" is allowing two foreign keys to compare *correctly*, if one used "RESTRICT" and the other used "NO ACTION".       But , it's not a given that these two are equivalent in other cases.

As far as other databases, SQLIte is reporting back "NO ACTION" when it was set, and PostgreSQL is not, but it does report "RESTRICT".     For PostgreSQL, "NO ACTION" and "RESTRICT" are different in that "NO ACTION" supports deferrable constraints whereas RESTRICT does not, so as far as making these two equivalent, that idea goes away here.    

But there's still an inconsistency in that on various databases, if you set RESTRICT or NO ACTION, you may or may not get it back.

It seems like it might be a better solution across the board that "NO ACTION" is considered to be the default and does not actually get reported back in reflection results.   This would maintain compatibility with what the MySQL dialect has been doing for 12 years in any case as it would with the PostgreSQL dialect.

Oracle doesn't support ON UPDATE at all and at the moment it seems like we do not reflect this information for SQL Server.

Propose we add test support that "RESTRICT" comes back positively in reflection results, whereas "NO ACTION" is detected and is then dropped from the reflection dictionary, as it is the default.    this would allow for the best backwards and cross-compatibility setup.


Are you actually being impacted by this, or have you just come across this while reading the code?      This regex has had the phrase without the space for 12 years and has never produced any issues because it is the default value in any case.     Reflection of "NO ACTION" also does not return a value for PostgreSQL, as if you create the key with "NO ACTION", postgresql doesn't give it back to you, e.g. it's the default.

Additionally, MySQL calls this "RESTRICT", which is equvalent to "NO ACTION", which means a comaprison of two foreign keys one which uses "RESTRICT" and one which uses "NO ACTION" should be equivalent, 

That is, the fix here might be to remove "NO ACTION" entirely since it's the default in SQL.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Reflect "NO ACTION" as None; support "RESTRICT"** https://gerrit.sqlalchemy.org/1328

**Comment by zzzeek** [comment]
a one character typo vs. a 76 line patch.     we do it the hard way here

**Comment by saletnik** [comment]
The problem was detected when using "reflect" and "create_all" on the same object.
I expected the result to be the same as the input, but it was not.

Unfortunately, if you omit "NO ACTION", the created table will have a different definition, although it will behave the same way.
