### ISSUE TITLE
User password field and mapper

### ISSUE THREAD

**Issue by komaxko** [sqlalchemy/sqlalchemy#4742]
Greetings!

Thanks a lot for your work!

I have a problem storing user password. This field should be encrypted, but which way should I do that?
`#user table`
Users = sa.Table(
    "users",
    metadata,
    sa.Column("id", sa.Integer, nullable=False, autoincrement=True, primary_key=True),
    sa.Column("login", sa.String(256), nullable=False, unique=True),
    sa.Column("email", sa.String(256), nullable=False, unique=True),
    sa.Column("password", sa.String(256), nullable=False),
    sa.Column("is_superuser", sa.Boolean, nullable=False, server_default="FALSE"),

`#user class`

class User(object):
    def __init__(self, login, password, email):
        self.login = login
        self.password = hash_p(password)
        self.email = email

    def validate_password(self, password):
        return unhash_p(password, self.password)
`mapper(User, Users)`

in handlers I can not save User (class instance) to Users table:
`async def post(self):
        body = await self.text()
        response_obj = body
        async with self.app['db'].acquire() as conn:
            try:
                _data = json.loads(body)
                usr = db.User(**_data)
                cursor = await conn.execute(db.Users.insert(usr)
                record = await cursor.fetchone()
                return web.json_response(text=json.dumps(record, default=str))
            except Exception as e:
                return web.Response(text=str(e))`

Could you give me any advice please?

Thanks!

**Comment by zzzeek** [comment]
hi there -

the use case you are looking for has two varieties, "hashing" and "encryption".  Which one you use depends on how you need to use this password:

1. is this password field used only for users that are logging in to your website, and they will always be typing in their plaintext password for you to validate?  use hashing

2. is this password field one that you have to pass onto some other service, e.g. that you are using it to log the user into some other web service or similar elsewhere and therefore your application needs to see the plaintext password?  then use encryption


The strategy for choice 1 above is generally considered to be more secure because there is no easy way to get back the plaintext password assuming sufficiently secure passwords as well as a good hashing algorithm, whereas choice 2 is very difficult to secure because there will be a decryption key somewhere that can expose all the passwords and it's very challenging to keep this part secure.

Since I see you using the term "hash" in your example I assume you are looking for hashing.   There is a recipe that uses Postgresql's crypto feature at https://github.com/sqlalchemy/sqlalchemy/wiki/DatabaseCrypt.   Though it is likely more common that folks use Python side hashing in which case they use bcrypt: https://pypi.org/project/bcrypt/  , here's a good example of how to do that: https://stackoverflow.com/a/33717279/34549


The second part of your question seems to be using Python asyncio.   SQLAlchemy does not support asyncio and there is no valid reason to write a Python web application using async in any case - I recommend using Flask or Pyramid.

**Comment by komaxko** [comment]
@zzzeek ,

Thanks a lot for your response!

I'll ask these in aipog thread!
