### ISSUE TITLE
transaction traceability in pg >= 10

### ISSUE THREAD

**Issue by graingert** [sqlalchemy/sqlalchemy#4762]
> One feature quietly added to PostgreSQL 10 is the ability to determine the commit status of any transaction by transaction-id.

https://www.2ndquadrant.com/en/blog/postgresql-10-transaction-traceability/

It should be possible to configure SQLAlchemy to attempts a reconnect and check if a tx has committed with txid_status if a connection error occurs after issuing a "COMMIT" before bubbling the exception

**Comment by zzzeek** [comment]
I would have to find time to read the above article to understand fully what this means because it is not clicking as of yet.   however, since this is entirely specific to PG and possibly even specific PG drivers, my goal would be to *not* add this feature and to instead ensure that it can be implemented via recipe.      you can right now create error handling routines using the handle_error() event which we use in openstack extensively: https://docs.sqlalchemy.org/en/13/core/events.html?highlight=handle_error#sqlalchemy.events.ConnectionEvents.handle_error but it's not clear to me if you are suggesting that an error would not be raised at all.

There would also need to be a way to get at txid_status() from psycopg2.   If they were to support it as connection.txid_status(), you'd get this using exception_context.connection.connection.<psycopg2_api_call>.

the linked article doesn't show any code and it seems (?) not even a link to documentation, so feel free to describe a code example illustrating how this would look as well as how to get this value when using psycopg2.  thanks!

**Comment by graingert** [comment]
>  ensure that it can be implemented via recipe

Yes I figured this would actually be a docs change

**Comment by graingert** [comment]
> There would also need to be a way to get at txid_status() from psycopg2. If they were to support it as connection.txid_status(), you'd get this using exception_context.connection.connection.<psycopg2_api_call>.

According to this blog the tricky part is avoiding an extra round trip, sqlalchemy would need to issue `BEGIN; SELECT txid_current()` when flushing queries that performed a write. And issue `SELECT txid_current()` along with the first write if only 'SELECT's were issued 

> the linked article doesn't show any code and it seems (?) not even a link to documentation, so feel free to describe a code example illustrating how this would look as well as how to get this value when using psycopg2. thanks!

Here's a bit of docs https://www.postgresql.org/docs/10/functions-info.html#FUNCTIONS-TXID-SNAPSHOT

**Comment by graingert** [comment]
> but it's not clear to me if you are suggesting that an error would not be raised at all.

Yeah sort of. Essentially with this feature it's possible to recover from a connection error just after issuing 'COMMIT'

It's also possible to recover from application error after issuing 'COMMIT' if the application maintains its own "write-intent journal file"

**Comment by zzzeek** [comment]
So IIUC, it's , 1. error happens, 2. transaction cannot be continued, 3. get txid (or we have it already from the start, whichever), 4. begin new transaction, do <magic thing? docs?  recommended postgresql patterns?  >, now you are in the same state right up when the error occurred.

it's #4 that is the crazy part where the behavioral contract matters a lot.   

1. if my statement has triggers, and one of the triggers failed the transaction, did my INSERT proceed?    similar questions for many other kinds of scenarios where a single statement does multiple things, stored procedures, etc., seems very crazy

2. more basically, psycopg2.executemany() is used and it failed on parameter set number 50 of 100.  how do we know?

3. for this to be "useful", if this were some thing people really wanted with postgresql, ORM integration would be potentially very challenging.   it implies when flush() catches an error, it would have to do a partial success for the flush.   so this would require very significant changes to the unit of work since as you might be aware the rollback in flush is very definitive, and we can cleanly throw everything away and start again.  partial flushes would be a lot of work.

more basically, if this is not a big, PostgreSQL-recommended / documented process, it would have to see some mainstream adoption before we should be spending time reworking the ORM to accommodate it.

**Comment by graingert** [comment]
No this isn't it.

Consider executing:
```
BEGIN;
INSERT INTO user (name) VALUES ("example");
COMMIT; # you get a connection error here
```

How do you know if you inserted the record or not?

Also consider:

```python
cm = sess.begin()
tx = cm.__enter__()
tx.execute("INSERT INTO user (name) VALUES ('example')")
cm.__exit__()
# application is kill -9'ed
f.write(f"job {jid} completed")
```
Now you're in a situation where you've completed the job in the database but your application log is out of sync

**Comment by graingert** [comment]
You can't pick up where you left off, you just know if the transaction was committed or not

**Comment by graingert** [comment]
> it implies when flush() catches an error

No only when commit or __exit__ catches an error

**Comment by zzzeek** [comment]
oh, OK I just saw the word "recover" and my mind went into the huge world of what people always, always, want, which is, to continue a transaction when they get an error.

This is how do we know if commit failed, OK !   I dont think this applies towards a change in the unit of work code because we expire everything in the session when we rollback or commit regardless, trying to optimize for the case where we committed, it failed, but then it didn't actually fail, seems not worth it in the ORM.

But for folks who want to use this in Core, it would be best if psycopg2 had an API feature here,  but as always if you want to invoke calls upon the connection or cursor at commit time or whatever we have all the event hooks which intercept every statement and you can see which are DML and which are DQL only.

**Comment by graingert** [comment]
>  trying to optimize for the case where we committed, it failed, but then it didn't actually fail, seems not worth it in the ORM.

This isn't a performance optimization, it's for correctness.

**Comment by zzzeek** [comment]
the ORM stays correct by just throwing away all assumptions about the data after a rollback or commit.    the only reason people wouldn't like that is because it's inefficient if you are expecting to get lots of errors.

**Comment by zzzeek** [comment]
why do we have to emit BEGIN in order to `SELECT txid_current()` ?    is it because psycopg2 did not necessarily send its own BEGIN yet ?

**Comment by zzzeek** [comment]
http://initd.org/psycopg/docs/extensions.html#connection-status-constants and/or http://initd.org/psycopg/docs/extensions.html#transaction-status-constants should tell you this

**Comment by zzzeek** [comment]
the id seems to be there up front without calling anything special:
```

>>> import psycopg2
>>> conn = psycopg2.connect(user="scott", password="tiger", host="localhost", database="test")
>>> cursor = conn.cursor()
>>> cursor.execute("SELECT txid_current()")
>>> cursor.fetchall()
[(53343,)]
>>> cursor.execute("insert into a (id, data) values (5, 'foo')")
>>> cursor.execute("SELECT txid_current()")
>>> cursor.fetchall()
[(53343,)]   # it didn't change
>>> cursor.close()
>>> conn.commit()
>>> cursor = conn.cursor()
>>> cursor.execute("SELECT txid_current()")
>>> cursor.fetchall()
[(53344,)]  # new tx, new id

```

**Comment by zzzeek** [comment]
I don't have any actions to take here, mind if I close this?  use of this feature falls under PostgreSQL's documentation, not ours, IMO.

**Comment by graingert** [comment]
Ok
