### ISSUE TITLE
with_for_update() waits for lock but returns old data if object is in identity_map

### ISSUE THREAD

**Issue by reclosedev** [sqlalchemy/sqlalchemy#4774]
Minimal reproduce script:

```python
import logging
import threading
import time

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.orm import sessionmaker


OBJ_ID = "some-id"
logging.basicConfig(level=logging.INFO, format="%(asctime)s: %(message)s")
engine = create_engine('postgresql://ttt:ttt@localhost/ttt', echo=False)
Session = sessionmaker(bind=engine)
Base = declarative_base()


class Data(Base):
    __tablename__ = 'data'
    id = Column(String, primary_key=True)
    value = Column(String)

Base.metadata.create_all(engine)


def operation1():
    session = Session()
    logging.info("1 before query")
    obj = session.query(Data).with_for_update().get(OBJ_ID)
    logging.info("1 got value %r", obj.value)
    obj.value = "modified"
    logging.info("1 sleeping")
    time.sleep(2)
    session.commit()
    logging.info("1 commited")


def operation2():
    session = Session()
    logging.info("2 before query")
    # some queries use objects without attempt to modify it
    obj = session.query(Data).get(OBJ_ID)
    logging.info("2 value %r before lock", obj.value)
    # now we need to modify it
    # session.expire(obj)  # !!! expire is required
    obj = session.query(Data).with_for_update().get(OBJ_ID)
    # This query returns cached object too
    # obj = session.query(Data).with_for_update().filter(Data.id == OBJ_ID).first()
    logging.info("2 locked value %r", obj.value)
    obj.value += "-append"
    session.commit()
    logging.info("2 commited")


def main():
    session = Session()
    session.query(Data).delete()
    session.add(Data(id=OBJ_ID, value="initial"))
    session.commit()
    t1 = threading.Thread(target=operation1)
    t2 = threading.Thread(target=operation2)
    t1.start()
    t2.start()
    t1.join()
    t2.join()
    obj = session.query(Data).get(OBJ_ID)
    logging.info("Result %r", obj.value)


main()
```

Output
```
2019-07-19 11:58:07,946: 1 before query
2019-07-19 11:58:07,948: 2 before query
2019-07-19 11:58:07,951: 1 got value 'initial'
2019-07-19 11:58:07,952: 1 sleeping
2019-07-19 11:58:07,958: 2 value 'initial' before lock
2019-07-19 11:58:09,959: 1 commited
2019-07-19 11:58:09,959: 2 locked value 'initial'
2019-07-19 11:58:09,963: 2 commited
2019-07-19 11:58:09,966: Result 'initial-append'
```

As you can see, `operation2` waits for `operation1`, but returns old state.

If you uncomment 
```
session.expire(obj)  # !!! expire is required
```
then it works as expected.

Tried on 1.3.5

**Comment by zzzeek** [comment]
hi there -

thanks very much for writing a clear and complete test.    however, I don't see any behaviors that are surprising.     it's [documented](https://docs.sqlalchemy.org/en/13/faq/sessions.html?highlight=serializable#i-m-re-loading-data-with-my-session-but-it-isn-t-seeing-changes-that-i-committed-elsewhere) that there is no implicit synchronization of data between concurrent transactions and that the Session by default behaves as though transactions are fully isolated, which of course they aren't, however *how* they aren't isolated is a completely moving target across backends and isolation levels.   if the Session were tasked with guessing at what points it might need to load data that's changed externally within the scope of an ongoing transaction, it would be immensely complicated for that to be built in.     

As I write this, I wonder if perhaps a pluggable strategy approach might work here, e.g. expiration strategies that are tuned for various backends and isolation levels.  This is possible to implement right now using events.   An example for this case is below.

If you'd like the query that uses with_for_update() to definitely overwrite any objects that may be in the identity map, you can add populate_existing():

   obj = session.query(Data).with_for_update().populate_existing().get(OBJ_ID)

this works in a more general way than expire since usually a query is for an arbitrary number of rows:

   objs = session.query(Data).with_for_update().populate_existing().all()

you can then use an event hook to make this automatic.    This is the "pluggable strategy" I refer towards.    Add this event hook:

```
from sqlalchemy import event
from sqlalchemy.orm import Query
@event.listens_for(Query, "before_compile", retval=True)
def _expire_on_for_update(query):
    if query._for_update_arg is not None:
        query = query.populate_existing()
    return query


```

which will link the for_update call with the populate existing call.

A big issue with the before_compile event hook is that using it usually requires access to private members of the Query.    Eventually I'd like Query to have a better introspection API but that's where it's at for the moment.

**Comment by reclosedev** [comment]
Thank you for the detailed answer! 

Now I understand why it's valid behavior. `Query.populate_existing()` is what I was looking for.

**Comment by GregorGrasselli** [comment]
Would it be possible to mention data from the identity_map and using populate_existing to get around it in the documentation of with_for_update?

**Comment by zzzeek** [comment]
is it like a common thing that people are getting an object twice in one transaction and only using with_for_update() the second time?    I suppose a note that reminds people that objects are already present in such a case is fine.     are people not aware of the identity map or is it just useful to remind people to keep in mind that it's there?

**Comment by GregorGrasselli** [comment]
In my case, different queries are run, one of which may in some cases also contain the row to be locked. A mention in the docs would save me quite a bit of time. And yes, I was unaware of the identity map, which is definitely my fault for not taking the time to learn how it works, but just use it and read the minimal amount of docs as the need arises.
