### ISSUE TITLE
Doc suggestion: reference to @validates in the core/defaults section of the doc

### ISSUE THREAD

**Issue by msouth** [sqlalchemy/sqlalchemy#4796]
I spent a long time trying to figure out how to centrally/automatically make the 'y'/'' that Flask/WTForms gave me for a boolean into a '1'/NULL for MySQL's tinyint(1) implementation of boolean.  It's very close to the mechanisms available in the core/defaults section, and a quick mention/example there might save someone a few hours

```
    @validates('enter_time_manually','active','is_setup')
    def convert_form_strings(self, key, value):
        if isinstance(value,str):
            if value == '':
                return 0
            elif value == 'y':
                return 1
        else:
            return value
```

**Comment by zzzeek** [comment]
why not a [typedecorator](https://docs.sqlalchemy.org/en/13/core/custom_types.html#typedecorator-recipes) recipe? 

is the issue with `@validates` that you didn't know `@validates` existed, or you didn't know that it could be used that way ?

I'm also not following how this relates to column defaults.

**Comment by msouth** [comment]
I'm new to all of: Python, SQLAlchemy, Flask, WTForms.  When I looked for documentation on "how do I affect the value of a column as it goes into the database" **the place I ended up, and where I think other people are likely to end up, is the code in this section** (<--that's the answer to "how does this relate to column defaults"--it doesn't, but I think it's the shore that newbies will wash up on, so maybe we should post a sign to the correct place).  I was imagining someone not knowing validates existed and/or not realizing it could be used as a mechanism for changing rather than just checking data, so I thought a little call-out here would help them find it.

As far as "where this code should actually go", I think I should either be extending the Boolean [insert correct term here--type definition?]  to do this for all Boolean columns.  I don't want to repeat the same @validates stanza in a zillion different models.  But given my newness to the language and toolchain I thought this might be the easiest way to tackle this for now.  (Ostensibly I could be digging into WTForms to see if there is some global config where I can say that I want checkboxes to say '1', '0' instead of 'y', ''...).

**Comment by zzzeek** [comment]
> I'm new to all of: Python, SQLAlchemy, Flask, WTForms. When I looked for documentation on "how do I affect the value of a column as it goes into the database"

OK I googled it, and yes, it takes me right to here: https://docs.sqlalchemy.org/en/13/core/defaults.html

but that is google, and that is the wrong answer.   A "default" is basically the value of a column *if no value is given*.   So I can't fix google, but that's not where any of this should go.

Here is the thing.   SQLAlchemy cannot be learned, at a basic level, by googling.   You need to read [both](https://docs.sqlalchemy.org/en/13/core/tutorial.html) [tutorials](https://docs.sqlalchemy.org/en/13/orm/tutorial.html) before you should be googling anything, because a basic conceptual knowledge is essential.  You also need to know a bit about SQL, which means you'd know that a SQL default is not related to a value that you've given the database, it has to do with when there *isn't* a value.


>  **the place I ended up, and where I think other people are likely to end up, is the code in this section** (<--that's the answer to "how does this relate to column defaults"--it doesn't, but I think it's the shore that newbies will wash up on, so maybe we should post a sign to the correct place). 

google is entirely unpredictable and there are an infinite number of search terms that could lead anywhere in the documentation so I don't know how this strategy could be generalized.   We could put hundreds of "did google 'how do i do XYZ lead you here?  go here instead" and we'd basically have mowed about a square inch of a ten acre lawn.   I'm sorry google didn't give you the right page but I'm not sure this is a generally solvable problem.

> I was imagining someone not knowing validates existed and/or not realizing it could be used as a mechanism for changing rather than just checking data, so I thought a little call-out here would help them find it.

OK well @validates is not the only way to even do this.  I really think people need to just spend some quality time with the documentation and just get a top level view for whats possible.

> 
> [Edit: Yes, I think the type decorator is exactly what I'm looking for--same suggestion, though, just maybe a "if you need more than to just change defaults, such as changing the data on the way in or out, you might look at @validates or TypeDecorators depending on your needs"]

I can cross link between TypeDecorator and `@validates` because these are two related concepts.     Technically, the docs have a convention that the Core docs almost never link to the ORM docs, so at least `@validates` could mention TypeDecorator as an alternative.   But readers have to find these two concepts by just reading the table of contents and getting familair with the docs, I can't try to anticipate google hits, the docs are not updated nearly enough to keep up with whatever they are doing and there are a limitless number of potential search terms.

**Comment by zzzeek** [comment]
I will commit something to the docs here, but I haven't actually used WTForms.  Technically, things ilke converting string "Y" into boolean should be done at the web form level, not in an ORM model.   Form controls should have validation that converts from strings into Python data values like string "5" into the number 5, string dates into Python datetimes, stuff like that.     Usually a form library does that stuff.

**Comment by zzzeek** [comment]
so the work here is really part of a much larger initiative, which is that as Python, relational databases, SQLAlchemy, and programming in general now reach an audience that is dramatically expanded since the 90s and early 2000's when these tools were first built, a large portion of the audience is coming from a different perspective where phrases like "database insert /update defaults" aren't concepts the user is familiar with.   As I read the introductory paragraph at "column insert/update defaults", it clearly assumes the user has experience with DDL level column defaults as it hardly says anything, so basically an effort that can locate areas of verbiage, particularly introductory verbiage, and ensure that it defines the terminology we are using such that a non-database person can get an idea what it is, would be helpful.
