### ISSUE TITLE
Exclude Parameters from Exceptions

### ISSUE THREAD

**Issue by ambsw-technology** [sqlalchemy/sqlalchemy#4806]
Is it possible to categorically suppress parameters from being included in log messages?

As a HIPAA compliant organization, we need to limit the potential exposure of patient data.  Obviously, this is the kind of data that is passed across database drivers like SQL Alchemy.  Unfortunately, while testing, we ran into some errors (e.g. `sqlalchemy.exc.OperationalError`).  When pushing the error string to our logger, we discovered that the SQL statement **and** parameters were included.  Since the parameters *are* the patient data, this is far from ideal.  

Unfortunately, my (usually strong) google-fu could not find any information about when/how these values are injected into exceptions and (critically) if they can be categorically suppressed **at the source**.  Trying to catch and suppress them in each and every use is not practical since a single mistake could leak patient data into systems where we'd rather not store it.

**Comment by zzzeek** [comment]
Hi there -

you can intercept all the SQLAlchemy error objects which include parameters using the [handle_error](https://docs.sqlalchemy.org/en/13/core/events.html#sqlalchemy.events.ConnectionEvents.handle_error) event.   Here is a handler that will replace the raw parameter structure, which may be a dictionary, tuple, or list of dictionaries or tuples depending on the type of database and execution, with a single dictionary that includes no information:

```
from sqlalchemy import event
from sqlalchemy import engine


@event.listens_for(engine.Engine, "handle_error")
def erase_parameters(exception_context):
    for exc in [
        exception_context.chained_exception,
        exception_context.original_exception,
        exception_context.sqlalchemy_exception,
    ]:
        if exc is not None:
            exc.params = {"no_parameters": "parameters hidden"}

```

this will cover that particular case, however would not cover the case if you've turned on SQLAlchemy INFO logging, which will log SQL statements and their parameters as well.

The only way to truly guarantee a particular string can be controlled everywhere is by ensuring when this string first exists in your Python process, it is immediately tainted such that it will *never* display anywhere.   Here's a super quick one:

```
class SensitiveString(str):
    def __repr__(self):
        return "<redacted>"

```

if you use that object for your sensitive data, it will never `__repr__()`.    While you can use the SensitiveString object in your application directly, any results you get back will not use that type, which would be inconvenient since usually an application is feeding data from the database itself back into new queries, so you can use a custom datatype to ensure this string is used on all columns for which you are storing sensitive data.    Here is a demo:



```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy import TypeDecorator
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session


class SensStringType(TypeDecorator):
    """Store a string that should not be displayed."""
    impl = String

    def process_bind_param(self, value, dialect):
        if value is not None and not isinstance(value, SensitiveString):
            value = SensitiveString(value)
        return value

    def process_result_value(self, value, dialect):
        if value is not None:
            value = SensitiveString(value)
        return value

class SensitiveString(str):
    """A string that doesn't repr."""

    def __repr__(self):
        return "<redacted>"

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(SensStringType(50))


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

# in SQL logging, we won't see the parameter value, because the bind processor
# runs on the parameter before it is logged.
# Note that DEBUG logging, which we aren't using here and is not commonly
# used, will show the raw values in logged result rows.
s.add(A(id=1, data="some sensitive data"))
s.flush()

# when we get it back...
data, = s.query(A.data).first()

# the string is there...
assert data == str(data) == "some sensitive data"

# but again, no repr
assert repr(data) == "<redacted>"


# error messages are also logged with the redacted string.  Here
# we intentionally create an integrity error to demontrate
s.add(A(id=1, data="some sensitive data"))
s.commit()
```

above, you can see we deal with the sensitive data naturally, but the type handler makes sure in the majority of cases that it is automatically coerced to a SensitiveString object that will not indicate any data in its `__repr__`.     you can of course use SensitiveString objects explicitly also (likely you'd want to give them a short name like s("")) and if you really wanted to enforce explicit use of these safe strings throughout your application, you could change the "process_bind_param()" method to enforce that the incoming object is a SensitiveString object.

This should be added as a recipe to the wiki at https://github.com/sqlalchemy/sqlalchemy/wiki/UsageRecipes.   The technique above is one I used when I used to work in finance and we had an application that required PII to be encrypted in the database.  I implemented a similar approach using tainted strings like above so that they were automatically encrypted using a symmetric key going into and coming out of the DB.

**Comment by zzzeek** [comment]
output from the above demo looks like:

```
2019-08-14 23:28:29,862 INFO sqlalchemy.engine.base.Engine ()
2019-08-14 23:28:29,863 INFO sqlalchemy.engine.base.Engine COMMIT
2019-08-14 23:28:29,864 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-08-14 23:28:29,865 INFO sqlalchemy.engine.base.Engine INSERT INTO a (id, data) VALUES (?, ?)
2019-08-14 23:28:29,865 INFO sqlalchemy.engine.base.Engine (1, <redacted>)
2019-08-14 23:28:29,867 INFO sqlalchemy.engine.base.Engine SELECT a.data AS a_data 
FROM a
 LIMIT ? OFFSET ?
2019-08-14 23:28:29,867 INFO sqlalchemy.engine.base.Engine (1, 0)
2019-08-14 23:28:29,868 INFO sqlalchemy.engine.base.Engine INSERT INTO a (id, data) VALUES (?, ?)
2019-08-14 23:28:29,868 INFO sqlalchemy.engine.base.Engine (1, <redacted>)
2019-08-14 23:28:29,868 INFO sqlalchemy.engine.base.Engine ROLLBACK
Traceback (most recent call last):
  # ...
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: a.id
[SQL: INSERT INTO a (id, data) VALUES (?, ?)]
[parameters: (1, <redacted>)]

```

**Comment by ambsw-technology** [comment]
This is exactly what we needed.  I was sure we weren't the only one.

It'd be nice if the `SensitiveString` was part of sqlalchemy.  If it were, it sounds like all I would need to do is change `String` to `SensitiveString` in table definitions (and not run on DEBUG in production).  Correct?  Erase parameters is unnecessary once the strings are all `SensitiveString`s.

FWIW a SSN could be stored in a numeric type (ignoring the hyphens).  I wonder if a more generalizable solution could be provided.   The syntactical goal would be something like (using your above example):

    class A(Base):
        __tablename__ = "a"
    
        id = Column(Integer, primary_key=True)
        data = Column(sensitive(String(50)))
        ssn = Column(sensitive(Integer)))

In this approach, `sensitive()` would wrap `process_bind_param` and `process_result_value` with a method.  That method would call `super()` and replace/wrap `__repr__` in the return value.  I suggest wrapping `__repr__` (even though it's unnecessary in your example) to provide a template for more sophisticated behavior.  For example, an enterprizing developer could decide to encrypt (rather than suppress) the paramter using public key encryption.  This secures the data in logs, but permits decryption if necessary (e.g. to identify problem records for further analysis).

**Comment by zzzeek** [comment]
Re: including this, unfortunately as you noticed in the "integer" case, this solution has many areas in which it can grow to be much more significant and complicated depending on an organization's needs.  If I include this in SQLAlchemy as a feature, it is on me to forever produce, maintain, and support this capability including new feature requests, documentation, etc.    In truth, this technique has nothing to do with SQLAlchemy, it has to do with Python and the ability to provide a `__repr__` method.   I'm happy to document this recipe however it is on users to tailor approaches like these to fit their needs.  This is ultimately simpler than having a feature on my end.  For example, suppose you didn't like the string "redacted".   You can just change it, that's easy.  But if it's my "feature", now it becomes a parameter that must be documented, tested, and then what if someone wants the string to have some special behavior based on the value; now it has to be a callable, which I have to add and maintain, etc., having this as an API feature is more cumbersome to both parties in fact.

Also I would not advise storing an SSN as an integer,and I wouldn't even store it in any plaintext form in the database at all, in fact, it should be an encrypted string, see https://security.stackexchange.com/a/61004 for background.    You might want to take a look at the existing encryption recipe at https://github.com/sqlalchemy/sqlalchemy/wiki/SymmetricEncryption .

**Comment by zzzeek** [comment]
Or of course, you could provide your own SQLAlchemy-sensitive package on pypi and I will gladly link to it.

**Comment by ambsw-technology** [comment]
I appreciate your concern about maintenance so let me suggest a different perspective...

I think there's a case to be made that the default is the problem (and should be altered).  As a widely-used database driver, it seems to me that information security should be the default.  If our environment hadn't triggered the error, we'd be unaware that it was possible to leak PII/PHI.  I wouldn't be surprised if there are thousands of users in regulated industries and that same situation.

With the exception of debug logging (which is a pandora's box everywhere), I don't think parameters should ever end up anywhere but the place where a user intentionally puts the data.  If they want to enable parameters-in-logs, it can be easy to do so, but should require a proactive choice by the developer.

If anything, parameter-in-logs should be the unsupported, 3rd party package.  That's the case that is completely unnecessary for normal operation.  To enable verbose logging packages, it can make sense to pass lots of context to the error logger, but the default logger should not use anything that could leak data.

P.S. I would never implement SSN-as-int in practice.  I was just trying to imagine another data type that could contain obviously sensitive data.  SSN is a reasonably trivial one and an int could, in some extreme cases, be favored by a reasonable developer for storage efficiency (either on-disk or in-memory).

Nor am I confident that we can adopt package-specific security features since the database is currently configured by a Django application (a choice made before my time).  But I appreciate the suggestion!

**Comment by zzzeek** [comment]
> I appreciate your concern about maintenance so let me suggest a different perspective...
> 
> I think there's a case to be made that the default is the problem (and should be altered). As a widely-used database driver, it seems to me that information security should be the default. If our environment hadn't triggered the error, we'd be unaware that it was possible to leak PII/PHI. I wouldn't be surprised if there are thousands of users in regulated industries in that same situation -- either leaking data without realizing it or with the potential to do so unexpectedly.

OK, but your information is *not* secure.  You aren't encrypting your data in the database, and I assume you aren't using SSL for your database connections either.   If you were using these things, they are still not the default, nor should they be.   If you are storing PII in your database, you should not assume it is secure.  SQLAlchemy cannot take on this responsibility automatically.   You must be aware of the special security issues surrounding PII and as the application developer, take the additional steps necessary to secure this information.   the tools should support you in this task but it should not be a "surprise" to the developer that they did nothing to secure their PII and they suddenly realize it's not secure.

> 
> With the exception of debug logging (which is a pandora's box everywhere), I don't think parameters should ever end up anywhere but the place where a user intentionally puts the data. If they want to enable parameters-in-logs, it can be easy to do so, but should require a proactive choice by the developer.

An option to not add parameters to exceptions and logging is maybe doable, however the default IMO is that it should remain turned on, as this is intended to help with debugging and is relied upon by new users and veteran users alike to be able to follow what's going on.     The PII situation is not the default nor is it even much the norm.    Storing SSN in the database is a special situation which always requires special steps be taken.

> 
> If anything, parameter-in-logs should be the unsupported, 3rd party package. That's the case that is completely unnecessary for normal operation. To enable verbose logging packages, it can make sense to pass lots of context to the error logger, but the default logger should not use anything that could leak data.

I disagree.   SQL and parameter logging is enormously useful for debugging and transparency into what the Core and ORM are doing.     PII is a much more special and specific case than being able to see data going into the database when logging is enabled.

> 
> P.S. I would never implement SSN-as-int in practice. I was just trying to imagine another data type that could contain obviously sensitive data. SSN is a reasonably trivial one and an int could, in some extreme cases, be favored by a reasonable developer for storage efficiency (either on-disk or in-memory).

Dollar amounts are a good example of a numeric value that would often want to be shielded.

> 
> Nor am I confident that we can adopt package-specific security features since the database is currently configured by a Django application (a choice made before my time). But I appreciate the suggestion!

Django includes parameters to SQL statements in its own logging:

https://docs.djangoproject.com/en/2.2/topics/logging/#django-db-backends

Here is the code where the SQL statement and paramters are formatted right into the message:

https://github.com/django/django/blob/master/django/db/backends/utils.py#L125

**Comment by ambsw-technology** [comment]
> Django includes parameters to SQL statements in its own logging

Yes, but only at the DEBUG level.  Stuff like this is common at DEBUG which is why I said (above) that DEBUG is a Pandora's box.  For me, the key point is that DEBUG is not the default so someone had to intentionally escalate the logging level.  As a result, they bear obvious responsibility for understanding the side effects -- and dangerous ones can be documented alongside the setting.

> SQL and parameter logging is enormously useful for debugging and transparency

I was trying to emphasize the fact that 3rd party packages often fail due to changes in core.  The "no parameters" logic **cannot** fail so it's not suited to 3rd party implementation.  The "all parameters" can fail so (of the two) it's better suited.  If you were bandwidth constrained, "all parameters" is the better one to delegate to the community (not necessarily that you *should* delegate it).

> your information is not secure. You aren't encrypting your data in the database, and I assume you aren't using SSL for your database connections either

We provide single tenant VMs and everything runs in Docker containers on that VM (including a database instance).  For the database, we use [Data Partition Encryption](https://www.postgresql.org/docs/current/encryption-options.html) and store the key on a different physical and logical device.  Our production instances still use old-school links so there isn't an internal network to snoop... and even if there was the user would already have sufficient permission to go directly to the database.  Any security model can be improved, but we're covering the obvious bases -- including both you mention albeit in different ways.

> the tools should support you in this task but it should not be a "surprise" to the developer that they did nothing to secure their PII and they suddenly realize it's not secure

We never (intentionally) send PHI or PII in logging messages, but our logging facilities are **still** HIPAA compliant just-in-case.  The only way data enters/exits our networks is over an (encrypted) site-to-site VPN.  Clients have dedicated VLANs.  Despite all of this we **still** encrypt all of our internal network traffic.  Layers upon layers.

None of that caution changes my opinion that the package should not leak data into logs by default.  Even if you're not responsible for PHI, PII, or financial data, I can think of no compelling reason to do so unless you're debugging a specific error.  In that case, it should be intentional and the developer has the opportunity to clean up after themselves.

... but I really don't want to be the "opponent" in a debate.  That puts both of us in a defensive mindset.  I'm trying to highlight an opportunity to "improve the security of defaults".  I don't think security is objectionable.  I think you can still serve the needs of debuggers at the DEBUG log level.  I'm open to the possibility that someone actively benefits from the status quo, but I suspect the balance of users would benefit from the change (even if most never know it).

**Comment by zzzeek** [comment]
I will comment this further, but I am sensing some moving of the goalposts here.   Your position, which perhaps wasn't clear earlier, is that you are assuming some special meaning to INFO logging, vs DEGUG logging, and that INFO logging if i read correctly you are seem to be implying as a "default" ("package should not leak data into logs by default.").   SQLAlchemy logs nothing by default.  We use DEBUG logging for the much more debuggy case of dumping the *results* as well.  These behaviors have been this way for 15 years and this has never been raised.

Also, let me clarify, third party package refers to the more elaborate "tainted string" recipe.  This is a python trick with lots of caveats and behaviors that many users would find undesirable by default and for which a potential featureset is out of scope for SQLAlchemy.   This should be considered to be distinct from the "don't log the parameters" request, which is very simple and can be within even the next release, depending upon when debate over defaults can end and implementation can begin :)

In this case, as mentioned before, a simple flag to omit or custom format the parameters in exceptions and messages is not controversial, someone else had requested a similar feature for totally different reasons.   Making it a default would  not be in scope for the 1.3.x series and that decision would be put out to the wider user community which they'd prefer for the next major release.

**Comment by ambsw-technology** [comment]
You're right.  Discussion about logging levels distracted us from my original issue -- that params are included in the content of Exceptions e.g.:

> (psycopg2.OperationalError) server closed the connection unexpectedly
> This probably means the server terminated abnormally
> before or while processing the request.
> [SQL: INSERT INTO message_delivery_incomingmessage (key, message_type, message, processed, time_created, time_last_processed, sender_app_id, receiver_app_id, message_hash) VALUES (%(key)s, %(message_type)s, %(message)s, %(processed)s, now(), now(), %(sender_app_id)s, %(receiver_app_id)s, %(message_hash)s) RETURNING message_delivery_incomingmessage.id]
> [parameters: {'key': 'http://demo.domain.com/api/patients/1/', 'message_type': 'clear_facet_tasks', 'message': '<?xml version="1.0" encoding="utf-8"?>\n<message type=\'clear_facet_tasks\'>\n    <envelope>\n        \n       ... (53 characters truncated) ... ts/1/"/>\n        \n        <facet name="Generic Commitment"/>\n    </envelope>\n    <body><![CDATA[]]></body>\n</message>', 'processed': False, 'sender_app_id': 3, 'receiver_app_id': 2, 'message_hash': '081a063a9b087335a5d6cc20c087003a'}]

Unless [this page](https://github.com/sqlalchemy/sqlalchemy/blob/0116a988ec87aa418a83c182d543e72b6a40da1d/doc/build/core/engines.rst) is wrong, SQLAlchemy does write to logs by default:

> By default, the log level is set to logging.WARN within the entire sqlalchemy namespace so that no log operations occur, even within an application that has logging enabled otherwise.

So I'm willing to scale back my focus to this more restricted "default" case of WARN, ERROR, and Exception bodies.  I think there's a case for other changes (e.g. distinguishing among queries, params, and results using settings flags vs. debug levels), but I agree that it's a separate issue.

**Comment by zzzeek** [comment]
> 
> So I'm willing to scale back my focus to this more restricted "default" case of WARN, ERROR, and Exception bodies. I think there's a case for other changes (e.g. distinguishing among queries, params, and results using settings flags vs. logging levels), but I agree that it's a separate issue.

ok then the sentence is not clear: "By default, the log level is set to logging.WARN within the entire sqlalchemy namespace so that no log operations occur, even within an application that has logging enabled otherwise."

With one exception in the connection pool, SQLAlchemy only writes logs to the INFO and DEBUG loggers under the "sqlalchemy" namespace.   By setting the default level to "WARN" for "sqlalchemy", it means that even if you set up logging for "sqlalchemy.engine", you will still see nothing unless you also change the default log level.    Additionally, SQLAlchemy does not log SQL / DBAPI errors at all, they are always considered fatal / unchecked and are raised, so it is the calling application that would be logging them.

At the moment, the only log messages written to log.error() are in the connection pool that a critical exception was encountered while trying to close a DBAPI cursor or connection; since the pool seeks to continue running, this is a handled exception so it logs it.   But there are no SQL or parameters in these logs.

Demo, SQLAlchemy logs nothing by default, even if you turn on logging:

```
from sqlalchemy import create_engine

import logging
logging.basicConfig()

logging.getLogger("sqlalchemy.engine").warning("logging is turned on for WARN")

e = create_engine("sqlite://")

# but no INFO
e.execute("SELECT 1")

# errors are also not sent to logs
try:
    e.execute("SELECT * FROM fake_table")
except:
    pass


```

output:

```
[classic@photon2 sqlalchemy]$ python test3.py 
WARNING:sqlalchemy.engine:logging is turned on for WARN

```

I continue to recommend the tainted strings recipe as the most comprehensive way to make sure PII strings are treated as "special" within an application, however I can also provide for an engine/dialect-level flag hide_parameter_logging=True which will prevent parameters from being displayed in log messages and exception stringify.   docs for this new feature will refer to the tainted string recipe as a more comprehensive approach, rather than trying to provide fora custom formatter at the engine level.

**Comment by ambsw-technology** [comment]
Thanks for your time and consideration and I appreciate a package-level option.

I certainly see how the tainted strings approach could have an impact beyond the package, but wonder how many applications use `str` in error messages, unintentionally circumventing the protection (if I understand how it's meant to work).  I did a quick search and we still have error messages that use `str`.  We also have some business logic that uses `str` though it may be a hangover from legacy str-unicode issues created by a 2.x messaging library.

P.S. If your intent is to generate no log messages, perhaps it would be more clear to change the default to `CRITICAL`.  That would make it crystal clear to a 3rd party user that no messages are expected and would guard against future changes that add an error or warn that violate the implicit assumption about logging.  It would be backwards compatible to users currently reconfiguring the level to access debug messages.  The only potential backwards incompatibility would be on 3rd party packages logging in the sqlalchemy namespace.

**Comment by zzzeek** [comment]
> Thanks for your time and consideration and I appreciate a package-level option.
> 
> I certainly see how the tainted strings approach could have an impact beyond the package, but wonder how many applications use `str` in error messages, unintentionally circumventing the protection (if I understand how it's meant to work). I did a quick search and we still have error messages that use `str`. We also have some business logic that uses `str` though it may be a hangover from legacy str-unicode issues created by a 2.x messaging library.

I'm not familiar with a canonical pattern that calls `str()` on Exception objects.   in any case, this does not affect if you have custom repr() behavior because the stringify of the exception will give you the message, which was generated using the repr as you can see at https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/exc.py#L363.   Additionally, the proposal I am offering is that the params would not be in the exception string at all when the flag is used.


> 
> P.S. If your intent is to generate no log messages, perhaps it would be more clear to change the default to `CRITICAL`. 

the current intent is to generate no SQL log messages, but for very rare, unexpected errors closing cursors that are otherwise silently handled, to emit an ERROR log, if the user has in fact applied a handler to the sqlalchemy log name.   

> That would make it crystal clear to a 3rd party user that no messages are expected and would guard against future changes that add an error or warn that violate the implicit assumption about logging. It would be backwards compatible to users currently reconfiguring the level to access debug messages. The only potential backwards incompatibility that occurs to me would be on 3rd party packages logging in the sqlalchemy namespace.

OK, again there are only two log.error() calls and they are explicitly for when a very unusual error occurs in closing a cursor or a connection that is being discarded in any case.   It's not unusual that libraries or interpreters will emit more aggressive messaging for some unusual circumstances.   

I'm looking to make a positive addition for this issue that solves your problem without getting mired in hypotheticals, would you find a create_engine() parameter that prevents .params from being included in log messages and execption objects useful or should I assume you're moving forward with tainted strings?

**Comment by ambsw-technology** [comment]
> would you find a create_engine() parameter that prevents .params from being included in log messages and execption objects useful

Yes please.  

> I'm not familiar with a canonical pattern that calls str() on Exception objects.

I guess I didn't follow your point about the advantage of tainted string.  I don't want to waste your time to rehash it since I prefer the flag.

**Comment by zzzeek** [comment]
see #4806

**Comment by lucaswiman** [comment]
For future people who find their way here via google, the relevant feature seems to be https://github.com/sqlalchemy/sqlalchemy/commit/05e1c2c2dbf2e1df0c7d35f32f33c56646ea3f1e (add `hide_parameters=True` to `create_engine`).

From the perspective of HIPAA compliance and reducing leakage of PHI/PII into logs, this feature doesn't seem to be sufficient, since if the database raises an error. This means that a bug on inserting a record where a non-nullable column was set to null can still leak all the other values of columns in that row into the logs. For example, an `IntegrityError` can look like the following, where the string `PHI` represents some value which shouldn't be put into logs:

> `IntegrityError('(psycopg2.errors.NotNullViolation) null value in column "patient_control_number" violates not-null constraint\nDETAIL:  Failing row contains (1, null, null, null, null, null, null, null, null, null, null, PHI, PHI, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2020-09-25 21:56:47.339412+00).\n')`

The solution here is fairly non-obvious. Even a specialized wrapper like `SensitiveString` probably wouldn't keep the PHI out of the underlying database driver's exception repr. One option is to modify the `erase_parameters` method above to scrub substrings after `Failing row contains (...` and similar strings emitted by the database driver. That's a bit brittle.

**Comment by zzzeek** [comment]
that "DETAIL: failing row" thing comes from libpq in any case.    for extremely sensitive logs you should write a custom logging.Formatter that scrubs strings and/or encrypts the whole log.

**Comment by lucaswiman** [comment]
Indeed. I wasn't suggesting that you fix this, just adding some notes for others who come to this thread who might think that `hide_parameters=True` will totally solve the problem.

**Comment by IncludeSec** [comment]
Relevant blog post written about this issue:
https://r2c.dev/blog/2020/fixing-leaky-logs-how-to-find-a-bug-and-ensure-it-never-returns/
