### ISSUE TITLE
Core expression output by Query don't track the ORM entities from which they originated which is needed for session.get_bind() context

### ISSUE THREAD

**Issue by wpk-** [sqlalchemy/sqlalchemy#4829]
The [CTE example code in the Query API docs](https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.cte) fails with an `UnboundExecutionError` when the session is configured with `binds={Base: engine}` rather than `bind=engine`.

Full working example:

```python
from sqlalchemy import Column, Integer, String, create_engine, func
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import aliased, sessionmaker

Base = declarative_base()


class Part(Base):
    __tablename__ = 'part'
    part = Column(String, primary_key=True)
    sub_part = Column(String, primary_key=True)
    quantity = Column(Integer)


engine = create_engine('sqlite:///:memory:', echo=True)
Base.metadata.create_all(engine)

Session = sessionmaker(binds={Base: engine})
# Session = sessionmaker(bind=engine)
session = Session()


included_parts = session.query(
                Part.sub_part,
                Part.part,
                Part.quantity).\
                    filter(Part.part=="our part").\
                    cte(name="included_parts", recursive=True)

incl_alias = aliased(included_parts, name="pr")
parts_alias = aliased(Part, name="p")
included_parts = included_parts.union_all(
    session.query(
        parts_alias.sub_part,
        parts_alias.part,
        parts_alias.quantity).\
            filter(parts_alias.part==incl_alias.c.sub_part)
    )

q = session.query(
        included_parts.c.sub_part,
        func.sum(included_parts.c.quantity).
            label('total_quantity')
    ).\
    group_by(included_parts.c.sub_part)

if __name__ == '__main__':
    q.all()                     # !! UnboundExecutionError
```

**Comment by zzzeek** [comment]
this is not mysterious because the query being run is a Core expression language construct and has no ORM entities within it.   if you ran session.execute(select([Part])) or session.query(Part.__table__) you'd get the same thing.  

it's not that this is an invalid use case however, it would be nice if given a binds mapping that doesn't include any Table objects, it extrapolates them from the ORM mapped classes it has, though in this case just giving it Base doesn't really give it enough information to figure that out unless additional assumptions about declarative bases were added.

another way this might be considered to be more correct would be that ORM annotations from the original Part columns would be fully propagated outwards as the Query builds off Core subquery objects so that the original mappings were intact.   This is probably where this should happen since Query sends to Session the context.

The reality is that the "binds" system with Session is not very widely used as it is more for the niche case that one has a single Session dealing with vertically partitioned classes across multiple database engines.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Annotate parententity in Query-produced selectables** https://gerrit.sqlalchemy.org/1442

**Comment by zzzeek** [comment]
the linked review will fix this issue, however it's too large of a change for the 1.3.x series.  1.4 has many months to go before it will see releases.    if you need a workaround let me know and i will see if we can come up with something.  otherwise if you're just experimenting, then yeah.

**Comment by wpk-** [comment]
Wow, that's an amazingly quick fix!

The issue arose because some application stores data in multiple (three) SQLite files, which I need to work against. I thought I should include all these in the same session. There are some table columns corresponding between the different files. Is that what "vertical" means? (Sorry, I am very new to SQLAlchemy.)

Perhaps an easier approach in my case is to create separate sessions for the individual databases? The cte doesn't span multiple databases anyway. (And yeah, I'm mostly just toying around so a solution that uses `binds` would be neat, but is by no means necessary.)

**Comment by wpk-** [comment]
(PS. I would multiply `parts_alias.quantity` by `incl_alias.c.quantity`  in the `included_parts.union_all` statement.)

**Comment by zzzeek** [comment]
"vertical" means that yes, you have the total set of data you are dealing with partioned among multiple databases, and the databases are split what we say "veritcally", that is, different tables are in different databases.    If the split was "horizontal" then you'd have different rows of a single table in the different databases.

for your use case, using one Session is indeed a fairly reasonable way to do it, however, if you want to use multiple sessions instead, that is fine as well.     A workaround you can do for now is to populate the "binds" dictionary with all the Table objects you care about also.     this is not super convenient, but if you can make sure that you've mapped all your classes first, you can use a recipe like this:

```
binds = {Base: engine}
binds.update({table: engine for table in Base.metadata.tables.values()})

Session = sessionmaker(binds=binds)

```

**Comment by wpk-** [comment]
Yes! That works wonders. Thanks.

**Comment by zzzeek** [comment]
the patch will close the issue when it's merged

**Comment by zzzeek** [comment]
just as an FYI the approach taken here was further reworked in 6930dfc032 so that the subject mapper is worked out as we receive the arguments.
