### ISSUE TITLE
JSONB nested array insert syntax is problematic

### ISSUE THREAD

**Issue by mikepc** [sqlalchemy/sqlalchemy#4852]
I submitted the question to SO:

https://stackoverflow.com/questions/57845413/how-to-insert-an-element-into-a-nested-jsonb-array-with-sqlalchemy-on-postgres/57845890#57845890

The JSONB API is extremely .. cryptic. Is there anything that can be done to make this easier to work with and less "wonky"? It took me a couple of hours of trial and error before I stumbled onto the syntax for this.

**Comment by zzzeek** [comment]
hi there-

this doesn't seem to be related to SQLAlchemy, it's something to do with GINO which looks to be yet another fork of SQLAlchemy that provides it's own execution engine, or the asyncpg driver which has less support for PostgreSQL's features than psycopg2.

In SQLAlchemy you can use func.jsonb_insert() directly as you'd write SQL:

```

func.jsonb_insert(
                A.__table__.c.data,
                ["newkey"],
                cast({"newsubelement": "newvalue"}, JSONB),
            )
```

surprisingly it looks like psycopg2 even handles that string array automatically these days, pretty easy.   usually you would have needed to put postgresql.array(["newkey]") around that.


full POC:
```

from sqlalchemy import cast
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import func
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(JSONB)


e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(data={"key1": "value1", "key2": "value2"}))
s.commit()


with e.connect() as conn:
    conn.execute(
        A.__table__.update().values(
            data=func.jsonb_insert(
                A.__table__.c.data,
                ["newkey"],
                cast({"newsubelement": "newvalue"}, JSONB),
            )
        )
    )

    assert conn.scalar(select([A.__table__.c.data])) == {
        "key1": "value1",
        "key2": "value2",
        "newkey": {"newsubelement": "newvalue"},
    }

```

**Comment by mikepc** [comment]
Thank you so much for a great response! I really appreciate it.  I went with Gino looking for an async library for postgresql. I'm considering switching to https://pypi.org/project/async-sqlalchemy. I haven't been involved in the python community for several years, would you recommend that or something else?

**Comment by mikepc** [comment]
I would like to add though, that is not a POC that serves my use case. I needed to append an element to an existing array.

eg. "applications": [
   { 
       "elementattr1": "a",
      "elementattr2": "b",
}
]

For the above case I would have used jsonb_set instead.

**Comment by zzzeek** [comment]
While I'm not opposed to SQLAlchemy having async support, because async is popular, it's not something it seems like I would have the resources to do anytime soon and it would need to be based on a very future version of SQLAlchemy (version 2.0 which is in the works).      however it's well known that I think Python's version of async is pretty unnecessary for relational database access, so it's hard for me to recommend anything because I don't think you're really gaining anything by using those async frameworks.

**Comment by mikepc** [comment]
@zzzeek I just read your blog post https://techspot.zzzeek.org/2015/02/15/asynchronous-python-and-databases/ and I find it really compelling actually.

I know this is a wild branch from the original topic, but you really have me questioning some fundamental misconceptions I've had for a very long time about async database access. I'm going to refactor my project to use straight SQLAlchemy in a synchronous way.

The funny part I see about what you're saying is.. there are very very very few benchmarks for the async postgres libraries, either in comparison to other python libraries or even other languages. This leads me to the conclusion that the science doesn't support the assumption.

The science is in for web requests, but for database access it really does seem like there isn't solid evidence for it.

**Comment by mikepc** [comment]
Back to topic though, the API syntax for interacting with Postgres' powerful JSON/B support is really rough. There has to be a way we can make it easier to work with, without forking the darn thing.

**Comment by zzzeek** [comment]
> @zzzeek I just read your blog post https://techspot.zzzeek.org/2015/02/15/asynchronous-python-and-databases/ and I find it really compelling actually.
> 
> I know this is a wild branch from the original topic, but you really have me questioning some fundamental misconceptions I've had for a very long time about async database access. I'm going to refactor my project to use straight SQLAlchemy in a synchronous way.

wow I don't know if I've ever changed someone's mind before that's amazing ! :)

> 
> The funny part I see about what you're saying is.. there are very very very few benchmarks for the async postgres libraries, either in comparison to other python libraries or even other languages. This leads me to the conclusion that the science doesn't support the assumption.

OK there's a caveat here, which is that the asyncpg driver *is* much faster than psycopg2, however, not because it's async, it's because it does things differently as far as how it sets up statement executions and deals with datatypes and stuff.    My statements here are all based on benchmarks that were posted by asyncpg's author when it first came out and also some discussions I had with him as I had observed the speed improvements were based on non-async factors (https://magic.io/blog/asyncpg-1m-rows-from-postgres-to-python/) not to mention what that blog post states.

> 
> The science is in for web requests, but for database access it really does seem like there isn't solid evidence for it.

sure, the sqlalchemy site and all that runs under apache but I use the event-based worker MPM, certainly if all you're doing is pushing out files to clients that might take any amount of time to get your data, you want a wide channel on the cheap and that's what event-based gives you.

**Comment by zzzeek** [comment]
> Back to topic though, the API syntax for interacting with Postgres' powerful JSON/B support is really rough. There has to be a way we can make it easier to work with, without forking the darn thing.

back to topic...where the SQLAlchemy version looks OK to me?  Postgresql's JSON functions are many, and completely specific to that database, and are changing all the time.  so if you are proposing some facade that uses them automatically for mutation operations, I don't see that as much of a win, usually people want to use those functions as PG documents them so I think exposing them as is is likely the best approach.

**Comment by zzzeek** [comment]
closing this for now.
