### ISSUE TITLE
add support for sqlite "uri=True"

### ISSUE THREAD

**Issue by abitrolly** [sqlalchemy/sqlalchemy#4863]
How to connect to SQLite in read-only mode? Using connection URL like `sqlite:////usr/share/ibus-libpinyin/db/english.db?mode=ro` gives the error `TypeError: 'mode' is an invalid keyword argument for this function`.

```
from sqlalchemy import MetaData

metadata = MetaData('sqlite:////usr/share/ibus-libpinyin/db/english.db?mode=ro')
metadata.reflect()
```

**Comment by zzzeek** [comment]
There is no "mode" keyword specified as part of the Python sqlite3 driver:

https://docs.python.org/3/library/sqlite3.html#sqlite3.connect

however, also in that document, it is claimed that using the "uri" parameter with a URI would allow this to be possible.

however the dialect currently runs the given database name through os.path.abspath(), preventing the use of the URI, so support for uri=True would have to be added explicitly. 

you can make a connection right now passing a custom connection function:
```

>>> import sqlite3
>>> def connect():
...     return sqlite3.connect("file:mydb.db?mode=ro", uri=True)
... 
>>> from sqlalchemy import create_engine
>>> e = create_engine("sqlite://", creator=connect)
>>> c = e.connect()
>>> c.scalar("select 1")
1
>>> c.execute("create table bar (id integer)")
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Support SQLite URIs** https://gerrit.sqlalchemy.org/1473

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Support SQLite URIs** https://gerrit.sqlalchemy.org/1474

**Comment by abitrolly** [comment]
Is it possible to implement `readonly=True` flag that will hide low level details?

**Comment by zzzeek** [comment]
There's not a good reason to do that as folks who want to use this feature would have been reading SQLite's documentation and will want to use their API as directly as possible.  There's no "readonly" concept for other databases at the driver level so this is not portable.   The SQLite driver also supports about ten other flags apparently and we wouldn't add "high level" versions of those either, including one called "immutable" which also implies readonly. So it's much better we just allow people to use SQLite's system documented at https://www.sqlite.org/uri.html as directly as possible.

**Comment by abitrolly** [comment]
Is `file:` prefix necessary?

**Comment by zzzeek** [comment]
absolutely, that's the API documented by the sqlite3 driver, i have no idea if they are to add some new kind of prefix someday.

this is the same theme.   At the level of things like driver URIs and such, it's best that SQLAlchemy get involved as little as possible, because otherwise, someone attempting to use some driver feature must not only learn how the driver feature works, but then also learn how SQLAlchemy has decided to conceal and obfuscate the feature into some new format for no real benefit.  it's better that a very specific driver feature, one which a developer would not be using if they weren't already familiar with the idiosyncrasies of that driver, be exposed as directly as possible so that the developer only needs to learn one set of documentation.
