### ISSUE TITLE
Percent sign is duplicated in filter clause

### ISSUE THREAD

**Issue by davidmoseler** [sqlalchemy/sqlalchemy#4888]
The following syntax:

Model.query.filter('table_name.column_name % \'query_string\'').all()

will generate a correct sql expression, except by the percentage sign, which will be duplicated, rendering: "model.column_name %% 'query_string'".

This duplication is unavoidable so far as I know by the docs, but it should be possible to provide literal SQL to the filter clause, in order to not disturb code which dynamically relies on concatenation of filters.

The above % syntax is compatible with posgres fuzzy search module.

**Comment by zzzeek** [comment]
Hi there -

it's not supported to pass a string to filter() directly, if you are on 1.3 or greater this raises an error and if you are on any version above 1.0 or so, the above code emits a warning.

you need to use the text() construct:

    query.filter(text("col % str"))

the doubling of the percent sign is then conditional upon if the DBAPI you are using requires it.   psycopg2 for example requires that the percent sign is doubled because it uses the `%(named)s` parameter format.   if the DBAPI does not require it, then as of #3740 it will not be doubled.    

so your steps are as follows:

1. use text()

2. upgrade to 1.3

if that does not solve your issue then please provide an MCVE.

**Comment by davidmoseler** [comment]
Thank you very much!! Didn't notice the version was not up to date. Perfect!
