### ISSUE TITLE
Accessing an association proxy in an after_flush context duplicates the last linked object 

### ISSUE THREAD

**Issue by maarten-dp** [sqlalchemy/sqlalchemy#4890]
Hello,

When writing some after_flush code we noticed a strange behavior, where the last linked child object is duplicated in the parent object's association proxy. This association proxy is a many to many.

Here's a little script to reproduce

```python
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.associationproxy import association_proxy

engine = sa.create_engine('sqlite:///:memory:')
Base = declarative_base()
Base.metadata.bind = engine
Session = sa.orm.sessionmaker(autocommit=False, autoflush=False, bind=engine)
session = sa.orm.scoped_session(Session)


class Teacher(Base):
    __tablename__ = 'teacher'
    id = sa.Column(sa.Integer, primary_key=True)


class Class(Base):
    __tablename__ = 'class'

    teacher = sa.orm.relationship('Teacher', backref='classes')
    teacher_id = sa.Column(sa.Integer, sa.ForeignKey('teacher.id'), primary_key=True)

    student = sa.orm.relationship('Student', backref='classes')
    student_id = sa.Column(sa.Integer, sa.ForeignKey('student.id'), primary_key=True)


class Student(Base):
    __tablename__ = 'student'

    id = sa.Column(sa.Integer, primary_key=True)

    teachers = association_proxy('classes', 'teacher')



@sa.event.listens_for(Session, 'after_flush')
def report_teachers(session, flush_context):
    for target in set(session.new).union(session.dirty):
        if isinstance(target, Student):
            print(target.teachers)
            print([t.id for t in target.teachers])

Base.metadata.create_all()

student = Student()

french_class = Class(teacher=Teacher(), student=student)
session.add(french_class)
session.commit()

dutch_class = Class(teacher=Teacher(), student=student)
session.add(dutch_class)
session.commit()
```

When running this script, the result is 

```
❱ python test.py
[<__main__.Teacher object at 0x7f6df50bb6d8>]
[1]
[<__main__.Teacher object at 0x7f6df5048cf8>, <__main__.Teacher object at 0x7f6df5048da0>, <__main__.Teacher object at 0x7f6df5088978>]
[1, 2, 2]
```

As you can see, after the first commit, the list only has the teacher for the french class, while after the second commit, the list has one teacher for the french class, and a duplicated teacher for the dutch class (same database id, different internal python id).

Doing a `session.refresh(target)` within the after flush is a current workaround.

Versions this was reproduced on:
- 1.2.0b3
- current master branch (3836a90dcf9b202db2eb8f013b8eca07245067be)

Python version is 3.6.7

To allow Mr. Bayer's fun on Link's awakening, I will investigate further and see if I can propose a fix at a later date ;)

**Comment by zzzeek** [comment]
you're only creating two Teacher objects which means for there to be more, something is being loaded, and since there are no queries shown, it has to be related to expiration.   i'll look in a few but I would suppose if you put expire_on_commit=False in your session that might change this behavior.    not like that's the solution but it would confirm this has something to do with refreshing collections.    also I'm wondering (again I will know in 3 seconds when I run the script) if the list remains in the wrong state if you do only a flush(), and not a commit(), at the end, or if this is only seen within the after flush handler itself.

**Comment by maarten-dp** [comment]
expire_on_commit=False does indeed result in the correct behavior :)

**Comment by zzzeek** [comment]
There was an issue in openstack neutron that might have been similar to this, where we saw multiple objects with the same identity popping up as a result of events.

I'm trying to see if I can add a warning (Python warning) for this as it is likely the best I can do, however this condition is also known for other reasons where the warning might not work there so need to see.

at the very least we probably need a dragon at https://docs.sqlalchemy.org/en/13/orm/events.html?highlight=after_flush#sqlalchemy.orm.events.SessionEvents.after_flush .
basically the after_flush() event is before the Session has done the work of putting the new objects into the identity map, or done anything with clearing out the pending history of collections.   The new Class and Teacher objects are not in the identity map yet, but the rows have been inserted into the database.   

so when you emit a load of target.classes and then each teacher object, which is what target.students does, it goes to the database, gets primary key 1 and 2 for the classes / teachers, puts the newly loaded class / teacher objects into the identity map, and populates the collection.  then it also gives you the objects that you have appended to the target.classes collection which are still sitting in a temporary buffer (see this via `inspect(target)._pending_mutations["classes"].added_items`) also, which is this other Class object that also has primary key 2 because its row was just inserted, but is in the middle of a flush and is not in the identity map yet.

the end result is nothing is really corrupted since the identity map has maintained just two Class and Teacher objects but your collection is in an invalid state due to where it was loaded.

this is a patch that I can't put in as is, as we have an existing test where this is a valid condition (swapping primary keys of objects), although I can decide that the warning is worth it in that case also.  if you wanted to play with this patch to see the warning that might be helpfu.

```diff
diff --git a/lib/sqlalchemy/orm/identity.py b/lib/sqlalchemy/orm/identity.py
index 2da5d66b3..cb49e1719 100644
--- a/lib/sqlalchemy/orm/identity.py
+++ b/lib/sqlalchemy/orm/identity.py
@@ -125,10 +125,13 @@ class WeakInstanceDict(IdentityMap):
                 if existing is not state:
                     self._manage_removed_state(existing)
                 else:
-                    return
+                    return None
+        else:
+            existing = None
 
         self._dict[state.key] = state
         self._manage_incoming_state(state)
+        return existing
 
     def add(self, state):
         key = state.key
diff --git a/lib/sqlalchemy/orm/session.py b/lib/sqlalchemy/orm/session.py
index c345c4281..a2801fcea 100644
--- a/lib/sqlalchemy/orm/session.py
+++ b/lib/sqlalchemy/orm/session.py
@@ -1935,7 +1935,13 @@ class Session(_SessionClassMethods):
                 # there can be an existing state in the identity map
                 # that is replaced when the primary keys of two instances
                 # are swapped; see test/orm/test_naturalpks.py -> test_reverse
-                self.identity_map.replace(state)
+                old = self.identity_map.replace(state)
+                if old is not None:
+                    util.warn(
+                        "Identity map already had an identity for %s, "
+                        "replacing it with newly flushed object"
+                        % (instance_key, )
+                    )
                 state._orphaned_outside_of_session = False
 
         statelib.InstanceState._commit_all_states(

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Warn for object replaced in identity map during flush** https://gerrit.sqlalchemy.org/1497

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Warn for object replaced in identity map during flush** https://gerrit.sqlalchemy.org/1498

**Comment by zzzeek** [comment]
so great to get a clear test case thanks for that

**Comment by maarten-dp** [comment]
It's the least I can do. Thanks for the quick reply and fast action!

**Comment by zzzeek** [comment]
eep...it looks like this condition might also occur as an object is GC'ed....hmmm...let me try to adjust for that
