### ISSUE TITLE
Suppress compatibility check warning in Oracle

### ISSUE THREAD

**Issue by tdbabas** [sqlalchemy/sqlalchemy#4898]
We are using SQLAlchemy to connect to an Oracle database, hosted centrally by our organisation. After updating to 1.3.9, whenever we run our scripts, we get the following warning:

```
/<virtualenv>/lib/python3.6/site-packages/sqlalchemy/dialects/oracle/base.py:1273: SAWarning: Could not determine compatibility version: (cx_Oracle.DatabaseError) ORA-00942: table or view does not exist
[SQL: SELECT value FROM v$parameter WHERE name = 'compatible']
(Background on this error at: http://sqlalche.me/e/4xp6)
  util.warn("Could not determine compatibility version: %s" % err)
```

We are not Oracle DBAs, so we don't have access to the `v$parameter` table. It is unlikely that our IT department would grant us access to the table.

Our scripts run as expected, despite this warning. However, is it possible to suppress this warning so that our outputs and logs don't get cluttered?

**Comment by zzzeek** [comment]
so for this particular warning, we are looking at the change now described in the documentation at https://docs.sqlalchemy.org/en/13/dialects/oracle.html#max-identifier-lengths, where it describes that Oracle has made a dramatic change to their maximum identifier length as of server version 12.2.   In order for SQLAlchemy to know if this change applies, it needs to know the server version.  However, Oracle also added the capability for a so-called "compatibility version" that might cause a 12.2 server to act like an Oracle 11 server, so in the less likely case that you are using these specific Oracle versions and that your DBAs set this flag, SQLAlchemy would have t know that also.   The query comes from oracle's own documentation at https://docs.oracle.com/en/database/oracle/oracle-database/12.2/upgrd/what-is-oracle-database-compatibility.html#GUID-7FCE8614-8163-4393-AE66-2ADD1F73934F .

so I would advise making sure the above changes don't impact your application, or perhaps sharing the above Oracle document with your DBAs to see if they would consider allowing tools to view the database settings so that they may work more correctly and efficiently.   To suppress warnings, Python has a warnings filter documented at https://docs.python.org/3/library/warnings.html#the-warnings-filter which you can use here like this:

```
import warnings
warnings.filterwarnings("ignore", "Could not determine compatibility version")
```

What I might have done here is that if you do set max_identifier_length on your create_engine(), it wouldn't try to get the compatibility version.  it doesn't work that way right now, however.

**Comment by tdbabas** [comment]
Thanks for that. The `filterwarnings` addition seemed to do the trick!

Is there a roadmap for future changes such as these (particularly for Oracle), so we can get a heads up about future issues?

**Comment by zzzeek** [comment]
in general, you can keep an eye on the migration document for 1.4 at https://docs.sqlalchemy.org/en/14/changelog/migration_14.html  , and for the point releases you can look in the changelog, which always includes the changes to be in the next unreleased version as we go along, at https://docs.sqlalchemy.org/en/13/changelog/changelog_13.html .    we try not to introduce new warnings in a point release but at the same time it's a surprise to me that closing off access to "v$parameter" is a normal thing, so if more people complain about this then we will likely have to improve the text of the warning and make it conditional on whether or not max_identifier_length is set.

**Comment by grant-humphries** [comment]
@zzzeek just came here to file this ticket fwiw

**Comment by zzzeek** [comment]
@grant-humphries so would you prefer the warning is more clear or would you prefer we don't warn at all ?   what if you set compatibility mode on your 12.2 database it only allows 30 character identifiers, should SQLAlchemy just use 128 character identifiers and fail ?  that might be better I guess

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Repair Oracle compat version check; dont warn if failed** https://gerrit.sqlalchemy.org/1510

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Repair Oracle compat version check; dont warn if failed** https://gerrit.sqlalchemy.org/1511

**Comment by zzzeek** [comment]
OK the parsing for compat is also broken and I'm returning 128 on version 1.3 so this has to be released ASAP right now with a fix
