### ISSUE TITLE
mappings to outer joins that INSERT (or DELETE?) the joined tables based on attributes being present or not

### ISSUE THREAD

**Issue by tgross35** [sqlalchemy/sqlalchemy#4927]
SQLAlchemy 1.3.8

When inserting into outer joined tables where a record exists in only one of the tables, I would expect that SQLAlchemy would create the record where it is missing. Instead, it returns the following error:

`sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'table_b' expected to update 1 row(s); 0 were matched.`

Here is the model that causes the issue (using the flask-sqlalchemy wrapper)

```python
t_table_a = db.Table(
    'table_a',
    db.Column('id', db.Integer, primary_key=True, unique=True, autoincrement=True),
    db.Column('field1',db.String(255)),  ...
    )

# This table extends table A
t_table_b= db.Table(
    'table_b',
     db.Column('id', db.Integer, db.ForeignKey('table_a.id'), primary_key=True, autoincrement=True),
     db.Column('detail1', db.String(255)),   ...
    )

joined_tables = db.outerjoin(t_table_a, t_table_b)

# Create an editable class based on the two underlying tables
# Documentation here https://docs.sqlalchemy.org/en/13/orm/nonstandard_mappings.html#mapping-a-class-against-multiple-tables
class JointTable(db.Model):
    __table__ = joined_tables

    # This line maps id to both of these columns
    id = db.column_property(t_table_a.c.id, t_table_b.c.id)
```
And here is where it is called:
```python
item = JointTable.query.filter_by(id=item_id).first()
form.populate_obj(item)         # create a db item from the form
db.session.add(item)
db.session.commit() 
```

This works perfect for editing items that exist in both tables or adding new records, but runs into the issue if an item exists in table_a, but there is no item with the same ID in table_b. I believe the cause of the issue is from seeing that the record exists in table_a and deciding to use UPDATE statements for both tables, which fails when there is no record in table_b to update. Instead, sqlalchemy should check each table individually and see if the record exists, then accordingly UPDATE or INSERT on a per-table basis.

The desired behavior can be accomplished with serverside triggers, but it would be nice to have the flexibility to do this using the ORM.

_Edit: added sqlalchemy version_

**Comment by zzzeek** [comment]
I think for the forseeable future the best we can do is a warning in the above mentioned docuemention section that it won't do this.    this feature is similar to the "change of class" feature for joined table inheritance and it's highly complicated,because, there can be more than two tables involved, and you also need to consider would you want this to also DELETE if the attributes are nulled out on the joined table?  what if theres a join of three tables, and you set up attributes for the leftmost and the right most table, but there's not enough information to INSERT for the middle table?  things like that.

**Comment by zzzeek** [comment]
also there's the general issue of an ORM operation that is both INSERT / UPDATE (and maybe DELETE) for the same object.  there's a lot of stuff going on with defaults, version counters, and such that all gets a lot more complicated for that.

**Comment by tgross35** [comment]
That all makes sense! I can see this spiraling out of control a bit, and the fix is easy enough to check in code and create a new record if necessary.

Just my 2¢, curious to see what others have to say -- I would expect two or more joined tables (inner or outer) to act exactly like one large table, only allowing inserts or updates if constraints for every column (in all base tables) are satisfied. If you want to update tables A and C without touching B, shouldn't you use a separate join between A and C? Then if you need the B parameters sometime later, you could use A∪B∪C and the B record would be created as needed. DELETE action is kind of on a per-join basis from user definition -- if you delete a record from B then it will, of course, disappear from A∩B (inner join) and A right join B, but still be present on A, A∪B, and A left join B. Of course, this might be way out of scope of an ORM and I might be thinking way too application-specific.

**Comment by zzzeek** [comment]
another big issue is that SQLAlchemy doesn't *know* that this table needs an INSERT.  this would add a whole new level of state tracking that is not implemented right now.   your mapping is even joining together the two primary key columns into one attribute, so SQLAlchemy can't even look at the "primary key" here because it's not tracked separately.   

you can, if you'd like, implement an INSERT using the before_update() hook: https://docs.sqlalchemy.org/en/13/orm/events.html?highlight=before_update#sqlalchemy.orm.events.MapperEvents.before_update

the "connection" is right there, and if you can look at the object's state and determine that it needs an INSERT for one of the tables (that part you have to invent somehow), you can emit an INSERT for the table within this hook and then your update will succeed.

**Comment by zzzeek** [comment]
that is:

```
from sqlalchemy import event

# standard decorator style
@event.listens_for(JoinTable, 'before_update')
def receive_before_update(mapper, connection, target):
   if target.some_related_attribute is None:
        connection.execute(t_table_b.insert(), {"id": target.id})

```

**Comment by tgross35** [comment]
Easy enough, thanks for the help and for the understanding!

**Comment by zzzeek** [comment]
the goal is to add a doc note for now and include that mini-recipe in it.
