### ISSUE TITLE
Support public accessor for `single_entity` on Query

### ISSUE THREAD

**Issue by pfhayes** [sqlalchemy/sqlalchemy#4934]
Currently the logic for detecting if a query will return a list of entities or a list of tuples is inside lib/sqlalchemy/orm/loading.py, but it would be useful if this was available publicly. The use case is for library maintainers who are writing middleware between an application and sqlalchemy.

As a simple example:

```python
def issue_query_and_wrap_results(query, Wrapper):
  results = query.all()
  for result in results:
    if q.is_single_entity:
      return Wrapper(result)
    else:
      return tuple(Wrapper(r) for r in result)
```

Without this accessor, you need to inspect the return results or private members of the
query and try to guess the intent

Is this acceptable to add to the public API? If so I can add a PR

**Comment by zzzeek** [comment]
this area is a little troubling for me because I want to get rid of the whole non-tuple / tuple assumption in Query by SQLAlchemy 2.0.  However, that's a bit of a way off and may well be on a new query object that is not Query in any case, since this is just an accessor and there is already the "only_return_tuples" awkwardness, it should be fine.

**Comment by sqla-tester** [comment]
**Patrick Hayes** has proposed a fix for this issue in the **rel_1_3** branch:

**Add public accessor `is_single_entity` to Query** https://gerrit.sqlalchemy.org/1549
