### ISSUE TITLE
Assigning string values to an Oracle NUMBER backed attribute

### ISSUE THREAD

**Issue by fredludlow** [sqlalchemy/sqlalchemy#4961]
While updating an older app from 1.0.3 to 1.3.10, I found it was assigning strings (pulled out of a web form) to various numeric columns. It shouldn't have been doing this but it hadn't caused an error before and we'd not spotted it. On 1.3.10 this sometimes throws an error, depending on the asdecimal state of the column:

```python
from sqlalchemy.dialects.oracle import NUMBER

class C(Base):
    x = Column("x", NUMBER(asdecimal=True)
    y = Column("y", NUMBER(asdecimal=False)

# ...
c = C()
c.x = "1.5" # A flush now will throw StatementError
c.y = "1.5" # A flush now is fine
```

The actual error raised is from [dialects/oracle/cx_oracle.py](https://github.com/zzzeek/sqlalchemy/blob/d76cb7213557c24609a1a75d8c391aea0179562a/lib/sqlalchemy/dialects/oracle/cx_oracle.py#L350):

```python
            def process(value):
                if isinstance(value, (int, float)):
                    return processor(value)
                elif value is not None and value.is_infinite():
                    return float(value)
                else:
                    return value
```

This process function is only used when asdecimal is True

I'm not really sure what correct behaviour is here, is it?
 * Both cases should succeed
 * Both should fail
 * The correct behaviour isn't defined here, just stop assigning strings to NUMBER columns
 * This is actually completely correct behaviour and I'm missing something :)

**Comment by zzzeek** [comment]
for now the choice would be #3, the behavior is undefined.   the SQLAlchemy type functions try as hard as possible to not get involved with what the DBAPI wants to do with the data.  The cx_Oracle DBAPI happens to be super complicated in the area of typing, but still, there's no supported validation of data on the SQLAlchemy side.    that is, we could add a test here that the Oracle dialect raises for a numeric that is passed as a string, but then that means we have to add the same function for all the other dialects, and also implies we need to add similar functions to all datatypes across the board, which not only is a lot of complexity and code to support, it's also a performance hit. 

it looks like you'd be getting an error here because the value is not int/float so assumes this is a Decimal object, which it's not.         I assume that's why it's StatementError because it is wrapping the TypeError.

**Comment by fredludlow** [comment]
Thanks @zzzeek, that makes sense.
