### ISSUE TITLE
Update the documentation to remove dead bitbucket links

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5013]
In the documentation some links are still pointing to the dead bitbucket wiki (at https://bitbucket.org/zzzeek/sqlalchemy/wiki/)

This is an example:
https://docs.sqlalchemy.org/en/13/orm/extensions/baked.html#rationale

>There is an example of this on the wiki in the section [BakedQuery](https://bitbucket.org/zzzeek/sqlalchemy/wiki/UsageRecipes/BakedQuery), a precursor to this feature ..

I'm not sure if it is just a find `https://bitbucket.org/zzzeek/sqlalchemy/wiki/` and replace `https://github.com/sqlalchemy/sqlalchemy/wiki/` job. 
If so I can try to open a pr for it

**Comment by zzzeek** [comment]
sure, simple documentation PRs don't require an issue to be open so if you could propose corrections for these against master I can merge + backport to all published doc versions.  thanks!

**Comment by CaselIT** [comment]
In that particular example, it seems that there is no longer the wiki entry in github (at https://github.com/sqlalchemy/sqlalchemy/wiki/UsageRecipes/BakedQuery)

What is the best approach in this case?

**Comment by zzzeek** [comment]
just take that whole sentence out.   im looking at this documentation and i can't even believe i wrote all this, people usually don't read all this stuff.   i have learned that with documentation, every paragraph you add that isn't showing exactly how to do something right now is just losing more readers.

**Comment by CaselIT** [comment]
I went down a rabbit hole today looking for something in sqlalchemy and landed on that page.

In that particular case I think a lot needs to be taken out, since from then on it uses `.bake` in the query, which I think was added in the example in the wiki

**Comment by zzzeek** [comment]
whenever I am not fixing issues I am trying to work on a larger push to replace the whole bakedquery system wholesale so all those docs are going to be obsolete.   BakedQuery does need a little bit of a "Rationale" section because the lambda thing is so weird, the newer approach is probably going to either do away with the lambda thing or have it only as an optional approach.

**Comment by CaselIT** [comment]
Yes the lambda is a bit wired. At least it's not usual. 
I wanted to start using it, should I hold off, since it is bending deprecation or it will just change how it is used?

I'll try a find and replace on the docs, and maybe flag the dead links if I find a way to automate it

**Comment by zzzeek** [comment]
bakedquery is getting a fair amount of use but the plan is hopefully that the whole thing would become transparent.   

one of the biggest technical issues I'm having however is that to generate an "honest" cache key, which means, to actually look at all the expressions and parameters you put into the query and build up a cache key based on what is constructing the query, rather than "cheating" which is what the lambda thing is doing, is still fairly computationally expensive.     the "lambda:" trick is still by far the most performant approach it's just very strange looking.    in the newer caching system, if I keep the lambda concept in, it will work even better because I've figured out a way to derive literal values from them.    that is, you won't need to worry about using bindparam() inside of them.  

That probably all sounds very vague but it would take me a lot of time to explain, I hope that I can just get some time to make more progress with the newer approach.

if you need faster ORM queries right now I think you should use BakedQuery because the newer idea is not going to be production quality for at least a year.

**Comment by CaselIT** [comment]
Understood. Thanks for the input

**Comment by CaselIT** [comment]
The entry in that documentation page seems to be the only link to the bitbucket wiki.

Since you plan to rework the backed query anyway, and the is no longer the entry in the github page, I'll leave it alone
