### ISSUE TITLE
create_engine isolation level does not work for postgresql

### ISSUE THREAD

**Issue by z10z10b10** [sqlalchemy/sqlalchemy#5015]
Env:
	postgresql ： 11.5
	sqlalchemy: 1.2.1

According to my knowledge, setting `create_engine(isolation_level="AUTOCOMMIT”)` will have the same effect if  I set `sessionmaker(bind=engine, autocommit=True)` to generate sessions in SQLAlchemy.

But when having set `create_engine(isolation_level="AUTOCOMMIT”)` only, if I do a `select` query with SQLAlchemy, and do not mannualy `session.commit()`, I will not be able to alter my data structure with `alter table` in my postgresql database and will be warned `waiting for lock`.

If I set  `sessionmaker(bind=engine, autocommit=True)`, such problems won’t happen. 

Is there any differnce between setting `create_engine(isolation_level="AUTOCOMMIT”)` and `sessionmaker(bind=engine, autocommit=True)`?    
I tried to find recorresponding documentations but found nothing.

**Comment by zzzeek** [comment]
hi there-

responses inline.

> Env:
> postgresql ： 11.5
> sqlalchemy: 1.2.1
> 
> According to my knowledge, setting `create_engine(isolation_level="AUTOCOMMIT”)` will have the same effect if I set `sessionmaker(bind=engine, autocommit=True)` to generate sessions in SQLAlchemy.

The "autocommit=True" option to sessionmaker is a (not recommended) SQLAlchemy feature described at https://docs.sqlalchemy.org/en/13/orm/session_transaction.html#autocommit-mode.     Whereas the 'isolation_level='AUTOCOMMIT'" has to do with a psycopg2 driver option described at https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#transaction-isolation-level  .  These two options are completely unrelated and **do totally different things**.   

The former causes all Session operations to use a new connection from the connection pool for every SELECT statement, which when this connection is returned, a rollback() is called on the connection so that the psycopg2 transaction is closed.  

The latter sets a driver-level flag on the psycopg2 connection that causes psycopg2 to not emit any BEGIN/COMMIT/ROLLBACK at all on the connection, which is not the normal DBAPI behavior which is that BEGIN must normally be emitted unconditionally when the connection is used.     There is similarity in the end effect of these two flags but they don't work the same way and only psycopg2's flag will allow for certain postgresql DDL operations to proceed.

> 
> But when having set `create_engine(isolation_level="AUTOCOMMIT”)` only, if I do a `select` query with SQLAlchemy, and do not mannualy `session.commit()`, I will not be able to alter my data structure with `alter table` in my postgresql database and will be warned `waiting for lock`.


cannot reproduce.  Here is an [MCVE](http://stackoverflow.com/help/mcve) that illustrates I can DROP TABLE while I just got a SELECT on a different connection.  If i take out the autocommit, it blocks:

```
from sqlalchemy import create_engine

e = create_engine("postgresql://scott:tiger@localhost/test", isolation_level='AUTOCOMMIT')

c = e.connect()

print(c.connection.connection)
assert c.connection.connection.autocommit

c.execute("create table foo (id integer);")

c2 = e.connect()
result = c2.execute("select * from foo")
result.fetchall()

# if autocommit is not set, this will block
c.execute("drop table foo")

```
> 
> If I set `sessionmaker(bind=engine, autocommit=True)`, such problems won’t happen.

this is because the autocommit=True sessionmaker will use a new connection from the connection pool for each statement, then return it.  when it returns the connection, the pool calls .rollback() on it, so the transaction is closed.


> 
> Is there any differnce between setting `create_engine(isolation_level="AUTOCOMMIT”)` and `sessionmaker(bind=engine, autocommit=True)`?
> I tried to find recorresponding documentations but found nothing.

autocommit=True is described at https://docs.sqlalchemy.org/en/13/orm/session_transaction.html#autocommit-mode:

> In this mode, the Session begins new transactions automatically as soon as it needs to do work upon a database connection; the transaction then stays in progress until the Session.commit() or Session.rollback() methods are called.

AUTOCOMMIT for psycopg2 is described at:  https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#psycopg2-isolation-level  which refers to the psycopg2 set_isolation_level() method; to know what that is, you need to read psycopg2's documentation at http://initd.org/psycopg/docs/connection.html?highlight=set_isolation_level#connection.set_isolation_level  which would take you to http://initd.org/psycopg/docs/usage.html#transactions-control:

> It is possible to set the connection in autocommit mode: this way all the commands executed will be immediately committed and no rollback is possible. A few commands (e.g. CREATE DATABASE, VACUUM…) require to be run outside any transaction: in order to be able to run these commands from Psycopg, the connection must be in autocommit mode: you can use the autocommit property.
> By default even a simple SELECT will start a transaction: in long-running programs, if no further action is taken, the session will remain “idle in transaction”, an undesirable condition for several reasons (locks are held by the session, tables bloat…). For long lived scripts, either make sure to terminate a transaction as soon as possible or use an autocommit connection. 


feel free to provide a short, single file MCVE demonstration script of your issue.    hope this helps.

**Comment by z10z10b10** [comment]
My problem has been solved. Thank you very much for your answer.
