### ISSUE TITLE
implement per-dialect datetime representations, not just strsqlcompiler

### ISSUE THREAD

**Issue by pasenor** [sqlalchemy/sqlalchemy#5052]
When I try to compile a query with datetime parameters using `literal_binds`, e.g.:

    from sqlalchemy import create_engine
    from sqlalchemy.ext.declarative import declarative_base
    from sqlalchemy import Column, DateTime
    from sqlalchemy.orm import sessionmaker
    from datetime import datetime

    engine = create_engine('sqlite:///:memory:', echo=True)
    Base = declarative_base()
    class M(Base):
        __tablename__ = 'M'
        d = Column(DateTime, primary_key=True)

    Session = sessionmaker()

    print(Session().query(M).filter(
        M.d < datetime.now()
    ).statement.compile(
        compile_kwargs={'literal_binds': True}
    ))

the engine gives me the following error

    NotImplementedError: Don't know how to literal-quote value datetime.datetime(2019, 12, 25, 14, 26, 42, 756674)

There probably should be a default representation for datetimes as an iso-formatted string in single quotes.

**Comment by zzzeek** [comment]
hi there -

why aren't you passing the engine to compile?  The SQLite dialect necessarily has a datetime formatter of its own as there is no datetime support in SQlite directly.

passing engine to compile allows it to generate this form.   for StrSQLCompiler, which is not meant to be used to actually emit SQL, there is apparently not an issue for this but I would want it to generate a string using str() for any kind of object and then applies safestring quoting to it in all cases.

**Comment by pasenor** [comment]
Yes, it works for SQLite, thanks. But my actual problem was with mysql: I wanted to debug an application and print out a compiled query with datetime parameters. So the example here should have been

```
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, DateTime
from sqlalchemy.dialects import mysql
from sqlalchemy.orm import sessionmaker
from datetime import datetime

engine = create_engine('mysql+pymysql://root:root@127.0.0.1:3306/test?charset=utf8', echo=True)
Base = declarative_base()
class M(Base):
    __tablename__ = 'M'
    d = Column(DateTime, primary_key=True)

Session = sessionmaker()

print(Session().query(M).filter(
    M.d < datetime.now()
).statement.compile(
    bind=engine,
    dialect=mysql.dialect(),
    compile_kwargs={'literal_binds': True}
))
```
It still gives the same error. I'm not familiar with SQLAlchemy internals, but it seems one could define `sqltypes.DateTime._cached_literal_processor` to produce engine-independent representation, would that be a sensible approach?

**Comment by zzzeek** [comment]
despite what the standard says (good job finding that btw) there is no engine-independent representation, witness Oracle:

```
SQL*Plus: Release 11.2.0.2.0 Production on Thu Dec 26 11:50:21 2019

Copyright (c) 1982, 2011, Oracle.  All rights reserved.

Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL> create table foo (data date);

Table created.

SQL> insert into foo (data) values ('2019-12-26 11:51:00.516384');
insert into foo (data) values ('2019-12-26 11:51:00.516384')
                               *
ERROR at line 1:
ORA-01861: literal does not match format string


```

Oracle's default format for the DATE type is "DD-MON-YY".    Yes, five days before 2020, that is still the default date format.  Where's the timestamp portion and why am I talking about DATE?  Because that's the datatype that oracle has for all date / timestamp values.   If you want to insert a timestamp you have to do something like this:

    insert into foo (data) values (TIMESTAMP '2019-12-26 11:51:00.516384');


but that likely is not available on older Oracles, where we historically would always have to do this, note this doesnt support the microseconds:

    insert into foo (data) values (TO_DATE('2019-12-26 11:51:00', 'YYYY-MM-DD HH24:MI:SS'));

So, there is no engine-independent datetime respresentation and the default behavior for any dialect where it's not implemented should be to raise that it doesn't know how.

in your test example, you're passing the MySQL dialect so this would indicate you're looking for a literal date processor for MySQL.

Right now there are no literal date processors for any engine other than SQLIte.  I can tell that I will eventually lose the battle to code in date formatters for all the included dialects and the architecture supports this so I can support simple PRs to add these individually.      The reason this is a "battle" is because the "war" is, "SQLAlchemy should guarantee a literal renderer for *all* datatypes on *all* backends", and I really don't want to to that, because it is a massive duplication of effort for what every DBAPI we use is already doing.     

However, we have literal rendering for strings, ints, booleans and maybe floats already in, date  / time and timestamp values are likely inevitable so I can accept PRs for these (note that an issue needs to be created for each PR, like if you were supplying the literal renderer for MySQL alone, create an issue for that, etc.).

**Comment by zzzeek** [comment]
also note that yes, if we implement a set of ISO rendering functions, the "normal" dialects like Postgresql and MySQL can fall back to using that rendering function.

**Comment by zzzeek** [comment]
some of the work for Postgresql is in this review, apparently we may need to add the "timestamp" keyword for PG: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/18/

**Comment by CaselIT** [comment]
> StrSQLCompiler, which is not meant to be used to actually emit SQL, there is apparently not an issue for this but I would want it to generate a string using str() for any kind of object and then applies safestring quoting to it in all cases.

I'll work on this for now. using the python `str` to render the string

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**String compiler can now literal compile datetime objects** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1816

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**String compiler can now literal compile datetime objects** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1825

**Comment by CaselIT** [comment]
I think that we can reopen this, since at the moment we just implemented a default representation when literally compile without a dialect.
These is still no implementation for specific dialects, other that sqlite

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**implement iso date literals for all backends** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3744
