### ISSUE TITLE
Short-circuit in or_ operator not being utilised.

### ISSUE THREAD

**Issue by aintHuman** [sqlalchemy/sqlalchemy#5061]
The filter condition causes an error:

```
or_(
  age_min is None,
  Model.age >= age_min,
),
```

> "Only '=', '!=', 'is_()', 'isnot()', 'is_distinct_from()', 'isnot_distinct_from()' operators can be used with None/True/False"

shouldn't the first condition in the `or_` group cause a short-circuit of the second condition, which would otherwise and very reasonably throw an error when trying to use gte operator on a None variable?

In other words, in the above, when age_min is actually None, then the above should be reduced to the following, and in doing so, discarding the problematic and now inconsequential second condition?

```
or_(
  age_min is None,
),
```
Since `age_min` is a variable in the python abstraction layer, this should be logically handled prior to translation into sql code.

**Comment by zzzeek** [comment]
the SQLAlchemy "or_()" construct does not perform any boolean logic in Python, it is used to render the OR operator in the database.      If you use `or_()` and pass two expressions to it, it will render two expressions in the SQL string.    From a python perspective, it is not possible for your second expression to not be invoked by SQLAlchemy even if SQLAlchemy wanted to be in the business of guessing which components of an expression are actually intended to be evaluated as Python expressions and not SQL expressions.

The error you are getting is because age_min is None, SQLAlchemy has an assertion that it doesn't make sense to compare to NULL using "greater than", but this is still valid SQL and in this odd case it would be fine.   To work around that check, use the literal() function:

```
>>> print(or_(age_min is None, column('q') >= literal(age_min)))
true
>>> age_min = 10
>>> print(or_(age_min is None, column('q') >= literal(age_min)))
q >= :param_1

```

It is not possible from a Python interpreter perspective to not invoke the second expression you are passing to "or_()".   SQLAlchemy or_() is a function, and in Python, all arguments to the function are evaluated.

Even if it were somehow possible, this still would not be SQLAlchemy's domain as this would suggest that SQLAlchemy's expression constructs would have to intermingle boolean expressions invoked on the Python / client side and boolean expressions rendered in SQL and invoked on the database side, which is not possible.

in this case it is advised to use the clearest and most explicit approach, which is to simply apply the filter condition conditionally:

```
if age_min is not None:
    query = query.filter(table.col >= age_min)

```

the above form makes the design and intent unambiguously clear.

**Comment by aintHuman** [comment]
That is a seriously thorough answer, and I very much appreciate the time you put into clarifying. Clear as crystal. Cheers.

**Comment by zzzeek** [comment]
thanks, as is often the case you hit upon an area that's a little strange and that I forgot how my own or_() operator works didn't help
