### ISSUE TITLE
dialect-level temp table fixture for tests

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5085]
@pauldex and I have been working on getting [sqlalchemy-firebird](https://github.com/pauldex/sqlalchemy-firebird) to fly with the test suite and we've hit upon an issue with ComponentReflectionTest and temporary tables. Firebird appears to have implemented GLOBAL TEMPORARY tables similar to what we see in the test suite code for Oracle starting [here](https://github.com/sqlalchemy/sqlalchemy/blob/2734439fff953a7bb8aecdedb5f851441b5122e9/lib/sqlalchemy/testing/suite/test_reflection.py#L303).

This might be a good time to implement that "dialect-level temp table fixture" mentioned in the code comment now that we have a real-world use case for it.

**Comment by zzzeek** [comment]
okey doke, so this also leads me to note a few other strange things:

1. the README at https://github.com/sqlalchemy/sqlalchemy/blob/master/README.dialects.rst doesn't exactly say **how** to run the tests.  it sort of implies you'd run py.test, which is fine.  however, it doesn't talk about having a tox.ini file and also it doesn't get into the fact that for SQLAlchemy itself we run the tests with pytest-xdist, which uses multiprocessing, and has a whole extra set of requirements that the suite can provision new databases.

2. not sure if I've shown you this before, but there is in fact a whole dialect-level test suite "create database provisioning" system in https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/testing/provision.py.     The good news is that is IS extensible, the bad news is that it has all the current DBs inside of SQLAlchemy hardcoded into that one file and also uses private underscore names to define things.

So here is what I think we should do:

1. refactor provision.py above so that all the different dialect logic that is currently hardcoded in there is moved out to each dialect.  So all the functions that say "sqlite" would move out to lib/sqlalchemy/dialects/sqlite/provision.py, such as:

```
# lib/sqlalchemy/dialects/sqlite/provision.py

from ..testing.provision import _follower_url_from_main
from ..testing.provision import _post_configure_engine

@_follower_url_from_main.for_db("sqlite")
def _sqlite_follower_url_from_main(url, ident):
    url = sa_url.make_url(url)
    if not url.database or url.database == ":memory:":
        return url
    else:
        return sa_url.make_url("sqlite:///%s.db" % ident)


@_post_configure_engine.for_db("sqlite")
def _sqlite_post_configure_engine(url, engine, follower_ident):
    from sqlalchemy import event

    @event.listens_for(engine, "connect")
    def connect(dbapi_connection, connection_record):
        # use file DBs in all cases, memory acts kind of strangely
        # as an attached
        if not follower_ident:
            dbapi_connection.execute(
                'ATTACH DATABASE "test_schema.db" AS test_schema'
            )
        else:
            dbapi_connection.execute(
                'ATTACH DATABASE "%s_test_schema.db" AS test_schema'
                % follower_ident
            )


```

2. there would have to be some hook so that the test suite knows how to load up lib/sqlalchemy/dialects/sqlite/provision.py.   for starters, we can do something simple:

```
diff --git a/lib/sqlalchemy/dialects/sqlite/__init__.py b/lib/sqlalchemy/dialects/sqlite/__init__.py
index 142131f63..9ab10196c 100644
--- a/lib/sqlalchemy/dialects/sqlite/__init__.py
+++ b/lib/sqlalchemy/dialects/sqlite/__init__.py
@@ -24,6 +24,7 @@ from .base import TEXT
 from .base import TIME
 from .base import TIMESTAMP
 from .base import VARCHAR
+from . import provision
 
 
 # default dialect

```

3.  we change the names in provision.py to not have underscores:

```
diff --git a/lib/sqlalchemy/testing/provision.py b/lib/sqlalchemy/testing/provision.py
index 70ace0511..d4f6d283e 100644
--- a/lib/sqlalchemy/testing/provision.py
+++ b/lib/sqlalchemy/testing/provision.py
@@ -98,32 +98,38 @@ def _configs_for_db_operation():
 
 
 @register.init
-def _create_db(cfg, eng, ident):
+def create_db(cfg, eng, ident):
+    """write a docstring """
     raise NotImplementedError("no DB creation routine for cfg: %s" % eng.url)
 
 
 @register.init
-def _drop_db(cfg, eng, ident):
+def drop_db(cfg, eng, ident):
+    """write a docstring """
     raise NotImplementedError("no DB drop routine for cfg: %s" % eng.url)
 
 
 @register.init
-def _update_db_opts(db_url, db_opts):
+def update_db_opts(db_url, db_opts):
+    """write a docstring """
     pass
 
 
 @register.init
-def _configure_follower(cfg, ident):
+def configure_follower(cfg, ident):
+    """write a docstring """
     pass
 
 
 @register.init
-def _post_configure_engine(url, engine, follower_ident):
+def post_configure_engine(url, engine, follower_ident):
+    """write a docstring """
     pass
 
 
 @register.init
-def _follower_url_from_main(url, ident):
+def follower_url_from_main(url, ident):
+    """write a docstring """
     url = sa_url.make_url(url)
     url.database = ident
     return url

```

the names also change for all the dialect-level decorator calls.

4. we have to document those methods and how to use them in README.dialects.rst.


5. FINALLY, we add a new method to the provision.py framework called create_temp_table(), where we pass it the table name, metadata, and columns and it just returns that Table object with the correct flags.   this could also be used for the "CREATE VIEW" we have in there as well as some other hardcoded things other places in the test framework I'd get into later.

now why am I not just adding CreateTempTable() etc. to the dialects.    Because these temp tables need to be created in a way that is specific to what the test suite wants and I'd prefer they not become more complicated, general use APIs inside the dialects.   The case is the same for everything else in provision.py - commands like CREATE DATABASE could be regular SQLAlchemy features and we of course get asked for that all the time, but in provision.py you'll note there are very specific forms of CREATE DATABASE such as the one for PostgreSQL that uses the existing "test" database as a template.   The idea is, by having test-suite specific functions in provision.py, these functions are *easier* to write since they aren't generalized "create database" / "create temp table" commands in the dialect that then somehow have to also know that this is in the context of the test suite, the functions can be written as simply as possible with the assumption they just have to work for the test suite and nothing else.


In the case of Firebird, for now the Firebird dialect can just skip the temp table tests by marking them as not supported in requirements.py.

**Comment by gordthompson** [comment]
I've done steps 1 through 3 above. When I tried tox -e py36-sqlite I got

```
(venv) gord@xubuntu64-nbk1:~/git/sqlalchemy$ tox -e py36-sqlite
GLOB sdist-make: /home/gord/git/sqlalchemy/setup.py
py36-sqlite inst-nodeps: /home/gord/git/sqlalchemy/.tox/.tmp/package/1/SQLAlchemy-1.4.0b1.dev0.zip
py36-sqlite installed: apipkg==1.5,attrs==19.3.0,execnet==1.7.1,importlib-metadata==1.4.0,more-itertools==8.1.0,packaging==20.0,pluggy==0.13.1,py==1.8.1,pyparsing==2.4.6,pytest==5.3.2,pytest-forked==1.1.3,pytest-xdist==1.31.0,six==1.13.0,SQLAlchemy==1.4.0b1.dev0,wcwidth==0.1.8,zipp==0.6.0
py36-sqlite run-test-pre: PYTHONHASHSEED='2202419579'
py36-sqlite run-test: commands[0] | python -m pytest --log-info=sqlalchemy.testing -n4 --max-worker-restart=5 --db sqlite
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/gord/git/sqlalchemy/.tox/py36-sqlite/lib/python3.6/site-packages/_pytest/main.py", line 194, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/home/gord/git/sqlalchemy/.tox/py36-sqlite/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/gord/git/sqlalchemy/.tox/py36-sqlite/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/gord/git/sqlalchemy/.tox/py36-sqlite/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/gord/git/sqlalchemy/.tox/py36-sqlite/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/gord/git/sqlalchemy/.tox/py36-sqlite/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/gord/git/sqlalchemy/.tox/py36-sqlite/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/gord/git/sqlalchemy/test/../lib/sqlalchemy/testing/plugin/pytestplugin.py", line 98, in pytest_sessionstart
INTERNALERROR>     plugin_base.post_begin()
INTERNALERROR>   File "/home/gord/git/sqlalchemy/test/../lib/sqlalchemy/testing/plugin/plugin_base.py", line 253, in post_begin
INTERNALERROR>     fn(options, file_config)
INTERNALERROR>   File "/home/gord/git/sqlalchemy/test/../lib/sqlalchemy/testing/plugin/plugin_base.py", line 344, in _engine_uri
INTERNALERROR>     from sqlalchemy.testing import provision
INTERNALERROR>   File "/home/gord/git/sqlalchemy/.tox/py36-sqlite/lib/python3.6/site-packages/sqlalchemy/testing/provision.py", line 6, in <module>
INTERNALERROR>     from ..dialects.mssql.provision import _reap_mssql_dbs
INTERNALERROR>   File "/home/gord/git/sqlalchemy/.tox/py36-sqlite/lib/python3.6/site-packages/sqlalchemy/dialects/mssql/__init__.py", line 11, in <module>
INTERNALERROR>     from . import provision  # noqa
INTERNALERROR>   File "/home/gord/git/sqlalchemy/.tox/py36-sqlite/lib/python3.6/site-packages/sqlalchemy/dialects/mssql/provision.py", line 5, in <module>
INTERNALERROR>     from ...testing.provision import create_db
INTERNALERROR> ImportError: cannot import name 'create_db'
ERROR: InvocationError for command /home/gord/git/sqlalchemy/.tox/py36-sqlite/bin/python -m pytest --log-info=sqlalchemy.testing -n4 --max-worker-restart=5 --db sqlite (exited with code 3)
_______________________________________________________________ summary _______________________________________________________________
ERROR:   py36-sqlite: commands failed
```

It looks like tox is unhappy with `from ...testing.provision import create_db`, but PyCharm had no complaints.

**Comment by zzzeek** [comment]
there's an import cycle that you can see in the stack trace.   idealy the "testing/provision.py" file would not have any imports of "from ..dialects.mssql.provision", that would need to be brought about in the other direction, which means the whole "Reap dbs" thing also needs to be generalized a bit.

import cycle issues are not very easy stuff to navigate so let me know if you want me to push it along.

**Comment by gordthompson** [comment]
>  let me know if you want me to push it along.

Yes, please.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Refactor test provisioning to dialect-level files** https://gerrit.sqlalchemy.org/1663

**Comment by zzzeek** [comment]
OK you got it, if you want to take a look what I did in gerrit.  do you want to work on the gerrit side for this one now?   the PR is basically behind.

**Comment by zzzeek** [comment]
there's a dropdown that says "diff against", and if you select "diff against: 1", you can see the differences in my change vs. yours.  (stuff that github PRs don't really make very easy)

**Comment by zzzeek** [comment]
this is great!   we can have "provision.py" be part of README.dialects.rst for this it's going to be great

**Comment by pauldex** [comment]
Awesome!  I'm looking forward to adding this change to sqlalchemy_firebird.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Refactor test provisioning to dialect-level files** https://gerrit.sqlalchemy.org/1684
