### ISSUE TITLE
Arrow Flight as a new connector type

### ISSUE THREAD

**Issue by narendrans** [sqlalchemy/sqlalchemy#5089]
It looks like we have odbc, jdbc as the main connector types in lib/sqlalchemy/connectors. Is it possible to implement a new one for Arrow Flight? https://arrow.apache.org/blog/2019/10/13/introducing-arrow-flight/

SQL statements can be sent via the flight protocol. An example from an implementation of flight is here: https://github.com/dremio-hub/dremio-flight-connector

```from pyarrow import flight
import pyarrow as pa

class HttpDremioClientAuthHandler(flight.ClientAuthHandler):

    def __init__(self, username, password):
        super(flight.ClientAuthHandler, self).__init__()
        self.basic_auth = flight.BasicAuth(username, password)
        self.token = None

    def authenticate(self, outgoing, incoming):
        auth = self.basic_auth.serialize()
        outgoing.write(auth)
        self.token = incoming.read()

    def get_token(self):
        return self.token

username = '<USERNAME>'
password = '<PASSWORD>'
sql = '''<SQL_QUERY>'''

client = flight.FlightClient('grpc+tcp://<DREMIO_COORDINATOR_HOST>:47470')
client.authenticate(HttpDremioClientAuthHandler(username, password)) 
info = client.get_flight_info(flight.FlightDescriptor.for_command(sql))
reader = client.do_get(info.endpoints[0].ticket)
batches = []
while True:
    try:
        batch, metadata = reader.read_chunk()
        batches.append(batch)
    except StopIteration:
        break
data = pa.Table.from_batches(batches)
df = data.to_pandas()```

**Comment by zzzeek** [comment]
hi there -

the "connector" concept is not essential for the production of any particular SQLAlchemy dialect, they are present in SQLAlchemy mostly due to historical reasons, the main one that back when we supported zxJDBC, we were trying to supply it for all backends.  However, Jython stopped being maintained and it never gained any traction, so all of that JDBC code will likely be removed in upcoming releases.

For ODBC, it wasn't clear what role ODBC would play in the Python database API scene in the early days, and as there's a bit of mix-and-match going on with ODBC, namely that we added support not just for pyodbc but also mxodbc (the latter of which has not been maintained), and that pyodbc featured support for MSSQL, Sybase, and MySQL, led to the decision to factor out some of the common logic from these various backends into the "connector".    

However if you look at the "connector", there's almost nothing there, and additionally, if someone were writing a third-party dialect for SQLAlchemy, it might be preferable for them to use their own "connector" since that way they can make tweaks as needed that are specific to their dialect / DBAPI without waiting for SQLAlchemy to add them.

The point is that the whole notion of these database-agnostic middle layers eliminating any artifacts of the backend database and driver is 100% a myth.    In practice, it doesn't work at all.  When I first was tasked with getting mxodbc to work with SQLAlchemy, it was extremely difficult, even with 100% tests passing with pyodbc.  There were many behavioral artifacts that differ between these two drivers.  Within pyodbc itself, we have a MySQL dialect and the MSSQL dialect, and again there are all kinds of issues that make one work and not the other in various contexts.     In practice, people *always* prefer to use a non-ODBC dialect when possible.   For SQL Server, it was very unfortunate that the pymssql driver no longer could be supported; it was a lot better than pyodbc for a time but Microsoft not suprisingly funded pyodbc so for the moment pyodbc is winning again.  But issues like [these](https://github.com/mkleehammer/pyodbc/issues/134) are what we get with this arrangement.

Given all that, looking at Flight, this protocol looks interesting however it is brand new.    it would not be applicable to SQLAlchemy unless there was a high demand for a variety of dialects that are based on this system.  Additionally, the whole concept of the "connector" is not necessary in order for a particular DBAPI to be supported;  if you are writing a SQLAlchemy dialect for a particular Python DBAPI + backend database combination that is based on Flight, you could just as easily include the "connector" code within your dialect directly.         I would recommend going with this approach for the moment.   If a whole ecosystem of "flight" based SQLAlchemy dialects comes online, then the connector concept could be used, but even in that case, it could still be published as an external dependency to these dialects that are themselves already third party.

Only if the proposal is towards the goal of adding dialects for the current "built-in" databases: Postgresql, MySQL, SQL Server, Oracle, via the Flight driver, would this be appropriate.   But as has already been observed, the non-"agnostic" drivers already tend to be preferred for these backends as well with the exception of SQL server.

I would be -1 on this proposal for now as it doesn't add any value to have this code be part of SQLAlchemy.  The emphasis for dialects should be towards third-party support rather than adding more maintenance burden to SQLAlchemy itself.

**Comment by zzzeek** [comment]
feel free to reopen if you have more questions thanks!
