### ISSUE TITLE
metadata.reflect() still displays dropped table

### ISSUE THREAD

**Issue by danjenson** [sqlalchemy/sqlalchemy#5112]
Here is a simple code snippet that creates a table, reflects to show that table, then deletes the table and reflects again...but the table still shows up. If I log into the db, the table is definitely not there. Why does reflect still see it, and how can I get it to remove that dropped table?
```
import pandas as pd
from sqlalchemy import create_engine, MetaData
e = create_engine('sqlite:///test.db')
m = MetaData()
m.reflect(e)
m.tables  # immutabledict({})
df = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
df.to_sql('simple', e)
m.reflect(e)
m.tables # immutabledict({'simple': Table('simple', ...)})
m.tables['simple'].drop(e)
m.reflect(e)
m.tables # immutabledict({'simple': Table('simple', ...)}) <=== ??????
```

**Comment by zzzeek** [comment]
the MetaData colletion still has the Table object inside of it that you loaded.  metadata.reflect() doesn't erase Table objects that are already present.

**Comment by danjenson** [comment]
so, the metadata doesn't sync with the actual table schema; how can I get it to do that? This seems like unexpected behavior, especially since it updates when tables are created, and it's not documented anywhere afaik.

**Comment by zzzeek** [comment]
> so, the metadata doesn't sync with the actual database table schema; how can I do that, metadata or otherwise?

you would call metadata.clear() first then start again.

> This seems like unexpected behavior, 

if "sync"- like behavior were to be supported, this would imply that if you removed a Column from one of your tables, it would sync that as well; the same for if you changed the name of a foreign key constraint, changed the precision of a numeric type somewhere, etc.  "sync" would imply that **everything** would have to be fully refreshed.  if it were to do this "surgically", that is, not by just calling clear() and starting from scratch, it would require a whole lot of new logic (as well as test support, etc). for this to work correctly, in all cases.   Currently, none of the metadata structures support fine-grained removal of anything.  You can't remove a column from table, you can't remove a table from the metadata, etc.  This is because the whole system is optimized for generating SQL queries and ORM models and as such the metadata structure once built tends to be highly inter-linked, e.g. tables with foreign key constraints refer to each other,  a Column in a Table is going to be linked from all the SQL constructs and mappings you've made, etc.   So "remove" of individual elements is a very involved process to get right and then it's a use case that is basically never needed.  The SQLAlchemy project makes a decision for a given behavior as to the ratio of complexity and maintenance burden to actual need, and for the "remove a single table / remove a single column / etc" use case, the ratio is huge.  Especially that one can call metadata.clear() first, and then start again, and get a perfect "sync" with none of that complexity required, as long as you agree you didn't build queries and mappings on those tables that you'd want to keep.    Performance-wise this also makes little difference since a complete "sync" behavior would need to run through the full set of queries that are called in any case.    Less than complete "sync" behavior would be inconsistent.  So there's basically none.


> especially since it updates when tables are created; it's also not documented anywhere afaik.

it's documented here, albeit no dragons are flying around for this one:

https://docs.sqlalchemy.org/en/13/core/metadata.html#sqlalchemy.schema.MetaData.reflect

> Automatically creates Table entries in this MetaData for any table available in the database but not yet present in the MetaData. May be called multiple times to pick up tables recently added to the database, however no special action is taken if a table in this MetaData no longer exists in the database.

**Comment by chrispy-snps** [comment]
Manually removing the table entry after the drop works for me: 

```python
import sqlalchemy

engine = sqlalchemy.create_engine("...")

# create a "test" schema for our experiment
with engine.begin() as conn:
    conn.execute(sqlalchemy.text("DROP SCHEMA IF EXISTS test CASCADE"))
with engine.begin() as conn:
    conn.execute(sqlalchemy.text("CREATE SCHEMA test"))

# define two tables in the metadata object, then create them
metadata = sqlalchemy.MetaData()
table1 = sqlalchemy.Table("table1", metadata, sqlalchemy.Column("id", sqlalchemy.Integer, primary_key=True), schema="test")
table2 = sqlalchemy.Table("table2", metadata, sqlalchemy.Column("id", sqlalchemy.Integer, primary_key=True), schema="test")
metadata.create_all(engine)

# list all tables contained in the metadata object
print(f"Metadata tables before deletion: {metadata.tables.keys()}")

# DELETION STEP 1 - drop table from actual database
metadata.tables["test.table1"].drop(engine)

# DELETION STEP 2 - remove table entry from metadata object
metadata.remove(metadata.tables["test.table1"])

# list all tables contained in the metadata object
print(f"Metadata tables after deletion: {metadata.tables.keys()}")

# list all tables actually in the database
with engine.connect() as conn:
    result = conn.execute(
        sqlalchemy.text("SELECT table_name FROM information_schema.tables WHERE table_schema = 'test'")
    )
    print(f"Database tables after deletion: {result.fetchall()}")
```
