### ISSUE TITLE
Identifier case sensitivity in 'assert' 

### ISSUE THREAD

**Issue by pauldex** [sqlalchemy/sqlalchemy#5117]
While converting the internal Firebird dialect into an external one, I noticed that many of the existing reflection tests were failing because of the case of the identifier (table name, column name, index name, etc.).  For example, "expected value: 'test1', actual value: 'TEST1'."

In Oracle and Firebird, unquoted identifiers are converted to upper-case before being stored as metadata.  Here is a great [blog post by Lorenzo Alberton](http://www.alberton.info/dbms_identifiers_and_case_sensitivity.html) which explains the SQL standards and the way various database vendors implement the standard regarding case sensitive identifiers.

For Firebird, I could either change the creation of the test table to use quoted identifiers for lower case ones and keeping the expected values, or keep the current method of creating the test table and make the expected values upper-case.  Actually there are many other scenarios which would end up actually testing the reflection instead of failing because of an unexpected side effect.  Most of them would not work on all of the database dialects.

I think the best solution for this situation is to allow the dialect to perform the test.  My understanding is that the SQLAlchemy test suite supports this option.  However, I can't locate documentation that would explain or show how to do this.  It would be very helpful if someone could provide this.

**Comment by zzzeek** [comment]
Hi Paul -

the issue of Oracle and Firebird representing DDL identifiers as UPPERCASE in their system tables is a long-solved problem in SQLAlchemy, using a technique called "name normalization".     All of the reflection tests in SQLAlchemy pass 100% for Oracle using this technique and they should be passing, for the most part, for the existing Firebird dialect as well.

In SQLAlchemy, an all lower case name is considered to be "case insensitive", and if the name has any non-lower case characters, it becomes a "case sensitive" name.   So in order to translate between this naming convention and a dialect that has the [requires_name_normalize](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/default.py#L169) flag set, when the dialect is asked to reflect a DDL object, an all lowercase name is converted to UPPERCASE first ("name denormalize"), and then when the DDL structures come back, those that are represented as all UPPERCASE names are then converted to all lowercase ("name normalize").   This system is described for the Oracle dialect at https://docs.sqlalchemy.org/en/13/dialects/oracle.html#identifier-casing.

There is additionally a system by which strings can be constructed that force the use of quoting on or off.  These objects among other things may be used to handle the one very unusual case that this system does not naturally support, that of the Oracle or Firebird database identifier that is all uppercase and also quoted.   This system is described at https://docs.sqlalchemy.org/en/13/core/sqlelement.html?highlight=quoted_name#sqlalchemy.sql.elements.quoted_name.

for code that illustrates some of the mechanics of "name normalize" see https://github.com/sqlalchemy/sqlalchemy/blob/master/test/sql/test_quote.py#L1005

**Comment by zzzeek** [comment]
in the existing firebird dialect you can see the usage of denormalize_name() and normalize_name() as it requests and returns the list of columns for a table of a certain name: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/firebird/base.py#L815

**Comment by pauldex** [comment]
Great!  Thanks for explaining this and pointing out some examples.  I'll get this implemented in the external Firebird dialect next week.

**Comment by zzzeek** [comment]
OK great, glad that all works for you.

**Comment by gordthompson** [comment]
Name normalization already works in the (external) sqlalchemy-firebird dialect. I have a patch that will eliminate all current failures in ComponentReflectionTest once #5092 is merged.

**Comment by zzzeek** [comment]
you are all awesome

**Comment by pauldex** [comment]
Thanks Gord.
