### ISSUE TITLE
include lpad and to_number

### ISSUE THREAD

**Issue by popokatapepel** [sqlalchemy/sqlalchemy#5119]
I would like to include the generic functions lpad and to_number to functions.py like this

```
class lpad(GenericFunction):
    type(sqltypes.String)

class to_number(GenericFunction):
    type(sqltypes.Integer)
```

since this would be my first pr, i read https://www.sqlalchemy.org/develop.html and would include the tests and docs

**Comment by zzzeek** [comment]
hi there -

The functions that are in sqlalchemy.sql.functions need to be available on all backends, that is, they are either SQL standard functions or otherwise are common.

In this case, the to_number() function on Oracle is equivalent to CAST unless you need to add Oracle-specific formatting options, so you can likely use sqlalchemy.sql.cast() for that feature.  

LPAD is not SQL standard either, so I wouldn't want that in generic functions either.

Both of these functions can be used without being declared as "generic", that is, just call upon func.lpad() func.to_numnber() and they will render properly.   If you need return type support, you can either set up the above generic functions in your own application (GenericFunction classes can be declared anywhere, not just in SQLAlchemy, and they are automatically registered), or just use the type as ad-hoc, like   `func.lpad('some string', 5, type_=String)`.

**Comment by popokatapepel** [comment]
Ok, so `functions.py` is only for db-functions not limited to a db type. Thanks for the clearification and for the hint using `func`

**Comment by alfonso1003** [comment]
For anybody reading this and was still confused like I was, the following code will work:
```
from sqlalchemy import func
func.lpad( .... )
```

However, it's important where you get `fnc` from. For example, this won't work:
```
from sqlalchemy.sql.expression import func
func.lpad( .... )
```
