### ISSUE TITLE
forcing default casing of identifieres even if objects in metadata are mixed-case

### ISSUE THREAD

**Issue by njndst** [sqlalchemy/sqlalchemy#5126]
I have a set of metadata that have to be applied on sql server and Oracle. The metadata identifieres are mixed case, because this is wanted on mssql. On Oracle, defautl casing is wanted. 

I asked a question on stackoverflow, but perhaps this is a better place. 

https://stackoverflow.com/questions/59963513/create-objects-on-mssql-and-oracle-from-sqlalchemy-metadata-with-different-casin

Regards Niels

**Comment by zzzeek** [comment]
"I have a set of metadata that have to be applied on sql server and Oracle"

Define "applied".  What operations do you need to do?  do you need the *same* set of tables to work on both databases?     can you have two separate, independent sets of metadata?  is the issue just how to create these two independent sets of metadata , or how to have a single set of metadata work on either kind of backend?  

"But the names of objects should be mixed-case on MSSQL and default case on Oracle (all-caps)."

You can either use case sensitive identifiers, or case insensitive identifiers.   An identifier that requires that it be identified as MixedCase by definition is case sensitive, and on Oracle, the UPPERCASE names you describe are case insensitive.

The actual answer that I would strongly recommend would be to use case insensitive identifiers on all backends.  It's not really practical or necessary to have to use two different casings on different backends.

However, failing that, it depends completely on what you are actually trying to do which is not clear.   your stack overflow answer seems to suggest that you want to modify a single MetaData structure in place, indicating a single process of the application would only be talking to one database, however, changing all these names would impact how these Table objects are referred towards in code, since you are not using the [key](https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=column%20key#sqlalchemy.schema.Column.params.key) attribute on columns which I would think would be required for these Table objects with changing names to be useful in any practical sense.

**Comment by njndst** [comment]
Thank you for clarifying.  The situation is that my organization is cooperating with another organization  on an application that will run in each of out installations. We are using Oracle, they are using SQL Server. If we let the app use sqlalchemy core, the idea is to only have connectionstrings be different. Data structures will be maintained in SQLALchemy metadata statements. 

Having thought some more about the situation, I think we will try to convince the other guys to go case-insensitive. In which case the issue goes away entirely. 

Once again, thank you for taking the time to give valuable advice.

**Comment by zzzeek** [comment]
OK, otherwise we need to discuss within what scope you need this change to occur since that's where all the complexity occurs.  reopen if you need more guidance.
