### ISSUE TITLE
warn and deprecate for back_populates with viewonly=True

### ISSUE THREAD

**Issue by marty-se** [sqlalchemy/sqlalchemy#5149]
We're having some issues with `back_populates` of relationships referring to other relationships with `viewonly=True`. We get duplicates in the relationship list that the `back_populates` refers to.  Test case:

```python
import sqlalchemy
from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import attributes
from sqlalchemy.orm import relationship

Base = declarative_base()


class User(Base):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    name = Column(String)
    boston_addresses = relationship(
        "Address",
        # primaryjoin="and_(User.id==Address.user_id, Address.city=='Boston')",  # Not necessary but shows the use case
        viewonly=True)  # Setting viewonly = False prevents the issue


class Address(Base):
    __tablename__ = 'address'
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey('user.id'))
    user = relationship('User', back_populates='boston_addresses')

    city = Column(String)


def main():
    session = setup_database_and_session()

    user = User()

    session.add(user)
    session.commit()

    # user.boston_addresses   # Reading the value here prevents the issue

    address = Address(user=user, city='Boston')
    
    actual = user.boston_addresses
    expected = [address]
    assert actual == expected, f"{actual} != {expected}"


def setup_database_and_session():
    engine = sqlalchemy.create_engine("sqlite://")
    session_maker = sqlalchemy.orm.sessionmaker(bind=engine)
    session = session_maker()
    Base.metadata.create_all(engine)
    return session


if __name__ == "__main__":
    main()
```

Result: 
```
AssertionError: [<__main__.Address object at 0x10d95aeb8>, <__main__.Address object at 0x10d95aeb8>] != [<__main__.Address object at 0x10d95aeb8>]
```

**Comment by zzzeek** [comment]
there are a bunch of things going on here and it is not clear if further action is warranted:

1. the test case here will behave differently in 1.4, due to #4993 , where there are no longer any persistence-related cascades on the "boston_addresses" relationship

2. when you emit `Address(user=user, city='Boston')`, and then you expect user.boston_addresses to have entries inside of it, there are some assumptions going on here that SQLAlchemy is likely going to change, as a result of, OK forgot to add the ticket for this, here it is, #5150.   Basically you made an `Address()` and pointed it to the persistent user.   By backref rules, that means the address is appended to the user.boston_addresses list, which is already an issue because you've labeled this as viewonly=True and it just got mutated.  however, if you then expect "address" to be present in the Session in preparation for persistence, that only occurs due to the user.boston_addresses append.  This is where backrefs confuse everyone, in that they move objects into the Session when you didn't actually "put" them anywhere.   That will reverse due to #5150, as well as due to #4993 which will turn off the save-update cascade for viewonly.

Basically the test case in 1.4 will look like this:


```
    address = Address(user=user, city='Boston')

    # did not add address to the session
    assert address not in session

    # it's in user.boston_addresses due to back_populates,
    # but this does not imply DB persitence
    assert user.boston_addresses == [address]

    # persist to the DB and expire (similar to session.commit())
    session.flush()
    session.expire_all()

    # Address was not persisted because it was never added to the
    # session, collection is empty
    assert user.boston_addresses == []

```

so what can we do here except perhaps warn that "back_populates" doesn't make sense with viewonly=True, because, it's viewonly, and nothing is supposed to be appended to it.   I think that might be where we have to go here.    will try that.

**Comment by zzzeek** [comment]
this should be warn in 1.4 and possible 1.3.x as well.  2.0 should disallow.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Begin to disallow back_populates with viewonly=True** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1719

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Begin to disallow back_populates with viewonly=True** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1720

**Comment by marty-se** [comment]
Thanks for your swift and thorough analysis!

I agree that my setup was fishy, it was deduced from a much more complex setup that eventually boiled down to this.

**Comment by maparent** [comment]
I may be wrong, but I think that we’re losing an important use case here, which is introspection of inverse relationships. I would recommend allowing the backref IFF the backref is also view_only.


(Also commented on bitbucket, but I think here is more appropriate; sorry for double-posting.)

**Comment by zzzeek** [comment]
@maparent  the sourcecode for SQLAlchemy is right in this github repo, you can comment here.

Show me a code example illustrating the introspection of inverse case you are referring towards, thanks.

**Comment by maparent** [comment]
I can show you in my own code, but it's very idiosyncratic: for example 
https://github.com/conversence/idealoom/blob/cfa59684f638446e228b9e6337ee13ffbb0dc22b/assembl/views/traversal.py#L880 or https://github.com/conversence/idealoom/blob/cfa59684f638446e228b9e6337ee13ffbb0dc22b/assembl/lib/sqla.py#L1429.
I'm starting to add my backrefs to info so I can navigate back and forth, as in https://github.com/conversence/idealoom/blob/cfa59684f638446e228b9e6337ee13ffbb0dc22b/assembl/models/idea.py#L1710
But rather than justify my code, I'm realizing that a broader argument can be made: Anytime we have a many-to-many relationship with a non-trivial join table, it makes sense to forbid direct manipulation (because the join table rows should be created explicitly) but we may still want a view_only relationship for convenient navigation through the join. Being able to simply declare a backref in this case remains convenient, though I agree totally the backref should also be view_only.
Best regards,
Marc-Antoine Parent

**Comment by zzzeek** [comment]
I dont like "backref()" either and it's been superseded by back_populates which is more explciit and less misleading.   "backref()" isnt going away but it's not the best practice now.

there is no option to restore the back_populates flag for viewonly because it implies a mutating behavior.    trying to guess that both sides (noting there can be more than two sides in inheriting scenarios) are "viewonly" is not worth the complexity and nor does it really make sense because again back_populates is about mutations of attributes.    if you want some notational feature for some highly custom introspective system, I think using .info is your best bet as you can be guaranteed these collections can always be set.

**Comment by maparent** [comment]
Hmmm... I hear your concern about backref but I would plead for it, as I find it is an incredibly convenient declarative way to do relationships in both directions. But it's your choice obviously.

The only point I can try to argue is when you speak of the complexity of "trying to guess that both sides are viewonly", because in the case of the backref you would be constructing it yourself, not guessing; or if it's a backref() function, I get the impression one can check it pretty easily. Hmmm... would you be open to a PR?

**Comment by zzzeek** [comment]
> Hmmm... I hear your concern about backref but I would plead for it, as I find it is an incredibly convenient declarative way to do relationships in both directions. But it's your choice obviously.

as i said, backref() is not going away.

> 
> The only point I can try to argue is when you speak of the complexity of "trying to guess that both sides are viewonly", because in the case of the backref you would be constructing it yourself, not guessing; or if it's a backref() function, I get the impression one can check it pretty easily. Hmmm... would you be open to a PR?

a PR for...no warning with back_popualtes / backref and viewonly?  sorry, I'm opposed to that because I am triyng to ensure the rules for things are strict and consistent to as great a degree as is feasible.     I also don't have a clear rationale for the introspection use case either which as always can be performed on your end using the info dictionary.

**Comment by maparent** [comment]
Fair enough. Backref is going away in the view_only case, but I've already paid the cost and I'll live without it.
Regards

**Comment by zzzeek** [comment]
> Fair enough. Backref is going away in the view_only case, but I've already paid the cost and I'll live without it.
> Regards

as you might have been notified I have proposed a new series of flags to suit this use case in #5237.     there is an important behavior of back_populates that relates to loading for one particular case so the ability to do this should be restored.

**Comment by zzzeek** [comment]
in #5237 I am also proposing that we revert this issue completely and instead target it for 1.4 where the behavior simply changes.  warnings are removed

**Comment by dangayle** [comment]
What's the best way to turn off these warnings in the meantime? Setting the log levels doesn't seem to do the trick.
