### ISSUE TITLE
Prevent DDL From creating open transactions

### ISSUE THREAD

**Issue by jmarshall9120** [sqlalchemy/sqlalchemy#5152]
We are having constant problems with running sql scripts through sqlalchemy.  When DDL is detected it creates an open transaction, which seems to especially be a problem for sql scripts that both create temp tables and return rows.

Is there a way to force sql alchemy to execute whatever we pass it without creating any transactions?  

I have more details on my SO question:
https://stackoverflow.com/questions/60175605/sqlalchemy-gurantee-execution-of-sql-script

**Comment by zzzeek** [comment]
transactions are implicit in the Python DBAPI pep-249.  SQLAlchemy has no immediate control over this behavior that would be implicitly enabled.

Usually, when emitting DDL, once you're done emitting DDL, you commit the transaction, so that you can begin a new one for whatever else you're doing.  I'm not familiar with any difficulty that presents itself as far as temp tables or returning rows.

There isn't actually any way to emit SQL or DDL on a relational database without a "transaction" occurring behind the scenes at least, however, some of the more popular DBAPIs support a so-called "autocommit" mode which, while it cant elimiate the use of transactions since a database typically uses transactions for all operations, it at least would make the transaction not apparent as it commits immediately.  

For example PostgreSQL,  see the docs at https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#postgresql-isolation-level.     There are similar settings for SQLite as well as MySQL, see the individual dialect docs for those.

**Comment by gordthompson** [comment]
Your SO question mentions that you have cases where "SELECT statements won't return". A frequent cause of such behaviour is that the anonymous code block (or stored procedure) does not begin with `SET NOCOUNT ON;`. You could try prepending that to your SQL text and see if it helps. FWIW, this works fine for me:

```python
sql = """\
SET NOCOUNT ON;
CREATE TABLE #tmp (id int primary key, txt varchar(50));
INSERT INTO #tmp (id, txt) VALUES (1, 'foo'), (2, 'bar');
SELECT * FROM #tmp;
"""
with engine.begin() as cnxn:
    result = cnxn.execute(sql).fetchall()
print(result)  # [(1, 'foo'), (2, 'bar')]
```

**Comment by zzzeek** [comment]
reopen if further questions.

**Comment by jmarshall9120** [comment]
Close is the correct option here.  You were both right. I was missunderstanding the mechanism by which SqlAlchemy leaves DDL statements open.  It took me a few days to confirm experimentally.  Sorry for the delay.
