### ISSUE TITLE
`bulk_insert_mappings` silently drops columns with ClauseElement values

### ISSUE THREAD

**Issue by wadetregaskis-linkedin** [sqlalchemy/sqlalchemy#5165]
As a specific example, say I have Child & Parent tables with N:1 mappings.  I want to bulk-insert as efficiently as possible into Child, but I don't know in advance what the foreign key value is for the respective Parent records.  I can use e.g. a SELECT statement or a stored function to retrieve the appropriate Parent ID for each child, as part of the INSERT - the stored function being handy because it could automatically created the Parent if necessary, for example.

What I want to ultimately go out to the RDBM is something like:

```
INSERT INTO child_table (value, parent_id) VALUES (%s, get_or_create_parent(%s))
(('a', '1'), ('b', '1'), ('c', '2'), …)
```

The problem is that today, from stepping through the code in SQLAlchemy, I can see that while it does explicitly recognise a ClauseElement as a value, and does all this work of gathering values and so forth (in `_bulk_insert` / `_collect_insert_commands`), it then just completely forgets to include it when rendering the actual INSERT statement (in `_emit_insert_statements`).  So SQLAlchemy renders:

```
INSERT INTO child_table (value) VALUES (%s)
(('a'), ('b'), ('c'), …)
```

…and the insert fails because it's missing the required (non-nullable) foreign reference to parent_table.

_If_ I use `return_defaults=True` to `bulk_insert_mappings`, it now works _functionally_, but it does so by unnecessarily rendering a separate INSERT statement for every record, which is much less performant in my testing against MySQL 8:

```
INSERT INTO child_table (value, parent_id) VALUES (%s, get_or_create_parent(%s))
('a', '1')
INSERT INTO child_table (value, parent_id) VALUES (%s, get_or_create_parent(%s))
('b', '1')
INSERT INTO child_table (value, parent_id) VALUES (%s, get_or_create_parent(%s))
('c', '2')
…
```

While I can get the more efficient, intended bulk insert behaviour by basically doing it myself (using `child_table.insert().values(…)`), as a workaround, there seems to be no reason why `bulk_insert_mappings` can't just work as expected in this case.

**Comment by zzzeek** [comment]
this is documented:

https://docs.sqlalchemy.org/en/13/orm/session_api.html#sqlalchemy.orm.session.Session.bulk_insert_mappings

> The bulk insert feature allows for a lower-latency INSERT of rows at the expense of most other unit-of-work features. Features such as object management, relationship handling, and **SQL clause support are silently omitted** in favor of raw INSERT of records.

specifically the bulk inserts are looking to reduce Python overhead for lots of objects.  So having to add the expression `hasattr(value, "__clause_element__") or isinstance(value, sql.ClauseElement)` to every single column of every single row, which is what this would require without additional API features to somehow qualify it, is omitted.  

a more complex API here, such as some way to specify a "default" for entries that are missing, could maybe do this, but this starts to get out of scope for the bulk API.

in your case I would think running a SQL function that does a SELECT on every row is quite expensive already.   The more efficient way to do this would be to create the parent objects up front in a separate "bulk insert" step based on the child rows you're about to insert, collect all those IDs into a dictionary, then use those with your subsequent bulk insert.    if the number of parent objects is huge, then I would partition the scheme among chunks of child objects.

**Comment by wadetregaskis-linkedin** [comment]
From walking through the code in pdb, it looks like it's already doing all that work - it's just failing to generate the correct INSERT statement(s) from it.  It already checks for `__clause_element__` _and_ calls it, around line 507 in persistence.py, sequestering the result into `value_params`.  It passes all that as part of the records to `_emit_insert_statements`.  I don't recall now, after the weekend, precisely what codepath it takes through `_emit_insert_statements`, but in any case that's where it silently drops the _already computed_ clause elements, _unless_ `return_defaults` is set to `True`.

**Comment by zzzeek** [comment]
when you use bulk, "hasattr()" and isintance() are not called; Python features short circuit evaluation.  This is what's at line 507.  With bulk mode, "not bulk" is False:

```
            if value is None and col not in eval_none and not render_nulls:
                continue
            elif (
                not bulk
                and hasattr(value, "__clause_element__")
                or isinstance(value, sql.ClauseElement)
            ):
                value_params[col] = (
                    value.__clause_element__()
                    if hasattr(value, "__clause_element__")
                    else value
                )
            else:
                params[col.key] = value
```

in a source checkout of SQLAlchemy, you can run this:

```
$ python -m examples.performance bulk_inserts --test test_bulk_insert_mappings  --profile
Tests to run: test_bulk_insert_mappings
test_bulk_insert_mappings : Batched INSERT statements via the ORM "bulk", using dictionaries. (100000 iterations); total fn calls 1000850

```


apply this patch:

```
diff --git a/lib/sqlalchemy/orm/persistence.py b/lib/sqlalchemy/orm/persistence.py
index 95c5f8fa2..41222f94e 100644
--- a/lib/sqlalchemy/orm/persistence.py
+++ b/lib/sqlalchemy/orm/persistence.py
@@ -507,8 +507,9 @@ def _collect_insert_commands(
             if value is None and col not in eval_none and not render_nulls:
                 continue
             elif (
-                not bulk
-                and hasattr(value, "__clause_element__")
+                #not bulk
+                #and
+                hasattr(value, "__clause_element__")
                 or isinstance(value, sql.ClauseElement)
             ):
                 value_params[col] = (

```

then run again:

```
python -m examples.performance bulk_inserts --test test_bulk_insert_mappings  --profile
Tests to run: test_bulk_insert_mappings
test_bulk_insert_mappings : Batched INSERT statements via the ORM "bulk", using dictionaries. (100000 iterations); total fn calls 1200850

```

that is 20% more function calls.

now if you run without --profile, it shows you the time, so if I run with more iterations, like --num 1000000, I get about 10.2 seconds with the current code and 10.9 with the isinstance enabled for bulk on my machine.  This is pretty small stuff, but the bulk insert test is using a table with only three columns.    Trying to add some more columns:

```
diff --git a/examples/performance/bulk_inserts.py b/examples/performance/bulk_inserts.py
index 49469581d..65f7007c6 100644
--- a/examples/performance/bulk_inserts.py
+++ b/examples/performance/bulk_inserts.py
@@ -22,7 +22,13 @@ class Customer(Base):
     id = Column(Integer, primary_key=True)
     name = Column(String(255))
     description = Column(String(255))
-
+    x1 = Column(Integer)
+    x2 = Column(Integer)
+    x3 = Column(Integer)
+    x4 = Column(Integer)
+    x5 = Column(Integer)
+    x6 = Column(Integer)
+    x7 = Column(Integer)
 
 Profiler.init("bulk_inserts", num=100000)
 
@@ -115,6 +121,7 @@ def test_bulk_insert_mappings(n):
             dict(
                 name="customer name %d" % i,
                 description="customer description %d" % i,
+                x1=i, x2=i, x3=i, x4=i, x5=i, x6=i, x7=i
             )
             for i in range(n)
         ],

```

now I get about 23 seconds for the current code and 25.5 adding the two function calls back in.

it's small stuff but I don't really have any means of deciding which ORM features should be part of "bulk" vs. which should not.  Obviously as each ORM-like feature gets added back to "bulk", bulk will approach the slower speed of the regular ORM which takes about twice the time here.

The only thing I can go on here is, what problem is trying to be solved.   In this case, it's populate two different tables, using a method that is faster than using the regular ORM.   Having to run a stored procedure on every row is not how I would do that.

I'm beginning to work out how i would just remove this whole "bulk" mode in SQLAlchemy 2.0 in any case, because it is a little bit faster than the ORM but using straight Core is way faster.  I definitely don't want to be tweaking the capabilities of bulk upwards and downwards like this.     I'd rather remove it to be honest.

**Comment by wadetregaskis-linkedin** [comment]
I think you're misunderstanding the conditional check:

```
                not bulk
                and hasattr(value, "__clause_element__")
                or isinstance(value, sql.ClauseElement)
```

That conceptually (i.e. ignoring lazy evaluation) becomes `not True and True or True`.  `and` and `or` have equal precedence in Python, and are evaluated left-to-right.  So it works out as `((not True) and True) or True`.  Therefore the end result is `True`, not `False` as you seem to be assuming.

Now, it seems to me like it _intends_ to skip that loop if `bulk` is True, so in that sense this conditional is buggy.  But for my purposes it's actually closer to optimal, since I _do_ want clause elements evaluated.

In any case, when you talk about 'straight Core', do you mean e.g. `session.execute(Child.__table__.insert().values([<list of dict of column names to literal or ClauseElement values>])`?  What's the difference between that approach and `bulk_insert_mappings`?  It seems to work _better_ than `bulk_insert_mappings`, yet the existence of a specialised function, `bulk_insert_mappings`, would seemingly imply that `bulk_insert_mappings` should be used when efficiency is paramount?

(the side discussion about whether calling a stored function is optimal is case-specific; in my case, Python memory usage is _way_ more of a problem than SQL execution time, let-alone the code complexity considerations of trying to batch / partition record processing…)

**Comment by zzzeek** [comment]
> I think you're misunderstanding the conditional check:
> 
> ```
>                 not bulk
>                 and hasattr(value, "__clause_element__")
>                 or isinstance(value, sql.ClauseElement)
> ```
> 
> That conceptually (i.e. ignoring lazy evaluation) becomes `not True and True or True`. `and` and `or` have equal precedence in Python, and are evaluated left-to-right. So it works out as `((not True) and True) or True`. Therefore the end result is `True`, not `False` as you seem to be assuming.

yes so that's a bug, because the parens should be there.   I was wondering why I wasn't getting very good differences when I commented out that "bulk", I wasn't looking that closely.  now the callcounts are 800850 with the correct code and 1200850 with it, a 30% increase in calls, times still seem not that different 9.4 sec with the methods skipped vs. 10.3 sec with the methods called.

however, as you noted, this is totally wasted time because there are further codepaths that prevent this from using those parameters.  As I now re-familiarize with this, the real problem with using expressions here which is that it can no longer easily batch the INSERT statements together when they have "value_params" inside of them.   the format of the INSERT statement itself must change for these ad-hoc expressions.   in order to batch (e.g. use dbapi executemany(), which is a key goal here), it would need to compare all of these SQL expressions to each other to see that they are in fact identical, which is not a fast process at all if we are doing a real comparison, as opposed to checking to see if its the same expression.  that is, if you have:

    {"id": 1,  "data": func.foo('bar')}
    {"id": 2, "data": func.foo('bat')}
    {"id": 3, "data": func.bar('bar')}
    {"id": 4, "data": func.bar(some_col)}
    {"id": 5, "data": func.bar(some_col)}

Figuring out the correct way to batch the above requires comparison of the expressions and in particular to try to "batch" same function call but different parameters inside is even more complicated.   Comparison of SQL expressions requires that each sub-element of the expression must be traversed and compared, which is *very* expensive to do for thousands of rows individually.   there's also no reliable comparison system in 1.3, that's new in 1.4 in fact but it is not performant enough for this case.  that was the original reason there's no support for ad-hoc SQL expressions in the batch methods, I forgot about this, sorry.  it should be more prominently documented.

in persistence.py , specifically there's a codepath for "we can use executemany()" and there's a codepath for "we can't use executemany()", and if there are any "value params", it picks the "we can't use executemany()" codepath.  so without major rewrites of that logic, having expression support in the bulk  API would very much defeat one of the key goals of the system which is to try to batch INSERT statements into executemany().

this is why I proposed "a more complex API here, such as some way to specify a "default" for entries that are missing, could maybe do this, but this starts to get out of scope for the bulk API." if the function is the same every time, and could be declared up front, then we can still batch.  

> 
> Now, it seems to me like it _intends_ to skip that loop if `bulk` is True, so in that sense this conditional is buggy. But for my purposes it's actually closer to optimal, since I _do_ want clause elements evaluated.
> 
> In any case, when you talk about 'straight Core', do you mean e.g. `session.execute(Child.__table__.insert().values([<list of dict of column names to literal or ClauseElement values>])`? What's the difference between that approach and `bulk_insert_mappings`? It seems to work _better_ than `bulk_insert_mappings`, yet the existence of a specialised function, `bulk_insert_mappings`, would seemingly imply that `bulk_insert_mappings` should be used when efficiency is paramount?

when you do that, you are determining the structure of the INSERT statement up front because you know what you want, so you feed in jus a single statement and it uses executemany() for it.  The ORM needs to do this on the fly.  that's the big issue here.

> 
> (the side discussion about whether calling a stored function is optimal is case-specific; in my case, Python memory usage is _way_ more of a problem than SQL execution time, let-alone the code complexity considerations of trying to batch / partition record processing…)

I'm not sure how many records you are dealing with but if it is arbitrarily large then you have to batch the records in any case.     I'm not sure what the input to your funciton is but if its the related primary key, it looks like:

```
related_ids = set(rec.related_id for rec in batch)
current_ids = set(id for id, in session.query(Related.id).filter(Related.id.in_(related_ids))))
for need_to_create in related_ids.difference(current_ids):
   # create recs for need_to_create

# now INSERT statements can assume the related id exists

```

**Comment by zzzeek** [comment]
it's also documented here:

https://docs.sqlalchemy.org/en/13/orm/persistence_techniques.html#orm-compatibility

"SQL expression inserts / updates"  

could add a rationale

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Remove needless clauseelement check for batch** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1743

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Remove needless clauseelement check for batch** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1744

**Comment by wadetregaskis-linkedin** [comment]
SGTM - seems like for my use(s) I should really just be using the 'Core' workflow as you suggest, and forget about `bulk_insert_mappings`.  `bulk_insert_mappings` is, I now see, trying to provide quite a lot of functionality that I don't need; I know at 'compile'-time that there are simple, tight constraints on the values.  It's not as 'low-level' as I thought - given this thread I now see the distinction with it being 'low-level' _relative_ to the ORM layer, _not_ the Core layer.

Perhaps that last section in the docs, comparing the bulk methods to the 'Core' approach, could be more direct / opinionated about which approach to use?  e.g. tell folks to only use the bulk methods if they actually need its additional [vs Core] functionality like supporting varying keys in the records' dictionaries.
