### ISSUE TITLE
open up warn_for_conflicting_sync_targets to track simple FK conflict

### ISSUE THREAD

**Issue by Peter92** [sqlalchemy/sqlalchemy#5171]
If you override `__init__` to allow optional arguments, if you have an optional but non nullable relationship argument in there (so you can either manually set the relationship or rely on append), then SQLAlchemy bugs out a bit.

[I asked about a super weird error last year](https://stackoverflow.com/questions/56378863/sqlalchemy-unusual-not-null-failure-when-appending-to-a-relationship) and someone found it was down to this particular bug, and wrote a very good example of it happening.

This is the relevant part in regards to why the issue may be happening:

> The manner in which these relationships resolve foreign key values appears to be inconsistent, so sometimes it's trying to flush with parent_id=1 which is the pk of the new Application object, and other times it's trying to flush with parent_id=None as the constructor dictates.

My result of running this is 9 failures and 11 successes.

```python
from sqlalchemy import create_engine, Column, Integer
from sqlalchemy import ForeignKey
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker

engine = create_engine('sqlite://')

Base = declarative_base()

Session = sessionmaker(bind=engine)


class Parent(Base):
    __tablename__ = 'parent'
    id = Column(Integer, primary_key=True)
    children = relationship('Child')


class Child(Base):
    __tablename__ = 'child'
    id = Column(Integer, primary_key=True)
    num = Column(Integer)
    parent_id = Column(Integer, ForeignKey('parent.id'), nullable=False)
    parent = relationship('Parent')

    def __init__(self, parent=None, **kwargs):
        super(Child, self).__init__(parent=parent, **kwargs)


if __name__ == '__main__':
    Base.metadata.create_all(engine)
    error_cnt = 0
    success_cnt = 0
    for _ in range(20):
        s = Session()
        try:
            parent = Parent()
            parent.children.append(Child())
            s.add(parent)
            s.commit()
        except IntegrityError:
            error_cnt += 1
        else:
            success_cnt += 1
        finally:
            s.close()
    print('errors', error_cnt)
    print('successes', success_cnt)
```

**Comment by zzzeek** [comment]
hi there -

thanks for the clear test case.

you are actively setting child.parent = None, which indicates that child.parent_id should be populated as None in the database rather than relying upon implicit default.

but then, you are also setting parent.children.append(child), which indicates that child.parent_id should be populated with the primary key of parent, rather than relying on implicit default.

you have two unrelated relationship() constructs, both being given an active value, and both have an opinion, conflicting in this case, as to what child.parent_id should be set towards.  therefore non-deterministic failure mode.

what you would like to occur is that:

1. build Child.  child.parent is None, implies child.parent_id is None

2. append child to parent.  this also implies that child.parent is set to that parent.

3. both relationships now agree on intent and no failure.

the pattern in number 2 is provided by an essential relationship feature known as a **back reference**.  Configuring back references is introduced in the ORM tutorial and described in detail at https://docs.sqlalchemy.org/en/13/orm/backref.html#relationships-backref.

```
    children = relationship('Child', back_populates="parent")

    parent = relationship('Parent', back_populates="children")

```

20 successes 0 failures.

**Comment by Peter92** [comment]
Thanks for the reply, you're correct in that's what I'd have liked to occur. Is what I reported actually something that needs fixing, or is it just one of those things that should be done in a different way?

Before I go adding `back_populates` to each relationship, is there any disadvantage to using it other than a bit more Python overhead?

**Comment by zzzeek** [comment]
there's definitely no disadvantage to using back_populates, it is very unusual to see two relationships that *dont* have a back_populates or backref() configuration in use.

The SQLAlchemy ORM could in theory try to detect that more than one relationship is impacting a particular column-based attribute and that these two relationships are not synchronized with each other, but this would be a very involved task and may also produce false positives.   backrefs are a really fundamental SQLAlchemy concept and as they are introduced in the ORM tutorial I think they are pretty hard to miss.     I've never seen this issue reported before since backrefs were first added about 15 years ago, so I don't see prioritizing a check for this right now as worth it unless someone really wanted to dig into the ORM and work on it.

**Comment by Peter92** [comment]
When I originally read about backrefs, I always assumed you _only_ used it as a shortcut to add the relationship to the other class, so for the most part I've phased them out as I prefer to explicitly set up each side of the relationship. I'll definitely be throwing in `back_populates` on everything tomorrow :)

I wasn't so much asking as in "this should be fixed soon", I just mean in terms of if it's worth closing the issue since it'll never be fixed, or leaving it open at the bottom of the pile for someone to come across in the future.

**Comment by zzzeek** [comment]
Well when I said "this would be a very involved task", I was correct.  However, I failed to realize that a large part of this task has already been done in _warn_for_conflicting_sync_targets in https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/relationships.py#L3103.    

To open this up so that it warns for your test case specifically looks like:

```
diff --git a/lib/sqlalchemy/orm/relationships.py b/lib/sqlalchemy/orm/relationships.py
index 5573f7c9a..7fe82cd9d 100644
--- a/lib/sqlalchemy/orm/relationships.py
+++ b/lib/sqlalchemy/orm/relationships.py
@@ -3120,8 +3120,6 @@ class JoinCondition(object):
             # if multiple relationships overlap foreign() directly, but
             # we're going to assume it's typically a ForeignKeyConstraint-
             # level configuration that benefits from this warning.
-            if len(to_.foreign_keys) < 2:
-                continue
 
             if to_ not in self._track_overlapping_sync_targets:
                 self._track_overlapping_sync_targets[
@@ -3134,11 +3132,6 @@ class JoinCondition(object):
                 for pr, fr_ in prop_to_from.items():
                     if (
                         pr.mapper in mapperlib._mapper_registry
-                        and (
-                            self.prop._persists_for(pr.parent)
-                            or pr._persists_for(self.prop.parent)
-                        )
-                        and fr_ is not from_
                         and pr not in self.prop._reverse_property
                     ):
 

```

a bunch of tests fail, some which are against that logic specifically which would need to be altered to accommodate the new behavior, and some others fail likely due to the fixtures themselves trying to cheat on things which can be adjusted.

**Comment by zzzeek** [comment]
basically i can't have issues like these open for years.   i have to do it right now or close it b.c. i will never do it if not now.  since the logic is right there will see if i can get it to pass all tests

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Open up check for relationships that write to the same column** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1748
