### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by tteaka** [sqlalchemy/sqlalchemy#5176]
I would like to implement a plugin system (at first for the `Query` class).

I see some libraries that extends SQLAlchemy capabilities. Some of them are providing helper function that takes a query as argument and I would like to propose another pattern.

I don't want to discuss yet the implementation details because of my lack of understanding the ORM internals, but here is the idea :

Current situation :

```
from my_helper_lib import sa_helper

query = session.query(Model)

new_query = sa_helper(query, x, y)

```

What I propose:

```
from sqlalchemy.plugins import register_plugin

register_plugin("sa_helper", sa_helper)

new_query = session.query(Model).sa_helper(x, y)
```

As mentionned, I propose it for the `Query` class but it could be implemented for other classes.

What are your thoughts about this ?

**Comment by zzzeek** [comment]
hi there -

Query has a plugin path right now which is to use the query_cls argument to Session or sessionmaker:

https://docs.sqlalchemy.org/en/13/orm/session_api.html?highlight=query_cls#sqlalchemy.orm.session.Session.params.query_cls

this parameter doesn't have to be a class, it can be any callable, for which you can provide a Query subclass, or if you wanted to, you could monkeypatch.

I would not recommend a plugin system that by the fact of it being installed in the same Python environment, a global change to the Query class in all applications occurs.  There always has to be some explicit opt-in by an application that wants to modify the SQLAlchemy library in some way and it has to be local to that application.

Also, the future of the Query class itself is uncertain.  there's a plan in 2.0 that a query would start from the select() object.   While this plan is currently in motion, it's still early days, but the idea is that the pattern would be like "stmt = select(...);   results = session.execute(stmt)""  so that there would be no "session.query()" factory pattern, except as a legacy feature.  See https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#orm-query-unified-with-core-select for current background on this.

**Comment by zzzeek** [comment]
oh, in case it was not apparent, "register_plugin" by default loads from setuptools entrypoints.  we do have such a system in place for third party dialects as well as engine plugins, but that's because the engine is loaded up from a string URL.   for patterns that are explicit in python code, the third party library should have a python-based invocation path.

**Comment by tteaka** [comment]
> I would not recommend a plugin system that by the fact of it being installed in the same Python environment, a global change to the Query class in all applications occurs. There always has to be some explicit opt-in by an application that wants to modify the SQLAlchemy library in some way and it has to be local to that application.

What I had in mind (and didn't mention), was probably a little bit different than altering the Query class (if it is not desired), but could be effective globally for a Python environment.

In sqlalchemy:

``
class Query:

    def __getattr__(self, name):
        if plugin_registry.has_plugin(name):
            return plugin_registry.get_plugin(name):
        else:
            self.name # raise AttributeError

class QueryPluginRegistry:

    def __init__(self):
        self.registry_dict = dict()

    def register_plugin(self, name, callable):
        self.registry_dict[name] = callable

    def has_plugin(self, name):
        return name in self.registry_dict.keys()
``

But above is just a draft idea, because current query instance is not passed as argument to callable.

And about the future of Query class that is uncertain, as Query class will not remain a first class citizen, I think then relying on the current pattern that subclasses it should be sufficient.

**Comment by zzzeek** [comment]
SQLAlchemy certainly has a lot of `__getattr__()` schemes within it in order to make various dynamic instrumentation and SQL generation scenarios work, however these are not used to implement fixed APIs, that is, a pre-defined namespace of methods on a class.     For top-level API usage, like a class with methods on it, `__getattr__()` produces a class object that is difficult to document and more importantly will not work with modern IDEs or with [pep-484](https://www.python.org/dev/peps/pep-0484/) tools.      There are also many ways a third party tool might want to extend the functionality of Query that would not be compatible with this approach, including replacement / augmentation of existing methods as well as application of events, special options, etc.  

Right now, a library that wants to package some custom builders for query need only implement the functions themselves, which can be injected into a Query explicitly using [with_transformation](https://docs.sqlalchemy.org/en/14/orm/query.html?highlight=with_transformation#sqlalchemy.orm.query.Query.with_transformation):
    
    from mythirdparty import filter_by_foo
    q = q.with_transformation(filter_by_foo(x=5))

above, there is no "magic" going on as to where this external function comes from, IDE and MyPy like tools can receive it directly and the dependency is explicit in code.

to the degree that the above pattern is a little verbose can be evaluated based on what kinds of third party extensions you actually want to build and what the usage patterns might look like.

**Comment by zzzeek** [comment]
at the moment SQLAlchemy has a lot of plugin points already so I'm -1 on a new registry system.
