### ISSUE TITLE
failed to execute raw sql query with ';' in the ending for oracle

### ISSUE THREAD

**Issue by hackergnome** [sqlalchemy/sqlalchemy#5188]
conn_string = oracle+cx_oracle://{user}:{password}@{host}:{port}/{sid}

query to be executed = select * from table where c1 = 'condition';
execution status = error
error message= sql query not properly ended
SQLAlchemy version =  1.3.12    

query to be executed = select * from table where c1 = 'condition'
execution status = success

**Comment by CaselIT** [comment]
I think that the problem is caused by the cx_oracle driver.
Here is the relevant documentation: https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html

When executing raw sql, the statement is passed without change to the underling db driver, `cx_oracle` in this case.

You can use sqlalchemy events to check for a semicolon at the end of the statement and remove it.
These is a similar example in the docs, here https://docs.sqlalchemy.org/en/13/core/events.html#sql-execution-and-connection-events

**Comment by zzzeek** [comment]
I would simply not use semicolons in SQL statements passed to connection.execute().  This is not part of SQL syntax any more than the "GO" command used in SQL Server console tools is.  The semicolons are part of the command line / console interface tools used to indicate the separator between statements.    if you are reading strings from a file of SQL commands, just strip off the semicolons first.
