### ISSUE TITLE
Constraint columns don't have very straightforward behaviour

### ISSUE THREAD

**Issue by Peter92** [sqlalchemy/sqlalchemy#5191]
I'm using a simple setup like this so there's nothing fancy going on:

```python
class User(Base):
    id = Column(Integer, primary_key=True)
    username = Column(String(32), nullable=False, unique=True)
    __table_args__ = (CheckConstraint(func.length(username)>2),)
```

My specific use case is I was wanting to grab that "2" for automatic validation, and in investigating how to do that, I hit some issues that required a bit of trial and error that weren't very obvious from the documentation.

```python
>>> constraint = User.__table__args__[0]

>>> constraint.columns
['User.username']
>>> constraint.columns[0]  # Based on what was printed above, I was initially confused why this didn't work
KeyError: 0
>>> constraint.columns['username']
User.username

# This took me a while to figure out why it was always returning False
>>> constraint.contains_column('username')
False
>>> constraint.contains_column(User.username)
False
>>> constraint.contains_column('User.username')
False
>>> constraint.contains_column(User.__table__.c.username)
True
```

### Suggestions:

1. Adapt `contains_column` it so it's able to use `InstrumentedAttribute`s and strings, or add a traceback which will warn that the given item is not a column.

2. Make `str(constraint.columns)` display `{'username': User.username}` instead of `['User.username']`, since it's actually a dict that just looks like a list.

**Comment by CaselIT** [comment]
You can also directly compile the constraint with setting `literal_binds` to True
https://docs.sqlalchemy.org/en/13/faq/sqlexpressions.html#rendering-bound-parameters-inline

This is usually easier that having to directly check the sqlalchemy internals

**Comment by zzzeek** [comment]
it's not trivial to expect that ColumnCollection can accommodate ORM objects that reduce down to columns, because there are many methods throughout ColumnCollection and related collections in sql/base.py that receive Core ColumnElement objects as arguments.  While there is a role system in master (not 1.3) that generalizes the conversion of objects from systems such as the ORM to the underlying ClauseElement, it has a small performance impact that would need to be tested and there would need to be a new series of tests within test/base/test_utils.py -> ColumnCollection that exercise all methods for an appropriate response being passed a non-ClauseElement that has a __clause_element__() method.    Also to be decided is if contains_column() should raise an error when an inappropriate object is passed since it suggests the user isn't using it properly.

For the stringificaition, I'm -1 on using a "mapping" (i.e. dict) repr, since ColumnCollection is only a little bit like a mapping and in other ways not at all like one,  not the least of which is that it can now store multiple columns of the same name as well as that iteration will iterate the columns, not the "keys".  The "keys" of the ColumnCollection do not provide complete access to the collection. It is also redundant to display the keys separately which are 99% of the time the same name as the column.

I would favor qualifying the string output with "ColumnCollection(name1, name2, name3...)" so that there's no ambiguity that this is a special kind of collection being viewed and not a plain Python list or anything else.

**Comment by CaselIT** [comment]
we could maybe use triangular bracket. Like `⟨'User.username'⟩` ?

**Comment by zzzeek** [comment]
multiple would look like a tuple of strings ?    these aren't really strings.  i think it just has to be something that is clearly not any of the built-in datatypes right now because it isn't like any of those.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Improve the method ``__str__`` of :class:`ColumnCollection`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1813
