### ISSUE TITLE
implement transacvtion isolation including autocommit for Oracle

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5200]
This issue was split off from #5164 to handle Oracle as a separate change.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Implement autocommit isolation level for cx_oracle** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1787

**Comment by zzzeek** [comment]
Oracle has isolation levels and we need to support them:

https://docs.oracle.com/cd/E25054_01/server.1111/e25789/consist.htm

**Comment by zzzeek** [comment]
OK this might be tricky since there's no docuemnt4ed default isolation level and no way to get the isolation level so far...

**Comment by zzzeek** [comment]
There are only two real "levels": SERIALIZABLE and READ COMMITTED.  The very esoteric query we see at https://stackoverflow.com/questions/10711204/how-to-check-isoloation-level and elsewhere only returns a result if a transaction is started, which seems to require either that some DML has proceeded or that the dbms_transaction.local_transaction_id( TRUE ) PL/SQL call was emitted to explicitly "start" a transaction; we can't "stsrt" a transaction in order for get_isolation_level() to proceed.

so for the moment I propose we hardcode the isolation levels to READ COMMITTED and AUTOCOMMIT and don't have explicit support for SERIALIZABLE right now.     to "get" the current isolation level we will hardcode to READ COMMITTED since per many sources this is Oracle's default and there's no mention of it being alterable before a session begins (it can be altered per session or per transaction).

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Implement autocommit isolation level for cx_oracle** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1811
