### ISSUE TITLE
populate_existing and default behaviour w/ raw sql updates

### ISSUE THREAD

**Issue by djerraballi** [sqlalchemy/sqlalchemy#5211]
I am currently digging into issues with the following test code: 
```
# get a session, transaction_isolation is read committed
# autoflush is false, autocommit is false
 with get_db_session() as db_session:
            result: Contact = db_session.query(Contact).filter(Contact.id == contact.id).one()
            assert result.category == 'personal'
            
            # run some raw-sql update on this row
            update = "update database.contact set category='home'"
            db_session.execute(update)

            # re-execute the query
            query: Query = db_session.query(Contact).filter(Contact.contact == contact.contact)
            
            # assert that the contact object has changed 
            result = query.one()
            assert result.category == 'home'
```

If i change the last query to the following, i get the result that i expect: 
```
             result = query.populate_existing().one() 
```
Here is the relevant piece in loading.py: 
https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/orm/loading.py#L80-L84
https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/orm/loading.py#L585-L639

1. Why does sqlalchemy execute the base query if we aren't going to update the sqlalchemy instance? (Off the top of my head if the query returns rows that don't match an identity key in session state, then the execution results remain useful. Even so...)
 What are the use cases where the query returns one set of data for a row but we actually want to preserve the stale state on the SQLAlchemy model? 

2. Is there a simple way to ensure populate_existing is always true w/o going in and modifying every query? since i am already taking the hit of executing the query against the database, im ok w/ taking another hit if repopulating models in python, but its quite cumbersome to change all the queries everywhere to add 'populate_existing', and without doing so i am open to some undesirable behavior.

**Comment by zzzeek** [comment]
> 
>     1. Why does sqlalchemy execute the base query if we aren't going to update the sqlalchemy instance? 

SQLAlchemy does not know what row(s) your query is going to return, so it knows nothing about the fact that you happen to be accessing a particular Contact object that happens to be in the Session already.  If you want to look up the object in the Session first without invoking the query, query.get() does that.

Additionally, if your object has attributes that are unloaded or expired, and the query actually requested those columns, it will populate them on the object.  This also works for relationships that are loaded with eager loading.

>        What are the use cases where the query returns one set of data for a row but we actually want to preserve the stale state on the SQLAlchemy model?

the default behavior of the Session is to behave as though the transaction is using  "serializable" isolation (even though it is usually not), which includes that the transaction is repeatable read (which it often is, depending on backend).  This means if that row has already been read in that transaction, it would guaranteed to be the same.     this is not necessarily the actual case for some backends where the default isolation is "read committed" but in general, if someone is trying to view the contents of another transaction that has committed while this one is still in progress, that's an exception case where they would need to use populate_existing() or expire().

There is discussion of this behavior here: https://docs.sqlalchemy.org/en/13/faq/sessions.html#i-m-re-loading-data-with-my-session-but-it-isn-t-seeing-changes-that-i-committed-elsewhere  and also more deeply in my talk here: https://www.sqlalchemy.org/library.html#thesqlalchemysessionindepth

In your case, you're not trying to read from a different transaction, you're injecting a Core UPDATE statement into the mix.  What you're trying to do there would work better if you used query.update() instead as it can automatically expire those attributes on the object that you are modifying:  https://docs.sqlalchemy.org/en/13/orm/query.html?highlight=query%20update#sqlalchemy.orm.query.Query.update .  It can do this either from an in-memory scan or by running that second SELECT that you are doing, and you won't have to use populate_existing().


> 
>     2. Is there a simple way to ensure populate_existing is always true w/o going in and modifying every query? 

i believe you can use a before_compile() event https://docs.sqlalchemy.org/en/13/orm/events.html?highlight=before_compile#sqlalchemy.orm.events.QueryEvents.before_compile to set this setting on all queries. However this setting will cause queries to also erase any pending changes you have on objects, and I can't guarantee it wont have side effects in cases like when queries are used for lazy or eager loading.

In general it's preferable to use this method only when you know you need it (and to also avoid doing things that would necessitate it like running core update() statements against the row you've already loaded, rather than flushing the object with changes or using query.update()).


> since i am already taking the hit of executing the query against the database, im ok w/ taking another hit if repopulating models in python, but its quite cumbersome to change all the queries everywhere to add 'populate_existing', and without doing so i am open to some undesirable behavior.

if you use query.update() then you won't have to reload the object at all, it can modify it in place, or alternatively it will run that additional query for you and automatically update the record.

**Comment by zzzeek** [comment]
reopen if you need further info.
