### ISSUE TITLE
How do declare sql variables?

### ISSUE THREAD

**Issue by jmarshall9120** [sqlalchemy/sqlalchemy#5214]
I couldn't find this question searching so maybe I'm just doing something wrong, but how do you declare an sql style @variable using sqlalchemy core?

**Comment by gordthompson** [comment]
What do you plan to do with this variable? Local variables are only relevant to things like stored procedures and batches (anonymous code blocks), in which case you just `DECLARE` them. Are you trying to do something different?

**Comment by zzzeek** [comment]
this is more of a DBAPI issue.   What DBAPI are you using?  Can you produce a test script using that DBAPI that illustrates what you want to do?  if you can make cursor.execute() do it, then SQLAlchemy can do it too.

DBAPI: https://www.python.org/dev/peps/pep-0249/

**Comment by jmarshall9120** [comment]
So my use case for alchemy is that I build large backend systems in which lots of sql is replicated.  I would rather mange sql in Python than have a DBA copying code with slight changes to it all day everyday.  I can build a system myself that binds certain SQL expressions to python classes that I can then build dynamic scripts with, but I'd rather alchemy do it.

**Comment by zzzeek** [comment]
SQLAlchemy is a facade around the pep-249 DBAPI.   if you can run a single statement like this:

```
cursor.execute("""
declare @variable ;
select foo bar @variable whatever ;
etc etc;
""")
```

then that's how you'd do it.   See the section https://docs.sqlalchemy.org/en/13/core/connections.html#working-with-raw-dbapi-connections for background on how to do this with the cursor directly.

**Comment by jmarshall9120** [comment]
Thanks I know how to use the cursor connections. it just looks like I'm going to have to build my own version of alchemycore instead of be able to use this one which is a drag.

**Comment by zzzeek** [comment]
I have no idea what API you would like to see.

**Comment by zzzeek** [comment]
it's mostly not clear if you actually need to use server side variables, or if you are just looking for how to build composable SQL constructs in SQLAlchemy.     I need a concrete example of what SQL you need to emit.

**Comment by jmarshall9120** [comment]
Sorry for the confusion, so on @zzzeek's last comment, looking to build composable sql for use in scripts and procs mostly.  So for example, here's a script that gets reused for almost every data source that comes in. 

```
DECLARE @stagingDate NVARCHAR(50)

SELECT @stagingDate = CAST(MAX(src.[Conversion Time]) AS DATE)
FROM Staging.TdDailyConversions src
		
UPDATE stg
SET [SYS_OPERATION] = 'I'
FROM Staging.[TdDailyConversions] stg
WHERE NOT EXISTS (
	SELECT idm.[HashCode]
        FROM [IdMatch].[TdDailyConversions] AS idm
	WHERE stg.[HashCode] = idm.[HashCode]
        	    AND CAST(idm.[Conversion Time] AS DATE) = @stagingDate	
		)
```
		
So, in the past I would build classes to bind each part of the sql and then inject the necessary, dynamic info like, fields, tablenames, variable names and types.  The interesting thing is that I can almost replace these compositional systems with, alchemy but am running into a few snags in areas like "DECLARE", "IF", ect.

**Comment by zzzeek** [comment]
OK with the Python DBAPI, AFAIK you need all of those statements to run inside of a single cursor.execute() call, or at least, along the same cursor.    SQLAlchemy runs each statement inside of a new cursor.   so the options for using server side variables are limited.  

however, you're not doing anything above that actually *requires* a server side variable.  you can have that SELECT embedded in the UPDATE.  you can keep the code structure the same using Python.  here is very quick psuedocode showing how to embed the SELECT in the UPDATE as a python variable:

```
stagingdate = select([cast(func.max(table.c.col)).label("date")).select_from(table)

stmt = update(table).values(...).where(not(exists().where(idm.c.foo == table.c.bar).where(cast(idm.c.col) == stagingdate)


```

**Comment by zzzeek** [comment]
can confirm there is no way for you to use server side variables without appending everything into one single .execute() call, I tried multiple statements on one cursor w/ pyodbc SQL Server, not allowed:
```

>>> e = create_engine("mssql+pyodbc://scott:tiger^5HHH@mssql2017:1433/test?driver=ODBC+Driver+13+for+SQL+Server", echo=True)
>>> c = e.raw_connection()
>>> cursor = c.cursor()
>>> cursor.execute("DECLARE @stagingDate NVARCHAR(50)")
<pyodbc.Cursor object at 0x7fb12fc950b0>
>>> cursor.execute("SELECT @stagingDate='foo'")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Must declare the scalar variable "@stagingDate". (137) (SQLExecDirectW)')

```

whereas batching them together, no problem:

```
>>> cursor.execute("DECLARE @stagingDate NVARCHAR(50); \n  SELECT @stagingDate='foo';")
<pyodbc.Cursor object at 0x7fb12fc950b0>

```
so to use SQLAlchemy with server side variables you would need to create this single string to invoke at once by stringifying individual SQL constructs and appending them into a list of statements to be invoked at once.

**Comment by gordthompson** [comment]
... and always start such a block with `SET NOCOUNT ON;`.

**Comment by jmarshall9120** [comment]
Is there a preferred way extend alchemy to work with a "declare" object?  

Without going crazy into the details of the large data ops I'm testing this for, I can say the above won't work.  I know how to use the @complie.complier to hook into objects and create certain custom definitions.  Is there a way to create an object like below which I cold mix in seamlessly to the current sqlalchemy core syntax?  The win here is I can build my scripts, DDL them to the server using the raw cursor, and reuse the alchemy for architecture that executes client side?

import sqlalchemy as sa
class SqlVariable():
 ```
   def __init__(self, name, saType, default):
        self.name = name
        self.saType = saType
        self.default = default
        return

```

**Comment by zzzeek** [comment]
sure, you can make custom constructs:

https://docs.sqlalchemy.org/en/13/core/compiler.html

you only need subclass ClauseElement at the basic level.  if you want to send the object straight into conn.execute(), you probably want to subclass Executable as well.


but again, the big wall here is that the driver itself won't let you declare and use a variable across executions so you need to render one big SQL paragraph.

**Comment by jmarshall9120** [comment]
Thanks for the push.  I'm trying to see what I can come up with right now.  I can post the result here for the community.  

I'm assuming the hesitance to having such scripting functionality native to alchemy is that it would encourage hard-coded variables that some Einstein would then put in a front end?

**Comment by zzzeek** [comment]
> 
> I'm assuming the hesitance to having such scripting functionality native to alchemy is that it would encourage hard-coded variables that some Einstein would then put in a front end?

I have no resistance whatsoever except that I have no idea what is being proposed.   Im not sure if you're following, it is *NOT POSSIBLE* to script with server side variables and the Python DBAPI in a generalized way.   SQL Server is the only database that even has ad-hoc server side variables like this in the first place.

**Comment by jmarshall9120** [comment]
I think we're saying the same thing.  For my use case there is no problem appending everything into a single execute with embedded values( though this is insecure and should never be exposed to a front end).  The DBAPI isolating calls isn't necessary for long script in my particular situation.  The extension I'm purposing would probably be something that allowed me to compile my scripts but would throw a warning if someone tried to execute without converting to string.  That way I can write my crazy repetitive server side only SQL and my application sql using the same alchemy syntax.  Why would I want to do this?  From a business perspective it means I can teach any devs I work with only sqlalchemey and not alchemy + scripting abstraction monstrosity that I develop.  I'm happy to post the results of my little trist with alchemy, but I assume you'd also have some reservations about the fact it'll be insecure. Maybe a candidate for a wiki recipe if it succeeds?  If I'm doing something monumentally stupid please let me know.  Yours truly.

**Comment by zzzeek** [comment]
I have no resservations about security, SQLAlchemy is about writing SQL, go nuts with that.

I just dont know anything about what this "scripting" feature would look like and it also seems of very limited use.     you're bascially writing stored procedures without the proc and as those are imperative, not declarative, a Python DSL over it is not that useful.

as far as if it's a good idea or not, I think you're coming from a vastly different perspective than me so I would encourage you to stay on your path and see where it leads.

**Comment by zzzeek** [comment]
So for the moment I'm closing this, because over here we don't have plans to change things related to this right now.    It sounds like you have some ideas for something you want to try, and I encourage you to do that.   from my perspective, I don't have a clear idea what we'd be adding here; the request is a "SQL variable" construct, but this is as you noted very simple and from my POV I don't know how SQLAlchemy would use this, because 1. SQL variables aren't generally usable for most database backends, SQL Server and probably Oracle are the exceptions  2. even on those backends, SQL variables are still not useful with the way that DBAPI cursor.execute() works, in that these variables are not carried over between statement executions.

towards issue number 2, the only way to get around that issue is to clump multiple statements together into a single execute() call, and *that* is very much a DBAPI specific thing that I'm not even sure works on Oracle, and additionally SQLAlchemy has no compositional system for such batched constructs.     So the issue here is not so much "add a SQL variable construct", it is much more significant than that, it is, "add a SQL variable construct PLUS a whole new system of building up batched SQL paragraphs with multiple statements in a single execute() call" and that is a very significant concept.  It's not hard to build something quick that just concatenates statements together, but that's not coherent enough for a major SQLAlchemy release to deliver this as big new feature with a wholly different paradigm of operating.   At the current level of specificity, it's just a recipe that I'm sure you're capable of working out.    

so sum up one more time, 1. this is asking for a dramatically different way of composing queries to send to the database, for which a very well thought out and coherent API / vision / goal / problem to be solved would need to be worked out  2. it probably only works on SQL Server anyway  3. it's not clear what problem this new system would try to solve.  

I will grant that I think you might have a more specific vision in mind than I am seeing, and that's a good thing, so I would encourage you to work out the patterns you're looking for and if something of significant generalized use comes out of it which matches SQLAlchemy's cross-platform vision we can look into it again.
