### ISSUE TITLE
refresh of expired columns does not trigger autoflush

### ISSUE THREAD

**Issue by Diggsey** [sqlalchemy/sqlalchemy#5226]
Here's roughly what I have.

A column property:
```python
Parent.has_child = column_property(
    exists().where(Child.parent_id == Parent.id)
)
```

Some code which creates a child:
```python
session.add(Child(parent_id=parent.id, ...))
# session.flush()
session.expire(parent, ['has_child'])
```

Some code which checks whether the parent has a child:
```python
if parent.has_child:
    ...
```

These latter two snippets run one after the other in the same session. The session is using standard settings with auto-flush on and auto-commit off.

The problem is that the last snippet observes `parent.has_child == False`, unless the `session.flush()` line from the snippet before is uncommented. I would expect that accessing `has_child` after it has been expired would cause a query to be issued to the database, and this query would cause the session to be flushed so that the child would be visible to the query. However, this does not happen, and somehow the column property still sees no child.

Even more strangely, this only seems to happen if `parent.has_child` was *not* accessed before the child was added.

**Comment by zzzeek** [comment]
the query doesn't autoflush when it is re-populating the immediate column attributes of an object, as this operation typically means whatever values might be present on those attributes is to be overwritten, rather than persisted (this is the populate_existing() case which is not quite the same as the "expired" case but same codepath).

the patch to change this assumption looks like:
```

diff --git a/lib/sqlalchemy/orm/query.py b/lib/sqlalchemy/orm/query.py
index 3e975890e..b7020f6b1 100644
--- a/lib/sqlalchemy/orm/query.py
+++ b/lib/sqlalchemy/orm/query.py
@@ -3400,7 +3400,7 @@ class Query(object):
     def __iter__(self):
         context = self._compile_context()
         context.statement.use_labels = True
-        if self._autoflush and not self._populate_existing:
+        if self._autoflush and (not self._populate_existing or self._refresh_state):
             self.session._autoflush()
         return self._execute_and_instances(context)
 

```

when this assumption is changed as above, the following four tests fail.  I haven't looked to see why this is, or if these tests perhaps are merely testing this assumption in some indirect way and could be changed without risk of a greater change in assumptions, however the mechanics of expiry / refresh are way deep at the center of everything and I would characterize this change as a high risk change right now, not the least of which that the autoflush process is somewhat expensive even if there is no flush to proceed.  Given this I think the best solution for your immediate issue is to call the flush explicitly, or make use of hybrid properties so that when the attribute is called under Python it can use the current Python state to report the correct result.

```
=========================================================================== FAILURES ===========================================================================
__________________________________________________ O2OSingleParentNoFlushTest.test_replace_attribute_no_flush __________________________________________________
[gw0] linux -- Python 3.7.6 /home/classic/.venv3/bin/python3
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: addresses.user_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test/orm/test_cascade.py", line 844, in test_replace_attribute_no_flush
    u1.address = a2
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/attributes.py", line 272, in __set__
    instance_state(instance), instance_dict(instance), value, None
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/attributes.py", line 994, in set
    | LOAD_AGAINST_COMMITTED,
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/attributes.py", line 722, in get
    value = self.callable_(state, passive)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/strategies.py", line 750, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/strategies.py", line 868, in _emit_lazyload
    lazy_clause, params = self._generate_lazy_clause(state, passive)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/strategies.py", line 649, in _generate_lazy_clause
    state, dict_, ident, passive
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/mapper.py", line 2824, in _get_committed_state_attr_by_column
    state, dict_, passive=passive
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/attributes.py", line 791, in get_committed_value
    return self.get(state, dict_, passive=passive)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/attributes.py", line 717, in get
    value = state._load_expired(state, passive)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/state.py", line 652, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/loading.py", line 1012, in load_scalar_attributes
    only_load_props=attribute_names,
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/loading.py", line 207, in load_on_ident
    identity_token=identity_token,
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/loading.py", line 287, in load_on_pk_identity
    return q.one()
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/query.py", line 3360, in one
    ret = self.one_or_none()
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/query.py", line 3329, in one_or_none
    ret = list(self)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/query.py", line 3404, in __iter__
    self.session._autoflush()
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/session.py", line 1602, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/session.py", line 1591, in _autoflush
    self.flush()
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) NOT NULL constraint failed: addresses.user_id
[SQL: INSERT INTO addresses (user_id, email_address) VALUES (?, ?)]
[parameters: (None, 'asdf')]
(Background on this error at: http://sqlalche.me/e/gkpj)
______________________________________________________________ HistoryTest.test_remove_persistent ______________________________________________________________
[gw3] linux -- Python 3.7.6 /home/classic/.venv3/bin/python3
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test/orm/test_dynamic.py", line 1022, in test_remove_persistent
    self._assert_history(u1, ([], [], [a1]))
  File "/home/classic/dev/sqlalchemy/test/orm/test_dynamic.py", line 972, in _assert_history
    eq_(attributes.get_history(obj, attrname), compare)
  File "/home/classic/dev/sqlalchemy/test/../lib/sqlalchemy/testing/assertions.py", line 237, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: History(added=[], unchanged=[], deleted=[]) != ([], [], [Address(email_address='a1', id=1, user_id=None)])
assert History(added...], deleted=[]) == ([], [], [Add...ser_id=None)])
  At index 2 diff: [] != [Address(email_address='a1', id=1, user_id=None)]
  Full diff:
  - ([], [], [Address(email_address='a1', id=1, user_id=None)])
  + History(added=[], unchanged=[], deleted=[])
___________________________________________________________ LoadOnFKsTest.test_autoflush_on_pending ____________________________________________________________
[gw2] linux -- Python 3.7.6 /home/classic/.venv3/bin/python3
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test/orm/test_load_on_fks.py", line 184, in test_autoflush_on_pending
    assert c3.parent is None
AssertionError: assert <test.orm.test_load_on_fks.Parent object at 0x7f5178a2c610> is None
 +  where <test.orm.test_load_on_fks.Parent object at 0x7f5178a2c610> = <test.orm.test_load_on_fks.Child object at 0x7f5178a2c510>.parent
________________________________________________________ LoadOnFKsTest.test_m2o_lazy_loader_on_pending _________________________________________________________
[gw2] linux -- Python 3.7.6 /home/classic/.venv3/bin/python3
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test/orm/test_load_on_fks.py", line 318, in test_m2o_lazy_loader_on_pending
    assert c2.parent is None
AssertionError: assert <test.orm.test_load_on_fks.Parent object at 0x7f517890ed10> is None
 +  where <test.orm.test_load_on_fks.Parent object at 0x7f517890ed10> = <test.orm.test_load_on_fks.Child object at 0x7f5178bdf590>.parent
=================================================================== short test summary info ====================================================================

```

**Comment by zzzeek** [comment]
yes this change breaks the fix that was made many years ago for #2921 .  So the fix for that issue would need to be revisited in order to change this assumption; it seems to be related to unexpiration of a relationship-bound attribute but that has implications for the whole object.

basically per-column unexpiries can happen in a lot of cases so an autoflush here means a lot more users confused by premature flushes which tend to be the bigger issue.    im not sure if there is some way to allow this kind of decision to be configurable in some way.

**Comment by zzzeek** [comment]
If I can read that all correctly it sounds like you're saying you'd like unexpiry to trigger autoflush for those columns that were explicitly expired.

but this does not cover the case where an object has a mixture of columns that were auto-expired (like from query.update()) or simply unloaded (e.g. lazy loaded attributes) vs. explicitly expired as well as what happens in cases where the "unexpire" is buried more deeply as in the case in #2921 .    it suggests that the expiry logic would have to be broken into two levels, such that "unexpire but don't autoflush" is broken out from "unexpire and autoflush".   

looking at #2921 it's not clear why my patch proposed above actually affects that case, as this particular behavior is not part of what was changed for that patch.   but its test breaks.

overall however a change in default behavior here as I said is likely to be too risky for the 1.3.x series.  it would need to be in 1.4.  there are many months to go before a 1.4 is happening, so i was only trying to give you workarounds for now.

there is the notion of just adding a flag to session.expire() to indicate this special behavior.  but it's not clear if later we'd be looking to deprecate that flag quickly, and also it's not clear why this specific issue has never been reported before, since this behavior is pretty old. likely predates #2921.

**Comment by zzzeek** [comment]
looking at the #2921 case this is exactly the thing. there's a "no_autoflush" bit that is passed down through this operation, however it doesn't dig into the "load attributes" case, where it needs to load the expired ".id" of the parent object in order to perform a lazy load.  If this object was also flagged as having "expired attributes that require autoflush", then this case would alternatively work, or fail.    That is, I don't see how to avoid an "edge case" in this situation.  If we make it autoflush every time, we have edge cases. If we make it not autoflush, we have this edge case.  if we have it autoflush only if there are expired attributes that happen to have tweaked a "yes please autoflush on unexpire flag", now we have a *really* hard to pin down edge case where autoflush or not seems to change randomly.

I know you don't like the edge case here but the problem is I don't see a way to not have something that looks like an edge case.   it seems the only real way to do this is to just place column_property() that have a non-local expression, or perhaps "readonly" columns, into a whole new class of "expiry" where they are not expired as regular attributes, but are instead on their own track.  then you get a performance issue where two SELECTs are emitted for a certain object rather than one.     more edge cases.     besides a positive flag to just force "autoflush" for an expiry operation taht you'd set on your end, nothing that isn't very high risk for regressions in the 1.3 series.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Run autoflush for unexpire when session.expire() or refresh() were used** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1837

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Run autoflush for unexpire when session.expire() or refresh() were used** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1838

**Comment by zzzeek** [comment]
we will pick the "autoflush seems to happen only if i called expire() / refresh() explicitly" edge case, with a new flag "autoflush" that can be set to false if this really gets in someone's way.  expire() / refresh() are the least common paths for expiration to occur and certainly if someone is using those they are looking for things to happen with the database as far as being up to date.

**Comment by Diggsey** [comment]
I'm not necessarily arguing for it to be implemented this way, but the most "direct" way of implementing my proposed semantics would be to track a per-session "timestamp" (actually just an integer counter that would be incremented on every update to a session).

Instead of auto-flush being on or off, queries are also tagged with a timestamp such that any session updates prior to the timestamp in the query should be visible in the results (effectively guaranteeing that at least those session updates prior to the timestamp have been flushed). SQLAlchemy wouldn't necessarily need to actually support partial flushes, it would be fine to just say that if anything needs to be flushed then everything is flushed.

When those queries come from the user, the timestamp should be set to the latest update timestamp (preserving the current auto-flush behaviour). When those queries are issued internally (such as when a column property needs to be fetched) the timestamp would come from the property.

When a model is first loaded, all its properties (including deferred) are tagged with the timestamp of the query that loaded the model, meaning that deferred properties can be populated later on without requiring any flushes (because they would issue queries tagged with an "old" timestamp).

When you explicitly expire a property, it would set the timestamp on that property to the current timestamp, ensuring that if you later access it, at least those session changes prior to the expiry will be flushed.

**Comment by zzzeek** [comment]
So to follow this proposal correctly, if an object A has a deferred column attribute A.some_property, and it is loaded in generation 1, however, some_property is deferred, so nothing is loaded.  Later, a bunch of state is added to the session; pending objects that when flushed, will impact the value of A.some_property.    However, fetching A.some_property will not autoflush, due to it being of the older generation, and will show the number "zero".  But if for some reason as those pending objects are added, something happens to trigger autoflush, then fetching A.some_property will show the correct number, or actually, some arbitrary number based on when the flush happened.  This seems pretty unpredictable, am I misunderstanding ?

**Comment by Diggsey** [comment]
That's correct - it's still unpredictable but it would be more predictable than it currently is whilst allowing more flexibility for SQLAlchemy.

The important thing to me is that it's a simple and consistent model to understand and implement against. For the most part, I can pretend that deferred properties are eagerly loaded with the rest of the model, and that "deferring" a property is mostly an optimization. I don't really care that the property might sometimes show "newer" changes because the only changes it might reflect would be changes that I've made to the session.

It also provides natural ways to extend the model. For example, there could be an option `always_fresh=True` on deferred properties that ensures they are always queried with the latest timestamp instead of a stored timestamp.

If we put this idea aside for a second, when you're doing any kind of optimization, you are changing the target that a programmer is implementing against. When C++ compilers started adding optimisations, you could no longer write C++ against the hardware, you had to write C++ against the abstract machine which the C++ specification defined.

It is the same with SQLAlchemy: because it is an ORM and not just a query builder, users can no longer implement against the SQL database: they are implementing against the abstract model which SQLAlchemy creates. At the moment this model is defined at a very low level, by trying to specify exactly when SQLAlchemy will run what queries, but this provides the worst of both worlds. Firstly, it makes the model very complicated to understand, and secondly, it makes it very difficult to apply these kinds of optimisations without changing the model and breaking someone's code.

To solve this, SQLAlchemy would have to define its model in terms of observable behaviour rather than in terms of what queries will be executed, and then whether or not an optimisation is allowed should be determined by whether it's compatible with the model. If a user implements against this model, they would not need to think about the session cache or anything like that. If they see out of date data, it would not be because "the session hasn't been flushed", it would be because the operation they are doing is specified to maybe return out of date data in that scenario.

**Comment by zzzeek** [comment]
hi there -

I appreciate the energy you're putting into this, however SQLAlchemy is a lot simpler than you are giving it credit for.   autoflush is in fact completely predictable.   if a query is about to run, it autoflushes.   when you access anything that's expired, you should ideally be getting everything that is set to go to the database.  This is much simpler than a system that attempts to guess which changes should be autoflushed and which should not.   

in this case, you have a surprising case where you have a local column attribute that is dependent on other tables.   this is a bug.  So this will be fixed in the next release at least to the extent that you actually expired it.    the case should be further improved, as are any other cases we can identify, which I actually can, but they are extremely narrow edges, such as, the "updated_at" column on a row is deferred, but then you altered some other part of that row, and then accessed the "updated_at" column, it would not have autoflushed that ".id" yet.  This is very small inconsistency and is not really an issue for anyone.

> To solve this, SQLAlchemy would have to define its model in terms of observable behaviour rather than in terms of what queries will be executed, and then whether or not an optimisation is allowed should be determined by whether it's compatible with the model. If a user implements against this model, they would not need to think about the session cache or anything like that. If they see out of date data, it would not be because "the session hasn't been flushed", it would be because the operation they are doing is specified to maybe return out of date data in that scenario.

I have to apologize because I am simply not understanding the concept of this proposal, and it seems very much like it is inspired by some formal system that you are likely deeply familiar with.  As I lack formal training in many areas, I'm not understanding this at all, but at the same time, most of my users probably don't understand these things as well as I do, which makes it seem unlikely that this new "maybe autoflush, maybe not,  based on the order in which things were done" would actually be less "complicated to understand" for most users.     The current system is extremely simple, it is based on the same concept as implemented in the Hibernate ORM as well as the Storm ORM for Python, so it's not even my idea, it's a pretty standard approach.   It's very simply, flush everything before reading the database.   I would sooner flip the "autoflush" switch on for all queries and simply consider things like #2921 a lost cause or to be solved in a different way, so that the behavior is 100% consistent, before instead making autoflush less predictable.  that would be much less work.

I appreciate that you seem to have strong ideas on how this should work, and I would encourage you to develop this system in more detail.  If you look in the source code you will see that objects which have been loaded do in fact have an attribute called "_run_id" which is exactly this increasing counter you are looking for.   You should feel free to create a proof of concept where you subclass Query and implement this logic above at the line number illustrated, noting all this code will be reorganized in master soon.   The point at which autoflush occurs could even be enhanced to respond to an event hook where people could implement whatever heuristics they'd like for a given autoflush event, though this seems like it would not be something most people would be interested in using.

SQLAlchemy is a very old project and is currently undergoing a [massive rework of old crufty patterns](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html) towards the goal of making SQLAlchemy easier to understand.  The emphasis in all cases is on fewer patterns available, less internal decisionmaking.    A system is easier to understand when it has fewer implicit decisions to be made.     My focus is consumed 100% by this very large undertaking that I have been involved with already for almost a year, and the 1.4 release will already place a burden on a lot of users that are using older patterns, so we are in no place for further major paradigm shifts.

**Comment by Diggsey** [comment]
No worries: I really don't mind what SQLAlchemy does here. Personally I would not choose to use the ORM layer of SQLAlchemy in future projects, and I just wanted to try and explain the reasons constructively.

> SQLAlchemy is a lot simpler than you are giving it credit for. autoflush is in fact completely predictable. if a query is about to run, it autoflushes. when you access anything that's expired, you should ideally be getting everything that is set to go to the database. 

Hm, all I can say is that this has not been my personal experience, and I know SQLAlchemy has a reputation for being complex. Right now, if I *don't* explicitly expire a column property or relationship it's unclear as to whether it will reflect a particular change. At least, you can't determine this by looking at a local section of code, you'd have to understand the larger access pattern, along with some details of how SQLAlchemy is implemented,

> it seems very much like it is inspired by some formal system that you are likely deeply familiar with.

It's more that I think SQLAlchemy would benefit from having *some* formal system defined. In my experience "high level" abstractions fail without such a model because to reason about them you have to mentally translate what you are doing back to low-level operations, which largely defeats the point of having a higher-level abstraction.

**Comment by zzzeek** [comment]
> Hm, all I can say is that this has not been my personal experience, and I know SQLAlchemy has a reputation for being complex. Right now, if I _don't_ explicitly expire a column property or relationship it's unclear as to whether it will reflect a particular change. At least, you can't determine this by looking at a local section of code, you'd have to understand the larger access pattern, along with some details of how SQLAlchemy is implemented,

A relationship should always be up to date, because when you alter it, you are altering it in Python.   if you are altering things on the other side of a relationship, like the many to one side of a one to many, the backref logic ensures that both sides are kept in sync.

it's only the case where you want to manipulate foreign key attributes directly that the relationship doesnt update automatically, which is documented at https://docs.sqlalchemy.org/en/13/faq/sessions.html#i-set-the-foo-id-attribute-on-my-instance-to-7-but-the-foo-attribute-is-still-none-shouldn-t-it-have-loaded-foo-with-id-7, and the reasons that part works that way is because manipulation of foreign key attributes directly is not idiomatic SQLAlchemy usage.    

I would benefit more from full [MCVE](http://stackoverflow.com/help/mcve) examples in order to illustrate specific scenarios for which we want to behave in a specific way.

> It's more that I think SQLAlchemy would benefit from having _some_ formal system defined. In my experience "high level" abstractions fail without such a model because to reason about them you have to mentally translate what you are doing back to low-level operations, which largely defeats the point of having a higher-level abstraction.

This is a lament of the "leaky abstraction" issue however SQLAlchemy's philosophy is that abstractions *must* leak; SQLAlchemy is not about "hiding" the database, it is about automating redundant tasks and reducing code complexity.    I have a lot of talks about this if you were interested in seeing how SQLAlchemy has come to where it is.

**Comment by zzzeek** [comment]
> No worries: I really don't mind what SQLAlchemy does here. Personally I would not choose to use the ORM layer of SQLAlchemy in future projects, and I just wanted to try and explain the reasons constructively.
> 

I'm sorry to hear that, but also I am intrigued by your ideas about using a generational counter but I simply would need much more specific examples to understand how it works.

I am retargeting this issue to 1.4 where the autoflush logic will trigger for all column load operations unconditionally, including deferred, expired, etc., the one exception being a narrow set of "load the historical value" cases suited by #2921.

**Comment by zzzeek** [comment]
going to scale this back for the legacy case of session with autocommit=True.
