### ISSUE TITLE
Auto-Convert raw sql to sqlalchemy query

### ISSUE THREAD

**Issue by bytearchive** [sqlalchemy/sqlalchemy#5233]
Is there a way to convert raw sql to sqlalchemy objects automatically 

since sqlalchemy does does the opposite thing, i.e. convert objects to sql, reverse parser should be possible

**Comment by CaselIT** [comment]
I believe there is no such functionality currently in sqlalchemy.

The only thing that may be similar is the ddl reflection to generate the sqlalchemy schema from a db, but it uses queries to the information schema to obtain the required data, it does not parse the sql of the database schema, so it would not be much help for this.

**Comment by zzzeek** [comment]
Hi there -

there's no facility for this within SQLAlchemy and this wouldn't be part of SQLAlchemy itself if it existed because it is too broad of an issue.    There is a library called [sqlparse](https://sqlparse.readthedocs.io/en/latest/)  that can certainly be used to build such a system in conjunction with SQLAlchemy, and I would encourage you to look into that.

**Comment by CaselIT** [comment]
@zzzeek do you want to keep this open in the bluesky milestone, or close it?

**Comment by zzzeek** [comment]
no, this is not something that would be approrpriate as directly included in SQLAlchemy, would make a nice third party project.
