### ISSUE TITLE
Referencing a non-text CTE from a TextClause

### ISSUE THREAD

**Issue by jvolkman** [sqlalchemy/sqlalchemy#5272]
Is there a way to indicate that a `TextClause` uses a CTE defined elsewhere so that it is included in the compiled query?

For example:

```
my_cte = sa.select([tbl.c.id, tbl.c.val]).where(...).cte('mycte')
stmt = sa.text('select * from mycte') 

# how do I have my_cte included in the output?
print(str(stmt))
```
This is a contrived example, but I have instances where this feature would be useful. Specifically, I'd like to have one CTE be a `VALUES` clause with input data and generated by something similar to the [PGValues](https://github.com/sqlalchemy/sqlalchemy/wiki/PGValues) recipe on the wiki, and have other CTEs (including some written in text) pull from it.

Or is there a more general way to include independent CTEs with a statement? For example, Postgres allows for a query such as the following, where there's no reference from the main query to the CTE:

```
with pre_delete as (
  delete from "Foo" where ....
)
insert into "Foo" (...) ...
``` 

Certainly there are different ways to achieve the same result, but I haven't found a way yet to get SQLAlchemy to generate this type of query.

**Comment by zzzeek** [comment]
direct, first class support for this general kind of thing was proposed a while back in #4502 .  This is still something that can have a place in SQLAlchemy however it's not a priority and there's no resource assigned to work on this anytime soon (of course, anyone is free to pick it up although this would be a large change that needs lots of tests and docs, getting it wrong would be very difficult to change later).    Though even with that issue being put in, getting the CTE to come out as a string without any "select()" for context is not a built in behavior and I don't know an easy way to do that; if you do a str() on the CTE right now, it comes out as nothing because it does not have any rendering without an enclosing select() to give it a place to go.   difficult use cases with no clear API like this one are sort of why I'm not that optimistic about #4502 in general as it might do simple things, but it will constantly have non-working cases as the text is structureless.

so given that, there is not any first class, direct support for this right now, which means you'd have to roll it yourself, which in this case looks like:

```
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


tbl = sa.table("t", sa.column("id"), sa.column("val"))


my_cte = sa.select([tbl.c.id, tbl.c.val]).where(tbl.c.val > 4).cte("mycte")
stmt = sa.text(
    "with mycte as (%s) select * from mycte"
    % my_cte.element.compile(dialect=postgresql.dialect())
)

print(str(stmt))

```

**Comment by jvolkman** [comment]
Totally agree that arbitrary inclusion of sqlalchemy elements in text templates would be a large challenge. 

What about the alternative: telling something (the statement object? `execute`?) to include a CTE even if though nothing in the query explicitly references it? Seems like this would open up a lot of use cases for mixing text and generated SQL by using CTE bodies.

**Comment by zzzeek** [comment]
if you're giving it a textual string then there's nothing defined about that string and no clear place to put anything without a token.

the bigger question is what are these textual SELECT statements that can't at least be partially in select() form.   you can swap out the WHERE , FROM, etc. clauses in a select() for text() as well while still having some SELECT-like structure.   

we can do a SELECT-like structure and still have strings all over the place like this:

import sqlalchemy as sa


tbl = sa.table("t", sa.column("id"), sa.column("val"))


my_cte = sa.select([tbl.c.id, tbl.c.val]).where(tbl.c.val > 4).cte("mycte")

stmt = (
    sa.select([my_cte])
    .where(sa.text("mycte.id = some_table.some_whatever"))
    .select_from(
        sa.join(
            my_cte,
            sa.text("(SELECT some_whatever from haha) AS some_table"),
            sa.text("some_table.foo = my_cte.bar"),
        )
    )
    .select_from(sa.text("some_other_table"))
    .where(sa.text("some_other_table.x = my_cte.val"))
)


print(str(stmt))

**Comment by zzzeek** [comment]
this is kind a long term "possible nice to have" but actually making it happen would be quite complicated regarding how to actually specify the intent, whereas the expression language already solves this problem and allows for textual inclusion.    the longer term potential feature remains at #4502 so closing this.
