### ISSUE TITLE
Reliably getting attribute history for deleted entry?

### ISSUE THREAD

**Issue by davidparsson** [sqlalchemy/sqlalchemy#5286]
We have built a file storage with transaction support that integrates with SQLAlchemy. Because of that we need to keep track of attribute history for deleted entities, to know when a file associated with a database row is to be deleted.

We have relied on the `persistent_to_deleted` event to get the attribute history, to catch as much as possible including cascade rules, but recently we have come across a case where the history is no longer available in this event, because the entries has already been deleted.

Is that expected behaviour? Is there any other way to reliably get attribute history for all entries that is/will be deleted?

Our current approach is to record possible candidates for deletion in `before_flush`, and keep a reference of them until a later event, but that is rather cumbersome.

**Comment by zzzeek** [comment]
the attribute history that you get from inspect(object).attrs.history is a short lived, single change record that will only indicate the most recent change in state from the last database-loaded value for an attribute.   this state is typically reset when the object is flushed as part of the flush() operation, which with session autoflush occurs automatically when queries are performed.    it is also reset when the object or its attributes are expired, and it will be empty if the attribute in question was never loaded in the first place.

It's not really a strongly defined behavior that this state is not reset when the object has been deleted and a flush has proceeded, it's an artifact of the fact that an expire() is not run on objects that were deleted and then removed from the session.   this does not explain why you are observing history not being present on an object but I would guess it is likely that the object's attributes were somehow involved in an UPDATE operation in a flush, which reset the attributes, before the delete occurred.

The before_flush event can be used to ensure this attribute state is protected before your persistent_to_deleted hook is called.  There should be no need to keep a reference to the object itself, I would have it instead extract the attribute history that you care about and then store it on the object, so that persistent_to_deleted can get at it later.

**Comment by davidparsson** [comment]
Got it, then we are on the right track. Thank you! Very helpful, as always. Much appreciated! 🌻
