### ISSUE TITLE
Reflect PG Composite with local definition

### ISSUE THREAD

**Issue by olirice** [sqlalchemy/sqlalchemy#5301]
**Question**
Given a composite type that is defined by a user following these instructions:
https://docs.sqlalchemy.org/en/13/orm/composites.html

Is there a way to register that type with `PGInspector` or the dialect so that it is available/used during table reflection?

**Additional Context**
The closest thing to a solution I've found is the DDL for column reflection:
https://docs.sqlalchemy.org/en/13/core/events.html#sqlalchemy.events.DDLEvents.column_reflect

But since unknown column types get reflected as `NullType` and there might be more than one composite type, it isn't quite enough.

I could:
- Intercept `NullType` on `column_reflect`
- Use the column info to query postgres for the correct composite type name
- Lookup that composite type from a registry of locally defined composites
- Replace `NullType` with the correct composite type

But I don't see a way to access the connection in an "official feeling way" inside that DDL event. is there one?

Worst case scenario I'll stash the connection somewhere and retrieve it inside the event, but that's pretty gross so I'd like to avoid it if possible! 

**Related Issues**
This question is related to #2450 but doesn't require that the composite type definition is also reflected

Thanks!

**Comment by zzzeek** [comment]
#2450 is very old and vague but it is basically this issue.   it would include all the data about the type and would be somehow relatable to the entries you get back from get_columns().      There's no official way to extend what happens when the system reflects types right now other than putting the name of your type and your class into sqlalchemy.dialects.postgresql.ischema_names.

A nice to have here would be if the records from the "get_columns()" dictionary included raw info about the type that was reflected.  this is a big job to do for every dialect but I would support a PR that seeks to provide this with tests.

overall though this is a dupe of #2450 .

**Comment by CaselIT** [comment]
I think that maybe we could have two enhancement here, that are valid also for other backend:
- have `get_columns()` return the raw type from the db as string
- have a public api to register/de-register user defined types so the reflection system can use them. 

How are extensions, like geoalchemy, currently adding reflection support for additional types?

**Comment by CaselIT** [comment]
Also Mike, are you still of the idea of having a generic "Literal_type" (I just came up with the name, so it may not make sense) that wraps an unknown type, so that `get_column()` would return it instead of `NullType` when encountering an unrecognised type?

This change is probably a separate issue, since I thin 1.4 would be a better target for it, since I guess it could cause problems with external extensions

**Comment by zzzeek** [comment]
Right now adding the raw type info to the column_definitions will solve this problem at a basic level except for the fact that the dialects warn when they can't match up a type, and people hate warnings.   Also it would be good if the "column_reflect" hook were locally available when you call metadata.reflect() without having to apply it to the Table class. 

A built in hook is still needed because that way someone can use inspector.get_columns() and that would have the right data in it, and there would be no warning.     it also has to be a functional plugin, not just name->type, because types have all kinds of arguments in them which would need to be interpreted by such a hook.    what arguments the function should take however is not clear, or if the function would have a different argument signature for different backends.    it should likely be given the database connection too so that the hook can do further queries.

I don't see any issue creating UnknownType which subclasses NullType but this seems like a minor cosmetic change, the risk is low but I'm not sure it's worth it in any case.

**Comment by CaselIT** [comment]
What I meant by Literal_type would not be like null, that renders null when creating the table.
the literal table would render literally what was initialized with: 
```py
t = Table('bar', meta, Column('foo', LiteralType("my_custom_type(42, 'foo')")))
```
would generated the ddl
```sql
create table bar ( foo my_custom_type(42, 'foo'))
```
Not sure if something like this is desirable.

**Comment by zzzeek** [comment]
That can't really work that way because datatype reflection does not necessarily receive a DDL-ready version of the datatype without special logic.  That is, there's no generalized way we would know where to get 42 and "foo" from if you look at how type refection works within dialects; the arguments come from other parts of the reflection queries and there is hardcoded logic that knows which arguments go to which types and how.

for dealing with unknown types I think keeping to the same consistent approach that's present now is best, that being, "receive raw data, pass to functions that know how to interpret this data in a dialect-specific way, return a finished TypeEngine object".

**Comment by olirice** [comment]
very cool options for the future ^
since this is marked as a duplicate I'll close & keep comments centralized on #2450
