### ISSUE TITLE
Choosing max overflow for QueuePool under async workers

### ISSUE THREAD

**Issue by yoobles** [sqlalchemy/sqlalchemy#5308]
**Describe your question**
I understand that under async workers like gevent, sqlalchemy can exhaust the amount of connections to the underlying database. 

So under load I see errors like:
```
QueuePool limit of size 10 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)
```

Investigating things like the MySQL slow query log shows that most queries aren't taking a very long amount of time so I'm not sure there's performance optimizations in queries. This leads me to believe that the primary issue is the load versus the queries themselves. 

What is the appropriate way to set the pool size for async workers? Should the max overflow be unlimited? 

**Useful links**
https://stackoverflow.com/questions/38534203/why-limit-db-connection-pool-size-in-sqlalchemy
https://stackoverflow.com/questions/38515488/load-testing-sql-alchemy-timeouterror-queuepool-limit-of-size-3-overflow-0-re
https://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html

**Have a nice day!**

**Comment by zzzeek** [comment]
the general calculus with gevent is not different than it is with threads, if your system allows 500 concurrent greenlets that all do database access, then increase pool size + max overflow so that they add up to 500.

you don't want "unlimited" greenlets because MySQL server itself can only handle so many actual database connections based on server configuration, memory and CPU available.   For example with Openstack we cap it at 4096 connections usually and really big systems hit 8192, im sure Facebook turns it up to tens of thousands per database server, but even in those cases, you can be sure there's a limit.  so you want to still configure greenlet limits in your software.

**Comment by yoobles** [comment]
Interesting, thanks for answering. 

So if under gevent, the pool size is smaller than the amount of concurrent requests/greenlets, you're effectively hoping that your queries run fast enough to keep up with demand and have an available connection in the pool to handle the next request. 

And then if you have too much load, not enough connections, and too low a timeout you get the QueuePool size error.

**Comment by zzzeek** [comment]
greenlets represent a field of work that is going on concurrently with other greenlets, just like threads.  the only difference is the scheduling model.   so any wisdom here applies similarly to threads and greenlets.
