### ISSUE TITLE
sqlalchemy on db failover

### ISSUE THREAD

**Issue by rizplate** [sqlalchemy/sqlalchemy#5319]
Awesome project Mike, best orm out there imho, better than hibernate and toplink

is there a section in docs describing how sqlalchemy handles db failover?

**Example (if applicable)**
i.e. if a failover happens in oracle or postgres, from db-a to db-a-replica. how does sa handles it? 

**Additional context**
1. is the connection/session dropped and a connection is automatically re-established after retries?
1. or does sa will throw exception and wait for user to retry the connection and re-do the transaction and operation
1. does sa does some checks to make sure that data read is consistent at data write i.e. does db-a-replica has correct data when write happens ? (via version_id or record hash)

**Comment by zzzeek** [comment]
failover is outside of the scope of SQLAlchemy and this has to do with how you configure your driver, the host or datasource that it connects to, and then what is actually listening on that host.     We usually use HAProxy for this purpose with MySQL which works very well.   if you google for "postgresql failover" you get a lot of hits for many different products and approaches for this problem.

On the SQLAlchemy side, the only configuration you need assuming hosts are doing failover is the pre_ping flag described at https://docs.sqlalchemy.org/en/13/core/pooling.html?highlight=pre_ping#disconnect-handling-pessimistic .    Turn that on and then anytime your host fails over, the next SQLAlchemy attempt at using a connection from the pool will do a ping, detect that the current host is no longer available, and then all the connections in the pool that are currently present will be invalidated so they all reconnect on next use.

**Comment by zzzeek** [comment]
for question #3, the ORM has a version_id feature which you can see at https://docs.sqlalchemy.org/en/13/orm/versioning.html#mapper-version-counter

**Comment by rizplate** [comment]
Thanks, I will checkout the haproxy with sa

with `pre_ping` flag, when the failover happens and sa pings, detects failover and invalidates old connections and now at next use connection is re-established to the failed-over server.

at this point, if there is a cached orm object in sa, that cached object will be synced using new connection to failover db?, or in other words if the user is posting a value read from original db, and now updating that value in failed over db sa will issue the sql right away ?

i.e. if the replica is not in-sync with original db, the value written will result in updating stale data? I realize it is out of scope for sa, but was wondering if version_id can solve it or if you have any suggestions for this scenario

**Comment by zzzeek** [comment]
pre_ping is actually transparent.  you do engine.connect() and it will have done the ping and the switch of the new connection.     that's why it's "pessimistic".  the "optimistic" connection check style involves that you program has to catch the error and try again.

however, as far as transactions in progress when the current host goes down, those are lost, you'd have to organize your application to either gracefully fail or retry operations, depending on what you're trying to do.

SQLAlchemy doesnt "cache" data, it has an identity map that is only intended to be useful on a per-transaction basis.  The Session expires all data that was loaded when the transaction ends.    so new database connection, new transaction, read everything fresh.   you can of course change and work around these behaviors pretty easily but you'll be aware that you're doing so.   The version_id feature is relevant here also but if you have failover for an ongoing transaction, when you hit the database and it errors out you will probably see everything being rolled back and expired.  

Reading on this includes:  https://docs.sqlalchemy.org/en/13/orm/session_basics.html#session-frequently-asked-questions  https://docs.sqlalchemy.org/en/13/faq/sessions.html#i-m-re-loading-data-with-my-session-but-it-isn-t-seeing-changes-that-i-committed-elsewhere  


a long time ago I wrote an extension for a financial institution that actually recorded all the statements emitted in a transaction and then would re-emit them on a retry, in order to try to get transaparent replay of transactions.  While it certainly worked on simple test problems, I told them it was a bad idea to use for real, they likely never used it and I was glad to take their money for the experiment.

**Comment by rizplate** [comment]
Thanks Mike for the advice!, we will fail fast on any error and do manual fix if errors/inconsistency during failover or traditionary periods.

**Comment by roshanpathak500** [comment]
@rizplate What solution did you implement for the sqlalchemy-RDS failover problem ? I am currently facing the same issue and with no solution whatsoever. psycopg2 community focal mentioned they dont support RDS and it will be a paid support .
