### ISSUE TITLE
Cannot create a parent-child relationship with multiple children without flushing for every child

### ISSUE THREAD

**Issue by ColinFinck** [sqlalchemy/sqlalchemy#5329]
**Describe the bug**
Using `autoflush=False`, I cannot create a parent-child relationship with multiple children without a `session.commit()` for every child.
Instead, I get an exception `sqlalchemy.exc.InvalidRequestError: Instance <Item at 0x1aea8d6f700> is already associated with an instance of <class '__main__.Item'> via its Item.parent attribute, and is only allowed a single parent.`, even though I'm trying to create a valid parent-child relationship without breaking the single parent rule.
Adding a `session.commit()` after adding every child works around this problem, but negatively impacts the performance.

**Expected behavior**
I can create arbitrary hierarchies in memory and only need to flush my changes to the database at the very end.

**To Reproduce**
Create a PostgreSQL table having this format:
```sql
CREATE TABLE items (
    id         INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    parent_id  INT,
    name       VARCHAR NOT NULL,
    FOREIGN KEY (parent_id) REFERENCES items(id) ON DELETE CASCADE
);
```

Then run the following code:
```py
from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker

Base = declarative_base()

class Item(Base):
    __tablename__ = 'items'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('items.id'))
    name = Column(String)

    parent = relationship(
        'Item',
        lazy='joined',
        cascade='all, delete-orphan',
        backref='children',
        remote_side='Item.id',
        single_parent=True
    )


engine = create_engine("postgresql://testuser:testpassword@localhost:5432/sqlalchemy-test", client_encoding='utf8')
Session = sessionmaker(bind=engine, autoflush=False)
session = Session()

root = session.query(Item).filter_by(name='root').first() or Item()
root.name = 'root'
session.add(root)

child1 = session.query(Item).filter_by(name='child1').first() or Item()
child1.parent = root
child1.name = 'child1'
session.add(child1)

child2 = session.query(Item).filter_by(name='child2').first() or Item()
child2.parent = root
child2.name = 'child2'
session.add(child2)

session.commit()
```

It works when adding a `session.commit()` after every `session.add`.

**Error**

```
Traceback (most recent call last):
  File ".\sqlalchemy-test.py", line 44, in <module>
    child2.parent = root
  File "C:\Users\Colin\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\attributes.py", line 272, in __set__
    self.impl.set(
  File "C:\Users\Colin\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\attributes.py", line 1019, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "C:\Users\Colin\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\attributes.py", line 1041, in fire_replace_event
    value = fn(
  File "C:\Users\Colin\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\strategies.py", line 2507, in set_
    return _do_check(state, value, oldvalue, initiator)
  File "C:\Users\Colin\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\orm\strategies.py", line 2495, in _do_check
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Instance <Item at 0x1aea8d6f700> is already associated with an instance of <class '__main__.Item'> via its Item.parent attribute, and is only allowed a single parent.
```

**Versions.**
 - OS: Windows 10 v1909 or Ubuntu 18.04
 - Python: 3.8.0 (Windows) or 3.6.9 (Ubuntu)
 - SQLAlchemy: 1.3.17
 - Database: PostgreSQL 12.1 (Windows) or 10.12 (Ubuntu)
 - DBAPI: psycopg2 2.8.5

**Comment by zzzeek** [comment]
hi there -

there's a clue in the error message which is "is only allowed a single parent.".   this refers to the single_parent=True flag, which is preventing your "root" object from being associated with more than one "child" at the same time via "child.parent".   this flag should not be set.    

It looks like you've set this flag due to the "delete orphan" cascade telling you to do so, however that setting is also not in support of what you want to do here, so you'd want to take that flag off as well.   delete orphan cascade does not work for a many-to-one object, that is, there is no feature that will delete "root" once all "child" objects are removed.  you'd have to implement that yourself if that's what you actually want.

**Comment by ColinFinck** [comment]
@zzzeek Thanks for the prompt reply!
What I actually want is a single `Item` supporting an arbitrary number of child `Item`s via a `children` list property. Each child shall have a `parent` attribute backreferencing to a single parent `Item`. If an `Item` is removed from the table, all children shall be removed as well. Finally, I want to be able to create a parent-child relationship by adding a child to the parent `Item`'s `children` list or by setting the `parent` attribute of the child.

Is that possible with SQLAlchemy and what's the table class definition for that?
How could I have known that my class definition was invalid, especially because it seemed to work well when still flushing after every new child.

**Comment by zzzeek** [comment]
> @zzzeek Thanks for the prompt reply!
> What I actually want is a single `Item` supporting an arbitrary number of child `Item`s via a `children` list property. Each child shall have a `parent` attribute backreferencing to a single parent `Item`. If an `Item` is removed from the table, all children shall be removed as well. Finally, I want to be able to create a parent-child relationship by adding a child to the parent `Item`'s `children` list or by setting the `parent` attribute of the child.
> 
> Is that possible with SQLAlchemy and what's the table class definition for that?

yes that is exactly what all of this is designed to do, the tricky part is putting the things on the right side.    "cascades" typically go on the "many" side of a relationship as is in the examples at https://docs.sqlalchemy.org/en/13/orm/cascades.html#unitofwork-cascades .

the following version of your script will illustrate the rows being inserted, and then deleted when "root" is removed:

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import func
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import backref
from sqlalchemy.orm import relationship
from sqlalchemy.orm import sessionmaker

Base = declarative_base()


class Item(Base):
    __tablename__ = "items"
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey("items.id"))
    name = Column(String)

    parent = relationship(
        "Item",
        lazy="joined",
        backref=backref("children", cascade="all, delete-orphan"),
        remote_side="Item.id",
    )


engine = create_engine("sqlite://", echo=True)
Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine, autoflush=False)
session = Session()

root = Item()
root.name = "root"
session.add(root)

child1 = Item()
child1.parent = root
child1.name = "child1"
session.add(child1)

child2 = Item()
child2.parent = root
child2.name = "child2"
session.add(child2)

session.commit()

assert session.query(func.count(Item.id)).scalar() == 3


session.delete(root)
session.commit()

assert session.query(func.count(Item.id)).scalar() == 0


```

> How could I have known that my class definition was invalid, especially because it seemed to work well when still flushing after every new child.

So as with everything, it starts with the documentation, which is on me as well since there should likely be more cascade examples including at the self-referntial example given at https://docs.sqlalchemy.org/en/13/orm/self_referential.html where I'm sort of surprised there aren't cascade settings given.   But the general thing that I should try to emphasize more is that "delete, delete-orphan" cascades are always given on the "many" version of a relationship, as it states what the parent object should do to the child objects when it encounters a change in state.

as for "seems to work", it's probably because SQLAlchemy ORM is perhaps new to you that this seemed to work, because the error message should generally tell you that something is wrong with the mapping.   Also, as it seems you used single parent because another error message suggested it also is something I would consider suspicious, since you won't see the "single_parent" flag used throughout the docs where it shows "cascade" settings in most cases, something must have been off that this strange flag was being asked for.

the error messages unfortunately can't tell you flat out "your mapping is wrong" because it does not know what your actual intent is.    this particular error could perhaps have extra wording such as, "if your intent is to delete X when X.parent is deleted, then set single_parent=True, otherwise consider this may not be the4 correct place for the cascade setting", something like that, you may have noticed we have a lot of over-the-top error messages like that already and these human-discovered reasons are why.  I'll commit that now.

then it seemed to work when you did something awkward, that's only because that approach works around the mechanism which is trying to catch this problem.  you would have noticed things not doing what's expected in other ways, such as, if you deleted any of the child objects, it would delete the root also, and also deleting the root would not delete the child object as you wanted.   in a real program you would have noticed these things not working.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Reword delete-orphan on many error message and document** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1983

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Reword delete-orphan on many error message and document** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1984
