### ISSUE TITLE
What was the rationale for making `passive_deletes=False` the default?

### ISSUE THREAD

**Issue by thomas-mckay** [sqlalchemy/sqlalchemy#5349]
With this simple model in mind
```python
class Child(Base):
    __tablename__ = 'child'
    id = sa.Column(sa.Integer, autoincrement=True, primary_key=True)
    parent_id = sa.Column(sa.Integer,
                          sa.ForeignKey(f'parent.id', ondelete='NO ACTION'),
                          nullable=False)
    parent = relationship('Parent')

class Parent(Base):
    __tablename__ = 'parent'
    id = sa.Column(sa.Integer, autoincrement=True, primary_key=True)
    children = relationship(Child)
```

From what I understand from the documentation, when deleting a `Parent` instance (aka. deleting the one in a one-to-many relationship), SQLAlchemy has 4 possible cascading behaviors for the `.children` before actually issuing the `DELETE` for the parent:
- issue an `UPDATE` on the children to set their foreign-key to `NULL` (the default);
- issue an `UPDATE` on the children to set their foreign-key to `NULL` **if** they have been loaded (`passive_deletes=True`);
- do nothing and let the database handle the `ON DELETE` (`passive_deletes='all'`);
- issue a separate `DELETE` for all the children (`cascade='delete'`);

In practice, this is what the the default behavior means:
-  if `Child.parent_id` is configured with `nullable=False`, then there's a guaranteed that the delete won't go through because the `UPDATE child SET parent_id=NULL WHERE child.id = :id` will raise a non-null violation on the db side. The problem is that this error
    ```
    sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: child.parent_id
    [SQL: UPDATE child SET parent_id=? WHERE child.id = ?]
    [parameters: (None, 1)]
    ```
    leads the user down a debugging rabbit-hole (stacktrace + documentation)[^1]. Whereas this:
    ```
    sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
    [SQL: DELETE FROM parent WHERE parent.id = ?]
    [parameters: (1,)]
    ```
    doesn't require much investigation.

- on the other hand, if `Child.parent_id` is configured with `nullable=True`, then the `UPDATE child SET parent_id=NULL WHERE child.id = :id` won't raise. This will effectively bypass any cascading behavior on the database side because by the time the `DELETE` for the parent is emitted, all the children will have been orphaned, so the db will happily `DELETE` the parent row. Now if the db is set to `ON DELETE SET NULL`, good, because you've essentially done on the Python side what the db would have done itself (although I still think it would be best to let the database do this). But, if the FK's `ON DELETE` was anything else on the db side (`RESTRICT`, `NO ACTION`, `SET DEFAULT`, `CASCADE`)... well, let's just say it won't be pretty and the debugging won't be fun. And if you're _not_ in charge of the database, you might also have a horde of angry DBA hunting you down.

So with that in mind, I'm wondering what is the rationale for making `passive_deletes=False` the default. Wouldn't it be less error-prone to have the ORM defer this behavior to the database by default and let the users add on ORM mechanisms with explicit options?

**N.B.**: I was bitten by this fairly recently with a nullable self-referential FK with `ON DELETE NO ACTION` (the model required to have at least one instance without parent). It was a personal project so no DBA have put a price on my head... yet. And I caught it early and found the solution rather quickly, so no harm done. But it did surprise me, as I've always found SQLAlchemy to be set up with sensible, conservative defaults (i.e. it doesn't make requests unless you explicitly ask it to). I am sorry if the way I asked this question seems somewhat biased. I am genuinely interested in the reasoning behind the default. 

**N.B.2**: Also, I am very, **very** grateful for the work that has gone into this project. I can honestly say that using SQLAlchemy for the past few years has forced me to question and change a lot of my bad developing habits. So, thank you for that :+1: 

[^1]: Though, it *is* documented SQLAlchemy behavior, and I did end up finding the related documentation fairly easily.

**Comment by zzzeek** [comment]
hi there -

the rationale for passive_deletes=False is manyfold:

1. in relational databases, foreign keys default to NONE for their cascade.     SQLAlchemy has to set these columns to NULL in order to express the intent of the operation that the parent is to be de-associated from the child objects.  This only leaves the case that you describe, which is based on the two assumptions that all databases and all schema designs would include a FOREIGN KEY constraint and that this FOREIGN KEY is actually enforcing. If either of these two assumptions are false, then passive_deletes=True leads to silent failure.    Silent failure is of course the most difficult thing to debug, because you don't even get a stack trace.

2. Databases such as SQLite and for several decades MySQL default to having no foreign key support at all which means passive_deletes=True means guaranteed silent failure.       

3. SQLAlchemy relationships can also be configured using no foreign keys at all, so this would be another situation where passive_deletes=True would mean silent failure.


> In practice, this is what the the default behavior means:
> 
>     * if `Child.parent_id` is configured with `nullable=False`, then there's a guaranteed that the delete won't go through because the `UPDATE child SET parent_id=NULL WHERE child.id = :id` will raise a non-null violation on the db side. 

if the columns are non-nullable, that's a good thing.  it tells you that you either should not be deleting that parent or you have to set up cascade, either on the SQLAlhcemy side or on the foreign key side.

The problem is that this error
>       ```
>       sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: child.parent_id
>       [SQL: UPDATE child SET parent_id=? WHERE child.id = ?]
>       [parameters: (None, 1)]
>       ```
>       
>       
>       leads the user down a debugging rabbit-hole (stacktrace + documentation)[^1]. 
Whereas this:
>       ```
>       sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
>       [SQL: DELETE FROM parent WHERE parent.id = ?]
>       [parameters: (1,)]
>       ```
>       
>       
>       doesn't require much investigation.

Respectfully I disagree. There's a stack trace that points you to right where this happens, a stack trace that will be 95% the same in both cases.   While the behavior of setting the foreign key column to NULL might not be something that a newcomer to SQLAlchemy would immediately realize is necessary, as mentioned above it absolutely is necessary in order to avoid many silent failure scenarios, and it is also [prominent](https://docs.sqlalchemy.org/en/13/orm/tutorial.html#deleting) in the ORM tutorial which is the prerequisite documentation for using the ORM.  Once someone knows this is what SQLAlchemy does, it is not mysterious at all.


> 
>     * on the other hand, if `Child.parent_id` is configured with `nullable=True`, then the `UPDATE child SET parent_id=NULL WHERE child.id = :id` won't raise. This will effectively bypass any cascading behavior on the database side because by the time the `DELETE` for the parent is emitted, all the children will have been orphaned, so the db will happily `DELETE` the parent row. 

But that's exactly what you told SQLAlchemy to do.  You have a nullable foreign key column, you removed the parent, you didn't tell it you want the child objects to be deleted, the intent is clear that you would want the child rows to remain with NULL in that column.  Otherwise why set the column to allow nulls?


> Now if the db is set to `ON DELETE SET NULL`, good, because you've essentially done on the Python side what the db would have done itself (although I still think it would be best to let the database do this). 

it absolutely is best to let the database do it however users of SQLite, MySQL MyISAM and many other quasi-relational backends would experience silent failure if this were the default.

> But, if the FK's cascade was anything else on the db side (`RESTRICT`, `NO ACTION`, `SET DEFAULT`, `CASCADE`)... well, let's just say it won't be pretty and the debugging won't be fun. 

To a newcomer, debugging is going to be hard in all cases.   I really don't think it's that hard and the alternative is silent failure on many backends.


> And if you're _not_ in charge of the database, you might also have a horde of angry DBA hunting you down.

I'm not actually understanding this and this seems unrelated to the question at hand.

> 
> 
> So with that in mind, I'm wondering what is the rationale for making `passive_deletes=False` the default. Wouldn't it be less error-prone to have the ORM defer this behavior to the database by default and let the users add on ORM mechanisms with explicit options?

so to sum up I think one has to appreciate that foreign keys are not present in all cases nor are they actually enforcing.  So SQLAlchemy uses defaults that will prevent silent failure.  

> 
> **N.B.**: I was bitten by this fairly recently with a nullable self-referential FK with `ON DELETE NO ACTION` (the model required to have at least one instance without parent). It was a personal project so no DBA have put a price on my head... yet. And I caught it early and found the solution rather quickly, so no harm done. But it did surprise me, as I've always found SQLAlchemy to be set up with sensible, conservative defaults (i.e. it doesn't make requests unless you explicitly ask it to). I am sorry if the way I asked this question seems somewhat biased. I am genuinely interested in the reasoning behind the default.

this is the most conservative default.

> 
> **N.B.2**: Also, I am very, **very** grateful for the work that has gone into this project. I can honestly say that using SQLAlchemy for the past few years has forced me to question and change a lot of my bad developing habits. So, thank you for that +1

thanks!

> 
> [^1]: Though, it _is_ documented SQLAlchemy behavior, and I did end up finding the related documentation fairly easily.

**Comment by thomas-mckay** [comment]
Hi Mike, and thank you for the detailed answer. I'll gladly admit the ORM tutorial is not fresh in my head. Also, I'm using postgresql, so my understanding of the default was, in fact, biased. I see now that this is more complicated once you take into account the other RDBMS, and I am by no means an expert.

When you mention silent failures, I'm assuming you are speaking of a corruption in the data, as in the children would still reference a deleted parent if the db didn't enforce FKs and `passive_delete=True/'all' `. Am I understanding you correctly? If so, that was the point of my second paragraph and the little joke about the DBA. Sorry I didn't make it clearer. What I was trying to say is that with the default in place `passive_delete=False`, if you have a nullable FK and your DBA set it up so that you can't delete a parent that still has children (`ON DELETE RESTRICT / NO ACTION`) or so that it cascades, you'll essentially bypass the DBA' configuration of the database and introduce erroneous data (i.e. a lot of orphan children).

This is closer to what I was working on, so maybe I'll be clearer here. Assume a db that models a recursive relationship, such as files and folders of a filesystem. You have your root node, with `parent_id = NULL`. Then under the root(s), you have the first level with `parent_id = root_node.id`, etc... `passive_deletes` is `False` and your FK is nullable. Now let's assume I delete a parent node. In this model, all of it's children will immediately become root nodes once their fk is nullified.
But maybe the DBA had put a safeguard against that in the db (`CASCADE/RESTRICT/NO ACTION`). The default bypasses it. that's what I meant by "you'll get angry DBAs after you".

But I do get your point. The sensible default here has to take into account a lot more than this use case.

**Comment by zzzeek** [comment]
yes the case where the FK is nullable and there's an ON DELETE <something> action in any case calls not just for passive_deletes=False, but passive_deletes='all', which is a more recent addition that handles more unusual cases like this.  

However the DBA shouldn't blame the programmer for this case, the purpose of constraints is to prevent things from happening.  If their constraint configuration is failing to prevent this from happening, that's on them - that column should be set as NOT NULL.   it's a pretty broken schema where there's an FK thats nullable, meaning it's allowed to have rows that are "orphans", but only "orphans" that somehow have never had a parent, or something.

It should be clear that SQLAlchemy should not assume that such an unusual case is present, where in the vast majority of cases where such assumptions are not presesnt, it runs the risk of creating a data corruption scenario.      Anyone who did LAMP style database programming in the 90's came across databases where columns referred to keys that didn't exist, and the site would not only be down and crashing it would also be impossible to fix.    it would be quite broken for SQLAlchemy to leave these non-existent keys in place and hope an unusual constraint is going to stop it.

**Comment by zzzeek** [comment]
I think aside from the "DBA" theme distracting me, I think this is an example of a default behavior that caused you to spend more time than you wanted on an error message that you didn't understand.   but now that you know this is to be expected, there's no need to keep throwing time cycles into it on both of our parts.  thanks for the comments.
