### ISSUE TITLE
add wrapper function compile_to_raw_query(query)

### ISSUE THREAD

**Issue by copdips** [sqlalchemy/sqlalchemy#5377]
Hello,

For a bubug/logging purpose, I need to convert a BinaryExpression to raw sql query.
I found the doc: https://docs.sqlalchemy.org/en/13/faq/sqlexpressions.html?highlight=literal_bind#rendering-bound-parameters-inline, it works very well, but could you please add a wrapper function something like ` compile_to_raw_query(query or filter)` in order to get rid of the explicit params.
I think some other users also have the same need.

Furthermore, it would be nice to bind the function to the BinaryExpression, in order to find it directly by `dir(query or filter)`

**Comment by zzzeek** [comment]
hi there -

For debugging purposes, I would not recommend using this approach.   I would instead recommend using [.params](https://docs.sqlalchemy.org/en/13/core/internals.html?highlight=params#sqlalchemy.engine.interfaces.Compiled.params):

```
>>> from sqlalchemy import column
>>> expr = column('x') == 5
>>> print(expr.compile())
x = :x_1
>>> expr.compile().params
{'x_1': 5}

```

that should solve your issue of the method being available with dir(), and it will also work for all datatypes which the "inline parameters" approach currently will not.

**Comment by zzzeek** [comment]
this is also documented right at the beginning of the core tutorial: https://docs.sqlalchemy.org/en/13/core/tutorial.html#insert-expressions

**Comment by copdips** [comment]
Thx, I know the `expr.compile().params`, but what about for logging purpose, I would like to log all the raw queries passed by sqlalchemy even for PRD environment ?
Current trick with `expr.compile().params` needs to write a little bit more codes everytime, it would be nice to have a simple wrapper.

**Comment by zzzeek** [comment]
Not sure what "PRD" is.    SQL is logged using regular logging: https://docs.sqlalchemy.org/en/13/core/engines.html#configuring-logging  , which represents the bound parameters separately.  this is more accurate as this is what's being sent to the DBAPI driver, I don't see why having the parameters "inline" is helpful for logging.  Also, the approach in the FAQ for "inline parameters" only works for a small handful of datatypes so is not a general solution.

the FAQ approach remains a lesser used, special use case and there is no need for SQLAlchemy to create redundant versions of an existing feature.     if you are writing a custom logging solution, that seems like somehting you'd be writing just once, so I don't get the "everytime" part of it.   for pdb/convenience I would stick to compile() and compile().params since that is the most accurate version of what actually will be used.

**Comment by copdips** [comment]
thx for your explanation.
