### ISSUE TITLE
sqlalchemy 'result' object has no attribute 'email' when querying several tables

### ISSUE THREAD

**Issue by MosheVai** [sqlalchemy/sqlalchemy#5382]
I have the following tables:

    class User(Base):
        __tablename__ = 'users'
        email = Column(String, primary_key=True)
        name = Column(String)
    
    class Document(Base):
        __tablename__ = "documents"
        id = Column(Integer, primary_key=True)
        author = Column(String, ForeignKey("users.email"))
when I perform a very simple query, and when i try to access the `email` attribute :

    results = (session.query(User, Document)
                      .join(Document, User.email == Document.author).all())
    results[0].email 

i get the error 

    'result' object has no attribute 'email'
only when I do the following does it give me the email attribute:

    results[0].User.email 
surely this isn't the way to use sqlalchemy? how can I access all the results attributes in a flat manner?

----
when I compile the query it seems to be as expected

    >>> print(q.statement.compile(dialect=postgresql.dialect()))
    SELECT users.email, users.name, documents.id, documents.author 
    FROM users JOIN documents ON users.email = documents.author

**Comment by zzzeek** [comment]
hi there -

in Python, "User" and "Document" above are types.   You know this because you declared them using the `class` keyword.   When an ORM query is performed and passed a series of one or more types to fetch, you get back instances of those types, e.g., User and Document instances, or in other words, objects (this is detailed in the beginning of the Object Relational Tutorial at [1]).   Converting database rows into database objects is the most fundemental task that an ORM, or object relational mapper, is intended to perform.  

These are the full blown objects with a `__dict__` element and a "self" that is passed to all the methods on those objects.  Object instances are not just namespaces (bags of key/value pairs), they are encapsulated units of data and methods which operate upon that data and cannot be arbitrarily merged together.   This should be apparent if we proposed that the User class had a method such as "get_username()" on it and the Document class had some method such as "get_documentname()", these methods are invoked with a "self" argument, which is the instance of User or Document in use; it wouldn't make any sense that a library could produce some kind of "UserDocument" that acts like a "User" and a "Document" at the same time nor would anybody really want that.   At a more simplistic level if both User and Document had a "name" attribute, there would be no definable way of dealing with that either.

in this way, when folks use Query and pass a series of types, they're going to do something like this:

```
    for user, document in session.query(User, Document).... :
        user.email
        document.author

```
If you're looking for a tuple of values that are derived from the User and Document mappings, but otherwise are not linked to a "self", you want to usually request those elements directly, such as session.query(User.email, Document.author) [2], or to request the rows as  table rows, that is session.query(User.__table__, Document.__table__) which will use a Core style approach as detailed in [3].

Hope this helps to clarify what's going on.

[1] https://docs.sqlalchemy.org/en/13/orm/tutorial.html#querying-with-joins

[2] https://docs.sqlalchemy.org/en/13/orm/tutorial.html#querying

[3] https://docs.sqlalchemy.org/en/13/core/tutorial.html#selecting-specific-columns
