### ISSUE TITLE
When i use `session.merge`, i got `IntegrityError`

### ISSUE THREAD

**Issue by optiona1** [sqlalchemy/sqlalchemy#5390]
**Describe your question**
When i use `session.merge`, i got a `(pymssql.IntegrityError) (2627, b"Violation of PRIMARY KEY constraint 'PK__payment___357D4CF8B9E5C8E5'. Cannot insert duplicate key in object 'dbo.test'`. The same in mysql `sqlalchemy.exc.IntegrityError: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'payCode_-298' for key 'PRIMARY'`
**Example (if applicable)**
```python

from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base, declared_attr
from sqlalchemy.orm import sessionmaker, scoped_session

from config import Config

engine = create_engine(
    Config.SQLALCHEMY_DATABASE_URI,
    pool_size=Config.SQLALCHEMY_POOL_SIZE,
    max_overflow=Config.SQLALCHEMY_MAX_OVERFLOW,
    pool_recycle=Config.SQLALCHEMY_POOL_RECYCLE,
    # echo=True
)

db_session = scoped_session(
    sessionmaker(autocommit=False, autoflush=False, bind=engine)
)


class Base:
    @declared_attr
    def __tablename__(cls):
        return (
            "".join("_%s" % c if c.isupper() else c for c in cls.__name__)
            .strip("_")
            .lower()
        )


Base = declarative_base(cls=Base)
class PaymentMethod(Base):
    """test"""

    code = Column(String, primary_key=True, autoincrement=False, comment="primary_key")
    name = Column(String, comment="name")
    group_id = Column(String, comment="group_id")
    shop_id = Column(String, comment="shop_id")
    insert_time = Column(DateTime, comment="insert_time", default=datetime.now)

data = [{'name': 'payCode_-298', 'value': 'pospalopenpay_yiling.clientscanpos'}, {'name': 'payCode_-299', 'value': 'pospalopenpay_yiling.clientscanpos'}, {"name":'payCode_-298', 'value': 'pospalopenpay_jlpay.clientscanpos'}, {'name': 'payCode_-299', 'value': 'pospalopenpay_jlpay.clients'}]
for i in data:
    db_session.merge(PaymentMethod(code=i["name"], name=i['value'], shop_id='test_shop_id', group_id='test_group_id'))
db_session.commit()
```
**Additional context**
The tables in the database are clean

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there, and thanks for the clear test case.    

in this example, you've turned off autoflush and you are not flushing in between merges.  therefore your code puts into the Session's "pending" list two objects for each primary key 'payCode_-298' and 'payCode_-299', for a total of four objects; the existing primary key is not detected because they are not in the database nor are these new objects in the identity map, because they are all waiting in the pending state.  then the first flush occurs within the commit and you get the integrity violation.  

re-enabling autoflush will allow each object to be flushed before the next merge() occurs so that the existing row can be found in the identity map and/or database.

note you can also get help for issues like these on the IRC channel, gitter channel or mailing list (resources: https://www.sqlalchemy.org/support.html )

**Comment by optiona1** [comment]
Hi, thanks for such a quick feedback.That works. @zzzeek
