### ISSUE TITLE
switch pkg_resources use to importlib.metadata, if installed

### ISSUE THREAD

**Issue by lkollar** [sqlalchemy/sqlalchemy#5400]
As dialect discovery relies on `pkg_resources`, if `setuptools` is not installed (which is rare, but possible), the discovery process is skipped.

https://github.com/sqlalchemy/sqlalchemy/blob/5624430eb1d07c68d0931bc89f7146bc003fde19/lib/sqlalchemy/util/langhelpers.py#L269

Is this an optional feature where the user needs to ensure `setuptools` is installed, or should it be a runtime dependency?

**Comment by zzzeek** [comment]
if you want to use plugins you would need to have setuptools installed.  a plugin itself installed via setup.py would probably not be installable without setuptools being present, so i think that's how it works out.

**Comment by lkollar** [comment]
Right, but that just means `setuptools` is available during installation. Since nothing declares a runtime dependency on it, it does not have to be available when plugin discovery happens. I encountered this issue in a situation where we package application dependencies based on the dependencies they declare, and deploy those as a bundle. As nothing declares the `setuptools` dependency, custom dialects stop working.

**Comment by zzzeek** [comment]
what's a bundle?  is it this?  https://pypi.org/project/bundle/   ? this is not something I'm familiar with.   I've never heard of a Python environment where the libraries that are required to get the software installed are suddenly vanishing when the things are run.

for this kind of issue I look to other prominent packages to see how they handle this.

pytest supports entrypoints: https://docs.pytest.org/en/latest/writing_plugins.html
but no runtime dependency if im reading this correctly: https://github.com/pytest-dev/pytest/blob/master/setup.cfg

sphinx supports plugins via entrypoints: https://www.sphinx-doc.org/en/master/extdev/index.html
they do seem to have setuptools: https://github.com/sphinx-doc/sphinx/blob/3.x/setup.py#L17

if I use the "console_scripts" setuptools entrypoint, a console script is created that imports pkg_resources, however in basic examples of console_scripts like in https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point I don't see any guidance that "setuptools" needs to be an explicit dependency.

it seems kind of broken to me that a setup.py which has setuptools and includes entrypoints would also need to explicitly state setuptools as also part of install_requires, and comments like the one I see here in Click https://github.com/pallets/click/blob/master/requirements/dev.txt#L55 make me doubtful that this is a best practice.

We put a simple pyproject.toml file in SQLAlchemy so that Black could work and it was like the world came crashing down.  I can't make changes like these without extremely clear guidance from pypa developers.    Otherwise , I'd ask what this "bundle" is and why exactly that tool does not include setuptools automatically considering this is likely a very widespread pattern.

**Comment by zzzeek** [comment]
also in Click they have a spot where they are importing pkg_resources and then falling back if it's not present:

https://github.com/pallets/click/blob/master/src/click/decorators.py#L281

**Comment by zzzeek** [comment]
as is customary for these pypa types of problems, I've asked on twitter for the best practice.   issues like these tend to go very poorly when I just change things and release, in ways that I would never be able to predict.

**Comment by zzzeek** [comment]
things I never bother to learn about but just verified, pip can install a wheel without setuptools being present.

So I guess you're making a big list of .whl files and just installing that then ?    I'm still not sure if its safe for setuptools to be an install_requires though.

**Comment by zzzeek** [comment]
flask has a conditional import for pkg_resources:

https://github.com/pallets/flask/blob/2062d984abd3364557a6dcbd3300cfe3e4ecf156/src/flask/cli.py#L524

no dependency on setuptools:

https://github.com/pallets/flask/blob/master/setup.py#L12

**Comment by zzzeek** [comment]
for Python 3.7 + we can potentially use importlib.metadata: https://docs.python.org/3/library/importlib.metadata.html   there is also a pypi package for this but im hoping not to add any kind of dependency here.   making this a "fixed in python 3.7" issue and using importlib.metadata would be preferable.

**Comment by zzzeek** [comment]
also everything im reading about setuptools/pkg_resources suggest it's a terrible dependency to have so at the moment I'm leaning towards trying to import importlib.metadata and work w/ that for this one bit of code, otherwise the workaround for older pythons is to ensure the dependency is present.

**Comment by lkollar** [comment]
First of all, thanks @zzzeek for taking the time to research this issue. 

> what's a bundle? is it this? https://pypi.org/project/bundle/ ? this is not something I'm familiar with. I've never heard of a Python environment where the libraries that are required to get the software installed are suddenly vanishing when the things are run.

What I meant by a bundle is a result of a custom solution which relies on package metadata for creating self-contained Python applications. I'm not at liberty to share more details about this right now, but this is just an example where this could come up - as you suggested a `pip` installation without `setuptools` being present could also exhibit the issue.

I understand the hesitation to add a new dependency on `setuptools`. Reading up on the discussions you linked to, it's clear that this is not as simple as it sounds. Given the issues around `pkg_resources` use, it might be a better option to drop it entirely and switch to `importlib.metadata` and add a dependency on the [backport library](https://pypi.org/project/importlib-metadata/#description) for older Python versions.

A small correction: `importlib.metadata` was introduced in 3.8, not 3.7.

**Comment by zzzeek** [comment]
hi @lkollar 

This would mark the first time since 2005 SQLAlchemy has ever had any install requirements, and in particular this would be a requirement that goes away once Python 3.8 is the minimum supported version.    

Additionally, it's historically been problematic to have a "conditional requirement" inside of a setup.py file, see https://github.com/sqlalchemy/mako/issues/249 for an epically long drama on how badly things went when Mako tried to do this.   That said, these days there are improved systems for this as we can see in Flake8 https://gitlab.com/pycqa/flake8/-/blob/master/setup.cfg where they can have python versions established declaratively within the requirements, but again these would all be things that we have to get "right" and as mentioned previously we have really bad luck whenever we do *anything* with installation.

Whether or not the requirement is "conditional", the 1.3.x series is very mature now and I would not be doing this until 1.4 if at all, 1.4 production releases are not expected until the Autumn at the earliest.

On top of all of that, this is as mentioned at the top, an extremely unlikely issue, and if we do have an import attempt for "importlib.metadata", the issue will go away on its own.

Where I'm going with this is that for your end, you definitely have to just add the setuptools requirement for now to make your internal system work.   for 1.4 I am comfortable adding the check for "importlib.metadata" but for the requirement part, I'd need to work with that more to see if I'm comfortable with that part.

**Comment by lkollar** [comment]
Sounds good. We have added a `setuptools` dependency on our end as a workaround.

**Comment by zzzeek** [comment]
the new setup.cfg thing (not that new anymore but new to me :)  ) should probably allow us to just add the 3rd party importlib_metadata as a dependency for python < 3.8.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use importlib_metadata; add namespace for mariadb** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2144
