### ISSUE TITLE
Dynamically joined Many-To-One pop by index skips index 0

### ISSUE THREAD

**Issue by jslay88** [sqlalchemy/sqlalchemy#5425]
**Describe the bug**
I am having an issue where I am getting different values for the same index on a model attribute that is dynamically joined via backref.

For instance, say `child` was backref'd with a dynamic join to `parent` under the attribute `children`.

and lets say parent has 4 children, `a`, `b`, `c`, and `d`  in this order.

if I iterate over the children by index directly against the attribute, i get the following output
```py
for i in range(4):
  print(parent.children[i])

b, b, c, d
```

but if I type cast it to a list before popping via index, I get the correct return
```py
for i in range(4):
  print(list(parent.children)[i])

a, b, c, d
```

The issue is resolved if I have it automatically join via `joined` instead of `dynamic`

**Expected behavior**
Grabbing an item from a many-to-one dynamically joined backref via index

**To Reproduce**
```py
class Owner(db.Model):
    id = db.Column(db.VARCHAR(16), primary_key=True)
    name = db.Column(db.VARCHAR(32), nullable=False)

class Product(db.Model):
    sku_prefix = db.Column(db.VARCHAR(24), db.ForeignKey('default_product.sku_prefix'), primary_key=True)
    owner_id = db.Column(db.VARCHAR(16), db.ForeignKey('owner.id'), primary_key=True)
    enabled = db.Column(db.Boolean, nullable=False, default=True)

    default_product = db.relationship(DefaultProduct, backref=db.backref('products', lazy='dynamic'), lazy='joined')
    owner = db.relationship(Owner, backref=db.backref('products', lazy='dynamic'), lazy='joined')

owner = Owner.query.first()
print('Indexed Product 0', owner.products[0])
print('List Indexed Product 0', list(owner.products)[0])
print('Indexed Product 1', owner.products[1])
print('List Indexed Product 1', list(owner.products)[1])
print('Indexed Product 2', owner.products[2])
print('List Indexed Product 2', list(owner.products)[2])

Indexed Product 0 <Product product_1>  # <---- This is wrong
List Indexed Product 0 <Product product_0>
Indexed Product 1 <Product product_1>
List Indexed Product 1 <Product product_1> 
Indexed Product 2 <Product product_2>
List Indexed Product 2 <Product product_2> 
```

**Versions.**
 - OS: Windows/Linux
 - Python: 3.7 and 3.8
 - SQLAlchemy: 1.3.18
 - Flask-SQLAlchemy: 2.4.3
 - Database: Postgres 12
 - psycopg2: 2.8.5

**Comment by zzzeek** [comment]
hi there -

your MCVE is not runnable as it does not provide the "DefaultProduct" model, nor any sample data, but I have confirmed that query slicing on the PostgreSQL dialect is working as expected for index zero, see the MCVE below.

Your issue is almost certainly that you don't have any ORDER BY clauses on your relationships, and because you also have a joinedload() occurring on a separate relationship, the SQL will contain additional LEFT OUTER JOINs and in some cases there may also be a row-limited subquery present, either of which can randomly affect ordering if it is not stated explicitly.   The SQL to get index zero includes "LIMIT" only whereas index 1 and greater includes "LIMIT OFFSET" so it is a different query.   echoing on the engine will illustrate this.

Steps to take are:

1. turn on echo='debug' to confirm that the [0] index without an OFFSET is in fact causing a different ordering to take place in PostgreSQL's query results

2. ensure all relationship()s where ordering is important include [order_by](https://docs.sqlalchemy.org/en/13/orm/relationship_api.html?highlight=relationship%20order_by#sqlalchemy.orm.relationship.params.order_by):

    owner = db.relationship(Owner, backref=db.backref('products', lazy='dynamic', order_by='Product.sku_prefix'), lazy='joined')


demo of working behavior:
```

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import backref
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)


class B(Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    c_id = Column(ForeignKey('c.id'))
    data = Column(String)
    a = relationship(
        "A", backref=backref("bs", lazy="dynamic", order_by="B.id")
    )
    c = relationship("C", lazy="joined")

class C(Base):
    __tablename__ = 'c'
    id = Column(Integer, primary_key=True)


e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

c1, c2 = C(), C()

s.add(A(bs=[B(id=1, c=c1), B(id=2, c=c2), B(id=3, c=c1), B(id=4)]))
s.commit()

a1 = s.query(A).first()

assert a1.bs[0].id == 1
assert a1.bs[1].id == 2

```


SQL SELECT output at the end illustrates the different styles of LIMIT / OFFSET:

```
SELECT a.id AS a_id, a.data AS a_data 
FROM a 
 LIMIT %(param_1)s
2020-06-27 10:44:32,473 INFO sqlalchemy.engine.base.Engine {'param_1': 1}
2020-06-27 10:44:32,483 INFO sqlalchemy.engine.base.Engine SELECT b.id AS b_id, b.a_id AS b_a_id, b.c_id AS b_c_id, b.data AS b_data, c_1.id AS c_1_id 
FROM b LEFT OUTER JOIN c AS c_1 ON c_1.id = b.c_id 
WHERE %(param_1)s = b.a_id ORDER BY b.id 
 LIMIT %(param_2)s
2020-06-27 10:44:32,483 INFO sqlalchemy.engine.base.Engine {'param_1': 1, 'param_2': 1}
2020-06-27 10:44:32,490 INFO sqlalchemy.engine.base.Engine SELECT b.id AS b_id, b.a_id AS b_a_id, b.c_id AS b_c_id, b.data AS b_data, c_1.id AS c_1_id 
FROM b LEFT OUTER JOIN c AS c_1 ON c_1.id = b.c_id 
WHERE %(param_1)s = b.a_id ORDER BY b.id 
 LIMIT %(param_2)s OFFSET %(param_3)s
2020-06-27 10:44:32,491 INFO sqlalchemy.engine.base.Engine {'param_1': 1, 'param_2': 1, 'param_3': 1}

```

**Comment by jslay88** [comment]
Sorry, was a late night troubleshooting this.

It appears that this is the issue, and the `order_by` on the backref fixes the problem.

Thanks for such a quick and effective response.
