### ISSUE TITLE
Confusing points in the documentation v1.4

### ISSUE THREAD

**Issue by aplatkouski** [sqlalchemy/sqlalchemy#5428]
This issue contains the remaining unanswered questions from PR #5371

### Question 1.
https://github.com/sqlalchemy/sqlalchemy/blob/5f5b56d646f154ee572c9de80449423304103bad/lib/sqlalchemy/sql/selectable.py#L4042-L4043
Is the description of this parameter correct now?

**Pay attention for**: The ``c`` collection of the resulting ``Select`` object will use ...

**By fact** that in v.1.4 a select() object no longer has a ``.c`` attribute (see #4617 )

### Question 2.

Are the following three excerpts from the documentation and docstrings correct?

**Prerequisite:** Changed in version 1.4: the SessionTransaction **is not created immediately** within a Session when constructed or when the previous transaction is removed

#### Quote 2.1

https://github.com/sqlalchemy/sqlalchemy/blob/5624430eb1d07c68d0931bc89f7146bc003fde19/lib/sqlalchemy/orm/session.py#L1250-L1252

#### Quote 2.2

https://github.com/sqlalchemy/sqlalchemy/blob/5624430eb1d07c68d0931bc89f7146bc003fde19/lib/sqlalchemy/orm/session.py#L3377-L3380

#### Quote 2.3

[orm/session_basics.rst](https://github.com/sqlalchemy/sqlalchemy/blob/master/doc/build/orm/session_basics.rst#committing)
> Note that the default behavior of the :class:`~sqlalchemy.orm.session.Session` is **that a "transaction" is always present**; this behavior can be disabled by setting autocommit=True

### Question 3.

Is there a contradiction in the following excerpt?

**Prerequisite:** This documentation for v.1.4 and 
https://github.com/sqlalchemy/sqlalchemy/blob/5624430eb1d07c68d0931bc89f7146bc003fde19/lib/sqlalchemy/orm/relationships.py#L227-L229

#### 3.1 but see quote
[orm/extensions/declarative/relationships.rst](https://github.com/sqlalchemy/sqlalchemy/blob/master/doc/build/orm/extensions/declarative/relationships.rst#evaluation-of-relationship-arguments)
>  **evaluated as Python expressions using Python's built-in eval() function.**

### Question 4.

Is there a contradiction in the following excerpt?

**Prerequisite:** [changelog/migration_10.html#bug-3288](https://docs.sqlalchemy.org/en/14/changelog/migration_10.html#bug-3288)
> Python-side defaults invoked **for each row** individually when using a multivalued insert

#### 4.1 but see quote
https://github.com/sqlalchemy/sqlalchemy/blob/5624430eb1d07c68d0931bc89f7146bc003fde19/lib/sqlalchemy/sql/dml.py#L909-L911

### Question 5.

Is the correct description in the excerpt below?

see parameters of method:
https://github.com/sqlalchemy/sqlalchemy/blob/5624430eb1d07c68d0931bc89f7146bc003fde19/lib/sqlalchemy/engine/reflection.py#L243

#### 5.1 and docstrings:
https://github.com/sqlalchemy/sqlalchemy/blob/5624430eb1d07c68d0931bc89f7146bc003fde19/lib/sqlalchemy/engine/reflection.py#L258-L261

### Question 6.

**Prerequisite:** [changelog/migration_07.rst](https://github.com/sqlalchemy/sqlalchemy/blob/master/doc/build/changelog/migration_07.rst)
> ``DDLElement.execute_at`` method are deprecated and now implemented in terms of the
new system

#### 6.1 Quote
https://github.com/sqlalchemy/sqlalchemy/blob/5624430eb1d07c68d0931bc89f7146bc003fde19/lib/sqlalchemy/sql/ddl.py#L98-L99

**Comment by CaselIT** [comment]
> P.S. There were six questions in PR #5371 (question 4 - 9) describing the contradiction in the documentation, but unfortunately they disappeared from PR, and I don't know how to restore my comments.

I think they where under "load more items"

Here are the links.
- 4 https://github.com/sqlalchemy/sqlalchemy/pull/5371#discussion_r438355832
- 5 https://github.com/sqlalchemy/sqlalchemy/pull/5371#issuecomment-645037497
- 6 https://github.com/sqlalchemy/sqlalchemy/pull/5371#issuecomment-645044634
- 7 https://github.com/sqlalchemy/sqlalchemy/pull/5371#issuecomment-645048631
- 8 https://github.com/sqlalchemy/sqlalchemy/pull/5371#issuecomment-645051397
- 9 https://github.com/sqlalchemy/sqlalchemy/pull/5371#issuecomment-645054966

If you could edit them in the opening post of this issue instead of opening a new one for each, it would be great

**Comment by aplatkouski** [comment]
@CaselIT That's all.

P.S. Thank you for your time.

**Comment by zzzeek** [comment]
does this still need to be open?

**Comment by aplatkouski** [comment]
This issue contains a list of inconsistencies in the documentation. Where a statement in one place is not consistent with a statement elsewhere.

Code inserts (see above) into the issue are still relevant. I suppose that the issue is also actual.

Unfortunately, right now I don't have the opportunity to dive into the source code of the project in order to understand where the error is in the documentation, and whether there is a contradiction at all.

The final decision is at your discretion.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Repair documentation issues** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2220

**Comment by zzzeek** [comment]
@aplatkouski  you have an incredible organizational ability to see these, thanks very much for noting !  they are extremely difficult to pick up especially when you are the writer of the documentation.

I've fixed two issues still outstanding in the gerrit linked in the previous comment.  For the remainder:

1: fixed here

2.1 fixed in 96dba1a9f4

2.2 fixed in 5de0f1cf50

2.3 fixed in 5de0f1cf50

3.   the doc in question states " For most of these arguments except that of the main argument, these strings are evaluated as Python expressions using Python's built-in eval() function.".   the "main argument" refers to the "argument" parameter and is excluded from eval().  the change in question here occurred at 17e31604ae13ebd58b14 for #5238.   The documentation for declarative is being further reworked for 1.4 in https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2202 , the paragraph is at https://gerrit.sqlalchemy.org/plugins/gitiles/sqlalchemy/sqlalchemy/+/refs/changes/02/2202/23/doc/build/orm/basic_relationships.rst#485 with similar wording but it seems clear to me when read in context.

4. These two documents are not in conflict as the changelog refers to the multi-valued version of insert.values(), whereas the dml.py document refers to the insert.from_select() method.  in the former case, a list of values each correponding to a unique row is passed explicitly.  in the latter case, only a single set of parameters is passed from the Python side and the production of the set of rows is done server side as the result of a select.

5. the parameter was removed in 00b5c10846 however the paramref for order_by wasn't removed at that time.  @caselit removed the erroneous paramref in 8dcf876fe9a06f3360b8d2604 as a one-off in a larger change.

6. this looks to be referring to a whole feature that is still present within the ``.against()`` method and is tested in test/engine/test_ddlevents.py, but does not seem to be in the current narrative documentation (doc/build/core/ddl.rst).   the documentation for DDL() still refers to the general idea of what this argument is for but not in great detail.  added more detail to the against() method and similar, however ideally the narrative doucmentation would be expanded as well.

the above gerrit should close this all out, again thanks very much!
