### ISSUE TITLE
joinedload not working with a non "fresh" session?

### ISSUE THREAD

**Issue by davidgu** [sqlalchemy/sqlalchemy#5491]
I have a function which runs several queries with a single session object, with the following "pseudocode".
```
session1 = Session()
objects_1 = session1.query(Object1).filter(...).all()
objects_2 = session1.query(Object2).filter(Object2.id.between(A, B)).all()
session1.close()

session2 = Session()
objects_3 = session2.query(Object3).options(joinedload(Object4.field).joinedload(Object5.field).joinedload(Object6.field)).get(id)
session2.close()
```
There is no data written to the db though this session at any point. The 3rd query is quite complex, and has unacceptable performance without the `joinedload` as otherwise hundreds of queries would be required to load related rows.

If I do not create the second `Session` object `session2`, the `joinedload` seemingly does not work since the profiler reports hundreds of cursor.execute calls, and performance is very bad. Am I misunderstanding some aspect of how the `Session` is supposed to be used, and it's associated performance characteristics?

Sorry for not being able to attach a reproducible example.

**Comment by zzzeek** [comment]
this depends a lot on the specifics of what is being loaded in session1, which from the above example doesn't indicate what the problem might be since Object1/Object2 are not the same class as Object3 / Object4, so I assume that you are dealing with objects of the same types in the two separate sessions.

eager loading won't take place for objects that are already loaded basically, but for any unloaded collections it should still be populating them, so I can't exactly work out what your issue is without an MCVE.   However, to force a query to unconditionally populate everything you can use query.populate_existing(), and that should erase any unwanted side effects of objects that are already loaded.

**Comment by zzzeek** [comment]
please open if additional details
