### ISSUE TITLE
sqlite misuse of aggregate error after upgrade to python 3.8.4

### ISSUE THREAD

**Issue by olinger** [sqlalchemy/sqlalchemy#5495]
**Describe the bug**
I am seeing the following error in code that has not changed after upgrading python from 3.8.2 to 3.8.4 (it also happens in 3.8.3). I have downgraded back to 3.8.2 and confirmed there is no error when running in python 3.8.2.
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) misuse of aggregate: sum()
```
The error is happening in a unit test. My unit tests are using a sqlite database. The project itself is using a mysql database. There is no issue with the query in question in python 3.8.4 when running the app itself, the query executes and the results are the expected one. The error only occurs in the unit test which is using sqlite.

**Expected behavior**
No error

**To Reproduce**

The query that is causing it:
```py
meta_query = PatientBill.query.with_entities(func.sum(PatientBill.subtotal).label("subtotal"))\
.filter(*query_adapter.filters).first()
```

The property in question on the PatientBill model:
```py
subtotal = column_property(select([func.sum(PatientBillLineItem.subtotal)]).\
                            where(PatientBillLineItem.patient_bill_id == id).\
                            correlate_except(PatientBillLineItem))
```
The property referenced by the above column_property on the PatientBillLineItem model:
```py
subtotal = column_property(func.round(adjusted_price * quantity, 2))
```
**Error**

```
test_get_all: test_get_all
Fail: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) misuse of aggregate: sum()pytest(./app/test/services/test_patient_bill_service.py::test_get_all)
test_patient_bill_service.py(19, 5): test_get_all
base.py(1245, 21): self.dialect.do_execute(
default.py(588, 9): cursor.execute(statement, parameters)
test_patient_bill_service.py(35, 9): results: List[PatientBill] = PatientBillService.get_all_patient_bills(query_adapter)
patient_bill_service.py(49, 9): meta_query = PatientBill.query.with_entities(func.sum(PatientBill.subtotal).label("subtotal"))\
query.py(3287, 13): ret = list(self[0:1])
query.py(3065, 17): return list(res)
query.py(3389, 9): return self._execute_and_instances(context)
query.py(3414, 9): result = conn.execute(querycontext.statement, self._params)
base.py(982, 13): return meth(self, multiparams, params)
elements.py(293, 13): return connection._execute_clauseelement(self, multiparams, params)
base.py(1095, 9): ret = self._execute_context(
base.py(1249, 13): self._handle_dbapi_exception(
base.py(1476, 17): util.raise_from_cause(sqlalchemy_exception, exc_info)
compat.py(398, 5): reraise(type(exception), exception, tb=exc_tb, cause=cause)
compat.py(152, 13): raise value.with_traceback(tb)
base.py(1245, 21): self.dialect.do_execute(
default.py(588, 9): cursor.execute(statement, parameters)

```

**Versions.**
 - OS: macOS 10.14.6
 - Python: 3.8.4 (no error in 3.8.2)
 - SQLAlchemy: 1.3.13
 - Database: sqlite / mysql

**Comment by zzzeek** [comment]
hi there -

im not familiar with a specific change in SQLite but I would assume you have a query with non-aggregated columns in it and there is no GROUP BY.  can you please paste the SQL statement being rendered?   note that SQLite versions themselves move up as you move to new Python versions since they embed SQLite itself.

**Comment by olinger** [comment]
This is the query
```
SELECT sum((SELECT sum(round((patient_bill_line_item.price - patient_bill_line_item.price * patient_bill_line_item.discount) * patient_bill_line_item.quantity, :round_1)) AS sum_1 
FROM patient_bill_line_item, patient_bill 
WHERE patient_bill_line_item.patient_bill_id = patient_bill.id)) AS subtotal
```

**Comment by zzzeek** [comment]
so that is doing a sum() of a single element which is itself a sum(), so that outer sum() is unnecessary.  it's an awkward query that I would seek to improve so that it only asks for sum() once.

if the issue is, "why does the query render two sum()s like that", I don't really know I would need an [MCVE](http://stackoverflow.com/help/mcve), the fragments of code you've illustrated only show "sum()" running once.   Overall though the use of Flask's "Model.query" thing leads to this kind of problem since the columns clause gets set to one thing, then another, and it's not clear. I'd use standalone select() to more accurately deliver the specific SQL query you want.

**Comment by olinger** [comment]
Ok I will give that a try. And you are likely right that it is the SQLite version itself that broke this, but hopefully reworking the query will resolve that.

**Comment by zzzeek** [comment]
ok reopen if needed.
