### ISSUE TITLE
Connection pool rollback()s obscuring pg_stat_database metrics

### ISSUE THREAD

**Issue by pearsonhenri** [sqlalchemy/sqlalchemy#5519]
I'm trying to keep a closer eye on some of the performance metrics for our production Postgres instance, and I was somewhat alarmed when I took a look at the `pg_stat_database` numbers (particularly the `xact_rollback` count). Dug into it a bit, and it appears that this is largely due to [connection release behavior](https://docs.sqlalchemy.org/en/13/core/connections.html):
> When the connection is returned to the pool for re-use, the pooling mechanism issues a rollback() call on the DBAPI connection so that any transactional state or locks are removed, and the connection is ready for its next use.

I suppose I understand the motive for this behavior (get the connection in a "clean" transactional state), but I don't really see that benefit outweighing the obfuscation of these meaningful database states. We have millions of aborted transactions, and it's very hard to find signal through the noise. Possibly we could avoid this problem by creating the connection with `autocommit=True`, but I don't exactly want that either. Is there something that I'm doing wrong here, or is there no way to have my cake and eat it too with SQLAlchemy and Postgres?

Thank you!

**Comment by CaselIT** [comment]
Hi, I believe you can take a loot at [`reset_on_return`](https://docs.sqlalchemy.org/en/13/core/pooling.html#sqlalchemy.pool.Pool.params.reset_on_return) to see if it suit your case

**Comment by pearsonhenri** [comment]
Wow, thank you so much for the quick response! Yup, that looks like it would solve the problem I'm worrying about, but I'm a little concerned about deviating from what seems very much to be the recommended path (calling `rollback()`). Is a high `xact_rollback` number simply expected behavior for Postgres + SQLAlchemy?

**Comment by zzzeek** [comment]
in theory, connection.rollback() should do nothing if no SQL was emitted on the connection.

therefore if you are seeing these rollbacks as doing something, that means you have state on the connection which could include things like row locks or table locks.

It's a necessary element of connection pooling that ROLLBACK, or something comparable in its effect, is emitted for a connection that has had some SQL emitted on it, yet is to be restored to a connection pool to be used again.  

pgbouncer appears to use DISCARD ALL or DEALLOCATE ALL: https://www.pgbouncer.org/config.html .   However per pep-249 a DBAPI connection must always start a transaction unless DBAPI-level autocommit is used.  So I'm not sure if DISCARD/DEALLOCATE  accomplish the right thing if a transaction was begun.

indeed I think your only options here would be to 1. not use connection pooling, use NullPool or 2. use DBAPI-level autocommit: https://docs.sqlalchemy.org/en/13/core/connections.html#setting-transaction-isolation-levels-including-dbapi-autocommit

**Comment by pearsonhenri** [comment]
Ah, well here's what's a bit tricky @zzzeek: we already _are_ using NullPool for our engine. And there may be some pending locks, but even just reading a table [puts an `ACCESS SHARE` lock on the table until the transaction completes](https://www.postgresql.org/docs/current/explicit-locking.html). But I guess what I'm most curious about is: Is a high xact_rollback number simply expected behavior for Postgres + SQLAlchemy? (It seems like it is if you use the default settings?)

**Comment by zzzeek** [comment]
if you're using NullPool then turn rollback_on_return off and you won't see any extraneous ROLLBACK activity.  I have no idea what a high xact_rollback number would be.

**Comment by jvanasco** [comment]
> But I guess what I'm most curious about is: Is a high xact_rollback number simply expected behavior for Postgres + SQLAlchemy?

Yes, but it's really the expected behavior for connection pooling and postgresql in general.

I think the big problem is that you're expecting to use the `xact_rollback` statistic to measure application health.  That can be tough and misleading, because the Postgres stats are pretty limited and only do `commit vs rollback`; they don't differentiate when a rollback was consequential (i.e. were there any insert/updates) or just because of a transactional lock.

We use `statsd` for this type of application monitoring (it is pretty legacy at this point, not sure what else is newer) and log database connections/checkouts, commits and rollbacks at the application level so they can be differentiated.  This approach lets the rollbacks trigger an "event" , which could be a generic or specific error, or "non-consequential" checkins.

We also use autocommit with postgres in two different scenarios:

* there are some "logging" autocommit connections; we use events in statsd to log when the connections have written
* there were some "read only" autocommit connections to replica nodes; the db user does not have write access and the application logic is designed to keep these from having locks.  these were eventually dropped to not use autocommit, because it was too messy to maintain and there was no noticeable overhead difference.

IMHO everything with Postgres is designed to be transactional. Postgres doesn't even have an actual "read uncommitted" isolation level, it just implements it by doing a "read committed" .  Rolling back when you do nothing is fairly standard, within SqlAlchemy or elsewhere.

**Comment by pearsonhenri** [comment]
@jvanasco wow, thank you for the thorough and thoughtful response! That makes a lot of sense. Indeed this does seem to be expected and documented behavior, inferring from this SQLAlchemy FAQ: https://docs.sqlalchemy.org/en/13/faq/connections.html#why-does-sqlalchemy-issue-so-many-rollbacks, and your explanation provides some very helpful context as well. Strangely, there are quite a bit of "Monitoring your Postgres instance" blog posts out there that mention you should keep an eye on this stat, but none mention that it may be completely normal and expected behavior given your application's connection manager 🤦 

Well, really appreciate the help and explanations from the various folks on this thread! Hopefully some other folks on the internet come across your guys' answers and spare themselves the unnecessary anxiety 🙃 Thanks!
