### ISSUE TITLE
Select Fetch first support with WITH TIES and PERCENT statements for supported dialect

### ISSUE THREAD

**Issue by jelther** [sqlalchemy/sqlalchemy#5576]
**Is your feature request related to a problem? Please describe.**
Can't use the WITH TIES and PERCENT statments when applying TOP (.limit()) to queries.

**Describe the solution you'd like**
Extra arguments to .limit() statement is enough.

**Describe alternatives you've considered**
.with_prefix() is for now how I've been applying these different operators.

**Additional context**
Here's the link to the documentation related to these extra statements on TOP.
[TOP T-SQL](https://docs.microsoft.com/en-us/sql/t-sql/queries/top-transact-sql?view=sql-server-ver15)
**Have a nice day!**

Edit by @CaselIT 

Support matrix

| db         | supported | fist/next | percent | only | with ties | extra | link |
|------------|-----------|-----------|---------|------|-----------|-------|-------|
| postgres   | yes 8.4+  | yes       | no      | yes  | yes(13+)  | -     | https://www.postgresql.org/docs/13/sql-select.html#SQL-LIMIT |
| oracle     | yes 12c+  | yes       | yes     | yes  | yes       | -     | https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6 |
| mssql (top)| yes (top) | -         | yes     | -    | yes       | uses top | https://docs.microsoft.com/en-US/sql/t-sql/queries/top-transact-sql |
| mssql (fetch)|yes 2012+| yes       | ?       | yes  | no        | require order by and offset |https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql|
| mysql      | no        |           |         |      |           |       |  |
| mariadb    | no        |           |         |      |           |       |  |
| sqlite     | no        |           |         |      |           |       |  |

**Comment by zzzeek** [comment]
hi there -

these are SQL Server -specific constructs, is that correct?

that's generally the purpose of with_prefix().   

I guess this can accept a custom SQL construct, which we can add as something you'd import from SQL Server.   Here's how to do it on your end:
```

from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import literal
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.dialects import mssql
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import ColumnElement

class SSLimit(ColumnElement):
    def __init__(self, expr, percent=False, with_ties=False):
        self.expr = literal(expr)
        self.percent = percent
        self.with_ties = with_ties


@compiles(SSLimit)
def _compile(element, compiler, **kw):
    text = "TOP (%s)" % compiler.process(element.expr, **kw)
    if element.percent:
        text += " PERCENT"
    if element.with_ties:
        text += " WITH TIES"
    return text


Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)

s1 = select([A]).prefix_with(SSLimit(10, percent=True)).order_by(A.id)
print(s1.compile(dialect=mssql.dialect()))
```

for direct modication of limit() we would have to support dialect-specific flags in the method, it would also have to check that there's no offset() present, etc.      It would be more straightforward for us to implement a construct like the above, but allow limit() to accept it so that it can be received by the SQL server dialect:

```
from sqlalchemy.dialects.mssql import top
stmt = select([A]).order_by(A.id).limit(top(10, percent=True))

```

There's a way to make that work right now a little bit but you'd need to use some private-ish API.

**Comment by jelther** [comment]
Great!

Guess that will works for now. 

```
from sqlalchemy.dialects.mssql import top
stmt = select([A]).order_by(A.id).limit(top(10, percent=True,withties=True))
```

Maybe adding the "withties" flah to the top construct will make it more complete.

**Comment by squeaky-pl** [comment]
> these are SQL Server -specific constructs, is that correct?

WITH TIES is also supported in PostgreSQL these days: https://www.2ndquadrant.com/en/blog/postgresql-13-limit-with-ties/

**Comment by zzzeek** [comment]
OK if WITH TIES is part of the standard then we add a "with_ties" keyword argument to limit().   how about PERCENT ?    I can look in my sql standard docs later

**Comment by zzzeek** [comment]
it claims it is sql 2008 standard.it's this: https://www.postgresql.org/docs/13/sql-select.html#SQL-LIMIT   

based on their docs it appears this clause entirely replaces LIMIT/OFFSET with FETCH and more formal syntax.     it seems like we would want to make this explicit, e.g. instead of adding to select.limit()/offset() there would be a new method select.fetch(), that accepts all the arguments here and means the user wants to work with a SQL FETCH clause.   This could be implemented in the base compiler and by default be totally separate from the implementation of limit()/offset().      compiler can have a visit_fetch_clause() method that works entirely with FetchClause(), an object that is generated internally when select.fetch() is called.

the reason I would have fetch() as a new construct is that a database like PG supports either / or syntax separately, which indicates giving users a choice which syntax they want to use, and also that the FETCH clause is more formal about how OFFSET is applied as well as ORDER BY; this all indicates a single method that accepts the "count" and "offset start" as well as all other keywords at once.    Since it's supported by the standard we can implement it exactly, in contrast to limit()/offset() which are not standard (i think?) and we tend to have to do whatever we have to in order to support them on various databases.

Basically, limit()/offset() will continue to mean, "do whatever you have to in order to limit/offset the rows", which includes all kinds of hacky things like rendering "TOP n ROWS" as well as rendering whole window function /subqueries in some terrible cases, and fetch() would mean, "use this very specific SQL standard construct".

for SQL Server, we've already implemented FETCH as the implementation for limit()/offset(), so SQL Server's compiler would implement visit_fetch_clause().  Within its existing limit_clause() method, for those cases where it begins to render FETCH, it would generate a FetchClause() object based on the limit/offset and then defer to its visit_fetch_clause() method.

summary:

1. add select.fetch() method, with arguments "count", "start", "with_ties=False|True", and *maybe* we can put "percent" here also, or perhaps "mssql_percent".

2. when select.fetch() is called, a FetchClause() construct is stored.  this is mutually exclusive from the existing internal _OffsetLimitParam that is used for select._limit_clause select._offset_clause which are more ad-hoc and informal

3. the compiler adds a visit_fetch_clause() step to the select() compilation scheme.   PostgreSQL then works by default

4. SQL Server dialect internally uses visit_fetch_clause in its existing routine for limit_clause().

5. ORM "_should_nest_selectable" also needs to include "fetch_clause" in its list of elements that suggest a row-limited query.

**Comment by zzzeek** [comment]
oh, issue.   SQL Server 2012 supports "fetch first" but the "WITH TIES" option is *only* in the more legacy "TOP" keyword ?!    this seems awkward, but we'd have to make that work also.   we should do some experimentation with this.

**Comment by zzzeek** [comment]
Oracle 12c supports FETCH with PERCENT.    two dbs doing the same keyword means we can add it.

**Comment by zzzeek** [comment]
I think we need to build up a feature matrix on this so that we get it right.  cc @jvanasco @CaselIT @gordthompson

**Comment by zzzeek** [comment]
SQL Server has the whole doc section for the "FETCH" clause, but WITH TIES they only support under TOP:  https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-ver15   facepalm

nevertheless we should implement this as select.fetch() and SQL Server dialect will continue hacking and guessing like it always does.    if SQL Server encoutners FetchClause() with "with_ties=True", then it moves it to TOP.  if the clause includes offset, it raises an error.

**Comment by CaselIT** [comment]
offset seems to be optional, at least on postgres. If that is indeed optional in all db, I guess fetch would be similar to limit in that it only controls how many rows are returned.

Also we can add db2 to the list of db that support this feature

**Comment by CaselIT** [comment]
Also maybe this is more of a 1.4.x. Nice to have for 1.4, but I think it's ok if we add it later

**Comment by zzzeek** [comment]
yes but not *too* late , we have added FETCH to SQL Server dialect in 1.4 already, and here we are seeing it's not quite right, perhaps.

**Comment by CaselIT** [comment]
> 
> 
> yes but not _too_ late , we have added FETCH to SQL Server dialect in 1.4 already, and here we are seeing it's not quite right, perhaps.

oh, I did not notice it. They yes, if possible we should unify it in a common api.

**Comment by CaselIT** [comment]
Looking at this https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#fetch-first-clause seems that percent is also in the sql standard

```
<result offset clause> ::=
  OFFSET <offset row count>  { ROW | ROWS }

<fetch first clause> ::=
  FETCH { FIRST | NEXT } [ <fetch first quantity>  ] { ROW | ROWS } { ONLY | WITH TIES }

<fetch first quantity> ::=
    <fetch first row count> 
  | <fetch first percentage> 

<offset row count> ::=
  <simple value specification> 

<fetch first row count> ::=
  <simple value specification> 

<fetch first percentage> ::=
  <simple value specification>  PERCENT

```

**Comment by zzzeek** [comment]
great.  at the moment, the only ugly thing is that SQL Server pushes those up to the TOP clause when meanwhile it has the SQL standard clause, they just broke it like that, I have no idea what people at these companies are thinking

**Comment by CaselIT** [comment]
support matrix

| db         | supported | fist/next | percent | only | with ties | extra | link |
|------------|-----------|-----------|---------|------|-----------|-------|-------|
| postgres   | yes 8.4+  | yes       | no      | yes  | yes(13+)  | -     | https://www.postgresql.org/docs/13/sql-select.html#SQL-LIMIT |
| oracle     | yes 12c+  | yes       | yes     | yes  | yes       | -     | https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6 |
| mssql (top)| yes (top) | -         | yes     | -    | yes       | uses top | https://docs.microsoft.com/en-US/sql/t-sql/queries/top-transact-sql |
| mssql (fetch)|yes 2012+| yes       | ?       | yes  | no        | require offset | seems not to be in the docs |
| mysql      | no        |           |         |      |           |       |  |
| mariadb    | no        |           |         |      |           |       |  |
| sqlite     | no        |           |         |      |           |       |  |

db2 also supports it.

Regarding mssql I think we don't implement fetch, but use top, since it does the same thing and has no downsides (I think. Can you use offset with top?)
Fwiw I think mssql has top since forever, so it's not like they added it after the fetch was standardized.

**Comment by CaselIT** [comment]
@jelther I've takend the liberty of coping the support matrix also in the top comment

**Comment by zzzeek** [comment]
ceratinly the whole reason this issue was opened was they wanted TIES and PERCENT on TOP, so yes we do that.  but IMO it has to be via select.fetch() which will mirror the SQL standard

**Comment by CaselIT** [comment]
Yes indeed.

the implementation seem to be all standard, other than mssql. So I think the default compiler will render the sql standard. If a db does not support something it will raise an error. Like pg with percent and with ties.

fetch syntax would be `fetch(value, percent=False, with_ties=False)`

**Comment by CaselIT** [comment]
@zzzeek I think only select should support this, not query.

Should we raise if limit is already set?

**Comment by zzzeek** [comment]
> @zzzeek I think only select should support this, not query.

absolutely, Query is frozen.

> 
> Should we raise if limit is already set?

or offset(), yes.  raise in the compiler

**Comment by CaselIT** [comment]
I think may offset stays at it is. It seems to work as currently. One could use just fetch to render the clause without offset

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Fetch first support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2276
