### ISSUE TITLE
Mysql5.7 gets invalid syntax of `.with_for_update(skip_locked=True)`

### ISSUE THREAD

**Issue by ashb** [sqlalchemy/sqlalchemy#5578]
#5290 added support for "SELECT ... FOR UPDATE SKIP LOCKED" to Mysql 8+, but due to a bug it still generates this construct on mysql 5.x.

There was a "supports" check added for `of=Model`, but it was incorrect when adding SKIP LOCKED.

Something like this would be a quick fix, but maybe i'ts better to not reuse the "supports_for_update_of" variable? Or to rename that?

```diff

-        if select._for_update_arg.skip_locked and self.dialect._is_mysql:
+        if select._for_update_arg.skip_locked and self.dialect.supports_for_update_of:
            tmp += " SKIP LOCKED"
```

**Comment by gordthompson** [comment]
There are already a number of cases where SQLA does not check for a specific backend version when implementing a new(er) feature. If a user is hitting a MySQL 5.x server and using a MySQL 8.x construct then the 5.x server will complain and the user will know to modify their code accordingly.

MySQL/MariaDB is a bit of a special case because so far they have both been handled by the `mssql` dialect. There have been a few features that have only been implemented on the one platform (MySQL or MariaDB) *as a whole*, so there were some instances where the core SQLA code needed to differentiate between the two, hence the notion of `self.dialect._is_mysql`.

There are also many cases where *test code* needs specific version information about the server it is hitting in order for backend tests to skip, expect failures, or expect warnings. However, (IMO) the core code should generally not spend a whole lot of effort trying to accommodate the peculiarities of any specific version of a backend, especially when the backend will provide a meaningful error to the user if they try to something that is not supported under that particular version.

One enhancement I *would* support for this issue would be to emit a warning for MariaDB instead of just silently ignoring the `.skip_locked` argument.

**Comment by zzzeek** [comment]
we do have some MySQL level supports flags for this section don't we ?   For the FOR UPDATE stuff we can pick and choose some of these flags based on version detection. it's just a wholesale SQL structure like a CTE where we have no reasonable fallback, we just let those raise.

**Comment by ashb** [comment]
> we do have some MySQL level supports flags for this section don't we ?   For the FOR UPDATE stuff we can pick and choose some of these flags based on version detection. it's just a wholesale SQL structure like a CTE where we have no reasonable fallback, we just let those raise.

Correct - and the `with_for_update(of=Model)` already has such a check and doesn't output of not supported.

**Comment by gordthompson** [comment]
> we do have some MySQL level supports flags for this section don't we ? 

At the base dialect level, yes, there are a couple of them defined starting here …

https://github.com/sqlalchemy/sqlalchemy/blob/645be4aa24a06241dfeb635aee8ca7a09574d800/lib/sqlalchemy/dialects/mysql/base.py#L2792

… but it becomes a question of how far down that road we want to go, especially if MariaDB strays (even further?) from its historical objective of being a "drop-in replacement for MySQL" and we get features that may be specific to different versions, or may-or-may-not be supported at all. Certainly, as I mentioned earlier, if we silently ignore a feature just because it is not supported for a given backend version, then IMO we're doing a disservice to the user.

**Comment by zzzeek** [comment]
it depends on if "SKIP LOCKED" represents an improved behavior from which can be safely degraded, or if it's a totally different behavior than not including it.  it sounds like @ashb is looking for a graceful degrade path here.  reading what it is at https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html#innodb-locking-reads-nowait-skip-locked it's not clear this is a graceful degrade if it's not available.   it literally means, dont block if some rows are locked.  if you put that flag in there you expect it to not block, then on mysql 5.7 it would.   

how exactly do you wish to use skip_locked but then also have your application work as expected on mysql 5.7 ?  it will block in places that it does not expect to.

**Comment by gordthompson** [comment]
> it depends on if "SKIP LOCKED" represents an improved behavior from which can be safely degraded

That's a much more succinct way of describing the point I was trying to make. It's one thing to implement some `high_level_SQLA_feature` in a version-independent way (e.g., an "upsert" operation that "just works" with or without ON CONFLICT) vs. an explicit invocation of a specific backend feature. In the latter case I would prefer to take the approach that "you can ask, but the backend itself may say 'no' depending on what version it is".

**Comment by zzzeek** [comment]
right so given this feature does not appear to be a safe silent degrade and there is no equivalent, this issue is IMO not a bug.     as far as the "SQLAlchemy should raise an exception" critique, there's already an exception raised by the database and we generally want the database to do as much of the work as possible.

**Comment by gordthompson** [comment]
There's already an exception raised by MySQL 5.x, which is good, but I was looking to add a warning when we ignore the `skip_locked=True` attribute for MariaDB. Currently when hitting MariaDB

``` python
    qry = tbl.select().where(tbl.c.id == 1).with_for_update(skip_locked=True)
    conn.execute(qry)
```

renders

``` sql
SELECT t.id, t.txt 
FROM t 
WHERE t.id = ? FOR UPDATE
```

with no indication to the user that SKIP LOCKED was omitted,

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add warning for skip_locked with MariaDB backend.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2229

**Comment by ashb** [comment]
I'm okay with the policy being "if you ask for something invalid for your specific engine you get an SQL error" -- the thing that surprised me (and let me to open this issue) was that _some_ parts of this construct are allowed, but not all.

**Comment by zzzeek** [comment]
that philosophy is not really laid down in any specific document, and if it were, nobody would ever see it because people are usually just looking at the reference docs for the function they want to use, I think the best approach is to add notes to the docstring for this specific method that some of these features are not supported, and which ones will not have a graceful fallback.

**Comment by zzzeek** [comment]
OK it's too bad this was implemented in 1.3 as silent ignore for mariadb. assuming we agree "SKIP LOCKED" is not safe to degrade from.

**Comment by CaselIT** [comment]
> that philosophy is not really laid down in any specific document, and if it were, nobody would ever see it because people are usually just looking at the reference docs for the function they want to use, I think the best approach is to add notes to the docstring for this specific method that some of these features are not supported, and which ones will not have a graceful fallback.

Maybe it could be a change for v2? I mean codify when sqlalchemy should try and detect if a feature is supported by the backend and when it should assume it is and let the backend error if it's not.
Currently it depends on the feature and the dialect implementation.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Add warning for skip_locked with MariaDB backend.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2234

**Comment by zzzeek** [comment]
this is not a v2 thing, this is all a right now thing.   

1. all backends should be raising an error when a user behavioral intent that cannot be fulfilled is received by a dialect, so first off, the for_update_clause() in compiler.py should be looking at all of these for_update flags and raising, that is, this is wrong:

```
   def for_update_clause(self, select, **kw):
        return " FOR UPDATE"

```
if should be:

```
   def for_update_clause(self, select, **kw):
        if select._for_update_arg.read:
           raise exc.CompileError("read only for update is not supported by this backend")
       elif select._for_update_arg.of is not None:
           raise exc.CompileError("....")
      elif ... # etc.

     return " FOR UPDATE"
   
```

2. we should implement all of the above as warnings for 1.3, so that we have some degree of an option to turn them into hard exceptions in 1.4, but if they turn into execptions in 2.0, that's fine.  but we should be warning now, if we have the development resources to take this on.

3. the Compiler raises explicit compile errors for major SQL features that have no "default" implementation.   E.g. "RETURNING", the base "def returning_clause()" raises an error.   There's no "version detection" at this level, and the reason we don't let the database try to throw an error is because there is not even a SQL standard thing we can do here.

4. For major SQL features that are 100% the SQL standard, like CTEs, the base Compiler implements them and assumes they exist.   if the backend database doesnt support it, like MySQL, the database raises an error.

5. Now we're in the realm of "a specific database", like different versions of Postgresql, different variants of MySQL.  

5a.  in this realm, the per-dialect compilers should implement the supported SQL features for the latest and greatest version of that database.   

5b. For those SQL features that won't work on an older version, but an explicit fallback exists, the dialect / compiler should do the fallback.     The example of MySQL dialect using SELECT @@transaction_isolation for mysql > 5.7.20 but SELECT @@tx_isolation for other versions is sort of an example, this is a place where we need to know the server version and we need to test it against a specific number.     

5c. for those SQL features that wont work on an older version, but the average intent would be to omit the behavior on an older version and things should still be "fine", we do version detection.     This is an area that we should probably do **much less of** in favor of allowing for "variants".    Looking around I can see examples like we silently drop the "CONCURRENTLY" keyword when we create a PostgreSQL index that asked for "postgresql_concurrently",    the index still gets built but it will not allow concurrent activity on the table on an older version.

5d. for those SQL features that wont work on older version and they clearly indicate a behavior that is very different from what it would be without that feature, the dialect should as often as possible just render it out to the DB and let it fail.   If rendering it out to the DB causes a very confusing  / unclear error condition then *sometimes* we will use version detection, but we really should not in most cases.

5e. if the feature is more of a DBAPI level / Python side feature, then we usually have to do more with DBAPI version detection since when you use a Python API incorrectly it's not really distinguishable from a bug.

The philosophy is:  we really don't want to be chasing down server_version_info and hardcoding server version infos any more than we have to.   we do it a bunch but only as a last resort.

This can be documented right now if people want to work on it, it can be on the dialects page or on the "Engines" page.   the problem is we are not very consistent in many areas right now including this FOR UPDATE area.

**Comment by CaselIT** [comment]
Thanks for the great explanation mike. I've taken the liberty of creating a new issue to track this. See https://github.com/sqlalchemy/sqlalchemy/issues/5583

**Comment by ktinker-athos** [comment]
This problem also occurs for "NOWAIT" if using MySQL 5.7, as NOWAIT was added in 8.0.

.with_for_update(nowait=True) produces the following error:
Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NOWAIT' at line 4

For us it's an upgrade issue.  The same code in SQLAlchemy 1.3 works without issue, but breaks when we upgrade to SQLAlchemy 1.4.22.  I suspect it's not actually doing anything with nowait=True in 1.3.

**Comment by CaselIT** [comment]
It was decided https://github.com/sqlalchemy/sqlalchemy/commit/31c3ed715ad2e6007bf6b98ae7670cb1a902731c to avoid silently skipping rendering part of the query for 1.4.

I would suggesting adding a flag somewhere that enables it if the connected mysql supports it.
If you only use 5.7 when you can remove that call since it will have no effect in 1.3
