### ISSUE TITLE
how to use natural full join in sqlalchemy

### ISSUE THREAD

**Issue by WangWenQiang** [sqlalchemy/sqlalchemy#5590]
in postgresql:
`
select * from a.connection natural full join b.connection;
`

**Comment by zzzeek** [comment]
hi there -

it's not clear if you are working with existing Table / ORM metadata or not.

if you want to emit that SQL as written, you of course can just use the text() construct:

   conn.execute(text("select * from a.connection natural full join b.connection"))

However, you are likely working with an ORM model of some kind.   In this case all the join() methods accept a flag called "full":

    session.query(A).join(A.bs, full=True)

This will render the join from A to B using "FULL OUTER JOIN".  The NATURAL keyword is not necessary because SQLAlchemy will produce an explicit ON clause based on the foreign key configuration in the mappings.

hope this helps!
