### ISSUE TITLE
Update README to show number of Downloads (Total, monthly, weekly) 

### ISSUE THREAD

**Issue by rcadhikari** [sqlalchemy/sqlalchemy#5594]
**Is your feature request related to a problem? Please describe.**
No, but having status to show number of downloads in real-time would be helpful.

**Describe the solution you'd like**
just need to add below code on README file:
```
# Downloads
[![Downloads](https://pepy.tech/badge/sqlalchemy)](https://pepy.tech/project/sqlalchemy) [![Downloads](https://pepy.tech/badge/sqlalchemy/month)](https://pepy.tech/project/sqlalchemy/month) [![Downloads](https://pepy.tech/badge/sqlalchemy/week)](https://pepy.tech/project/sqlalchemy/week)
```

**Additional context**
Having such status always helps a developer to compare and rank the package.

**Have a nice day!**

**Preview/Demo here**
https://gist.github.com/rcadhikari/b8d3ee5f761e3f02ecadb6624d0a28a9

**Comment by CaselIT** [comment]
Hi,

The README is in rst, so I'm not sure if this would work.

**Comment by zzzeek** [comment]
im so-so on this, there are other badges like this too, is that style of badge just something a bunch of different "stats providers" are copying off each other ?     like what is "shields.io" vs. "pepy.tech".   im not necessarily comfortable handing third parties free github stats.

**Comment by gordthompson** [comment]
@CaselIT - I put a monthly downloads tag in README.rst for [sqlalchemy-access](https://github.com/gordthompson/sqlalchemy-access) mostly for my own interest. So, it does work from .rst but I mainly view it as a novelty.

@zzzeek - AFAIK, adding a shields.io "downloads" tag does not give anybody any GitHub stats, it just grabs the PyPI download count from pypistats.org, e.g.

https://pypistats.org/packages/sqlalchemy-access

(I know that because pypistats.org recently stopped working for a little while and the shields.io badge broke until pypistats.org got fixed.)

**Comment by zzzeek** [comment]
@gordthompson I was referring to the fact that when you put a badge like that on your github page, someone's web server gets stats on every IP number / browser agent that has visited that specific github project, in the same way that any other tracking link does.   that's valuable information to advertisers.   it's not a problem it just is something I try to be mindful of as to when commercial interests may be at play.

**Comment by zzzeek** [comment]
I went with shields.io.
