### ISSUE TITLE
(MANYTOONE + ONETOMANY) interpreted as (MANYTOONE+MANYTOONE) in Error Message

### ISSUE THREAD

**Issue by jvanasco** [sqlalchemy/sqlalchemy#5601]
Bug report:

Two tables are defined with reciprocal `sqlalchemy.orm.relationships` via `back_populates` and a composite primary_join (`primary_join="and_(a, b)"`).

The first relationship is defined with `uselist=True`, the second relationship is defined with  `uselist=False`.

However, the error message states:

    {RelationshipA} and back-reference {RelationshipB} are both of the same direction symbol('MANYTOONE').

The exception is generated in /orm/relationships.py under `RelationshipProperty._add_reverse_property` https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/relationships.py#L2073-L2082

It looks like a cause is in https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/relationships.py#L3253-L3254

The error message is generated not by the uselist declaration, but inspecting the columns

            # fk collection which suggests ONETOMANY.
            onetomany_fk = targetcols.intersection(self.foreign_key_columns)

For the purpose of raising informative exceptions, shouldn't `uselist` imply a ONETOMANY?

line 63 of the attached file has a `VERSION` variable which can be toggled to reproduce the different messages

[mappers_many.txt](https://github.com/sqlalchemy/sqlalchemy/files/5250431/mappers_many.txt)

**Comment by zzzeek** [comment]
so figuring out how to make it clear what's happening in the docs is the challenge here.

foreign(col) means that's the col that in the database would have FOREIGN KEY on it, it means it holds a value that is required to exist in a primary key or unique column elsewhere.

So it's not possible to have these twe conditions simultaneously, because they are contradicting:

```
     primaryjoin="and_("
                    "Order2ChallengeTypeSpecific.domain_id==foreign(Authorization.domain_id),"
                    "Order2ChallengeTypeSpecific.order_id==foreign(Authorization.order_id__created),"
                    ")",
    )
        primaryjoin="and_("
                    "Authorization.domain_id==foreign(Order2ChallengeTypeSpecific.domain_id),"
                    "Authorization.order_id__created==foreign(Order2ChallengeTypeSpecific.order_id),"
                    ")",

```

now you can have remote() set up that way, because remote() is more about what's happening on the Python side.   but foreign(X) == Y means, "Y is unique, is populated first, and X may only have a value that's present in Y".   that condition is global to X and Y in the database and has nothing to do with the Python classes.

uselist on the other hand is only to do with the Python classes, and could almost be handled by the "collection_class" parameter.   it means the "collection" on the Python side is a single value that replaces the previous value.   has nothing to do with one-to-many / many-to-one, and I think it's even possible to have "uselist=True" on the "one" side of a relationship, you'd have a list that has only one element in it :)  (it might not let you do this but there's no strong reason it could not, even though it's fairly useless).

since you describe "authorizations" as heading from "one" to "many", that would imply authorization domain_id/order_id_created is the unique key and order2challenge ec is the many side so youd want both primary join conditions to read:

```
        primaryjoin="and_("
                    "Authorization.domain_id==foreign(Order2ChallengeTypeSpecific.domain_id),"
                    "Authorization.order_id__created==foreign(Order2ChallengeTypeSpecific.order_id),"
                    ")",


```

**Comment by jvanasco** [comment]
@zzzeek 

First, thank you for everything above.  You saved me some time today in figuring out what I was doing wrong, and how to set things up properly. 

I have an idea for the docs, and will generate a PR for it.

I do think the ErrorMessage should be better though, I expected SqlAlchemy to see that I specified "uselist" and that it would tell me "You set this up all wrong".    This was my first attempt at writing that relationship, and I knew it was wrong - but the message wasn't particularly helpful.

**Comment by jvanasco** [comment]
@zzzeek I did a docs PR in gerrit (https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2249) using your text and an oversimplified example. 

I called this approach "Virtual Private Keys"

**Comment by zzzeek** [comment]
your PR is sort of in backlog but it's on the list :)   closing this for now.

**Comment by ManuelLang** [comment]
Having the sane issue

**Comment by jvanasco** [comment]
@ManuelLang have you resolved it yet? If not, feel free to share the code here or the mailing list and I will try to help.
