### ISSUE TITLE
use Table as a type hint.

### ISSUE THREAD

**Issue by Bezmehrabi** [sqlalchemy/sqlalchemy#5602]
How Can I use `sqlalchemy Table` created as a type hint like `ORM Class` in my python code?

something like that for example, where I can use `country` table as return type of `get_countries`(this code will throw an error):
```
import database

country = Table(
    "country",
    Base.metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String(255), unique=True),
    Column("calling_code", String(5), unique=True),
)

async def get_countries() -> country: 
        query = country.select()
        return await database.fetch_all(query)
```
**Versions**
 - Python: 3.8
 - SQLAlchemy: 1.3.19
 - Database: Postgresql

**Comment by CaselIT** [comment]
Hi,

When using tables directly to query the database the returned values are tuple-like object.
If you need the returned value to act like python object, you should probably consider to use orm.

**Comment by Bezmehrabi** [comment]
Hi, I'm actually using FastAPI and [encode/databases](https://github.com/encode/databases) for async queries so I need to create a query(like `country.select().where(country.c.name == 'blah')`) and then run it.

I can also instead of use `Table`, use `orm` and then access the table with `__table__`. so the query would be:
`Country.__table__.select().where(Country.name == "blah")`

is there any different in terms of performance?

**Comment by CaselIT** [comment]
I have no experience with fast api or encode/databases, sorry.
If the returned value from that query is the same result object that is used by sqlalchemy, that is this on https://docs.sqlalchemy.org/en/13/core/tutorial.html#coretutorial-selecting, then the returned values as tuple-like.
If it's something else then it would be out of the control of sqlalchemy.

Using the table from the orm is the same as not using the orm, since the `__table__` object is a `Table`.
What I meant by using the orm to obtain object is this https://docs.sqlalchemy.org/en/13/orm/tutorial.html

> is there any different in terms of performance?

Using the orm is slower, since objects need to be created from the returned tuples etc.

**Comment by Bezmehrabi** [comment]
thank you :+1:

**Comment by CaselIT** [comment]
You are welcome,
Feel free to reopen if you have further questions.

Just FYI, sqlalchemy 1.4 will support async, starting with postgress. The first beta should be out by the end of the year. https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html

**Comment by Bezmehrabi** [comment]
I was actually googling it to see when is the release time of 1.4 :), looking forward

**Comment by Bezmehrabi** [comment]
Hi, Our project will be launched in about 6 months from now. Is it affordable to create our models with **ORM** (synchronously) and make it asynchronous at the time when SQLAlchemy **1.4** is released or go with SQLAlchemy **core** (asynchronously) and then use SQLAlchemy’s asyncio over [encode/databases](https://github.com/encode/databases)  for asynchronous queries? Because right now it doesn’t matter if our project is asynchronous or not. Thank you so much :)

**Comment by CaselIT** [comment]
The ORM with 1.4 can also be used asynchronously. https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#synopsis-orm

I think 1.4 will be out with stable releases in 6 month, but I cannot make any promises regarding this.

I don't know what the best path for your project will be, since I don't knowyour project or encode/databases.
You can try 1.4 by installing it from the main branch and check if the async orm and the [improvements](https://docs.sqlalchemy.org/en/14/orm/mapping_styles.html) added in 1.4 will fit your project need.

**Comment by jvanasco** [comment]
> I can also instead of use `Table`, use `orm` and then access the table with `__table__`. so the query would be:
> `Country.__table__.select().where(Country.name == 'blah')`

I want to clarify something that @CaselIT said in regards to this: you basically answered yourself here. This is just using SqlAlchemy's ORM API to define your model, and then using the Core API to do the actual work.

The only real differences in declaring your model with ORM vs Core are:

* initial setup- one may be slightly faster than the other. but this is likely a difference of microseconds and only during startup.
* the extra dot from grabbing the `Country.__table__`, which is negligible and could be coded around. 

In terms of basing your application's usage on ORM vs Core, the biggest overhead you would most-likely experience in this use-case is the automatic Session/transaction management that ORM offers; the overhead in building objects from tuples is fairly negligible until you start doing bulk operations with thousands of objects.  

The two APIs are compatible though - you can use the Core API expression language within the context of the ORM (the ORM is essentially a convenience layer built on top of Core), and much of the ORM exposes elements that can be used by Core (such as the `.__table__`).

**Comment by Bezmehrabi** [comment]
Thank you so much guyz :), we decided to go with SQLAlchemy 1.4 ORM, and use Core for bulk insert and stuff like that. thank you :)

**Comment by CaselIT** [comment]
> 
> 
> Thank you so much guyz :), we decided to go with SQLAlchemy 1.4 ORM, and use Core for bulk insert and stuff like that. thank you :)

Nice to hear. Let us know if you have feedback
