### ISSUE TITLE
Documentation for single table inheritance with one foreign key linked to different relationships

### ISSUE THREAD

**Issue by Peter92** [sqlalchemy/sqlalchemy#5610]
My suggestion is add a small section to the [single table inheritance](https://docs.sqlalchemy.org/en/13/orm/inheritance.html#single-table-inheritance)  documentation that demonstrates what to do if mapping one foreign key to different relationships. I wasn't able to deduce it from the documentation, but I managed to find a [solution](https://stackoverflow.com/a/7111348/2403000) from stack overflow.

In my actual case, I have an `ActionLog` table with an `entity_id` column. I wanted to have a mapping to models such as `UserActionLog`, which will take `entity_id` and create a relationship to the `User` table.

In case it's not clear, here's a rough example of the code I was wanting:

```python
class ActionLog(Base):
    __tablename__ == 'ActionLog'
    id = Column(Integer, primary_key=True)
    entity_type = Column(String(32), nullable=False)
    entity_id = Column(Integer, nullable=False)

    __mapper_args__ = {
        'polymorphic_on': entity_type,
    }

class ActionUserLog(ActionLog):
    user = relationship(User, primaryjoin='User.id==ActionLog.entity_id', foreign_keys=ActionLog.entity_id)

    __mapper_args__ = {
        'polymorphic_identity': 'user'
    }
```

**Comment by zzzeek** [comment]
hey there -

I've looked at the SO question a bit and at the above example and I'm not really "getting" the thing that's not documented, other than, this combines two SQLAlchemy APIs at the same time.    The SO answer does not seem to be using single table inheritance, it's basically doing a configuration that's well documented at https://docs.sqlalchemy.org/en/13/orm/join_conditions.html#creating-custom-foreign-conditions . 

as for the single table inheritance part, yes, you can put relationships on subclasses, that is documented here: https://docs.sqlalchemy.org/en/13/orm/inheritance.html#relationships-with-single-table-inheritance .

There's also a huge amount of docs to read on our site and I might guess people already don't find some of these basic sections above because there's just so much up there already.     When we add a new section to the docs we usually have to come from a perspective of, "here's another common problem that lots of people will have, that we haven't shown at all how it might be solved".  if it doesn't reach that threshhold then it's hard to justify adding new doc sections instead of perhaps enhancing existing sections.

can you state the actual problem you were looking to solve more explicitly and let me know how the above two sections didn't accomplish this, that would help define what might be documented here if anything.  thanks!

**Comment by zzzeek** [comment]
cc @jvanasco who is working on some docs in this area.

**Comment by Peter92** [comment]
All the relationship info in the documentation was for if the foreign key is on the same subclass. In my case, I wanted one foreign key on the parent class, where each subclass implemented its own relationship using that key.

I totally get you don't want to overdo the documentation, but I feel in this case it's a cool feature that's unique to single table inheritance. It's obviously not a common use case, but it's definitely something I think that others could make use of in certain circumstances.

Having not come from a SQL background I didn't realise I'd need to do primary joins. and I only stumbled across that SO answer after typing up my own question. The answer itself was not related to what I specifically wanted to do, but I was then able to do what I needed after seeing it, but ideally I'd have liked to see it as an example alongside the other relationship info in the docs.

If my above code wasn't super obvious, this is the change in syntax I was aiming for:

Old:
```python
session.add(Log('user', 'create'))
session.add(Log('user', 'edit.username'))
session.add(Log('script', 'create'))
```

New:
```python
session.add(UserLog('create'))
session.add(UserLog('edit.username'))
session.add(ScriptLog('create'))
```

**Comment by zzzeek** [comment]
> All the relationship info in the documentation was for if the foreign key is on the same subclass. In my case, I wanted one foreign key on the parent class, where each subclass implemented its own relationship using that key.

when you use single table inheritance, there's only one table.  all the "foreign keys" are on that table.  your table above is called "actionlog", the foreign key is on "entity_id".  

if OTOH by "foreign key" you mean "relationship", that's the second example at  https://docs.sqlalchemy.org/en/13/orm/inheritance.html#relationships-with-single-table-inheritance, illustrating the relationship on the "Manager" subclass, is that what we're talking about?



> 
> I totally get you don't want to overdo the documentation, but I feel in this case it's a cool feature that's unique to single table inheritance. It's obviously not a common use case, but it's definitely something I think that others could make use of in certain circumstances.

no controversy there just trying to understand what it is that is not already in the second example at https://docs.sqlalchemy.org/en/13/orm/inheritance.html#relationships-with-single-table-inheritance .


> 
> Having not come from a SQL background I didn't realise I'd need to do primary joins. 

you generally don't, if your tables are  set up with foreign key constraints

> and I only stumbled across that SO answer after typing up my own question. The answer itself was not related to what I specifically wanted to do, but I was then able to do what I needed after seeing it, but ideally I'd have liked to see it as an example alongside the other relationship info in the docs.

did you see the whole section at https://docs.sqlalchemy.org/en/13/orm/join_conditions.html ?


> 
> If my above code wasn't super obvious, this is the change in syntax I was aiming for:
> 
> Old:
> 
> ```python
> session.add(Log('user', 'create'))
> session.add(Log('user', 'edit.username'))
> session.add(Log('script', 'create'))
> ```
> 
> New:
> 
> ```python
> session.add(UserLog('create'))
> session.add(UserLog('edit.username'))
> session.add(ScriptLog('create'))

**Comment by Peter92** [comment]
The relationship between `Manager` and `Company` isn't quite what I'm meaning, I'll attempt to adapt the example. I'll answer some other bits at the bottom, but I don't want to waste much more of your time so no worries if you end up closing this aha.

So in this case, assume you have something that a `Manager` can have, and a different something an `Engineer` can have. While we're at it, a `Supervisor` can have something else, a `CEO` something else, etc. The way I'm doing it is to define the ID of that something in `Employee`, but that ID can be a foreign key to any table. Dealing with that ID is implemented inside each subclass.

```python
class Employee(Base):
    __tablename__ = 'employee'
    id = Column(Integer, primary_key=True)
    thing_id = Column(Integer)    
    
    __mapper_args__ = {
        'polymorphic_identity':'employee',
        'polymorphic_on':type
    }

class ManagerThing(Base):
    id = Column(Integer, primary_key=True)

class Manager(Employee):
    thing = relationship(ManagerThing, primaryjoin='ManagerThing.id==Employee.thing_id', foreign_keys=Employee.thing_id)

    __mapper_args__ = {
        'polymorphic_identity':'manager',
    }

class EngineerThing(Base):
    id = Column(Integer, primary_key=True)

class Engineer(Employee):
    thing = relationship(EngineerThing, primaryjoin='EngineerThing.id==Employee.thing_id', foreign_keys=Employee.thing_id)

    __mapper_args__ = {
        'polymorphic_identity':'engineer'
    }
```

> when you use single table inheritance, there's only one table. all the "foreign keys" are on that table. your table above is called "actionlog", the foreign key is on "entity_id".

At risk of repeating myself - this part I know, but I wanted to provide the correct relationship on the different types of logs. In the physical database, there's `ActionLog('user', 1)` and `ActionLog('session', 1)`.  Despite both having the same `entity_id`, in the ORM layer they will be mapped to different things.

```python
>>> ActionLog(type='user', entity_id=1)
ActionLogUser(entity_id=1)
>>> ActionLogUser(entity_id=1).user
User(id=1)
>>> ActionLogSession(entity_id=1).session
Session(id=1)
```

> if OTOH by "foreign key" you mean "relationship", that's the second example 

Yeah that was the documentation I was referring to, which didn't quite contain enough info for me to get this working.

> you generally don't, if your tables are set up with foreign key constraints

Since the ID can be linked to any table, setting it up with a foreign key constraint wasn't an option in this case

> did you see the whole section at https://docs.sqlalchemy.org/en/13/orm/join_conditions.html

I'm fine with the simple stuff, but I'm really out of my depth when extra primary/secondary/remote joins start being required. When it gets to that, I generally grab existing code and adapt it, but in this case I wasn't sure exactly what was needed until I accidentally came across it.

**Comment by jvanasco** [comment]
The forthcoming docs cover "Indirect Foreign Keys", I'll paste them below so you can see if it helps explain some of the related concepts better.

I have some concerns with your models/examples above, but I have zero experience with polymorphic  - so I need to familiarize myself with that stuff before I make any comments. It is likely my concerns are entirely due to my own misunderstandings.

-----------------------------

Indirect Foreign Keys
~~~~~~~~~~~~~~~~~~~~~

Another advanced scenario is when a desired relationship between two tables is
based on column(s) which contain foreign keys that reference another table(s).

Consider the following model that describes a restaurant ordering system:


    class MenuItem(Base):
        __tablename__ = 'menu_item'

        id = Column(Integer, primary_key=True)


    class Order(Base):
        __tablename__ = 'order'

        id = Column(Integer, primary_key=True)


    class OrderItem(Base):
        __tablename__ = "order_item"

        order_id = Column(
            Integer, ForeignKey("order.id"), nullable=False,
            primary_key=True
        )
        menu_item_id = Column(
            Integer, ForeignKey("menu_item.id"), nullable=True,
            primary_key=True
        )


    class OrderItemCustomized(Base):
        __tablename__ = "order_item_customized"

        order_id = Column(
            Integer, ForeignKey("order.id"), nullable=False, primary_key=True
        )
        menu_item_id = Column(
            Integer, ForeignKey("menu_item.id"), nullable=False,
            primary_key=True
        )


Notice the ``OrderItemCustomized`` object does not foreign key onto
``OrderItem`` itself, but instead uses the same foreign key
relationships as ``OrderItem``'s Primary Key.  This example is a simplification
of an advanced concept and used for illustrative purposes; a typical model
would declare a dedicated ``OrderItem.id`` column as the Primary Key.

In this example, a reciprocal relationship is desired to link ``OrderItem`` and
``OrderItemCustomized``.  The :func:`.foreign` :term:`annotation` can be used
within the :paramref:`_orm.relationship.primaryjoin` expression to establish
this relationship, by treating the columns as "Indirect Foreign Keys"::


    OrderItem.customizations = relationship(
        "OrderItemCustomized",
        uselist=False,
        primaryjoin="and_("
        "OrderItemCustomized.menu_item_id==foreign(OrderItem.menu_item_id),"
        "OrderItemCustomized.order_id==foreign(OrderItem.order_id),"
        ")",
        back_populates="order_item",
    )
    OrderItemCustomized.order_item = relationship(
        "OrderItem",
        uselist=True,
        primaryjoin="and_("
        "OrderItemCustomized.menu_item_id==foreign(OrderItem.menu_item_id),"
        "OrderItemCustomized.order_id==foreign(OrderItem.order_id),"
        ")",
        back_populates="customizations",
    )


The important detail to note in the above relationship is the
:paramref:`_orm.relationship.primaryjoin` arguments to both relationships are
identical and not the inverse of one another -- which is common to many
:func:`_orm.relationship` joins. This is beacause ``foreign(X) == Y`` means
"Y is unique, is populated first, and X may only have a value that's present in
Y".

To determine the correct join conditions above, a developer should consult their
overall database schema and determine which side of their relationships
function as the Indirect Foreign Key(s).  In this example, the schema implies a
composite primary key of ``OrderItem.menu_item_id`` and ``OrderItem.order_id``.
Consequently, both relationsips should annotate the ``OrderItem`` columns with
:func:`.foreign`.

Advanced joins may be difficult to set up at first, and exceptions will not be
raised until ':func:`_orm.configure_mappers` is invoked. Developers may want to
create a small testing harness to develop advanced relationships instead of
working directly on a full model or application.

**Comment by jvanasco** [comment]
After re-reading the docs a few times, I agree support for this pattern isn't obvious, and doesn't come across clearly in the examples/tutorial.  I think the main reason why is this pattern involves a table structure that is not fully normalized, and most of us are either used to working with fully normalized data or not using polymorphic subclasses when we do.

In any event, one of the things I love about SQLAlchemy is that it supports data models like this.

I proposed some docs to cover this in Gerrit https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2261

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **master** branch:

**Some docs about relationships and single table inheritance to clarify concerns.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2261

**Comment by zzzeek** [comment]
> The relationship between `Manager` and `Company` isn't quite what I'm meaning, I'll attempt to adapt the example. I'll answer some other bits at the bottom, but I don't want to waste much more of your time so no worries if you end up closing this aha.
> 
> So in this case, assume you have something that a `Manager` can have, and a different something an `Engineer` can have. While we're at it, a `Supervisor` can have something else, a `CEO` something else, etc. The way I'm doing it is to define the ID of that something in `Employee`, but that ID can be a foreign key to any table. Dealing with that ID is implemented inside each subclass.
> 
> ```python
> class Employee(Base):
>     __tablename__ = 'employee'
>     id = Column(Integer, primary_key=True)
>     thing_id = Column(Integer)    
>     
>     __mapper_args__ = {
>         'polymorphic_identity':'employee',
>         'polymorphic_on':type
>     }
> 
> class ManagerThing(Base):
>     id = Column(Integer, primary_key=True)
> 
> class Manager(Employee):
>     thing = relationship(ManagerThing, primaryjoin='ManagerThing.id==Employee.thing_id', foreign_keys=Employee.thing_id)
> 
>     __mapper_args__ = {
>         'polymorphic_identity':'manager',
>     }
> 
> class EngineerThing(Base):
>     id = Column(Integer, primary_key=True)
> 
> class Engineer(Employee):
>     thing = relationship(EngineerThing, primaryjoin='EngineerThing.id==Employee.thing_id', foreign_keys=Employee.thing_id)
> 
>     __mapper_args__ = {
>         'polymorphic_identity':'engineer'
>     }
> ```

When you used the phrase "mapping one foreign key to different relationships.", that suggested this pattern, but it wasn't clear if that's what you actually meant.  So now that you've defined what you're doing, I know this pattern and I have a lot to say about it, and it is documented in our example suite though not quite how you have it above (there's a lot of ways to do it).    

The main thing that it does suggest is a pattern that Ruby On Rails calls a "polymorphic association", and I think Django calls it "generic foreign key".   I wrote about this a SUPER long time ago, warning, insanely ancient content and paradigms, here: https://techspot.zzzeek.org/2007/05/29/polymorphic-associations-with-sqlalchemy/ .   From that blog post I added an example suite to SQLAlchemy which has been modernized several times and that is here: https://docs.sqlalchemy.org/en/13/orm/examples.html#module-examples.generic_associations and it's known as "generic associations".   

The general idea is pretty much the same as what you have here except from the other side's perspective - different kinds of objects all point to a collection of Address objects, so a Customer can have Address rows, a Supplier can have address rows, etc.   in your example above, we see this from the point of view of EngineerThing and ManagerThing - they each refer to a collection of Employee objects (it's just those Employee objects happen to be Engineer and Manager subclasses, and you aren't looking as hard from the EngineerThing->collection of Engineer side, you're looking from the Engineer -> has an EngineerThing, but it's the same).   in your original example, the User can have a list of ActionLog items, and then some other objects can as well.

So the good news is, the thing you want to do here IIUC is not only documented, there's a whole example suite talking about it.   The one that is exactly what you are doing from a database perspective is called a "generic foreign key".   It is not actually using class inheritance however, though it can and perhaps I should add that also here since it is cleaner (it's likely the ORM wasn't as flexible back when I wrote these examples 13 years ago), it is just tacking on multiple relationships onto the target class with the "generic foreign key" and using a descriptor to select the right one.  this because it was trying to look like django's feature.

The bad news is, the specific way you're doing it is the one I warn against in both my blog post as well as in the example suite, even though the example suite *does* include a version that does it this way, which is that you have a single column on a single table, ActionLog.entity_id, and then within this single column you are placing the primary key of another row elsewhere, but you are linking it to *different* tables.   From a relational database perspective, that's simply the wrong way to do it, unfortunately.   That was what my blog post set out to talk about and it's why I proposed two or three other ways of achieving this object pattern without actually violating relational rules.  

this is such a common thing people want to do, while at the same time being not recommended by database people, that I knew there'd be some good resources on this by now and I found this SO answer at https://stackoverflow.com/a/3383320/34549 that links to many good answers from database author Bill Karwin.     Basically, in relational algebra, a foreign key may only point to **one** table.   SQLAlchemy, being open ended, lets you do whatever here, however, as far as this pattern being documented, the example suite at "generic associaitions" covers it (noting we can add more variations here) and I recommend one of the alternate patterns provided.   Karwin lists out a whole bunch of alternatives as well at https://stackoverflow.com/questions/922184/why-can-you-not-have-a-foreign-key-in-a-polymorphic-association/922341#922341 .      His one liner critique of the pattern is "Polymorphic Associations are weak with respect to enforcing database consistency. The data integrity depends on all clients accessing the database with the same referential integrity logic enforced, and also the enforcement must be bug-free.", and that is the general idea.   

He seems to have come up with even more ways of modeling this.     The main thing to decide with this pattern is if you do in fact need to run queries against all the possible ActionLog items across all the subtypes they point towards, or not.  If the answer is "not", then a simple pattern like "table per related" is the way to go.    People are scared of "table per related" and "table per association" because it creates lots of sub-tables, but there's no actual "problem" here because we are using automated tools to manage our database schema.

Anyway, that's the gist, the thing you're doing above is more or less equivalent to what we see at https://docs.sqlalchemy.org/en/13/_modules/examples/generic_associations/generic_fk.html and I can add another version that uses single table inheritance also since it's likely cleaner.   But it's always going to have that cloud of "this is technically wrong" hanging over it :).   The suite lists out alternate forms and it's possible these can also be modernized further.

**Comment by Peter92** [comment]
Thanks for the detailed writeup, it helped me understand the theory a lot more. I like the "_Well, your DBA will never take you seriously again, but lets go with it (for now)_" on your old article haha.

I gave the links a good read (a few more than once as it's somewhat of a tricky concept), it looks like the only decent option to not violate the constraints is either using multiple foreign keys or tables. The supertable idea looks good only if you have one or two tables that need to be linked to another, less so if it's linking to everything at once (can't retroactively apply to an existing table, and the auto increment ID would shoot up very fast).

I personally dislike the idea of multiple foreign keys in this case as it creates a lot of redundant columns, but I was kind of on the fence about using multiple tables until actually writing this. My argument for the keeping same method was that the logs may not be related to specific tables, and therefore have no `entity_id`, but my idea has actually changed enough that this is no longer the case. I'll switch to using multiple tables, and in theory it should be easy replicate the exact same syntax as I had before.

Also great job on the docs Jonathan, it's exactly what I'd have found useful. I'm not sure if it'd be outside the scope in this case, but it might be helpful just having an extra sentence to say "as an alternative to using multiple foreign keys, consider using separate association tables for each subclass to keep the db integrity".

**Comment by jvanasco** [comment]
FWIW, I pretty much always use the single table pattern for this stuff, then enforce one object with a check constraint.  I don't know how to handle this in polymorphic.
```
class ObjectLog(Base):
    __tablename__ = 'object_log'
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey('User.id'), primary_key=True),
    posting_id = Column(Integer, ForeignKey('User.id'), primary_key=True),
```

**Comment by zzzeek** [comment]
we've got some docs in the works and i think we've clarified a lot here, closing this for now.
