### ISSUE TITLE
fix up association proxy examples a bit for the changes from #4351

### ISSUE THREAD

**Issue by alexhermida** [sqlalchemy/sqlalchemy#5647]
I found that the documentation about _Querying with Association Proxies_ is not consistent with the current message in the migration guide for version 1.3. 

In the migration [changelog for 1.3](https://docs.sqlalchemy.org/en/13/changelog/migration_13.html#associationproxy-now-provides-standard-column-operators-for-a-column-oriented-target) say 

>Note that the ColumnOperators.contains() operator is in fact a string comparison operator; this is a change in behavior in >that previously, the association proxy used .contains as a list containment operator only. With a column-oriented >comparison, it now behaves like a “like”:

```
print(s.query(User).filter(User.values.contains('foo')))
SELECT "user".id AS user_id
FROM "user"
WHERE EXISTS (SELECT 1
FROM element
WHERE "user".id = element.user_id AND (element.value LIKE '%' || :value_1 || '%'))
```

But in the current 1.3 docs for [Querying with Association Proxies](https://docs.sqlalchemy.org/en/13/orm/extensions/associationproxy.html?highlight=association%20proxy%20session#querying-with-association-proxies):

```
print(session.query(User).filter(User.keywords.contains('jek')))
SELECT user.*
FROM user
WHERE EXISTS (SELECT 1
FROM userkeywords, keyword
WHERE user.id = userkeywords.user_id
    AND keyword.id = userkeywords.keyword_id
    AND keyword.keyword = :keyword_1)
```

I was wondering if I'm missing something or the docs for AssociationProxy need to be updated. I would expect both docs showing the same "like" query.

Thanks all!

**Comment by zzzeek** [comment]
hey there -

There seem to be some issues with the examples in those docs however the contains example is still correct, because `User.keywords` is object-targeted, not column-targeted.  

now, there's a problem here, which is that this terminology "object-targeted" and "column-targeted" are completely confusing.   the example is showing a series of two association proxies linked together and the end "target" returned actually *is* a column value.  so the term "target" is not great here.    but what is actually happening there is that User.keywords points to an attribute on the UserKeyword object entity.  so containment operations are using the "EXISTS" style of operating at that level.   to get the LIKE you need to pull Keyword.keyword in explicitly like this:

```
>>> print(session.query(User).filter(User.keywords.any(Keyword.keyword.contains("jek"))))
SELECT "user".id AS user_id, "user".name AS user_name 
FROM "user" 
WHERE EXISTS (SELECT 1 
FROM user_keyword 
WHERE "user".id = user_keyword.user_id AND (EXISTS (SELECT 1 
FROM keyword 
WHERE keyword.id = user_keyword.keyword_id AND (keyword.keyword LIKE '%' || :keyword_1 || '%'))))

```

What i think ends up being the case is that an assocaition proxy that returns objects is object-targeted, and an association proxy that refers to another association proxy is also object targeted.    this can be demonstrated from that example like this:


```
class User(Base):
    __tablename__ = "user"
    id = Column(Integer, primary_key=True)
    name = Column(String(64))

    keywords = association_proxy(
        "user_keywords",
        "keyword",
    )

    special_keywords = association_proxy(
        "user_keywords",
        "special_key",
    )

# ...

>>> print(session.query(User).filter(User.special_keywords.contains("jek")))
SELECT "user".id AS user_id, "user".name AS user_name 
FROM "user" 
WHERE EXISTS (SELECT 1 
FROM user_keyword 
WHERE "user".id = user_keyword.user_id AND (user_keyword.special_key LIKE '%' || :special_key_1 || '%'))

>>> print(session.query(User).filter(User.keywords.contains("jek")))
SELECT "user".id AS user_id, "user".name AS user_name 
FROM "user" 
WHERE EXISTS (SELECT 1 
FROM user_keyword 
WHERE "user".id = user_keyword.user_id AND (EXISTS (SELECT 1 
FROM keyword 
WHERE keyword.id = user_keyword.keyword_id AND keyword.keyword = :keyword_1)))

```

you would almost think the association proxy -> association proxy should figure out how to chain that second contains().    but apparently right now it does not (I can't take that on right now either, AP is very difficult to work with and behavior changes are a big deal, as can be seen here).   so if you wanted the column oriented contains you need to do that like this, which also seems counterintuitive and I dont really know how to document this right now:

```

>>> print(session.query(User).filter(User.keywords.any(Keyword.keyword.contains("jek"))))
SELECT "user".id AS user_id, "user".name AS user_name 
FROM "user" 
WHERE EXISTS (SELECT 1 
FROM user_keyword 
WHERE "user".id = user_keyword.user_id AND (EXISTS (SELECT 1 
FROM keyword 
WHERE keyword.id = user_keyword.keyword_id AND (keyword.keyword LIKE '%' || :keyword_1 || '%'))))
```

also just as a note, embedding two correlated EXISTS like that is usually really bad performance-wise unless the optimizer knows how to un-nest the structure into JOINs.

I can add a few clarifitying notes right now and fix one of the examples but i dont know I can make this less confusing at the moment.

**Comment by zzzeek** [comment]
what this should include is:

1. fix the example `print(session.query(User).filter(User.keywords.any(keyword='jek')))` which fails right now

2. change sentence at https://docs.sqlalchemy.org/en/13/changelog/migration_13.html#associationproxy-now-provides-standard-column-operators-for-a-column-oriented-target to "Given an AssociationProxy where the target is a database column, as opposed to an object reference *or* another association proxy"

**Comment by zzzeek** [comment]
the join docs there are obsolete too.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Improve assoc proxy docs for 1.3 changes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2318

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Improve assoc proxy docs for 1.3 changes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2319

**Comment by zzzeek** [comment]
OK I mostly just scaled those docs back as I think in general the APs don't create very good SQL phrases, it clarifies the new behavior a bit. thanks for reporting.

**Comment by alexhermida** [comment]
@zzzeek aside from the complexity, I'd say it's much clear now. Thanks for taking the time and the effort!
