### ISSUE TITLE
Retry policy

### ISSUE THREAD

**Issue by Luttik** [sqlalchemy/sqlalchemy#5657]
The biggest power of SQLAlchemy is abstracting away from the database. This means not having to think about which type of database is behind the code but, arguably even more importantly, it also means being able to think in Python / SQLAlchemy paradigms rather than database paradigms. 

One of the places where SQLAlchemy does not do a great job of abstracting away from the database is in exception handling. It would be lovely if it would provide the option to automagically counter some of the most frequent database issues (like lost connections). 

IMHO it would be best to defer choices to the absolute experts (meaning the maintainers of SQLAlchemy) preferably implemented in an opinionated way (or just with smart defaults). Additionally (or alternatively), a comprehensive centralizes page with everything you need to know about error handling when using SQLAlchemy would also be welcome.

## Case in point: Current top search result for "retry policy sqlachemy"
The fact that the accepted answer for [the top search result for "retry policy sqlachemy"](https://stackoverflow.com/questions/53287215/retry-failed-sqlalchemy-queries) states the following: 

> Most of the query executors are calling \_\_iter\_\_ eventually as the most low level common point. I found this from their source code and trial and error. Its absolutely not fail proof and might not cover every case

Is pretty scary in my opinion, and an indication that I am not the only one who desires some more guidance with these issues.

## Root Cause
What pushed me to write this question is having this exception frequently: `sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL connection has been closed unexpectedly`. I hope that `pool_pre_ping=True` will prevent most of these issues but tips are welcome of course.

## Conclusion
While I am not an expert in this topic, and frankly sometimes have a hard time finding the right stuff in the SQLAlchemy documentation. I do believe that this is an important topic to consider and is fully in line with the place that SQLAlchemy has in the mind of python developers as the tool that makes databases easy(er).

**Comment by zzzeek** [comment]
hi there -

the "pre-ping" feature is there so that when you begin a new operation, if the database had been disconnected, the pooled connection will be "pinged" to test this situation so that a fresh connection can be made to be returned to you.  this is a straightforward feature.   if your disconnects occur in between operations, it will be fine, assuming we are catching for that specific PG error code (which seems like one that has been brought up recently as needing some work, not sure).

however, if you are working with this pooled connection, what's important to know is that all DBAPI connections are transactional, meaning all the things you are doing upon it are part of an ongoing transactional state.   to the degree that DBAPIs support "autocommit" modes, which we certainly support, these are the exception rather than the rule and overall SQLAlchemy seeks to orient itself around a transactional programming model since that's the best way to write applications that work with ACID compliant databases.

"retry" means that an entire transaction has to be replayed, so this is not a trivial problem.   to solve it, you have to use an event handler that intercepts *all* statements; inserts, updates, deletes, etc. and then when the connection fails, runs them all again.  That of course doesn't really scale, because when your transaction is being "retried", the state of the database has now changed and all those insert/update/delete statements now fail, in some cases silently as in the UPDATE statement that misses the row which it knew about earlier.

so the short answer is that "retry" means "transactional retry", and it has to be implemented in an application-specific way, where *your* methods that expect to be hit by disconnections have to restart the work they are doing and run it again.  This is referred towards in the docs here: https://docs.sqlalchemy.org/en/13/core/pooling.html#pool-disconnects :

> It is critical to note that the pre-ping approach does not accommodate for connections dropped in the middle of transactions or other SQL operations. If the database becomes unavailable while a transaction is in progress, the transaction will be lost and the database error will be raised. While the Connection object will detect a “disconnect” situation and recycle the connection as well as invalidate the rest of the connection pool when this condition occurs, the individual operation where the exception was raised will be lost, and it’s up to the application to either abandon the operation, or retry the whole transaction again.

A few other notes:

> it also means being able to think in Python / SQLAlchemy paradigms rather than database paradigms.

That's actually the opposite of SQLAlchemy's goal.  SQLAlchemy wants you to very much think in database paradigms, what it offers is a way to **automate** the work of the programmer in writing code that works with these paradigms.   I get into this at my talk at https://www.sqlalchemy.org/library.html#handcodedapplicationswithsqlalchemy .  

>     Most of the query executors are calling __iter__ eventually as the most low level common point. I found this from their source code and trial and error. Its absolutely not fail proof and might not cover every case

unfortunately they are all writing their applications in an unsafe way and I've remarked on that post that this is not an approach people should be using.    even if they wanted to transparently reconnect on a per-query basis, that's not how you would do it, you would use events, most likely dialect do_execute() at https://docs.sqlalchemy.org/en/13/core/events.html?highlight=connectionevents#sqlalchemy.events.DialectEvents . 

However, if everyone built their apps with transparent reconnections stuck in their do_execute() methods, now you'd have people posting stackoverflow issues where they say "SQLAlchemy is losing data in the middle of my transaction"!    because no error was raised and the "retry" moved along with more SQL statements, ignoring that everything which occurred previously has been lost.    not stopping when a transaction fails is a major mistake.

From this it follows that if *we* transparently reconnected in the middle of transactions, we'd be barraged with complaints of that nature, of silent failure of data to be committed which would be rather catastrophic.    it doesn't solve the problem, it just hides it which IMO makes it orders of magnitude worse.

I hope this clarifies where we are at on this.

**Comment by zzzeek** [comment]
certainly seems worthy of a bigger FAQ entry.

**Comment by zzzeek** [comment]
I will put up a recipe that does transaparent query retry when DBAPI autocommit is turned on.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add FAQ entry for retry subject; recipe w/ autocommit** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2316

**Comment by zzzeek** [comment]
the transparent query recipe is probably not worth it on 1.3 as it requires more internal API hacking to get around the way Connection keeps track of the Transaction.  I have no idea how that stackoverflow recipe works and I wonder if pymysql perhaps reconnects internally or something.   On 1.4 it works without anything special.
