### ISSUE TITLE
Catching model name in DBApi exception

### ISSUE THREAD

**Issue by kaldown** [sqlalchemy/sqlalchemy#5666]
Catching `DBApi` exception it would be nice to get the model name or at least the table name which caused the problem.

e.orig.args is not convenient:

`('duplicate key value violates unique constraint "unique_shop_item_user"\nDETAIL:  Key (shop_item_id, user_id)=(1, 96) already exists.\n',)`

due to the ambiguity of a message.

**Comment by zzzeek** [comment]
hey there -

unfortunately SQLAlchemy does not generate those messages, those come from your database.  you can look at the name of the constraint itself in order to determine which table is affected, and similarly the stack trace will show the exact line in your application where the error orginates. 

that's the best we can do, hope this helps!

**Comment by kaldown** [comment]
Sure thing.
But even parsing key name is not too obvious.

Thank you for clarification.

**Comment by zzzeek** [comment]
there could be a large job to catch all exceptions in the UOW and add some kind of context to them, Id rather not rethrow a new one because that would be a significant behavioral change and break schemes that currently rely upon DBAPI level exceptions being caught.   Just adding some string context is more doable but that wouild be kind of destablizing right now and we are getting set for a major new release that has plenty of huge changes already.  

usually though the stack trace tells people what they need to know if you can clarify why it's hard for you to see which model is affected that might be helpful.

**Comment by zzzeek** [comment]
rewriting exceptions in a dialect-specific way is outside of SQLAlchemy's current scope.  the drivers don't make this easy.
