### ISSUE TITLE
Table.params.extend_existing seems not working

### ISSUE THREAD

**Issue by gocreating** [sqlalchemy/sqlalchemy#5668]
As described in [Table.params.extend_existing](https://docs.sqlalchemy.org/en/13/core/metadata.html#sqlalchemy.schema.Table.params.extend_existing), why the following code are not working?

``` py
# in file1.py
class Doctor(Base):
    __tablename__ = 'doctor'
    __table_args__ = {
        'extend_existing': True,
    }

    first_name = Column(String)
    last_name = Column(String)
```

``` py
# in file2.py

class Doctor(Base):
    __tablename__ = 'doctor'
    __table_args__ = {
        'extend_existing': True,
    }

    test = Column(String)
```

The exception will be raised:

```
sqlalchemy.exc.InvalidRequestError: Multiple classes found for path "Doctor" in the registry of this declarative base. Please use a fully module-qualified path.
```

**Comment by jvanasco** [comment]
Can you please provide a SSCCE reproducible test case that will generate the exception?

**Comment by zzzeek** [comment]
hi there -

the issue here is that there are two Doctor classes on the same declarative base, and at some point they are being referred towards by an ambiguous name "Doctor".   this has nothing to do with extend_existing nor is this really what extend_existing is used for (it's used for table reflection use cases).

the correct usage is that there should be only one Doctor class declared, in just one module.  Remove the second "Doctor" class altogether and import the Doctor class from other modules as needed.

**Comment by bassg0navy** [comment]
How can this class be deleted. I thought it would be as easy as a simple `del <name_of_class>` but that's not the case.

**Comment by zzzeek** [comment]
you can delete a mapped class and that will remove the mapping entirely, **if** that class is not referred towards by any relationship.    

however, the whole "I want to delete just one mapped class" case should be avoided.   [registry.dispose()](https://docs.sqlalchemy.org/en/14/orm/mapping_api.html?highlight=registry+dispose#sqlalchemy.orm.registry.dispose) will clear all the mappers for a particular registry.
