### ISSUE TITLE
Get column types for custom query

### ISSUE THREAD

**Issue by PrimozGodec** [sqlalchemy/sqlalchemy#5677]
**Describe your question**

Hope that same question does not appear in issues already but I can not find it. I am using SQLAlchemy in a package where I want to offer user to write its own SQL query. For query, I would like to get column types. 

If I create a query with creating table first:
```
table = Table(table_name, meta, autoload=True)
query = select([table])
rs = conn.execute(query)
```
I can get types with looping through (like it is suggested [here](https://stackoverflow.com/questions/2258072/sqlalchemy-getting-column-data-types-of-query-results))
```
[col.type for col in rs.context.compiled.statement.columns.items()]
```
or from query:
```
types = [col.type for col in query.columns]
```

In cases when I execute a custom SQL query 
```
rs = conn.execute("SELECT * FROM Table_name")
```
both methods do not work. Same would not work for more complex custom queries.

Is there a way how to get column types in cases with a custom query? I was searching through the web a lot but could not find the answer.

**Example - please use the [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) guidelines if possible**
Examples are in the description above.

**Versions**
 - OS: Any
 - Python: Any, 3.8
 - SQLAlchemy: 1.3.20
 - Database: I was testing with MSSQL, but should also work for MySQL, PostresSQL, Oracle
 - DBAPI: I was testing with pymssql

**Useful links**
- [Get Support](https://www.sqlalchemy.org/support.html) on the website
- The [documentation](https://docs.sqlalchemy.org/en/latest/) website
- The [UsageRecipes](https://github.com/sqlalchemy/sqlalchemy/wiki/UsageRecipes) wiki
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sqlalchemy) tag
- SQLAlchemy [Google group](http://groups.google.com/group/sqlalchemy)
- [Gitter](https://gitter.im/sqlalchemy/community) chat

**Have a nice day!**

**Comment by zzzeek** [comment]
> **Describe your question**
> 
> Hope that same question does not appear in issues already but I can not find it. I am using SQLAlchemy in a package where I want to offer user to write its own SQL query. For query, I would like to get column types.
> 
> If I create a query with creating table first:
> 
> ```
> table = Table(table_name, meta, autoload=True)
> query = select([table])
> rs = conn.execute(query)
> ```
> 
> I can get types with looping through (like it is suggested [here](https://stackoverflow.com/questions/2258072/sqlalchemy-getting-column-data-types-of-query-results))
> 
> ```
> [col.type for col in rs.context.compiled.statement.columns.items()]
> ```
> 
> or from query:
> 
> ```
> types = [col.type for col in query.columns]
> ```

use query.inner_columns or in 1.4 query.selected_columns.    "query.columns" is being [removed](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#a-select-statement-is-no-longer-implicitly-considered-to-be-a-from-clause)


> 
> In cases when I execute a custom SQL query

"custom" SQL query we take to mean "plain textual SQL query"

> 
> ```
> rs = conn.execute("SELECT * FROM Table_name")
> ```
> 
> both methods do not work. Same would not work for more complex custom queries.

note the above form is also [deprecated in 1.4](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#execute-method-more-strict-execution-options-are-more-prominent) and you would want to use the [text](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.text) construct.

> 
> Is there a way how to get column types in cases with a custom query? I was searching through the web a lot but could not find the answer.

unfortunately a textual statement has no typing information available by default because SQLAlchemy relies upon the user to provide this information.

the correct use pattern is to provide this typing information when the query is constructed using [text.columns](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.TextClause.columns):

    stmt = text("SELECT * FROM Table_name").columns(table.c.id, table.c.name, ...)

from there you have the columns available from the ".columns" collection in 1.3 or the ".selected_columns" collection in 1.4.

if the statement is purely untyped then you can only get fragmented typing information from the database itself using [cursor.description](https://www.python.org/dev/peps/pep-0249/#description):

    result = conn.execute(stmt)
    types = [elem[1] for elem in result.cursor.description]

These will give you internal DBAPI type codes, or None if not supported.   generally this information is only marginally useful so you're best making sure your textual SQL statements are created with typing information passed.

**Comment by PrimozGodec** [comment]
Thank you for your fast and detailed response. 
Ok, now I understand that I need to provide column information if I want to get types. I will try to parse the user's SQL to get tables that are used in a query.

Anyway, I came out with another idea, since Python types are enough, I can try to get the first few results of the query and check their types. Do you think it would work or do you see any problem with this approach?

**Comment by zzzeek** [comment]
if your approach only needs to work when data is present then it should be fine, sure.
