### ISSUE TITLE
support mysql ssl_mode flag in ssl dictionary

### ISSUE THREAD

**Issue by thereisnosun** [sqlalchemy/sqlalchemy#5692]
**Description**
An ability to force TLS in MySQL

**Expected behavior**
When ssl_mode flag is specified MySQL connection should behave accordingly. Meaning, when I want to drop connection when SSL is disabled on the server it should drop. In mysqldb this is implemented via ssl_mode flag.

**To Reproduce**
Just add ssl_mode to your connect args.

Exception: "ssl_mode is not supported"

**Versions.**
 - OS: ALL
 - Python: 2.7, 3.6(Looks like all of them)
 - SQLAlchemy: 1.3.3(But I checked other version they don't provide such functionality as well"
 - Database: MySQL
 - DBAPI: mysqldb

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Added ssl_mode flag to mysqldb** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2358

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Added ssl_mode flag to mysqldb** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2359

**Comment by zzzeek** [comment]
as mentioned above I thought a patch was needed due to the separate "ssl" dictionary but per https://dev.mysql.com/doc/c-api/8.0/en/mysql-ssl-set.html that's not where "ssl_mode" is.

Also it does not seem to be supported by the driver, so that means I need to revert this change because it is not properly documented.  latest mysqlclient:

```
>>> from sqlalchemy import create_engine
e >>> e = create_engine("mysql://scott:tiger@localhost/test?ssl_mode=required")
>>> c = e.connect()
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/base.py", line 2977, in _wrap_pool_connect
__init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.NotSupportedError: MySQL client library does not support ssl_mode specification

```


latest pymysql:

```
>>> from sqlalchemy import create_engine
>>> e = create_engine("mysql+pymysql://scott:tiger@localhost/test?ssl_mode=required")
>>> c = e.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    return Connection(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl_mode'

```


sorry, I need to revert this and I need to know exactly what driver you are using as well as a case that illustrates the flag not working right now; any string you add to the query string is passed through in any case, the above behavior is the same without the patch as with it.

**Comment by zzzeek** [comment]
you can pass ssl_mode in the query or connect args right now, no patch is needed as long as this is not going into the "ssl" dictionary.

the fact that it raises "ssl_mode is not supported" is the driver, not SQLAlchemy, adding it to connect args does not change anything.

**Comment by gordthompson** [comment]
> MySQLdb._exceptions.NotSupportedError: MySQL client library does not support ssl_mode specification

I was getting this error too, but https://github.com/PyMySQL/mysqlclient-python/issues/439 suggested that it was because I was testing under Windows. When I test under Xubuntu 18.10 using the current SQLAlchemy master with the patch reverted (415ddce1) the `ssl_mode` argument is accepted and does seem to have an effect:

``` python
import MySQLdb
import sqlalchemy as sa

print(sa.__version__)  # 1.4.0b2
print(MySQLdb.version_info)  # (2, 0, 1, 'final', 0)

engine = sa.create_engine(
    "mysql+mysqldb://scott:tiger@192.168.0.199/test?ssl_mode=DISABLED"
)
with engine.connect() as conn:
    print(
        conn.execute(
            sa.text("SHOW SESSION STATUS LIKE 'Ssl_cipher'")
        ).fetchone()
    )  # ('Ssl_cipher', '')

engine = sa.create_engine(
    "mysql+mysqldb://scott:tiger@192.168.0.199/test?ssl_mode=REQUIRED"
)
with engine.connect() as conn:
    print(
        conn.execute(
            sa.text("SHOW SESSION STATUS LIKE 'Ssl_cipher'")
        ).fetchone()
    )  # ('Ssl_cipher', 'ECDHE-RSA-AES128-GCM-SHA256')
```

Unfortunately, I don't have a MySQL instance with SSL completely disabled so I can't confirm that `ssl_mode=REQUIRED` would abort the connection in that case, but if it didn't then that would also be a MySQLdb issue.

**Comment by zzzeek** [comment]
but in any case the parameter is passed through and it's a string so there's no need to change anything here.

**Comment by gordthompson** [comment]
@zzzeek - Agreed. And as to why you got the error while I didn't, it's probably that the CentOS repos have an older version of libmysqlclient-dev than the Ubuntu repos, similar to the issue you had with MariaDB in #5515 . (For the record, my version of libmysqlclient-dev was 5.7.32-0ubuntu0.18.04.1)

**Comment by zzzeek** [comment]
ssl mode seems to be kind of complicated with current drivers but in any case from the SQLAlchemy side this parameter is passed through.
