### ISSUE TITLE
Query drops aggregates when made without session

### ISSUE THREAD

**Issue by ing200086** [sqlalchemy/sqlalchemy#5720]
**Describe the bug**
Session.query creates different result than creating Query().with_session(session). Specifically it appears to drop any aggregate attributes.

**Expected behavior**
Both methods of developing the query should produce the same result query. 

**To Reproduce**
The following generates the **correct** query
```py
incoming_transaction = aliased(models.MoveTransaction)
incoming = self.db.query(
    incoming_transaction.target.label('target'), func.sum(incoming_transaction.quantity).label('quantity')
).filter(
     incoming_transaction.destination == location.uid
).group_by(incoming_transaction.target)

return incoming.all()
```
generates
```sql
SELECT trace_transaction_1.target AS target, sum(trace_transaction_1.quantity) AS quantity 
FROM trace_transaction AS trace_transaction_1 
WHERE trace_transaction_1.destination = ? GROUP BY trace_transaction_1.target
```

The following generates an **incorrect** query
```py
incoming_transaction = aliased(models.MoveTransaction)
incoming = Query(
    incoming_transaction.target.label('target'), func.sum(incoming_transaction.quantity).label('quantity')
).filter(
     incoming_transaction.destination == location.uid
).group_by(incoming_transaction.target).with_session(self.db)

return incoming.all()
```
generates
```sql
SELECT trace_transaction_1.target AS target 
FROM trace_transaction AS trace_transaction_1 
WHERE trace_transaction_1.destination = ? GROUP BY trace_transaction_1.target
```

**Versions.**
 - OS: Windows 10
 - Python: 3.8.6
 - SQLAlchemy: 1.3.20
 - Database: sqlite
 - DBAPI: sqlite

Any help to understand if this is a true bug or a mistake in my code would be greatly appreciated! I highly prefer to use the Query generation method for my current use case, and would love to know how to fix this.

**Comment by zzzeek** [comment]
hey there -

the Query object is not generally meant to be instantiated in this way, but the issue is that you are [using the wrong argument signature](https://docs.sqlalchemy.org/en/13/orm/query.html?highlight=query#sqlalchemy.orm.query.Query.__init__).   The columns are passed as a list, not positionally:

        incoming = Query(
            [incoming_transaction.target.label("target"),
            func.sum(incoming_transaction.quantity).label("quantity")]
        )

Note that this API is all legacy as of 1.4 so if you want to upgrade to 1.4 you can use `select(*cols)` across the board and it is fully consistent.

was not easy to notice and I had to write a test script to catch it so please send complete [mcve](http://stackoverflow.com/help/mcve) for future issues, thanks!

**Comment by ing200086** [comment]
Ah. Thank you so much. Next time I'll include more of the code to assist.
