### ISSUE TITLE
sqlalchemy ORM silently drops multiple filter conditions joined with Python boolean expressions

### ISSUE THREAD

**Issue by karlanke** [sqlalchemy/sqlalchemy#5723]
**Describe the bug**
```sql
CREATE TABLE myTable (foo int, bar int);
INSERT INTO myTable (foo, bar) VALUES (1, 1)
```

```python
results = db_client.query(MyTable).filter(MyTable.foo == 1 and MyTable.bar == 2)
for result in results:
    raise Exception("Shouldn't get here")
```

**Expected behavior**
Either:

- parse the two expressions as a developer would expect
- raise an exception

**Versions.**
 - OS: Docker (alpine)
 - Python: 3.7.9
 - SQLAlchemy: 1.3.20
 - Database: Postgres 12.3
 - DBAPI: psycopg2 2.8.6

**Additional context**
This may be working as intended, but it's *incredibly* unintuitive, especially coming from other ORMs. Without good testing, it's also a dangerous source of bugs.

**Comment by zzzeek** [comment]
hey there -

unfortunately there is no solution to this problem other than testing your code and ensuring queries return the data you expect.   Python provides no means of intercepting the "and" and "or" keywords; if they did, we'd be using those to render SQL expressions.  this also means there is no mechanism by which SQLAlchemy can detect this mistake and raise.     Other options, like detecting the use of bool() for each term, can't be done b.c. it's valid to evaluate "==" and "!=" in a boolean sense so that expressions can be placed in a hashing context like sets and dictionaries, or trying to detect that the condition is where(False) or where(True), arguably we could warn/raise on that but for databases like PostgreSQL it is valid SQL to emit "WHERE false" or "WHERE true".

Instead, SQLAlchemy overrides the bitwise "&" and "|" operators which should be used here instead; some guidelines for doing so are in the new operator guide at https://docs.sqlalchemy.org/en/14/core/operators.html#conjunction-operators .

**Comment by CaselIT** [comment]
Also please note that `&` and `|` have high precedence in python, so parents must be used in your use case: `(MyTable.foo == 1) & (MyTable.bar == 2)`

Other alternatives:
- In general you can also use `sa.and_` and `sa.or_` to render an `AND` or an `OR`. 
- Chain multiple calls to `filter` to render an `and`
- pass multiple arguments to `fitler`
