### ISSUE TITLE
postgresql+pyodbc

### ISSUE THREAD

**Issue by ruafelianna** [sqlalchemy/sqlalchemy#5726]
Hello!

Using ```engine = sqlalchemy.create_engine('postgresql+pyodbc://dsn=mydsn')``` results in this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/__init__.py", line 500, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/strategies.py", line 61, in create
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/url.py", line 172, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 268, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgresql.pyodbc
```

Is it a bug or not implemented feature?

Versions:
```uname -a```: ```Linux kali 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux```

```lsb_release -a```:
```
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2020.2
Codename:       kali-rolling
```

Python:
```
Python 3.8.3 (default, May 14 2020, 11:03:12) 
[GCC 9.3.0] on linux
```

```pip3 show sqlalchemy```:
```
Name: SQLAlchemy
Version: 1.3.20
...
```

```psql --version```: ```psql (PostgreSQL) 13.0 (Debian 13.0-4)```

```pip3 show pyodbc```:
```
Name: pyodbc
Version: 4.0.30
...
```

```apt show unixodbc```
```
Package: unixodbc
Version: 2.3.6-0.1+b1
...
```

```apt show odbc-postgresql```
```
Package: odbc-postgresql
Version: 1:12.02.0000-2
...
```

**Comment by zzzeek** [comment]
ah not implemented right now, we support psycopg2, pg8000 and in SQLAlhcemy 1.4 asyncpg as well.

**Comment by ruafelianna** [comment]
@zzzeek thank you for the reply!

Are you going to implement it anywhen? Should I post a feature request?

**Comment by zzzeek** [comment]
there's not much need for pyodbc w/ postgresql as you will get much better results not using an ODBC driver in the middle.  The postgresql dialects have a lot of special behaviors and features that would be difficult to implement with odbc as postgresql has very elaborate datatypes that pyodbc will not have native support for (e.g. ARRAY, JSON, etc).   what is the reason you require ODBC driver support?

**Comment by jvanasco** [comment]
Adding to what Mike said: the supported postgres packages, psycopg2 and pg8000, are installable by `pip`; pyscopg2 wraps an underlying c library, and pg8000 is pure-python -- so there shouldn't be a need for using ODBC.

**Comment by zzzeek** [comment]
the one reason someone might need ODBC is on an environment that is controlled in some way where an ODBC data source name is present, and that's all you have.    But most people who use pyodbc send a hostname through it anyway, DSNs have just not really caught on in most cases I see (we certainly used them back in the 90's though).   so just want to know if there's any rationale that an ODBC DSN is in use or if you have host/port access.

**Comment by zzzeek** [comment]
ODBC drivers might have custom HA options like multiple hostnames, things like that also, though psycopg2 supports these things directly.

**Comment by ruafelianna** [comment]
The thing why I want to use odbc with dsn is that I want to manage all my connections in one place. For example, I have an asterisk instance and I use my dsn there in several places, and I have a python application, and I want to use the same dsn there too. So if my connection changes it could change in all those places without changing 100500 config files.

I might do something ideologically wrong due to the lack of experience, then I ask you to enlighten me how to do such a thing in a better way. :-)

**Comment by zzzeek** [comment]
that is the purpose of the DSN it's just not something that's very popular these days.   The DSN has to be configured on a per-machine basis in any case and modern applications tend to scale horizontally so it still needs to be set up on many different servers.

that said I dont really understand why you would have so many configuration files if you werent using DSNs.  you could just as easily have all your applications load their database URLs from a file such as (assuming a unix system) `/usr/local/etc/config/my_connection.ini' or something similar.

There's no strong reason SQLAlchemy can't have a pyodbc dialect for PostgreSQL it just wouldn't support as many cases because it is a very unpopular choice for PostgreSQL and we have quite a lot of problems with pyodbc even on the database that it is primarily used with, which is MS SQL Server.  

by all means if you want to write one and drop it in, take a look at the mysql pyodbc dialect for how its constructed:  https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mysql/pyodbc.py    that dialect might even be deprecated also.   pyodbc is not very popular for the databases where another connectivity option exists and most SQL Server users even don't seem to be using DSNs.

**Comment by ruafelianna** [comment]
To be honest I haven't known anything about odbc until today and I've started using it because it was a preferrable way to connect asterisk with db in asterisk documentation. And then I had this python db migration script (in the asterisk source code) which required only a url for sqlalchemy to make it work. So I got here.

Your point is very clear and I'll try and read up more about this stuff. Thank you a lot for the help and have a nice day (or night)!
