### ISSUE TITLE
Queries execution order is not guaranteed causing concurrency issues

### ISSUE THREAD

**Issue by brmzkw** [sqlalchemy/sqlalchemy#5735]
**Describe the bug**

With the two following tables:

```python
class MyTable(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)

class MyTable2(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)
```

Trying to updates two objects during the same transaction does not always execute queries in the same order. For example, if we attempt to update the two objects obj1 and obj2:

```python
obj1 = MyTable.query.filter_by(id=1).one()
obj2 = MyTable2.query.filter_by(id=1).one()
obj1.name = str(random.random())
obj2.name = str(random.random())
db.session.commit()
```

the SQL emitted might update `MyTable` before `MyTable2`, or `MyTable2` before `MyTable`. The order might be different at every execution.

Now, imagine I need to call `db.session.flush()` before commit:

```python
obj1 = MyTable.query.filter_by(id=1).one()
obj2 = MyTable2.query.filter_by(id=1).one()
obj1.name = str(random.random())
obj2.name = str(random.random())
db.session.flush()

// do some work
time.sleep(.5)

db.session.commit()
```

With PostgreSQL, this update on a UNIQUE field requires to get a row lock. If this code runs concurrently, one execution might update `MyTable` before `MyTable2`, and another `MyTable2` before `MyTable` causing a deadlock.

**Expected behavior**

Queries execution should be repeatable. Updates should always be done in the same order.
Even better, the order could be specified with `db.session.add`, so `db.session.add(obj1); db.session.add(obj2);` should always update `obj1` before `obj2`.

**To Reproduce**

```python
import os
import random
import time
import sys

from flask import Flask
from flask_sqlalchemy import SQLAlchemy


CHILDREN = 10


# Create several process
for _ in range(CHILDREN):
    pid = os.fork()
    # pid == 0 for child process, only continue for the parent
    if not pid:
        break

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres@db/toto'
db = SQLAlchemy(app)


class MyTable(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)

class MyTable2(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)


# Seed database in parent.
if pid:
    db.create_all()
    MyTable.query.delete()
    MyTable2.query.delete()
    db.session.add(MyTable(id=1, name='xxx'))
    db.session.add(MyTable2(id=1, name='xxx'))
    db.session.commit()

    for _ in range(CHILDREN):
        os.wait()
    sys.exit()

# For child, wait until database is seeded.
else:
    time.sleep(.5)


while True:
    ot1 = MyTable.query.filter_by(id=1).one()
    ot2 = MyTable2.query.filter_by(id=1).one()

    ot1.name = str(random.random())

    # Uncomment this to fix the issue, and force MyTable to be always updated
    # before MyTable2.
    #db.session.flush()

    ot2.name = str(random.random())
    db.session.flush()

    time.sleep(.5)

    db.session.commit()
```

**Additional context**

The code to reproduce the issue might feel unlikely to exist in production. In reality, I have a flask API served by uWSGI. When the same update endpoint is called concurrently by two clients, two uWSGI workers run the same code but might execute the code in a different order, causing a PostgreSQL deadlock.

**Comment by brmzkw** [comment]
The problem comes from https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/unitofwork.py#L441

`UOWTransaction` has an attribute named `dependencies` of type set. In my example it could be equal to `{(SaveUpdateAll(mapped class MyTable->my_table), DeleteAll(mapped class MyTable->my_table)), (SaveUpdateAll(mapped class MyTable2->my_table2), DeleteAll(mapped class MyTable2->my_table2))}`.

A set is supposed to be ordered, but here it contains tuples of objects, so the order is determined by the objects' locations in memory, which vary over time.

To make the updates order deterministic, you can replace:

```python
for rec in topological.sort(self.dependencies, postsort_actions):
    rec.execute(self)
```

with:

```
for rec in sorted(
    topological.sort(self.dependencies, postsort_actions),
    key=lambda a: a.mapper.tables[0].name
):
    rec.execute(self)
```

Of course, the `key` I am suggesting here is not the one that should be used. It is just a quick hack to demonstrate how the problem could be fixed, but I am not aware enough of SQLAlchemy internals to provide a `key` that makes sense.

**Comment by CaselIT** [comment]
Hi, thanks for the great mcve and for pointing to the probably cause!

It's probably irrelevant in this case, but are you using the 1.3 series or the 1.4 beta version of sqlalchemy?

**Comment by zzzeek** [comment]
so, this issue has a little bit of similarity to #2501 but not that much.  in #2501 the issue is that the determined sort still does not accommodate for an edge case where rows with unique constraints are being swapped, and users have to use flush() to sort it out for now.

in SQLAlchemy unit of work, the determined sorting is as follows:

1. sorting is first performed at the level of target table, using a topological algorithm that uses mapper configurational structures to determine dependencies, these are the relationship() construct as well as some inheritance-related structures

2. if there are no dependency cycles between the target tables, the flush proceeds as:

   a. within a particular table, INSERT operations are processed in the order in which objects were add()'ed
   b. within a particular table, UPDATE and DELETE operations are processed in primary key order

SQLAlchemy's "deterministic" system goes that far right now when there are no inter-row dependencies between tables or a table to itself.

3. if there are dependency cycles between target tables, the per-table lists of objects among the affected tables are broken out into per-object records which are then toplogically sorted against each other.   INSERTS, UPDATES and DELETES proceed in the ordering given in 2, but only within subsets of objects that were not otherwise dependent on each other.

the system is oriented towards *not* going into #3 if at all possible, because this is a much less efficient road to travel.  it has to sort among all objects individually and also causes there to be lots more smaller operations of INSERT/UPDATE/DELETE that can't be batched.

so if we were to take your original proposal that .add() order would be honored among all INSERT, UPDATE, DELETE across all tables at once, we'd need to throw out item 2 altogether and have a more complicated per-item sort in all cases that would also be a whole new ballgame with new kinds of cycle-oriented issues coming up, etc.

your second proposal is closer to how this should be done, however it's not correct to "sort" the items coming back from topological sort because we are then unordering the answer it gave us.   toplogical.sort() has a "determnistic_order" flag so that if you give the items in a fixed order you will get the same answer every time, so to add this feature looks like:

```diff
@@ -422,6 +422,10 @@ class UOWTransaction(object):
     def execute(self):
         postsort_actions = self._generate_actions()
 
+        postsort_actions = sorted(
+            postsort_actions,
+            key=lambda item: item.sort_key,
+        )
         # sort = topological.sort(self.dependencies, postsort_actions)
         # print "--------------"
         # print "\ndependencies:", self.dependencies
@@ -438,7 +442,9 @@ class UOWTransaction(object):
                     n = set_.pop()
                     n.execute_aggregate(self, set_)
         else:
-            for rec in topological.sort(self.dependencies, postsort_actions):
+            for rec in topological.sort(
+                self.dependencies, postsort_actions, deterministic_order=True
+            ):
                 rec.execute(self)
 
     def finalize_flush_changes(self):

```

pretty easy.   the problem of course is that this is less performant, as we need to create a "sort_key" for all the unit of work objects (I have that in the patch), we have to add a sorted() step, and then the deterministic_order flag uses a homegrown OrderedSet that is faster than the one Python provides but still pretty slow compared to set().

We can try to take advantage of Python 3.7 ordered dictionaries to implement a new insert-order set that is more lightweight and I might prefer to do that first before implementing this.  nevertheless I will push up the review for this so that it can be worked on at some point however this is not highest priortity at the moment.    The above unit of work rules have been the same for about 15 years and this is the first time this issue has ever been reported, so I hope for the meantime you can stick with that flush() step in there.

**Comment by zzzeek** [comment]
note that the above fix does cause your test case to run without errors.

**Comment by brmzkw** [comment]
> It's probably irrelevant in this case, but are you using the 1.3 series or the 1.4 beta version of sqlalchemy?

I'm using v1.3.20.

> [...]

As usual, thanks a lot for the detailed explanations @zzzeek. Adding a second `flush()` ([here](https://github.com/openmaraude/APITaxi/commit/44b3a8afbf8f5a755ddaded8c0746ffba22ce197)) was enough to fix the problem for me.

I have been using SQLAlchemy for probably 10 years or so for simple or more complex projects, and it is the first time I encounter the issue. I discovered this bug because one of my clients does the same API query 3 times instead of 1. Who knows why. On the one hand, I tend to agree that it is a very low priority issue. On the other hand, I believe it is not uncommon to update several objects from the same transaction in a concurrent application.

**Comment by zzzeek** [comment]
consider if we want to use something like https://pypi.org/project/orderedset/ which is in cython for all of our orderedset needs.  this would just solve the problem of all the orderedset stuff we have, as in 1.4 we are getting a little more friendly with dependencies in any case.

**Comment by CaselIT** [comment]
> consider if we want to use something like https://pypi.org/project/orderedset/ which is in cython for all of our orderedset needs.  this would just solve the problem of all the orderedset stuff we have, as in 1.4 we are getting a little more friendly with dependencies in any case.

It seems that orderedset does bot ship wheels so it's less that ideal, since we should still keep both implementations for Windows ( and Mac) users that usually may not have compilers installed

**Comment by CaselIT** [comment]
> 
> 
> > consider if we want to use something like https://pypi.org/project/orderedset/ which is in cython for all of our orderedset needs.  this would just solve the problem of all the orderedset stuff we have, as in 1.4 we are getting a little more friendly with dependencies in any case.
> 
> It seems that orderedset does not ship wheels so it's less that ideal, since we should still keep both implementations for Windows ( and Mac) users that usually may not have compilers installed

Indeed it does not provide a fallback on windows:
```
ERROR: Failed building wheel for orderedset
  Running setup.py clean for orderedset
Failed to build orderedset
```

**Comment by zzzeek** [comment]
ugh.    trying to move past fallback stuff.    how hard is it to contribute a .github setup for them ?   we can open an issue on their tracker.  howver would be good to test the library first to make sure it is usable.

**Comment by CaselIT** [comment]
>We can try to take advantage of Python 3.7 ordered dictionaries to implement a new insert-order set that is more lightweight and I might prefer to do that first before implementing this.

I was taking a look and also OrderedDict can be updated to be a normal dict, if we can avoid the need for `sort`. And depending on how often we sort it may be worth it regardless even if sort becomes a slower.

**Comment by CaselIT** [comment]
> 
> 
> > We can try to take advantage of Python 3.7 ordered dictionaries to implement a new insert-order set that is more lightweight and I might prefer to do that first before implementing this.
> 
> I was taking a look and also OrderedDict can be updated to be a normal dict, if we can avoid the need for `sort`. And depending on how often we sort it may be worth it regardless even if sort becomes a slower.

Seems that sort is used only in the mapper config, so it should be ok of we take a bit longer there.

See gerrit here https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2396

**Comment by sqla-tester** [comment]
**Federico Caselli** referenced this issue:

**Replace ``OrderedDict`` with a normal ``dict`` in python 3.7+** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2396

**Comment by mrsarm** [comment]
I use in a project Python 3.10 and SQLAlchemy SQLAlchemy 2.0.17, and this error persists, not sure why it was closed. The call to `flush()` solves the problem, but is not an ideal solution.

I use Postgres 12.14, and:

```shell
$ pip freeze | grep -i SQLAlchemy
Flask-SQLAlchemy==3.1.1
SQLAlchemy==2.0.17
SQLAlchemy-Utils==0.41.2
```

**Comment by CaselIT** [comment]
Can you reproduce using the original example? If not please open a new issue with your failing example, thanks!

**Comment by dev-nasir-iqbal** [comment]
set the transaction level serializable like that after initialization of database
```
with app.app_context():
            db.session.execute(
                text("SET TRANSACTION ISOLATION LEVEL SERIALIZABLE"))
```

**Comment by zzzeek** [comment]
hi everyone, this issue is four years old.  please open a new issue with a proper MCVE thank you

**Comment by zzzeek** [comment]
just as a note, I would open a new discussion here, using SERIALIZABLE causes failures for reasons other than are what are stated in this issue.  

A full test that exercises the above withotu using flask:

```py
from sqlalchemy import *
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import *


import os
import random
import time
import sys
from sqlalchemy import create_engine

CHILDREN = 10



engine = create_engine("postgresql://scott:tiger@localhost/test", echo=True) #, isolation_level="SERIALIZABLE")


Base = declarative_base()

class MyTable(Base):
    __tablename__ = 'mytable'
    id = Column(Integer, primary_key=True)
    name = Column(String(80), unique=True, nullable=False)


class MyTable2(Base):
    __tablename__ = 'mytable2'
    id = Column(Integer, primary_key=True)
    name = Column(String(80), unique=True, nullable=False)

Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)


with Session(engine) as session:
    session.add(MyTable(id=1, name="xxx"))
    session.add(MyTable2(id=1, name="xxx"))
    session.commit()


# Create several process
for _ in range(CHILDREN):
    pid = os.fork()
    # pid == 0 for child process, only continue for the parent
    if not pid:
        break


if pid:
    for _ in range(CHILDREN):
        os.wait()
    sys.exit()

# For child, wait until database is seeded.
else:
    engine.dispose()
    engine = engine.execution_options(logging_token=f"pid: {os.getpid()}")
    time.sleep(0.5)


while True:
    with Session(engine) as session:
        print(f"PID {os.getpid()} GO")
        ot1 = session.query(MyTable).filter_by(id=1).one()
        ot2 = session.query(MyTable2).filter_by(id=1).one()

        ot1.name = str(random.random())

        # Uncomment this to fix the issue, and force MyTable to be always updated
        # before MyTable2.
        # session.flush()

        ot2.name = str(random.random())
        session.flush()
        print(f"PID {os.getpid()} DONE")

        time.sleep(0.5)

        session.commit()

```

adding the SERIALIZABLE causes concurrency errors but this is not due to order of operations, which remains deterministic

**Comment by zzzeek** [comment]
in particular, adding the `session.flush()` that "fixes" the issue previously does not solve the issue when SERIALIZABLE is in effect.

short answer: never use SERIALIZABLE, basically
