### ISSUE TITLE
Column alias in deeply nested subquery is truncated in Oracle

### ISSUE THREAD

**Issue by mkmoisen** [sqlalchemy/sqlalchemy#5772]
**Describe the bug**
With the Oracle dialect, when selecting a column alias from a deeply nested subquery, where the alias is longer than 24 characters, the alias in the outside select is truncated to 24 characters and then a '_' || i is concatenated, where i is the number of aliases being selected. However, the alias in the inside select is not truncated, leading to an ORA-00904 invalid identifier.

Interestingly, this behavior does not exist for 0 levels of nesting or 1 levels of nesting. Only after 2 levels does the alias get truncated.

A workaround is to set `oracle.dialect.max_identifier_length = 128`. (Incidentally, since Oracle 12.2, identifiers can be 128 characters. However SQLAlchemy assumes that the identifiers max length is 30.)

**Expected behavior**
Regardless of the number of nested select statements, a user created alias should not be truncated if it is longer than 24 characters.

I think what is happening is that by the second nested query, sqlalchemy loses track of whether or not the user created the alias, and it starts truncating.

**To Reproduce**

    from sqlalchemy import table, column, select
    from sqlalchemy.dialects import oracle
    import sqlalchemy

    def print_sql(statement):
        sql = str(statement.compile(dialect=oracle.dialect()))
        print(sql)

    # engine = sqlalchemy.create_engine('oracle://user:pass@db')
    # conn = engine.connect()

    foo = table('foo', column('a'), column('b'))

    # This is fine, it does not truncate with 0 levels of nesting
    sel = select([
        foo.c.a.label('this_identifier_is_24___'),
        foo.c.a.label('this_identifier_is_25____'),
        foo.c.a.label('this_identifier_is_26_____'),
        foo.c.b.label('this_identifier_is_30_________'),
        foo.c.a.label('this_identifier_is_40___________________'),
        ])
    
    print_sql(sel)
    # print([row for row in conn.execute(sel)])

    # This is also fine, it does not truncate with 1 level of nesting
    sel2 = select(sel.c).select_from(sel)
    print_sql(sel2)
    # print([row for row in conn.execute(sel2)])

    # Bug is here: the identifiers in the outermost select are truncated
    # while the identifiers in the two inner selects are not
    sel3 = select(sel2.c).select_from(sel2)
    print_sql(sel3)
    # Fails with cx_Oracle.DatabaseError: ORA-00904 invalid identifier
    # print([row for row in conn.execute(sel3)])

    # Work around: set max_identifier_length = 128 (Oracle 12.2 max)
    # Now it works fine. However this would still be an error if the
    # user created an alias of length between 123 and 128.
    oracle.dialect.max_identifier_length = 128
    print_sql(sel3)
    # print([row for row in conn.execute(sel3)])
   
**Versions.**
 - OS: Windows
 - Python: 3.6.5
 - SQLAlchemy: Tested on 1.2.10 and 1.3.20
 - Database: Oracle 12.2
 - DBAPI: cx_Oracle 6.4.1

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
Hey there-

Looking only at the 1.3 series and testing against Oracle 11, I'm not able to reproduce your issue into "one" level of nesting because your query fails immediately with no nesting:

```
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00972: identifier is too long
[SQL: SELECT foo.a AS this_identifier_is_24___, foo.a AS this_identifier_is_25____, foo.a AS this_identifier_is_26_____, foo.b AS this_identifier_is_30_________, foo.a AS this_identifier_is_40___________________ 
FROM foo]

```

this is because the 40-character label is intentionally longer than what Oracle 11 can support, and even though SQLAlchemy's default label length in the 1.3 series for Oracle is 30 characters, it does not truncate a user-defined label.

As far as the observation that using a label that is 40 characters long when the label length on ``oracle.dialect()`` is set to 30 characters leads to problems when you start to build nested queries, that's not significant because that is all undefined behavior, it is erroneous to be using a 40 character label when the label length is 30.

However, when you test your script on a newer version of oracle (which on this end I don't have installed yet), per [the documentation](https://docs.sqlalchemy.org/en/13/dialects/oracle.html#max-identifier-lengths) you should be immediately seeing a warning which will instruct how to correctly configure the engine, and it should be pretty noticeable because it's a long one:

            util.warn(
                "Oracle version %r is known to have a maximum "
                "identifier length of 128, rather than the historical default "
                "of 30. SQLAlchemy 1.4 will use 128 for this "
                "database; please set max_identifier_length=128 "
                "in create_engine() in order to "
                "test the application with this new length, or set to 30 in "
                "order to assure that 30 continues to be used.  "
                "In particular, pay close attention to the behavior of "
                "database migrations as dynamically generated names may "
                "change. See the section 'Max Identifier Lengths' in the "
                "SQLAlchemy Oracle dialect documentation for background."
                % ((self.server_version_info,))
            )

So first off please confirm you are seeing the above warning when you test your script with a live Oracle 12.2 + database, otherwise that would be a different issue.  The above warning is part of the migration of max_identifier_length to 128 which is the default in SQLAlchemy 1.4 and that is issue #4857 .

As the warning illustrates, you should be setting this parameter right up front in your create_engine until 1.4 where it will be automatic:
 
    engine = create_engine("oracle://...", max_identifier_length=128)

if you can clarify that you are getting the warning then we can close this.

**Comment by zzzeek** [comment]
if I change the oracle version number here to 10.2 and run on my 11.2 database I definitely get the warning, you should be seeing this:

`/home/classic/dev/sqlalchemy/lib/sqlalchemy/dialects/oracle/base.py:1377: SAWarning: Oracle version (11, 2, 0, 2, 0) is known to have a maximum identifier length of 128, rather than the historical default of 30. SQLAlchemy 1.4 will use 128 for this database; please set max_identifier_length=128 in create_engine() in order to test the application with this new length, or set to 30 in order to assure that 30 continues to be used.  In particular, pay close attention to the behavior of database migrations as dynamically generated names may change. See the section 'Max Identifier Lengths' in the SQLAlchemy Oracle dialect documentation for background.
`

**Comment by mkmoisen** [comment]
@zzzeek In our application we are using sqlalchemy 1.2.10. I do not see the warning in this version, but I just tried on sqlalchemy 1.3.20 and confirm that I see the warning (when I originally submitted this bug report, I also tried on 1.3.20 but didn't take notice of this). Thanks for the tip, I will add the `max_identifier_length=128` to my `create_engine` parameters.

However I think this issue can still potentially occur even while using the `max_identifier_length=128` - it is unlikely, but possible that someone creates an alias that is 128 characters (I would hope not anyways). Here is a reproducible script for this case, where the third level of nesting truncates the alias to 124 characters and concatenates a `'_1'` to the name:


    from sqlalchemy import table, column, select
    from sqlalchemy.dialects import oracle
    import sqlalchemy

    def print_sql(statement):
        sql = str(statement.compile(dialect=oracle.dialect(max_identifier_length = 128)))
        print(sql)

    # engine = sqlalchemy.create_engine('oracle://user:pass@db', max_identifier_length=128)
    # conn = engine.connect()

    foo = table('foo', column('a'), column('b'))

    # This is fine, it does not truncate with 0 levels of nesting
    sel = select([
        foo.c.a.label('a' * 128),  # 128 length alias
    ])
    print_sql(sel)
    # print([row for row in conn.execute(sel)])


    # This is also fine, it does not truncate with 1 level of nesting
    sel2 = select(sel.c).select_from(sel)

    print_sql(sel2)
    # print([row for row in conn.execute(sel2)])


    # Bug is here: the identifiers in the outer select are truncated
    # while the identifiers in the inner selects are not
    sel3 = select(sel2.c).select_from(sel2)
    # Can see the truncate to 124 characters, plus the '_1' added
    print_sql(sel3)
    # Fails with cx_Oracle.DatabaseError: ORA-00904 invalid identifier
    # print([row for row in conn.execute(sel3)])

-----

Also, in your output above regarding the warning to use max_identifier_length=128, it states:

> SAWarning: Oracle version (11, 2, 0, 2, 0) is known to have a maximum identifier length of 128, rather than the historical default of 30

Oracle 11.2 has a max identifier length of 30 - the 128 length wasn't permitted until 12.2. I'm not sure if that is because you monkey patched the version to produce this output or not but just wanted to let you know.

Thanks and best regards.

**Comment by zzzeek** [comment]
OK well let's look more closely at what you have there, where I will run it on my Oracle 11 database that supports only 30 characters (yes the warning I showed you was where I changed the code locally to illustrate it).  The reason your example continues to do strange things is likely due to the non-idiomatic way in which you are constructing subqueries, feeding in the "sel.c" collection directly into another select() construct and selecting from non-named subqueries, all of which are not well supported patterns since they wont work on most databases; Oracle and SQLite are the only two major databases that don't throw an error for an un-named subquery, so in SQLAlchemy 1.4 [anonymous subqueries are deprecated](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#a-select-statement-is-no-longer-implicitly-considered-to-be-a-from-clause).

So if I take your example and convert it to the 30 character version for my Oracle 11 database, I can confirm if I select from "sel.c" and select() from a select() directly (a not-really-supported use case now deprecated), it does produce errors, and then if I convert the unnamed subqueries into SQLAlchemy's idiomatic version (which in 1.4 will be much more obvious), everything works again:

```
from sqlalchemy import table, column, select
from sqlalchemy.dialects import oracle
import sqlalchemy


def print_sql(statement):
    sql = str(
        statement.compile(dialect=oracle.dialect(max_identifier_length=30))
    )
    print(sql)


engine = sqlalchemy.create_engine(
    "oracle://scott:tiger@oracle1120", max_identifier_length=30
)
conn = engine.connect()

foo = table("foo", column("a"), column("b"))

# This is fine, it does not truncate with 0 levels of nesting
sel = select(
    [
        foo.c.a.label("a" * 30),  # 128 length alias
    ]
)
print_sql(sel)
print([row for row in conn.execute(sel)])


# This is also fine, it does not truncate with 1 level of nesting
subq = sel.alias()

sel2 = select([subq]).select_from(subq)

print_sql(sel2)
print([row for row in conn.execute(sel2)])


subq2 = sel2.alias()

sel3 = select([subq2]).select_from(subq2)
# Can see the truncate to 124 characters, plus the '_1' added
print_sql(sel3)
print([row for row in conn.execute(sel3)])

```

output looks like this:

```
SELECT foo.a AS aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
FROM foo
[]
SELECT anon_1.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
FROM (SELECT foo.a AS aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
FROM foo) anon_1
[]
SELECT anon_1.aaaaaaaaaaaaaaaaaaaaaaaa_1 
FROM (SELECT anon_2.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa AS aaaaaaaaaaaaaaaaaaaaaaaa_1 
FROM (SELECT foo.a AS aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
FROM foo) anon_2) anon_1
[]

```

so anyway, yes there are probably some bugs involving the placement of a select() inside of a select() but as that use case is deprecated in favor of using explicit subqueries/aliases, your example seems to work fine, which makes sense because all of our name/label truncation test cases are against that pattern.

**Comment by mkmoisen** [comment]
Hey @zzzeek Thanks for the explanation. It makes sense. Just of of curiosity, did supporting anonymous queries in sqlalchemy cause any issues for you that inclined you to remove support for them, or did you just want to make this change to standardize and simplify your development?

I see that in my current version I can use `sel = sel.alias('foo')` to give the subquery a better name than `anon_1`. In 1.4, will the `subquery` function also support this (or, can I continue to use the `alias` function) ?

The reason I ask is because I do not actually run the queries in the sqlalchemy connection. Rather, I construct dynamic queries/DML that will eventually be used in PLSQL packages which are also created dynamically. I use sqlalchemy to construct the sql and then I format it using another package. So for my rare use case, it is important to give everything human readable names.

**Comment by zzzeek** [comment]
There's less of an issue with an unnamed subquery as there is with having the select() object be the Python interface for such a subquery.   I wanted to have a select().join() method that acted the way people wanted, and I wanted people to stop using select.c and getting confused, as these are not the columns *in* the select, they're the columns one can select *from*.

so the reason for the change is so that select() is not the same as "subquery".   There's now a subquery() method that gives you such an object that presents the FromClause interface which is distinctly different from that of the Select object, as it should be.

the "anonymous" vs."named" part of it is really not very important at all, SQLAlchemy generates an anonymous name for any subquery() or alias() in any case so there's no reason not to have one.

more to come in a few...

**Comment by zzzeek** [comment]
anyway the "subquery()" function and the "alias()" methods on the select() object are equivalent.  they do the same thing.   if you want to refer to your SELECT as a parentheized package with its own columns, you call subquery() on it.   to the degree that it's important that you get a string that doesn't "export" a name of some kind, you can give it a predictable name and regex it out or we would be fine having an "unnamed" option if you could work on that feature.

**Comment by mkmoisen** [comment]
@zzzeek Thank you.
