### ISSUE TITLE
Documentation error: Hybrid Attributes

### ISSUE THREAD

**Issue by trin5tensa** [sqlalchemy/sqlalchemy#5773]
**Describe the bug**
v1.4 Documentation at ORM extensions | Hybrid Attributes states:

> When dealing with the Interval class itself, the hybrid_property descriptor evaluates the function body given the Interval class as the argument, which when evaluated with SQLAlchemy expression mechanics returns a new SQL expression:

```
>>> print(Interval.length)
interval."end" - interval.start
```

Instead of getting the expected `interval."end" - interval.start` I get `Interval.length`.
I am running SQLAlchemy 1.4.0b, Python 3.9  on macOS BigSur 11.0.1

**Expected behavior**
The expected result is as described in the manual.

**The fix?**
The expected result can be produced if the following code is substituted:
```
 print(f"{Interval.length.expression}")
```

**Comment by zzzeek** [comment]
hey @trin5tensa  -

Looks like it has been this way since 1.1.   Hybrids used to be much simpler, totally agnostic of the ORM in fact, then as the edge cases arrived I needed to install ORM-specific mechanics around them, so today we see them acting a lot like any other ORM-mapped attribute.

I will make this .expression but also I think we need a docstring for that, coming up.

**Comment by zzzeek** [comment]
that should come up on the site within an hour, thanks for reporting!
