### ISSUE TITLE
SymmetricEncryptionServerSide with salt

### ISSUE THREAD

**Issue by rasai** [sqlalchemy/sqlalchemy#5807]
Hi all, 

I originally meant to post this on the mail list, but I was not able to post even after joining the group. So I apologize if this question is out of place.

I'm trying to get the SymmetricEncryptionServerSide typedecorator example posted at (https://github.com/sqlalchemy/sqlalchemy/wiki/SymmetricEncryptionServerSide) to work with a random salt. I am prepending 6 random characters before encrypting, and removing these characters after decryption (I can post the code if needed, but it is pretty much identical to the example in the link). Unfortunately, this breaks the select example with the WHERE clause. The issue seems to be that the Query object encrypts instead of decrypting. And because the salting makes encrypting produce different results, the query turns up empty. 

Is there a way to force the Query class to decrypt the column instead of encrypting the search term when compiling the SQL statement? I tried to look through the documentation for the Query class and also the TypeDecorator's comparators, but I couldn't find how to switch which side of the where clause gets encrypted/decrypted. Now I understand that I could just build the query manually using text, but I would like to avoid that if possible.

Here are versions of what I am using.
 - Python: 3.9
 - SQLAlchemy: 1.3.22
 - Database: MariaDB

Any help would be greatly appreciated. Thanks in advance!

**Comment by zzzeek** [comment]
hey there -

the first example at https://github.com/sqlalchemy/sqlalchemy/wiki/SymmetricEncryptionServerSide does decrypt the column, since in that case the encrypted value is dependent on other factors that are on a per-row basis, not too different of a requirement than your "salt" value that is also part of the encrypted value.   I just ran it, here's the SQL generated for the WHERE clause:

```
SELECT CAST(aes_decrypt(a.enc_data, unhex(sha2(%s, %s)), a.init_vector) AS CHAR CHARACTER SET utf8) AS anon_1 
FROM a 
WHERE CAST(aes_decrypt(a.enc_data, unhex(sha2(%s, %s)), a.init_vector) AS CHAR CHARACTER SET utf8) = %s
2020-12-29 22:16:27,810 INFO sqlalchemy.engine.Engine [generated in 0.00017s] ('some key', 512, 'some key', 512, 'my data')

```

as you can see, the column_property version in the first example decrypts on the SQL side as you are requesting.    so i would adapt the first form, as the example states the "TypeDecorator" version is the more simplistic example.

**Comment by rasai** [comment]
Thank you for the fast response! I see, in hindsight I should've tried the first form as well. Sorry, I just assumed they both produced the same statement. I'll give that a go.

Though out of curiosity, is there a way to do this with TypeDecorators, Comparators/ComparatorFactories or any other supported tools? If it is possible to have column_expression be applied instead of the bind_expression at compile time, I think it would generate the desired statement.

**Comment by zzzeek** [comment]
you can use TypeDecorator but you need to have a "comparator" that is going to run the "decrypt" on the local column rather than running the "bind processor" on the compared value.   it can likely be done but you just need to work out the combinations of comparators etc.   it gets tricky pretty quickly.

**Comment by rasai** [comment]
I see. Yeah, I'll stick to the first example. Thank you so much for the quick response and the help!

Closing.
