### ISSUE TITLE
Improve lazy loading error in async driver

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5832]
When trying to access an unloaded or expired attribute with asyncio an error is raised since no hidden db requests can happen.

The current error is : `sqlalchemy.exc.InvalidRequestError: greenlet_spawn has not been called; can't call await_() here.`

A bit more details could probably be added there. An alternative may be to make the orm aware of it and re-reaise a more appropriate error

See example https://gist.github.com/Icebreaker454/e22ca806f4b8427f5560277cc32735b7

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Improve error message when await_ call errors** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2466

**Comment by zikphil** [comment]
I thought Lazy Loading was disabled with the Async Engine by default? Why does it still attempt to lazy load the resources?

**Comment by zzzeek** [comment]
> I thought Lazy Loading was disabled with the Async Engine by default? Why does it still attempt to lazy load the resources?

You actually can use lazy loading with the async engine by using the [greenlet wrapper](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#adapting-orm-lazy-loads-to-asyncio), and additionally the unit of work flush process, which also is running inside of a greenlet adapted to async, is internally using lazy loads of relationships and expired columns in order to do its work.

So it would not work for all the various lazy loading routines to be checking a flag "session.is_async" because these routines still need to emit the query under the realm of the "async" session.

As these routines need to fail in any case when called outside of the greenlet adapter, there is no real difference in the end result if it attempts to use the connection and fails, vs. if it checks on its own up front and fails. In the latter design, the implementation detail of implicit IO is being moved into the ORM that otherwise doesn't know about this detail.

If the solution here is still insufficient and people want a first class ORM level exception throw, IMO the best architecture would be for the exception raised here to be caught and re-thrown as a new exception object.  Which still means it attempts to emit the query.



> 
> I am having the same issue trying to serialize SQLAlchemy object with Marshmallow and if I dont load all the available relationships it fails because Marshmallow tries to access a value that is not loaded and instead of returning None, it just raise the exception above.

The attribute or collection is intended to represent state within the database, so if the application needs access to these attributes it must ensure that appropriate [eager loading](https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html) is applied.   Returning None would not be the appropriate default response; if the value of these attributes aren't needed, then they should not be accessed.   The Marshmallow serialize operation should be configured to not require these collections in order to do its work if this state isn't needed, it's wasteful otherwise.

To make relationships return None by default can be achieved by setting "noload" as the lazy loading strategy (see https://docs.sqlalchemy.org/en/14/orm/relationship_api.html#sqlalchemy.orm.relationship.params.lazy) but "noload" may cause issues with flushes, such if a delete operation needed to load related objects and None were returned.   I would advise against using this setting in favor of making appropriate use of relationships.

**Comment by zikphil** [comment]
I just got back to SQLAlchemy and indeed I had forgotten about the relationship lazy default options. Might be a good thing to reference it in the lazy loading section of asyncio. `noload` fixed my issue and for those I really need I just added `selectin` directly in the ORM Model. 👍

**Comment by CaselIT** [comment]
I think it makes sense adding that section to the docs.

Will reopen this

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Improve noload documentation** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2529

**Comment by zikphil** [comment]
Actually `lazy="noload"` did not solve my issue because even when I attempt to manually load it in a query like this `select(Test).options(selectInLoad(Test.noload_relationship))` it does not work. Is it possible to have an option where we can tell the ORM to never attempt to load the relationship automatically unless I manually request it in a query?
