### ISSUE TITLE
Dependency on pysqlcipher3

### ISSUE THREAD

**Issue by hrishikeshrt** [sqlalchemy/sqlalchemy#5848]
File ``lib/sqlalchemy/dialects/sqlite/pysqlcipher.py`` depends on ``pysqlcipher3`` (https://pypi.org/project/pysqlcipher3/) which is no longer maintained (https://github.com/rigglemania/pysqlcipher3) and reads ``Security vulnerabilities may exist in this code. Use at your own risk.``
``sqlcipher3`` (https://github.com/coleifer/sqlcipher3) serves the same purpose as ``pysqlcipher3``, and is actively maintained.

Install of ``pysqlcipher3`` fails on some systems with python3.9+ due to deprecation of certain functions (``Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);``)
Which then causes import error in ``lib/sqlalchemy/dialects/sqlite/pysqlcipher.py``.

**Comment by zzzeek** [comment]
hi there -

Please note that for your immediate needs, you can use any DBAPI module you like by making use of the "module" argument:

```python

>>> import sqlcipher3
>>> from sqlalchemy import create_engine
>>> e = create_engine('sqlite+pysqlcipher://:testing@/foo.db?cipher=aes-256-cfb&kdf_iter=64000', module=sqlcipher3) 
>>> c = e.connect()

```

for the change, I'm not yet comfortable with any of the packages here.   Clearly we want to drop pysqlcipher entirely and if the author is claiming that it can't be guaranteed against security issues, that means we have to eradicate it from the code entirely, otherwise it becomes a CVE on our end.   So at the very least, we would need to document the above solution for Python 2 at least, as I assume (though I can't tell) that sqlcipher3 is Python 3 only.

for sqlcipher3 I am not getting a clear picture on if this package intends to be maintained either and overall I would want the "sqlcipher" community to make it a little more clear what should be used:

1. the README is not present on the pypi page, it's blank: https://pypi.org/project/sqlcipher3/
2. the code seems to be mostly that of pysqlcipher but isn't a fork, it's a new repo that starts up two years ago, what's that about ?
3. the package lacks proper trove classifiers, e.g. Python versions
4. the pysqlcipher README announces that it's no longer maintained, it should name a successor and/or simply allow itself to be transferred to the sqlcipher3 maintainer.   pysqlcipher still comes up at the top of searches, has more stars, etc.
5. most importantly there's nothing in sqlcipher3's readme at https://github.com/coleifer/sqlcipher3 that discusses its origins or maintenance intentions.  
6. While the sqlcipher3_binary package installs for me, the source distro had a strange failure mode in that it failed to build but then installed successfully anyway, not sure what that's about

since this is a package with security considerations, the bar is considerably higher for us to hardcode it within the module, only to find out the package has become insecure two years ago because the maintainer walked away from it.

The "dbapi" method that you've modified in #5849 could be altered to not import *any* DBAPI at all and simply point users to the above calling form; that way SQLAlchemy does not introduce security vulnerabilities by hardcoding to a library that might fall into an insecure state while we weren't looking.

At the very least, for your PR in #5849 it should be emitting a warning when pysqlcipher is used and in 1.4 I would be comfortable moving to "explicit DBAPI required" mode, as we are still supporting Python 2 for the 1.4 series.

**Comment by rhamnett** [comment]
A small but potentially confusing point - The logic is slightly incorrect on the exception raise it is printing the outer exception for the inner try. It should be:

```python
  @classmethod
    def dbapi(cls):
        try:
            from pysqlcipher import dbapi2 as sqlcipher
        except ImportError as e:
            try:
                from pysqlcipher3 import dbapi2 as sqlcipher
            except ImportError as ne:
                raise ne
        return sqlcipher
```

**Comment by zzzeek** [comment]
> A small but potentially confusing point - The logic is slightly incorrect on the exception raise it is printing the outer exception for the inner try. It should be:
> 
> ```python
>   @classmethod
>     def dbapi(cls):
>         try:
>             from pysqlcipher import dbapi2 as sqlcipher
>         except ImportError as e:
>             try:
>                 from pysqlcipher3 import dbapi2 as sqlcipher
>             except ImportError as ne:
>                 raise ne
>         return sqlcipher
> ```

is this what you were referring towards at https://github.com/1200wd/bitcoinlib/issues/170#issuecomment-792220501 ?   We would need a PR to resolve this issue.

**Comment by zzzeek** [comment]
OK there's also a regression in the connect function for 1.4 i will try to get basic support up here.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Repair pysqlcipher and use sqlcipher3** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2671
