### ISSUE TITLE
echo=true with hide_parameters=false not working

### ISSUE THREAD

**Issue by tiagotaveiragomes** [sqlalchemy/sqlalchemy#5852]
**Describe the bug**
I am trying to use `sqa.create_engine(conn, echo=True, hide_parameters=False)` to log queries with actual parameter values, but it looks like the parameters are not being replaced.

**To Reproduce**
```py
import sqlalchemy as sqa

echo_engine = sqa.create_engine(
  "postgresql://localhost/postgres",
  echo=True,
  hide_parameters=False
)

echo_engine.execute(sqa.text("select :some_private_name"), {"some_private_name": "1"})
```

**Error**
```
2021-01-19 19:23:07,829 INFO sqlalchemy.engine.base.Engine select version()
2021-01-19 19:23:07,829 INFO sqlalchemy.engine.base.Engine {}
2021-01-19 19:23:07,832 INFO sqlalchemy.engine.base.Engine select current_schema()
2021-01-19 19:23:07,833 INFO sqlalchemy.engine.base.Engine {}
2021-01-19 19:23:07,840 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-01-19 19:23:07,840 INFO sqlalchemy.engine.base.Engine {}
2021-01-19 19:23:07,844 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-01-19 19:23:07,844 INFO sqlalchemy.engine.base.Engine {}
2021-01-19 19:23:07,845 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2021-01-19 19:23:07,845 INFO sqlalchemy.engine.base.Engine {}
2021-01-19 19:23:07,847 INFO sqlalchemy.engine.base.Engine select %(some_private_name)s
2021-01-19 19:23:07,847 INFO sqlalchemy.engine.base.Engine {'some_private_name': '1'}
```

I would expect `select %(some_private_name)s` to be `select 1`

**Versions.**
 - OS: MacOS BigSur
 - Python: python3.8
 - SQLAlchemy: 1.3.22
 - Database: postgresql
 - DBAPI: postgresql://

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there -

"hide_parameters" is documented at https://docs.sqlalchemy.org/en/13/core/engines.html?highlight=hide_parameters#sqlalchemy.create_engine.params.hide_parameters and already defaults to False.   This parameter when set to True means that the log output will not show the parameters being passed, however it does not disable the usage of [bound parameters](https://docs.sqlalchemy.org/en/14/glossary.html#term-bound-parameter).

it looks like you are trying to use "inline literal" bound parameters, see the FAQ entry at https://docs.sqlalchemy.org/en/14/faq/sqlexpressions.html#how-do-i-render-sql-expressions-as-strings-possibly-with-bound-parameters-inlined for how this works as far as stringifying statements.

To disable "bound parameters" when actually executing SQL, SQLAlchemy does not encourage this pattern since it's a security hazard.  with text() you can do it simply as rendering the phrase inline:

    text("SELECT '1'")

or in 1.4 only you can use the literal_execute flag to create a bound parameter that will render inline:
```

import sqlalchemy as sqa

echo_engine = sqa.create_engine(
    "postgresql://scott:tiger@localhost/test", echo=True, hide_parameters=False
)

# SQLAlchemy 1.4 only
echo_engine.execute(
    sqa.text("select :some_private_name").bindparams(
        sqa.bindparam("some_private_name", literal_execute=True, type_=sqa.String)
    ),
    {"some_private_name": "1"},
)

```

however there is no option to transparently disable the use of bound parameters.

**Comment by tiagotaveiragomes** [comment]
Thank you very much for the clarification!

Maybe I can illustrate my difficulty with my use case.
I need to write to a file the SQL generated from pandas `df.to_sql()` method using an engine object. 

With the `echo=True` flag the queries are logged to `std.out` with the actual parameter values.
However when I do `logging.getLogger('sqlalchemy.engine').addHandler(logging.FileHandler(...))` the logged queries on the file do not show the bound parameter values. 

Thank you so much!

**Comment by tiagotaveiragomes** [comment]
So I ended up passing a logger at the DBAPI level by building the connection object on the `do_connect` event handler.  

```py
import logging
logging.basicConfig(level=logging.DEBUG)

import psycopg2
import sqlalchemy as sqa

handler = logging.FileHandler(filename="sql.log", mode="w")

sql_logger = logging.getLogger(__name__)
sql_logger.addHandler(handler)

@event.listens_for(sqa.engine.Engine, "do_connect")
def receive_do_connect(dialect, conn_rec, cargs, cparams):
  cparams["connection_factory"] = psycopg2.extras.LoggingConnection
  conn = psycopg2.connect(*cargs, **cparams)
  conn.initialize(sql_logger)
  return conn

engine = sqa.create_engine(metadata.conn) # Will log the actual queries to the file

df.to_sql(engine, ...)
```

Thank you for you help understanding this matter!

**Comment by zzzeek** [comment]
hey there -

OK, using events is one way to do it, but also you can have logging written to a file with your handler using standard Python logging idioms:

    logging.getLogger("sqlalchemy.engine").addHandler(my_handler)

logging is covered at https://docs.sqlalchemy.org/en/13/core/engines.html#configuring-logging

**Comment by tiagotaveiragomes** [comment]
That is right, but I can't get the query to come with the parameters replaced :)

**Comment by zzzeek** [comment]
oh I see you used a psycopg2 object that gives you the parameters embedded.  That's not something that would be available for any other backend, but that's handy, nice job!
