### ISSUE TITLE
Unnecessary unique constraint on primary key

### ISSUE THREAD

**Issue by fruttasecca** [sqlalchemy/sqlalchemy#5886]
Hi there, I have been noticing that the sqlalchemy ORM layer issues an unnecessary unique constraint to columns that are primary keys. I haven't had any luck finding out why this is the case and when it is desirable. 

```python
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer

conn = "postgresql://postgres@<set me>/<set me>"
engine = create_engine(conn, echo=True)
Base = declarative_base()

class User(Base):
     __tablename__ = 'users'

     id = Column(Integer, primary_key=True, unique=True)
     def __repr__(self):
        return str(self.id)

Base.metadata.create_all(engine)
```

This is the resulting command:
```sql
CREATE TABLE users (
	id SERIAL NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (id)
)
```

**Versions**
 - OS: Ubuntu 18.04
 - Python: 3.7.6
 - SQLAlchemy: 1.3.13
 - Database: PostgreSQL 13.1 (Debian 13.1-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
 - DBAPI: psycopg2, 2.8.6

Thank you

**Comment by CaselIT** [comment]
Hi,

This happens because you are also specifying `unique=True` in the column definition. If you remove it it should no longer render the unique constraints.
As to why it happens, I think it's because the primary key and unique constraints are considered separately and for multi-column primary key the two would not be equivalent.
