### ISSUE TITLE
2.0 Style Queries: count function

### ISSUE THREAD

**Issue by zikphil** [sqlalchemy/sqlalchemy#5908]
Hello,

Is there an equivalent to https://docs.sqlalchemy.org/en/14/orm/query.html?highlight=count#sqlalchemy.orm.Query.count while using the 2.0 style queries with the AsyncEngine or do we require to build the full query as described in the documentation?

Thanks!

**Comment by zzzeek** [comment]
Hi Philippe -

so query.count() is one of those functions that seems very simple but has caused nothing but problems for many years, as it is not always clear what it is people want to be counting when queries are more complicated.

as the 1.4/2.0 approach is now based on use of select(), it's really not very complicated to do a simple count:

```
count = session.scalar(
    select(func.count()).select_from(MyEntity)
)
```

using `func.count()` without an argument will render "COUNT *".

contrast this to the legacy format:

    count = session.query(MyEnitity).count()

the legacy format is clearly less SQL-ish, but the new API is all about looking like SQL.    I'm not sure how it could be made more succinct without creating a very arbitrary API that doesn't work for all cases.... ``session.count(MyEntity)`` ?  people usually want to do a WHERE clause.     ``session.scalar(count(MyEntity))``?   where ``count()`` is shorthand for ``select(func.count()).select_from(entity)``...I feel like little APIs like that just make it less clear what's actually going on.

For docs, I'm working on a new section about SQL functions in the 1.4 tutorial so I can add the example above.

**Comment by CaselIT** [comment]
@zzzeek what about passing `MyEnitity` to `func.count()`? Like maybe the shorthand could be `session.scalar(select(func.count(MyEntity)))`?

Using a table like `select(func.count(MyEntity.__table__))` almost works as expected, it currently renders `SELECT count() AS count_1 FROM my_entity`.
Would In general make sense passing a table/model to a function, aslo considering #3566?

**Comment by zzzeek** [comment]
if we wanted to make some kind of "convenience" here, I would not change how func.count() itself works, part of the "inconvenience" is having to be aware of "func" in the first place, and also it's very important that constructs meant to do a certain thing, in this case render the SQL function given, continue to do just that thing. 

I dont think #3566 applies here because that's talking about SQL functions that explciitly receive tables.   count() doesn't do that:

```
sqlite> create table foo (data integer);
sqlite> insert into foo (data) values (1), (2), (3);
sqlite> select count(foo);
Error: no such column: foo

```

if we were to have any kind of API here it would be similar to what we already have for Query,which would be like `select(MyEntity).count()`.    

Here's an example of what does not work with a naive version of count.  Suppose there's lots of rows.  Then you write this:

    stmt = select(MyEntity).limit(2).count()

What value would you expect to be returned?   What's the SQL that generates this value?

**Comment by zzzeek** [comment]
or another one, like this:

    stmt = select(MyEntity.name).distinct().count()

What SQL do you render for that?

**Comment by zzzeek** [comment]
these are basically all the bugs we had for years that led to our current query.count() solution, that wraps the entire thing in a subquery and counts that, which continues to be criticized for its inefficiency in the simple case that someone wants to do "select count(*) from table".     For a long time we had a huge bit of logic that was guessing which one we should render, here's that: https://github.com/sqlalchemy/sqlalchemy/blob/rel_0_6_5/lib/sqlalchemy/orm/query.py#L1978   it also was buggy.          

This is why I've decided for a long time that trying to "hide" the SQL here is not helping.   People will be much less misled by simply thinking in terms of SQL, which here means they start with "SELECT COUNT(*)" explicitly, then they decide the FROM clause they want.  Otherwise this is a classic case of something that is very easy to write becoming completely mysterious.

**Comment by zikphil** [comment]
I ended up adding this function to my BaseModel

```
    @classmethod
    async def count(cls, filters):
        session = sqla_session.get()
        c_q = select(func.count()).select_from(cls)

        for k, v in filters.items():
            c_q = c_q.where(getattr(cls, k) == v)

        result = await session.scalar(c_q)

        return result
```

**Comment by CaselIT** [comment]
> I dont think #3566 applies here because that's talking about SQL functions that explciitly receive tables. count() doesn't do that:

pg is happy to do this `select count(foo) from foo`

>         for k, v in filters.items():
>             c_q = c_q.where(getattr(cls, k) == v)

you can also use [filter_by](https://docs.sqlalchemy.org/en/14/core/selectable.html?highlight=filter_by#sqlalchemy.sql.expression.Select.filter_by): `c_q = c_q.filter_by(**filters)`

**Comment by zzzeek** [comment]
yes that's only PG though, nobody else does that

**Comment by yomajo** [comment]
I will pray that going from:
`subquery.count()`

to

`db.session.execute(sa.select(sa.func.count(some_previous_stmt.froms[0].c.id)) ).scalar()`

was worth it.

**Comment by mazen-isstech** [comment]
> I will pray that going from: `subquery.count()`
> 
> to
> 
> `db.session.execute(sa.select(sa.func.count(some_previous_stmt.froms[0].c.id)) ).scalar()`
> 
> was worth it.

Jokes aside. :) By having `count` as a class rather than a method, I assume, increases flexibility by allowing the user to add custom aggregate functions.
