### ISSUE TITLE
Feasibility of support for mssql 2005/2008 in 1.4

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5930]
Version 1.4 has some errors on mssql2005 reflection, mainly because a column used to reflect index condition is missing.

From https://github.com/sqlalchemy/sqlalchemy/issues/5921#issuecomment-775110453

> The [change log](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-d336d859babeb66e0bdcba407bea5410) states that should support from 2005+ so that may be a bug.
>
> The change that introduced the use of that column was [6950272](https://github.com/sqlalchemy/sqlalchemy/commit/69502725db4829a84872697fd6569631d2a3c47f)

From https://github.com/sqlalchemy/sqlalchemy/issues/5921#issuecomment-775361382

> 
> 
> _(Re-opening to complete the discussion of whether 1.4 will continue to "support" SQL Server 2005.)_
> 
> Current master branch tested against SQL Server 2005 Standard:
> 
> pytest --db=mssql_198 C:/Users/Gord/git/sqla-gerrit/test/dialect/mssql/test_reflection.py
> 
> [test-dialect-mssql-test_reflection.txt](https://github.com/sqlalchemy/sqlalchemy/files/5946012/test-dialect-mssql-test_reflection.txt)
> 
> pytest --db=mssql_198 -k ComponentReflectionTest C:/Users/Gord/git/sqla-gerrit/test/dialect/test_suite.py
> 
> [suite-ComponentReflectionTest.txt](https://github.com/sqlalchemy/sqlalchemy/files/5946017/suite-ComponentReflectionTest.txt)

Ref #5921

**Comment by gordthompson** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/History_of_Microsoft_SQL_Server), the history of SQL Server 2005 was:

Release Date: 14 January 2005 — 16.1 years ago
Mainstream End Date: 12 April 2011 — 9.8 years ago
Extended End Date: 12 April 2016 — 4.8 years ago

IMO, an app running against a backend that old can just pin their version of SQLAlchemy to 1.3.x.

**Comment by CaselIT** [comment]
I have no particular preference one way or the other. On the other end we are still supporting oracle 8 that was released in 1997 :)

The filter fix should be easy to do. Or if we drop support we should update docs / code etc.

**Comment by klapaukh** [comment]
I went through the public inspector API and the only query that failed was `get_indexes` which was trying to use a non-existent column. 

The only other two "failures" were that `get_check_constraints` and `get_unique_constraints` raised Not Implemented exceptions, which seemed strange because that wasn't mentioned in the docs (in contrast to other methods where it was). 

Oracle 8 is certainly older! SQL Server is widespread enough that surely I'm not the only person who still needs to sometimes use the 2005 version of it? (I am really hoping that I'm not just the one weirdo user who wants something that no one else will ever use).

**Comment by gordthompson** [comment]
As for SQL Server 2008 (whose Extended Support ended 18 months ago), version 1.4 is not too happy with it, either.

[sqla_14_mssql_2008.txt](https://github.com/sqlalchemy/sqlalchemy/files/5951554/sqla_14_mssql_2008.txt)

**Comment by CaselIT** [comment]
Maybe we could restrict the scope here to just making that get index call pass.

Not having db available for the CI will inevitably lead to new incompatibilities to be introduced, so even if we make all test pass at this point in time, there is no guarantee that they will not break again in the future

**Comment by gordthompson** [comment]
Okay, I just ran `tox -e py37-mssql-backendonly` for 1.4 against a SQL Server 2012 Express instance. We hit the 25 failure/error limit with this one too. The difference is that while the 2008 errors were mainly

> Invalid object name 'INFORMATION_SCHEMA.SEQUENCES'

the 2012 errors were primarily 

> 'JSON_VALUE' is not a recognized built-in function name

Since these older versions will almost certainly never be part of CI testing I don't see any point in messing around with the tests to get them to skip. Instead, I suggest that we treat those older versions as either "unsupported" or "best effort" and if issues arise then fix them if we can (like #5921).

I propose

|   | SQLA 1.3 | SQLA 1.4 | SQLA 2.0 |
| - | --------- | ---------- | --------- |
| MSSQL 2000 and earlier | unsupported | unsupported | unsupported |
| MSSQL 2005 | best effort | unsupported¹ | unsupported |
| MSSQL 2008² | best effort | best effort | unsupported |
| MSSQL 2012 | supported | supported | we'll see …³ |
| MSSQL 2014 and newer | supported | supported | supported |

¹ known issues in 1.4 (like the reflection error that originally prompted this issue) → won't fix
² Extended Support end date: 9 July 2019
³ Extended Support end date: 12 July 2022 

Also, when we update the docs we should note that practically speaking the oldest version we can support in CI is SQL Server 2017 (the first version available for Linux).

**Comment by CaselIT** [comment]
I mostly agree Gord.

Regarding this reflection issue, the patch is very easy to do:
```diff
diff --git a/lib/sqlalchemy/dialects/mssql/base.py b/lib/sqlalchemy/dialects/mssql/base.py
index 674d54179..c0318e374 100644
--- a/lib/sqlalchemy/dialects/mssql/base.py
+++ b/lib/sqlalchemy/dialects/mssql/base.py
@@ -2894,16 +2894,22 @@ class MSDialect(default.DefaultDialect):
     @reflection.cache
     @_db_plus_owner
     def get_indexes(self, connection, tablename, dbname, owner, schema, **kw):
+        filter_definition = (
+            "ind.filter_definition"
+            if self.version_info >= MS_2008_VERSION
+            else "NULL as filter_definition"
+        )
         rp = connection.execution_options(future_result=True).execute(
             sql.text(
                 "select ind.index_id, ind.is_unique, ind.name, "
-                "ind.filter_definition "
+                "%s "
                 "from sys.indexes as ind join sys.tables as tab on "
                 "ind.object_id=tab.object_id "
                 "join sys.schemas as sch on sch.schema_id=tab.schema_id "
                 "where tab.name = :tabname "
                 "and sch.name=:schname "
                 "and ind.is_primary_key=0 and ind.type != 0"
+                % filter_definition
             )
             .bindparams(
                 sql.bindparam("tabname", tablename, ischema.CoerceUnicode()),
```

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Add supported database version for internal dialects** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2585

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Fix a reflection error for MSSQL 2005** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2594
