### ISSUE TITLE
SSL SYSCALL EOF detected error

### ISSUE THREAD

**Issue by danner26** [sqlalchemy/sqlalchemy#5955]
**Describe the bug**
I am really sorry if this is not the right place for this, but I am trying to cover all of my bases, throw out everything I have and see if I get a bite anywhere. Any help you may have to offer is greatly appreciated! 

Hello, we are plagued by the never ending SSL SYSCALL error. We are running out postgres database on an RDS using a db.t2.large. Resource wise it has plenty of space and resources, and the connections are set to an amount that is no where near being hit. We have been plagued with this issue for a long time, but I just recently was assigned to the issue. This tends to happen when we the following uwsgi ini:
```
[uwsgi]
binary-path = /usr/sbin/uwsgi
virtualenv = /opt/webapps/iamp/venv
strict = false
module = wsgi
plugins = python36
buffer-size = 16384
die-on-term = true
lazy-apps = false #make this true to fix syscall issue
single-interpreter = true

# NETWORK CONFIG
socket = :8080
chmod-socket = 660

# WORKER CONFIG
master = true
processes = 4 #reduce this to 1 if syscall issue persists
enable-threads = true
#vacuum = true
threads = 8
minspare = 4
```

When we do not use lazy-apps it appears that it causes this issue. Sometimes it wont happen right away, but once you start writing to the database we start getting flooded with these. It breaks our flask application as well on the front end. A full dump of the error page can be seen here: https://pastebin.com/s5CgBrGs and https://pastebin.com/ySeVivHe

When we turn lazy apps on the ssl syscall issue disappears. Any assistance figuring this out would be greatly appreciated. 

**Versions.**
 - OS: RHEL 8.3
 - Python: 3.6
 - SQLAlchemy: 1.3.23
 - Flask-SQLAlchemy version: 2.4.4
 - Database: Postgres 10.13
 - DBAPI:

**Comment by jvanasco** [comment]
`lazy-apps` causes uwsgi to load the application post-fork, instead of pre-fork.

the exception you are seeing is from psycogp2, and usually tied to:

* database connection/disconnect issue
* database is full or tables locked
* database is out of memory

because lazy-apps post-fork affects this, it makes me think you have some code in your application that was connecting to the database.  

my suggestion is to use the uwsgi postfork decorator (https://uwsgi-docs.readthedocs.io/en/latest/PythonDecorators.html#uwsgidecorators.postfork) and to write a snippet of code that will call `engine.dispose`  (https://docs.sqlalchemy.org/en/13/core/connections.html#engine-disposal)
