### ISSUE TITLE
Python 3.8.8 test failure

### ISSUE THREAD

**Issue by dotlambda** [sqlalchemy/sqlalchemy#5969]
**Describe the bug**
After updating from Python 3.8.7 to 3.8.8, the test `test_pyodbc_extra_connect_azure` fails.

**Error**
https://termbin.com/gtcf1

**Versions.**
 - OS: NixOS
 - Python: 3.8.8
 - SQLAlchemy: 1.3.20

**Comment by SuperSandro2000** [comment]
Posting the error again because I think termbin does not store them forever.

```
=================================== FAILURES ===================================
_______________ ParseConnectTest.test_pyodbc_extra_connect_azure _______________
[gw8] linux -- Python 3.8.8 /nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/bin/python3.8
Traceback (most recent call last):
  File "/build/SQLAlchemy-1.3.23/test/dialect/mssql/test_engine.py", line 171, in test_pyodbc_extra_connect_azure
    eq_(
  File "/nix/store/s16wy5k6fn1dfrvn7h3a6kl2apa9iw1v-python3.8-SQLAlchemy-1.3.23/lib/python3.8/site-packages/sqlalchemy/testing/assertions.py", line 238, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: False != True
assert False == True
  +False
  -True
```

**Comment by gordthompson** [comment]
That test had a bug that was fixed in

https://github.com/sqlalchemy/sqlalchemy/commit/7293b3dc0e9eb3dae84ffd831494b85355df8e73

**Comment by mcepl** [comment]
Well, I came up with [slightly more complicated version](https://github.com/sqlalchemy/sqlalchemy/files/6030986/tests_overcome_bpo42967.patch.txt).

**Comment by gordthompson** [comment]
My understanding is that semicolons were considered okay in the past but are in the process of being phased out due to the potential vulnerabilities mentioned in the Python bug report. So if Python is going to insist on ampersands from now on then that's what we should use. 

When I originally wrote the test I used a semicolon not because is was technically legal in URLs but because it is the separator for ODBC connection strings and I was "thinking ODBC". Had I been "thinking URL" I might have used an ampersand and then @CaselIT wouldn't have had to come along later and clean up my mess. ;)

**Comment by mcepl** [comment]
Whatever you prefer.

**Comment by CaselIT** [comment]
@mcepl we decided to go with the python implementation, so only ampersands will be considered query separator.

The first patch here https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2598/1..2 was actually a vendoring of the old version of the `parse_qsl`, but we came to the conclusion that it's best to follow python best practice.

The fix will also be in 1.3 branch, but it's not yet released. You can use the rel1_3 branch or apply the fix manually.

Closing this since it's already fixed

**Comment by mcepl** [comment]
Thank you, we will pick your patch on the next release.

**Comment by CaselIT** [comment]
the commit in the 1_3 brach is this one https://github.com/sqlalchemy/sqlalchemy/commit/47e64c690c4ebde3f0885f5c69419d3c3303818b
