### ISSUE TITLE
Row vs LegacyRow in engine vs session

### ISSUE THREAD

**Issue by dferreruw** [sqlalchemy/sqlalchemy#6051]
Hi! Thanks for all your work on SQLAlchemy -- I'm excited to adopt 1.4.

I'm hoping to get clarity on behavior I wasn't expecting when upgrading from latest 1.3 release to 1.4.0. In [the 1.4 docs](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#result-rows-act-like-named-tuples), I see this: "Already part of 1.4, the previous KeyedTuple class that was used when selecting rows from the Query object has been replaced by the Row class, which is the base of the same Row that comes back with Core statement results **(in 1.4 when not using the create_engine.future flag with an Engine, it is the LegacyRow class)**." (Emphasis mine.)

When I query using `engine.execute`, I get a LegacyRow object. However, when I query with `session.execute`, I get a Row object. Here's a basic example:
```python
import sqlalchemy
from sqlalchemy import orm

engine = sqlalchemy.create_engine("sqlite://")
session = orm.Session(bind=engine)

session.execute("CREATE TABLE foo (bar INTEGER PRIMARY KEY)")
session.execute("INSERT INTO foo VALUES(1)")
session.commit()

session_result = session.execute("SELECT * FROM foo")
type(session_result.first())
# <class 'sqlalchemy.engine.row.Row'>

engine_result = engine.execute("SELECT * FROM foo")
type(engine_result.first())
# <class 'sqlalchemy.engine.row.LegacyRow'>
```

I tested a few permutations of this: connecting to a MySQL database, using SQLAlchemy Core rather than raw SQL queries, and using a sessionmaker. In all cases, `session.execute` returns a Row object, whereas I would expect it to return a LegacyRow object. Is this behavior expected? Am I reading the docs wrong or setting something up incorrectly? Hoping to upgrade from 1.3 to 1.4 without needing to update existing code for breaking changes.

**Version info:**
- OS: Darwin
- Python: 3.8
- SQLAlchemy: 1.4.0
- Database: sqlite

**Comment by CaselIT** [comment]
Hi,

It seems consistent with what the documentation says. You need to pass `future=True` to the engine to use Row also then using connections.

>  Hoping to upgrade from 1.3 to 1.4 without needing to update existing code for breaking changes.

Off the top of my head there are some breaking changes, and many deprecation, so I think some code changes will be needed.
A couple of thinks from the example: `engine.execute` is deprecated. Also running `connection.execute` with a string is deprecated (if you expect the string to be run as is, and not coerced to text)

**Comment by dferreruw** [comment]
Thanks for the reply! Sounds like this is expected behavior.

Just to confirm, it's expected that using `session.execute` with a `future=False` engine is expected to return a CursorResult rather than a LegacyCursorResult? Example:
```python
import sqlalchemy
from sqlalchemy import orm

engine = sqlalchemy.create_engine("sqlite://")
session = orm.Session(bind=engine)

session.execute(sqlalchemy.text("CREATE TABLE foo (bar INTEGER PRIMARY KEY)"))
session.execute(sqlalchemy.text("INSERT INTO foo VALUES(1)"))
session.commit()

result = session.execute(sqlalchemy.text("SELECT * FROM foo"))
result.first().values()
# Works in SQLAlchemy 1.3
# Throws error in SQLAlchemy 1.4
```

I was reading the docs to mean that this would raise a deprecation warning rather than throwing an error, but I think I was misinterpreting.

**Comment by CaselIT** [comment]
Yes, I think so, since the new objects are needed to support the new calling styles that use select also for orm. cc @zzzeek 

Btw I think I could have been clear regarding the execute thing:
- Using str with session.execute was not changed, since it did already transform to `text()`
- connection/engine.execute does not use `text()` but pass the string directly. This has been deprecate. In 2.0 it will bo as the session and transform to `text()`
- connection has a new method to pass sql directly valle `exec_driver_sql` that does not transform to `text()`

Hope it clarifies things.

**Comment by zzzeek** [comment]
I will push a change to clarify the Row thing - Core connection.execute() returns either LegacyCursorResult or CursorResult depending on the "future" flag.

for the Session, there's no good combination that doesn't have some change because I wanted Session.execute() to work with ORM-enabled select() statements, so it returns 2.0 style results in both Core and ORM cases.    it is already a behavioral change that if you pass a select() against an ORM entity to session.execute() you get back an ORM-enabled result set.

that said I'm surprised people are calling methods like .values() on the row, usually just interpreting as a list() will give you the values alone and that should work in all SQLAlchemy versions.

**Comment by dferreruw** [comment]
Thank you both! I was also surprised to see this use of `.values()` in our code... it's some old code, so hopefully bumping to SQLAlchemy 1.4 is good justification to go back and use better style 🙂

Appreciate the doc update, and I'll go ahead and close this.
