### ISSUE TITLE
Back reference is not available after session end

### ISSUE THREAD

**Issue by Randelung** [sqlalchemy/sqlalchemy#6059]
**Describe the bug**
In an eager loading setup, back references are not accessible outside of session block (while inside the block no additional SQL queries are being produced).

**Expected behavior**
Outside of session block the back reference is still available.

**To Reproduce**
https://gist.github.com/Randelung/81e0ccacc28c8ed1c205c3da799b3882
Have classes referencing each other, `back_populates` and `backref` in `relationship` both produce the same result.
The example builds a tree structure of four types A, B, C, and D, and fills them with three children for each level.
Load the structure using eager loading (`joined` is used in example, `selectin` produces same result).
Try to access the back reference (done via print and \_\_repr\_\_) both inside and outside the session block.
It prints fine inside the session block, even though it's not fetching any more data from the database, but throws an error when outside (move print statement).

**Error**

```
Traceback (most recent call last):
  File "D:\Desktop\work\VL\test\script.py", line 61, in <module>
    asyncio.run(main())
  File "C:\Users\rando\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\rando\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete     
    return future.result()
  File "D:\Desktop\work\VL\test\script.py", line 58, in main
    print(result)
  File "D:\Desktop\work\VL\test\script.py", line 27, in __repr__
    return f'A({self.id},{self.name},{self.bs})'
  File "D:\Desktop\work\VL\test\script.py", line 38, in __repr__
    return f'B({self.id},{self.name},{self.a.id})'
  File "C:\Users\rando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\attributes.py", line 449, in __get__
    return self.impl.get(state, dict_)
  File "C:\Users\rando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\attributes.py", line 893, in get    value = self.callable_(state, passive)
  File "C:\Users\rando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\strategies.py", line 827, in _load_for_state
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <B at 0x2280d585d30> is not bound to a Session; lazy load operation of attribute 'a' cannot proceed (Background on this error at: http://sqlalche.me/e/14/bhk3)
```

**Versions.**
 - OS: Win10
 - Python: 3.9.2
 - SQLAlchemy: 1.4
 - Database: MariaDB 10.5
 - DBAPI: 2.0

**Have a nice day!**

Edit: simpler test case means shorter error log. Same error, though.

**Comment by zzzeek** [comment]
hey there -

your test case doesn't actually lllustrate "Outside of session block the back reference is still available.".   I ran it, and just had to add an engine dispose at the end:

    await engine.dispose()

no error is produced.

it looks like maybe your issue is that you have joinedload() calls in a cycle, which the ORM will not traverse by default as it would lead to a loop.     if you can pare down your test as it looks quite complicated and then demonstrate the issue more simply we can identify if that's the problem.

**Comment by Randelung** [comment]
Hey, sorry if it's not clear.
The `print` call is inside the session block in the gist - which is the working case, yes. In order to trigger the error, the print needs to be moved out of the session block, i. e. to the left.
I changed the gist so it'll trigger out of the box.

I'll try to remove two of the classes, the tree depth probably shouldn't matter.

**Comment by zzzeek** [comment]
great this is a simple issue.    joinedload at the relationship() level will not automatically traverse loops, because it leads to a cycle between the two tables that is inherently wasteful - think of  "SELECT A, B, A1 FROM A join B join A AS A1" - not a good look.


instead, those many to ones are in the identity map because they were just loaded as a collection.   one way to make this work is to use "immediateload" and the "lazy load" will trigger immediately inline with the query, which is not actually a "load" at all because it pulls from the identity map:


```python
class B(Base):
    __tablename__ = 'b'

    id = Column('id', Integer, autoincrement=True, primary_key=True)
    a_id = Column('a', Integer, ForeignKey('a.id'))
    a = relationship('A', back_populates='bs', lazy='immediate')
    name = Column('name', String(255))

    def __repr__(self) -> str:
        return f'B({self.id},{self.name},{self.a.id})'

```

using the above technique, you get only one SELECT, the first one for A + A->B.   the many to ones don't use a SELECT or a JOIN or anything.   Depending on what you are doing and which side you are loading from, you may need to use loader options at query time to set this up, because if you load a lot of Bs for many different As you would see a SELECT statement per unique A emitted, unless you set up some options.

Given that "selectinload" is much better for collections, that leads to the next approach, use "selectinload" on the collection side  then stick with "joinedload" on the many-to-one.   When the "selectinload" takes place, the "joinedload" for your many-to-ones works too.   This also means you can safely load from the many-to-one side only and have eager loading in both directions.   The joinedload on for B->A is still there somewhat unnecessary as you already loaded A, but at least the ORM will ignore those columns on the second query:


```python
class A(Base):
    __tablename__ = 'a'

    id = Column('id', Integer, autoincrement=True, primary_key=True)
    name = Column('name', String(255))
    bs = relationship('B', back_populates='a', lazy='selectin')

    def __repr__(self) -> str:
        return f'A({self.id},{self.name},{self.bs})'

class B(Base):
    __tablename__ = 'b'

    id = Column('id', Integer, autoincrement=True, primary_key=True)
    a_id = Column('a', Integer, ForeignKey('a.id'))
    a = relationship('A', back_populates='bs', lazy='joined')
    name = Column('name', String(255))

    def __repr__(self) -> str:
        return f'B({self.id},{self.name},{self.a.id})'

```

with the second approach you get two queries but they are fairly decent:

```
SELECT a.id, a.name 
FROM a
SELECT b.a AS b_a, b.id AS b_id, b.name AS b_name, a_1.id AS a_1_id, a_1.name AS a_1_name 
FROM b LEFT OUTER JOIN a AS a_1 ON a_1.id = b.a 
WHERE b.a IN (%s, %s, %s)

```


overall i think the main idea is to use two different kinds of loading on the two sides by default.

**Comment by zzzeek** [comment]
also note if you specify options in the select() statement, there is no pre-emption of the loop, it trusts you know what you're doing: 

```python
    async with Session() as session:
        result = (await session.execute(select(A).options(joinedload(A.bs).joinedload(B.a)))).unique().scalars().all()

```
```sql

SELECT a.id, a.name, b_1.a, a_1.id AS id_1, a_1.name AS name_1, b_1.id AS id_2, b_1.name AS name_2 
FROM a LEFT OUTER JOIN b AS b_1 ON a.id = b_1.a LEFT OUTER JOIN a AS a_1 ON a_1.id = b_1.a
```

**Comment by Randelung** [comment]
Awesome, thank you for your elaborate reply.
I have some composite keys and MariaDB doesn't seem to like that in conjunction with `selectin`, that's why I've been trying `joined`. I hadn't seen `immediate` before, it's not in the [doc](https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html)?

But i can report success for mixing all of them (just `immediate` everywhere didn't work, though). Anything in the tree above the composite keys is `joined`, below is `selectin` (I might change that to `joined`, too, though, just to not run into issues with the reverse if ever needed), and back references are `immediate`. Outside of the session, the parent attribues all work as expected.

Perfect. Thanks a lot for your help!

Working with asyncio, your [page on working with asyncio](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#synopsis-orm) has been a great help. May I suggest adding an example with declarative relationship options like you explained? The article already mensions `selectinload`, which can easily be translated into a `lazy=` parameter, but `immediate` isn't mentioned.

Have a great day! Cheers.

**Comment by CaselIT** [comment]
@zzzeek should there be a documentation for immediate?

**Comment by zzzeek** [comment]
it's documented at:

https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html#sqlalchemy.orm.immediateload

https://docs.sqlalchemy.org/en/14/orm/relationship_api.html#sqlalchemy.orm.relationship.params.lazy

right now.  it's not widely used and in this case I think joinedload/selectinload is better.

what is really not documented is the way the different eager loaders will stop on cycles when they are used at the class level.  this creates for the strange case that you can use two different kinds of eager loaders on each side, but not the same kind (at least not and see them both happen at once).    plus the way that options always do what is given vs. what relationship-level does.

**Comment by zzzeek** [comment]
I woudl say we can add some sub-bullets to the first bullet at https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#synopsis-orm indicating "other loader options that are helpful include:  immediateload, joinedload, subqueryload"

**Comment by CaselIT** [comment]
I missed the header in the [list](https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html) "The primary forms of relationship loading are:"
