### ISSUE TITLE
have dialect-specific inserts w/ upsert clauses intercepted by ORM "update w/ arbitrary whereclause"

### ISSUE THREAD

**Issue by pinguingman** [sqlalchemy/sqlalchemy#6143]
**Describe the bug**
After on_conflict_do_update updates db record you get old value by primary key of changed row.

**Expected behavior**
Expecting to get updated value

```py
from sqlalchemy.dialects.postgresql import insert

class TestModel(database.Model):
    uid = database.Column(database.String, primary_key=True)
    email = database.Column(database.String)

    def __init__(self, uid, email=None):
        self.uid = uid
        self.email = email

database.session.add(TestModel('test_uid', 'test_email'))
_ = database.session.query(TestModel).all()
stmt = insert(TestModel).values(
    uid='test_uid',
    email='test_email'
).on_conflict_do_update(
    index_elements=TestModel.__table__.primary_key.columns,
    set_={
        TestModel.email.name: 'new_email',
    },
    where=TestModel.uid == 'test_uid'
)
database.session.execute(stmt)

assert 'new_email' == TestModel.query.get('profile_0').email # fails
```

**Versions.**
 - OS: Linux Mint
 - Python: 3.7
 - SQLAlchemy: 1.4.3
 - Database: postgres
 - DBAPI: psycopg2

**Comment by zzzeek** [comment]
hi this is expected behavior right now.   Insert() statements are not intercepted by the ORM.    right now we only support special forms of [update and delete](https://docs.sqlalchemy.org/en/14/orm/session_basics.html#update-and-delete-with-arbitrary-where-clause).   additionally "on conlfict" is not database agnostic right now so it is unlikely this syntax can be intercepted by the ORM without new internal directives of some kind that could signal to it *how* it could be receiving this updated state in a database agnostic manner.

that said, it is a novel idea to send the statement directly to session.execute(), this would be a companion to the current proposed #5441 feature.

**Comment by zzzeek** [comment]
I sort of like this idea but I have no time to work on it, but ill keep it as a use case.

**Comment by pinguingman** [comment]
Are there any workarounds for this behavior? At the moment I have to discard the entire identity_map after on_conflict_do_update.

**Comment by zzzeek** [comment]
absolutely, you can do what the ORM does:

For all approaches, the goal is to get the list of primary key identities you care about, then look them all up in Session.identity_map(), and then Session.expire() each instance, sending the names of the keys you are updating, in this case ['name'].    Alternatively, you can set the new name on these instances using [set_committed_value](https://docs.sqlalchemy.org/en/14/orm/session_api.html#sqlalchemy.orm.attributes.set_committed_value).

Options to get the primary key values:

1. run a SELECT first with your WHERE clause, to acquire primary key identities that already match the criteria. 

2. (this is the best approach) use [returning()](https://docs.sqlalchemy.org/en/14/core/dml.html?highlight=insert%20returning#sqlalchemy.sql.expression.Insert.returning) to retrieve the primary key identities accessed by your statement.    Lots of these will be the newly inserted keys but it will also include the rows that were updated.

3. you can also use the [orm.evaluator](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/evaluator.py) directly with your WHERE criteria to locate the objects in the session rather than using a SELECT, but this requires scanning through the Session (which might be fine if it's small):

    from sqlalchemy.orm.evaluator import EvaluatorCompiler

    callable = EvaluatorCompiler(TestModel).process(TestModel.uid == 'test_uid')

    for obj in session:
        if callable(obj):
            session.expire(obj, ['email'])

The implementations that do this right now can be seen at https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/persistence.py#L1747

**Comment by pinguingman** [comment]
Using the second approach 'identity_map` is cleared correctly, but I would not like to have so much boilerplate after each 'on_conflict_do_update'. Is it possible to move this in some listener or override some module?

```py
from sqlalchemy.dialects.postgresql import insert

class TestModel(database.Model):
    uid = database.Column(database.String, primary_key=True)
    email = database.Column(database.String)

    def __init__(self, uid, email=None):
        self.uid = uid
        self.email = email

database.session.add(TestModel('test_uid', 'test_email'))
_ = database.session.query(TestModel).all()
stmt = insert(TestModel).values(
    uid='test_uid',
    email='test_email'
).on_conflict_do_update(
    index_elements=TestModel.__table__.primary_key.columns,
    set_={
        TestModel.email.name: 'new_email',
    },
    where=TestModel.uid == 'test_uid'
).returning(
            *TestModel.__table__.primary_key.columns
        )
# second approach 
to_expire = [(TestModel, row) for row in session.execute(stmt)]

for key, _ in database.session.identity_map.items():
    if (key[0], key[1]) in to_expire:
        instance = database.session.identity_map[key]
        database.session.expire(instance)

assert 'new_email' == TestModel.query.get('profile_0').email # success
```

**Comment by zzzeek** [comment]
wow we will actually get a recipe out of this.  yes!  use do_orm_execute(), somehing like:

```python
@event.listens_for(Session, "do_orm_execute")
def do_orm_execute(context):
    if context.is_insert and isinstance(context.statement, postgresql.Insert) and \
      context.statement._post_values_clause:
        result = context.invoke_statement()
        # <do your identity map thing>
        return result   # Session will know you ran the statement already
```

**Comment by pinguingman** [comment]
Thank you for your answers. Working solution:
```py
@event.listens_for(Session, "do_orm_execute")
def do_orm_execute(context):
        if (context.is_insert
            and isinstance(context.statement, postgresql.Insert)
            and hasattr(context.statement, '_post_values_clause')
            and context.statement.exported_columns):
        result = context.invoke_statement()
        to_expire = [
            (context.statement.table.entity_namespace, row) for row in result
        ]
        for key, _ in context.session.identity_map.items():
            if (key[0], key[1]) in to_expire:
                instance = context.session.identity_map[key]
                context.session.expire(instance)
        return result
```

**Comment by CaselIT** [comment]
We could extract a wiki recipe for this.

Btw it could be optimized by removing the second identity map lookup `instance​ ​=​ ​context​.​session​.​identity_map​[​key​]` by using the value retuned in the for

**Comment by pinguingman** [comment]
The problem when working with ' returning` is that the CursorResult is already iterated and does not contain the query result.
So 
```py
assert [row for row in session.execute(stmt)] == [] # true because we went through it in listener
```

**Comment by zzzeek** [comment]
So I left that part out because you were already using an INSERT that had no RETURNING, and I assumed you didn't need to actually consume the RETURNING separately plus I wanted to keep the recipe simple. 

you can split off the Result object into two independently consumable results first using [freeze](https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=result%20freeze#sqlalchemy.engine.Result.freeze) .     see the example at https://docs.sqlalchemy.org/en/14/orm/session_events.html#re-executing-statements .

**Comment by zzzeek** [comment]
hello me from 18 months ago, this all seems very complicated when we in fact have [this documented approach](https://docs.sqlalchemy.org/en/14/orm/persistence_techniques.html#using-postgresql-on-conflict-with-returning-to-return-upserted-orm-objects) that can run any kind of upsert with RETURNING and populate the ORM objects directly.  Additionally we will be trying to make this pattern more automatic in 2.0 as can be seen in #7865.

So that's the approach, no need to write events to manipulate the identity map, just plain populate_existing is used.   

If people involved in this issue see that I'm missing something or misunderstanding, please reopen, but for the moment it looks like what we have in the docs above and continuing to improve that pattern is the most straightforward way to go here.
