### ISSUE TITLE
allow txn.rollback() to be used inside of transaction.begin() block without a warning

### ISSUE THREAD

**Issue by Roguelazer** [sqlalchemy/sqlalchemy#6155]
**Describe the bug**
Calling the `.rollback()` method on a transaction inside a context manager results in an SAWarning being emitted. This is a normal behavior used to intentionally trigger a rollback/commit while still having the "guaranteed-to-be-closed-in-case-of-exception" behavior of a context manger.

**Expected behavior**
No warnings should be emitted.

**To Reproduce**
```py
import os
import sqlalchemy


engine = sqlalchemy.create_engine(
    os.environ['DATABASE_URL'],
    pool_recycle=600
)
conn = engine.connect()
with conn.begin() as txn:
    conn.execute('SELECT 1')
    # do other stuff here that might fail!
    txn.rollback()
```

**Error**

```
venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:2362: SAWarning: transaction already deassociated from connection
  util.warn("transaction already deassociated from connection")
```

**Versions.**
 - OS: Linux
 - Python: 3.8.6
 - SQLAlchemy: 1.4.3
 - Database: MySQL 5.7.32
 - DBAPI: mysqlclient==1.4.6

**Additional context**
This appears to be new in sqlalchemy 1.4. 1.3.23 has no warnings.

The following code does _not_ raise a warning but is obviously a bit messier:

```py
try:
    txn = conn.begin()
    conn.execute('SELECT 1')
    # do other stuff here that might fail!
    txn.rollback()
finally:
    if txn.is_active:
        txn.rollback()
```

**Comment by zzzeek** [comment]
so that warning was added in 1.4 in order to let the user know that a transaction has something happening to it, but that this is a meaningless action.   the kind of pattern I'm specifically trying to draw attention towards here is:

```
conn = engine.connect()
with conn.begin() as txn:
    conn.execute('SELECT 1')
    # do other stuff here that might fail!
    txn.rollback()

    # conn still seems to work, so...are we in a transaction?
    conn.execute("INSERT INTO table ...")
```

do you agree it's appropriate that conn.execute() should emit a warning after manual .rollback() inside the block has occurred?  im not totally sure how to achieve that without adding more state variables to the connection.

**Comment by jvanasco** [comment]
Adding some context to what @zzzeek said, since he beat me to a response while I was looking at this code, the internal engine management is quite a bit different in 1.4 than it was in 1.3.

I can see how this could be a bit confusing, but it might make sense to just change the warning:

-             util.warn("transaction already deassociated from connection")
+             util.warn("transaction already deassociated from connection. this can happen in a context manager `__exit__` if you have issued a manual rollback, and can be safely ignored.")

@zzzeek if we wanted to handle this... what about sending a kwarg in `__exit__`, so the rollbacks are aware this is happening in the contextmanager?

**Comment by zzzeek** [comment]
I can fix the warning here to not emit for that part, it's just that if they call .rollback() inside the block, then keep doing things with connection.execute(), those things are not in a transaction.     in the legacy connection, they're going to autocommit, in the future connection, they will be rolled back in any case (At the moment in this case it seems to raise a different error which i think i also have to fix).    the warning here didn't catch that exactly, but it did warn that the pattern being used was unexpected.

I can say that the userbase is not too keen on "safely ignoring" warnings these days :)   so id rather adjust this now at least.

because legacy/future connection are so different im not sure it's worth trying to go beyond that right now.   the future connection handles this  a lot better.

**Comment by zzzeek** [comment]
right now for legacy connection, having the connection go back into "autocommit" mode when txn.rollback() is called is the same behavior as 1.3.   for 1.4 it goes into commit-as-you-go.

**Comment by Roguelazer** [comment]
I definitely think that an execute in a transaction block after a rollback should raise a warning, but as it stands this kind of prevents me from upgrading a bunch of code to 1.4 because the pattern of manually doing rollback/commit but relying on the context-manager as a safety net to catch exceptions or missed rollbacks is one which is pervasive throughout lots and lots of code here.

FWIW, many of these cases could probably be simplified if `conn.begin()` took a `default_action_on_close` kwarg of either commit or rollback...

**Comment by jvanasco** [comment]
@zzzeek Oh, I understand your concern. I didn't realize your example was `conn.execute` and not `txn.execute`

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Run trans.close() at end of block if transaction already inactive** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2687

**Comment by zzzeek** [comment]
i dont have an easy way to "warn for execute" in the block after `txn.rollback()` is called, and I'd rather not tinker with this logic too deeply right now while we're in early production releases, so with the change it will just do what it used to, you're back in autocommit mode while inside the block if you are not on a "future" connection.

**Comment by zzzeek** [comment]
> I definitely think that an execute in a transaction block after a rollback should raise a warning, but as it stands this kind of prevents me from upgrading a bunch of code to 1.4 because the pattern of manually doing rollback/commit but relying on the context-manager as a safety net to catch exceptions or missed rollbacks is one which is pervasive throughout lots and lots of code here.

OK, this was just an unanticipated use case, but as regular Python context managers like "open()" seem to tolerate a .close() within the block, we will add this use case.

> 
> FWIW, many of these cases could probably be simplified if `conn.begin()` took a `default_action_on_close` kwarg of either commit or rollback...

I think the introduction of more flags and options in this area would make the API more complicated to understand and test.     Once we move to 2.0 and the entire "legacy" transaction behavior can be dropped, things will be less crowded.
