### ISSUE TITLE
For PostgreSQL, server-side cursors at the SQL level, rather than driver level

### ISSUE THREAD

**Issue by tlocke** [sqlalchemy/sqlalchemy#6198]
A user of SQLAlchemy with pg8000 [reported that](https://github.com/tlocke/pg8000/issues/67) yield_per doesn't work with pg8000. This limitation is described in the [SQLAlchemy docs](https://docs.sqlalchemy.org/en/14/orm/queryguide.html#orm-queryguide-yield-per). For PostgreSQL at least, could server-side cursors be used at the SQL level (using [DECLARE](https://www.postgresql.org/docs/current/sql-declare.html), [FETCH](https://www.postgresql.org/docs/current/sql-fetch.html), [MOVE](https://www.postgresql.org/docs/current/sql-move.html) and [CLOSE](https://www.postgresql.org/docs/current/sql-close.html)), rather than driver level? Then SQLAlchemy features that required server-side cursors would work with any driver that supports DBAPI2. Here's an example:

```
>>> cur = conn.cursor()
>>> cur.execute("START TRANSACTION")
>>> cur.execute(
...    "DECLARE c SCROLL CURSOR FOR SELECT * FROM generate_series(1, 100)")
>>> cur.execute("FETCH FORWARD 5 FROM c")
>>> cur.fetchall()
([1], [2], [3], [4], [5])
>>> cur.execute("MOVE FORWARD 50 FROM c")
>>> cur.execute("FETCH BACKWARD 10 FROM c")
>>> cur.fetchall()
([54], [53], [52], [51], [50], [49], [48], [47], [46], [45])
>>> cur.execute("CLOSE c")
>>> cur.execute("ROLLBACK")
```

Happy Easter 🐰

**Comment by jvanasco** [comment]
I don't have a comment on this request, but I read through the ticket in pg8000, and it looks like the Windowed Query recipe/approach may achieve much of the functionality your user was looking for:

* https://github.com/sqlalchemy/sqlalchemy/wiki/RangeQuery-and-WindowedRangeQuery

**Comment by zzzeek** [comment]
SQLAlchemy doesn't have explicit support for the "scrolling" feature of a DBAPI cursor; our server side support is limited to a simple flag "stream_results", which means nothing more than use whatever "non buffered" cursor approach is available by the DBAPI, and yield rows in chunks rather than fetching all data over the wire before returning results.

given that, it is common in DBAPIs such as [pymysql](https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/cursors.py#L391) to provide a relatively simple subclass of their "Cursor" object that does a subset of the above cursor manipulation instructions, and it would be more appropriate for pg8000 to add this feature; simply one where, when we call .execute() on the cursor, the results are not immediately pulled over from the server, and are instead pulled over as they are requested via fetchone() / fetchmany() / fetchall().

**Comment by tlocke** [comment]
Hi all, I've created a [pull request](https://github.com/sqlalchemy/sqlalchemy/pull/6356) that implements a server side cursor in the pg8000 dialect. It seems to pass the tests, but I could easily have made obvious blunders etc, so any help / advice is gratefully received :-)

**Comment by tlocke** [comment]
I've updated my pull request to put the SQL-level server-side cursor in the PostgreSQL dialect base. That means that any PostgreSQL dialect will support stream_results, but a dialect can always override this default with their own native implementation. Hope you like it!

**Comment by tlocke** [comment]
I've made a slight change to use `NO SCROLL` rather than `SCROLL` when declaring the cursor. Since we never do a non-sequential scroll, this gives [better performance.](https://www.postgresql.org/docs/current/sql-declare.html)

**Comment by tlocke** [comment]
This has been implemented now, so I'll close it. Thanks everyone!
