### ISSUE TITLE
`yield_per()` regression in 1.4.x

### ISSUE THREAD

**Issue by ReagentX** [sqlalchemy/sqlalchemy#6206]
**Describe the bug**
The number of rows returned is not identical to what is returned when not using `yield_per()`. In versions older than 1.4.x, the results are correct.

**Expected behavior**
The number of rows returned should always be the same.

**To Reproduce**

```py
class Item(Base):
    prid = Column(String(length=10), primary_key=True)
```

```py
items: Query[Item] = session.query(Item)
found = 0
print(f'{items.count()}')

for item in items.yield_per(1000):
    found += 1

print(found)
```

**Error**

`found != items.count()`

**Versions**
 - OS: Amazon Linux 2, MacOS 10.14.6 (18G8022)
 - Python: 3.7.10
 - SQLAlchemy: N/A
 - Database: Aurora MySQL
 - DBAPI: 5.7.mysql_aurora.2.07.2

**Comment by zzzeek** [comment]
hi there -

your bug report did not include enough detail but I was able to figure out this occurs due to Python id() re-use for larger result sets, as Query's legacy behavior is to enable result.unique().   It should just leave this feature turned off for yield_per as it otherwise implies storing N entries which defeats the purpose of yield_per.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Disable and disallow Result.unique() with yield_per** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2717
