### ISSUE TITLE
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' when using 1.4 in libraries that don't expect it

### ISSUE THREAD

**Issue by WolfgangFahl** [sqlalchemy/sqlalchemy#6226]
**Describe the bug**
1.4 shipping breaks < 1.4 libraries

**Expected behavior**
1.4 shipping  should not break < 1.4 libraries

**To Reproduce**
Use a library depending on FLASK - SQL-Alchemy see
https://stackoverflow.com/a/66648061/1497139

```py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()   
```

**Error**

```
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query'
```

**Comment by CaselIT** [comment]
Hi,

You should probably open an issue with that 3rd party library.
`_ColumnEntity` is a private class in sqlalchemy that was removed or moved in 1.4.

> 1.4 shipping should not break < 1.4 libraries

by definition that's impossible, since the library support SQLAlchemy <1.4 and 1.3->1.3 is a major version change for SQLAlchemy

**Comment by WolfgangFahl** [comment]
You should not do incompatible major version changes in a way that breaks things on import.

**Comment by CaselIT** [comment]
I don't thinks it is reasonable to expect that a private class in a library cannot be changed between version changes, especially between major ones.
Having that constraint would make it impossible to make any kind of change to the api..

**Comment by WolfgangFahl** [comment]
You may make any change that happens in non static parts. A simple import should not break things.

**Comment by CaselIT** [comment]
As I mentioned, we cannot promise that importing private elements of SQLAalchemy will continue to work between version changes. They are private for a reason. All libraries that I know have the same understanding: use at your own risk.

The issue is that library you are using depends on private elements, while they probably should not.

Again you should raise the issue with the library that is causing the problem.

**Comment by zzzeek** [comment]
> You may make any change that happens in non static parts. A simple import should not break things. Version migration support is an important courtesy to the user community. 

the "lack of courtesy" quite frankly is on the part of flask_sqlalchemy using private SQLAlchemy APIs for literally years and never having the courtesy to come to us and request public API for their needs.     I don't actually know how it would be possible for us to ever remove any name ever, as SQLAlchemy as 6M downloads a week and I would need to assume that any developer anywhere in the world may be relying upon an underscored name that's deep in the internals somewhere.   It's not practical and that's why "private names" exist.
 
In Python, a name that has an underscore is non-public, and cannot be relied upon, period.   We go through [tremendous efforts](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html)  to [document every public-facing change](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html) in meticulous detail, but when libraries like flask_sqlalchemy decide to silently rely upon things that were never intended to be accessed on the outside, we simply cannot be expected to service that, and this is not different from any other library.  

> The stackoverflow question above has some 4k views and that has a reason. 

yes, because flask_sqlalchemy is broken and I would gather they are not fixing the issue.    Those 4K users have a problem with flask_sqlalhcemy, and they should fix their bugs.   We are here to assist in any way they need in choosing [appropriate compatible, public, documented APIs](https://docs.sqlalchemy.org/en/14/orm/query.html?highlight=column_descriptions#sqlalchemy.orm.Query.column_descriptions) for what they need to do 

> I even followed the pinning advice but to know avail. I get the error nevertheless while the library developers out there are struggling. 

**we are struggling too**. 


> I assume there is now a transitive dependency and I'll have to pin another library ... sigh

you should petition flask_sqlalchemy to fix their software

**Comment by zzzeek** [comment]
flask-sqlalchemy is not attempting to import `_ColumnEntity`.   No stack trace is provided here nor is there one on the above mentioned stack overflow issue.     Is it possible this is #6000 for sqlalchemy-utils?

**Comment by zzzeek** [comment]
It would appear to be https://github.com/kvesteri/sqlalchemy-utils/issues/474 

Opened on September 20, 2020, which is seven months ago.       You might want to try over there.

**Comment by WolfgangFahl** [comment]
Thx for the clarification:  the sqlalchemy bug is now cross-linked. The deeper problem is that is actually possible to access private elements in python. The separation of interface and class as it is possible in Java didn't make it into the python world and unfortunately its also not well received in the general software engineering community which is a pity given all the followup problems that arise from not following proper information hiding.

**Comment by ashb** [comment]
Python (and many other dynamic languages) operate on a policy of politeness:

You stay out of someone's house because it is the polite thing to d, not because they have a shotgun (i.e. don't import/access "private" names and expect it to carry on working)

**Comment by ashb** [comment]
https://pypi.org/project/SQLAlchemy-Utils/0.37.0/ was just released and should gix this issue.
