### ISSUE TITLE
statement.with_only_columns will skip over the FROM part of the query 

### ISSUE THREAD

**Issue by porschelau** [sqlalchemy/sqlalchemy#6231]
**Describe the bug**
it seems like the with_only_columns function does not work well and it strips the FROM clause from statement

**Expected behavior**
it should not strip the FROM part from the query

**To Reproduce**
```py
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from sqlalchemy import Column, Integer, String, ForeignKey, Enum, Numeric, DateTime, Boolean, func
from sqlalchemy.ext.associationproxy import association_proxy
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, backref

Base = declarative_base()


class Card(Base):
    __tablename__ = "card"
    id = Column(Integer, primary_key=True)
    title = Column(String(50))


engine = create_engine("sqlite:///:memory:", connect_args={"check_same_thread": False}, poolclass=StaticPool)
Base.metadata.create_all(engine)
session = sessionmaker(bind=engine)()


q = session.query(Card)
print(q)
new_q = q.statement.with_only_columns([func.count()])
print(new_q)
```

**Error**
No error, things will fail silently

**Versions.**
 - OS: macos latest
 - Python: 3.x
 - SQLAlchemy:  SQLAlchemy-1.4.6
 - Database: sqlite in mem, mysql 8.x
 - DBAPI:

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there -

for this case this is expected behavior; if columns are removed from a SELECT statement this indicates their implicit FROM entry as well.  

if you had:

   select(A.id, B.id).with_only_columns(A.id)

would you expect this SQL?

   SELECT a.id FROM a, b

in this case, apply the FROM you want:

    new_q = q.statement.select_from(Card).with_only_columns([func.count()])

I understand that this was not the behavior in 1.3, however this change is unavoidable due to the changes described at https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#many-core-and-orm-statement-objects-now-perform-much-of-their-construction-and-validation-in-the-compile-phase  .   I can add a note for this case.

**Comment by porschelau** [comment]
Thanks @zzzeek for clarification
