### ISSUE TITLE
Using dialect.has_table method returns False on first call and True on subsequent calls

### ISSUE THREAD

**Issue by VisionaryMind** [sqlalchemy/sqlalchemy#6260]
**Describe the bug**
Up until the last update, it was possible to check for the presence of a table using the dialiect.has_table method. Now, it never returns True on the first call under any circumstance. I can workaround the problem now by making two subsequent calls, but this is inefficient. Hopefully, this can be fixed.

**Expected behavior**
dialect.has_table should return True every time it is called, if a table exists.

**To Reproduce**

```
import sqlalchemy as sa
sqldb = sa.create_engine('mysql+mysqldb://root:***@/DATABASE?unix_socket=***')
assert sqldb.dialect.has_table(sqldb,'tableName')
```
Assert returns False.

**Versions.**
 - OS: Ubuntu 20.04
 - Python: 3.8.8
 - SQLAlchemy: 1.4.6
 - Database: MySQL
 - DBAPI: MySQLDB

**Comment by zzzeek** [comment]
hi there -

This is essentially an effect of the same issue reported in #5780, #6062, which is that this is a semi-private API that does not accept an Engine as its argument; it takes a Connection object.

In this case, the Engine is non-initialized when first called so the value of "default_schema_name" has not been initialized.

Other than the lack of an assertion here, which I will probably push up since for some reason this issue keeps coming up, you should not pass an Engine object to dialect.has_table(), and this method is not appropriate for public API use in any case.   The correct legacy API is [engine.has_table()](https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=engine%20has_table#sqlalchemy.engine.Engine.has_table) and the newer API is [Inspector.has_table](https://docs.sqlalchemy.org/en/14/core/reflection.html#sqlalchemy.engine.reflection.Inspector.has_table) .

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Explicitly test for Connection in dialect.has_table()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2741
