### ISSUE TITLE
build out weakref backrefs for async(sync_thing) -> (sync_thing)

### ISSUE THREAD

**Issue by abompard** [sqlalchemy/sqlalchemy#6319]
**Describe the bug**

I am filing it under "bug" because I think it is a regression. When using sync sessions, the `object_session()` function returns the session from ORM instances. There is no equivalent for async sessions, since `object_session()` and `AsyncSession.object_session()` only return the sync Session instance.

I think this was a very useful feature to avoid passing the session object to functions and methods in addition to the ORM instances. Maybe there could be a `AsyncSession.object_async_session()` classmethod which could return the original Async session that was used to get an ORM instance?

**Expected behavior**

There should be a way to get the AsyncSession from an ORM instance.

**To Reproduce**

```py
import asyncio

from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.future import select
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm import object_session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)


async def async_main():
    engine = create_async_engine(
        "sqlite+aiosqlite:///test.db",
        echo=False,
    )

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    async_session = sessionmaker(
        engine, expire_on_commit=False, class_=AsyncSession
    )

    async with async_session() as session:
        async with session.begin():
            session.add(A(data="a1"))

        stmt = select(A)
        result = await session.execute(stmt)
        a = result.scalar()
        print(session)
        print(object_session(a))
        print(AsyncSession.object_session(a))

asyncio.run(async_main())
```

**Error**

You'll see that the objects returned by `object_session()` and `AsyncSession.object_session()` are both regular sync Session instances.

**Versions.**
 - OS: Linux
 - Python: 3.9.2
 - SQLAlchemy: 1.4.7
 - Database: SQLite & MySQL
 - DBAPI: aiosqlite & aiomysql

Thanks!

**Comment by zzzeek** [comment]
so here is the thing about the asyncsession and also the asyncengine.   they are nearly stateless proxies for the real Session / Engine.   so as a two liner, we can add some API that gives you this as a new `AsyncSession` that refers to this origiinal `Session`.  Here's how to do that now:

```python
        def async_object_session(obj):
            sess = object_session(obj)
            if sess is not None:
                async_session = AsyncSession.__new__(AsyncSession)
                async_session.sync_session = async_session._proxied = sess
                return async_session
            else:
                return None

        print(async_object_session(a))

```

that's an easy feature add.  But the AsyncSession you are getting back is a different object than the original AsyncSession.    We already use this pattern in the `AsyncSession.connection` method, so there is precedent here: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/ext/asyncio/session.py#L269

now the more elaborate (still not that hard, but a little less elegant) feature add is that we build weak referencing registries of AsyncSession and likely also AsyncConnection so that these "backlinks" can give back the same object.     but overall it shouldn't matter, the one thing that wouldn't work is something like "async_object_session(obj) is my_async_session".   not sure if people need that.   

we might need to do the latter anyway since we have AsyncSession.bind pointing to the actual AsyncEngine so there is some inconsistency happening here.

**Comment by CaselIT** [comment]
I guess we could add a weakref of the async session to the regular session, so we continue to track the regular version, but we can get back the async one. I guess it may be gc-ed in some cases though, so the fallback of creating a new one would still be needed.

**Comment by zzzeek** [comment]
I think we should add weakref backrefs to the asyncio proxy thing directly, e.g. the ProxyComparable class, because these backref issues are going to keep coming up and it will be much cleaner.   There would not be any gc issues because as long as you have Async(Thing), it has a strong reference to the sync object.

**Comment by zzzeek** [comment]
also people are going to make subclasses of AsyncSession at some point and they will want that back.

**Comment by zzzeek** [comment]
> I think we should add weakref backrefs to the asyncio proxy thing directly, e.g. the ProxyComparable class, because these backref issues are going to keep coming up and it will be much cleaner. There would not be any gc issues because as long as you have Async(Thing), it has a strong reference to the sync object.

thinking about this now I'm not sure how I intended something like AsyncConnection to be strong ref'ed.    at the moment I'm thinking this might need one of those more complex weakref-callback-cleanup things such as what I did in sqlalchemy.events.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement proxy back reference system for asyncio** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2852
