### ISSUE TITLE
Strange insert statement

### ISSUE THREAD

**Issue by ghpxi** [sqlalchemy/sqlalchemy#6361]
**Describe the bug**
I'm trying to insert multiple values into a table, but SQLAlchemy generates a strange SQL statement:
```sql
INSERT INTO foo (id) VALUES (nextval('foo_id_seq')), (%(id_m1)s), (%(id_m2)s)
```
in the log I see prefetch queries:
```sql
select nextval('foo_id_seq')                                                          
select nextval('foo_id_seq')
```
the question is why it prefetches nexval only for 2nd and 3rd values and 1st uses inline?

The result of this query affects the id order that Postgres generates for rows. The first row will have a larger id than the second.

**Expected behavior**
SQLAlchemy should prefetch all values or it should use inline for each value.

**To Reproduce**
Run insert query with multiple values
```py
insert_query = insert(foo_table).values(foo_dicts).returning(literal_column("*"))
objects = conn.execute(insert_query).fetchall()
```

**Versions.**
 - OS: linux
 - Python: 3.8
 - SQLAlchemy: 1.3
 - Database: postgresql
 - DBAPI: postgresql+psycopg2

**Comment by zzzeek** [comment]
hi there -

as the creator of SQLAlchemy, it was apparent to me that your test case is using [an explciit Sequence object](https://docs.sqlalchemy.org/en/14/core/defaults.html?highlight=sequence#defaults-sequences), however, to the several other people here who generously help me quite a bit with triage for these issues, they might not realize that, so I would please ask that you provide [complete MCVE examples](http://stackoverflow.com/help/mcve) within the "To Reproduce" section, so that critical details like this are included.  thanks!

the bug is limited to when explicit sequences are in use, and would apply to any use of Sequence like on PostgreSQL, Oracle, etc.   


```python

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import insert
from sqlalchemy import Integer
from sqlalchemy import literal_column
from sqlalchemy import Sequence
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, Sequence("a_seq"), primary_key=True)
    data = Column(String)


e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

foo_table = A.__table__
foo_dicts = [{"data": "d1"}, {"data": "d2"}, {"data": "d3"}]

insert_query = (
    insert(foo_table).values(foo_dicts).returning(literal_column("*"))
)
with e.begin() as conn:
    objects = conn.execute(insert_query).fetchall()
```

**Comment by zzzeek** [comment]
for 1.3 you can work around this as follows:

```python

foo_table = A.__table__
seq = foo_table.c.id.default
foo_dicts = [
    {"id": seq.next_value(), "data": "d1"},
    {"id": seq.next_value(), "data": "d2"},
    {"id": seq.next_value(), "data": "d3"},
]

insert_query = (
    insert(foo_table).values(foo_dicts).returning(literal_column("*"))
)

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Handle Sequence in _process_multiparam_default_bind** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2778
