### ISSUE TITLE
Why was postgres:// dropped / deprecated?

### ISSUE THREAD

**Issue by dchevell** [sqlalchemy/sqlalchemy#6422]
Hi team,

I see in SQLAlchemy 1.4 we dropped the URI short form `postgres://` after a long deprecation, now requiring the long form `postgresql://`.

I can't find anything that points to the original _reason_ for this. Everything just points back to the work that removed it, but I can't find any supporting explanation. As far as I can tell, Postgres itself continues to support and document both forms with no indication that the short form is deprecated by them.

The reason for asking is that I've raised this in my org as something that we may need to fix in certain layers of our stack, but when asked "why are SQLAlchemy deprecating something that seems supported?" I haven't got a reasonable answer. If you could shed any light or context it would be helpful.

Cheers

Dave

**Comment by CaselIT** [comment]
Hi,

Please see https://github.com/sqlalchemy/sqlalchemy/issues/6083#issuecomment-801478013

As for the why, I think (I'm just supposing here, I was not around in 2010 when the original deprecation was added) the reason is that sqlalchemy associates a database url prefix with a package name of the dialect. So it does not support, without special logic, two prefixes pointing to the same package. This special logic was known to be used only in the postgresql case for a feature that was deprecated from 11 years. So it was removed.
