### ISSUE TITLE
Tests that aren't about primary keys shouldn't rely on automatic primary-key generation

### ISSUE THREAD

**Issue by jimfulton** [sqlalchemy/sqlalchemy#6469]
Hi again. 

There are too many tests that have nothing to do with primary keys that fail when a database doesn't provide a way to auto-generate primary keys.

SQLAlchemy is used for analytic databases, like BigQuery, Hive and Impala, that don't have primary keys, and for use cases where primary keys don't matter.

A case in point is [`RowCountTest`](https://github.com/sqlalchemy/sqlalchemy/blob/e064ca8bc9e9a79f766acda9d718a96929400674/lib/sqlalchemy/testing/suite/test_rowcount.py#L14). This test has nothing to do with primary keys but can't be initialized for BigQuery.  [I worked around this by providing primary-key values](https://github.com/googleapis/python-bigquery-sqlalchemy/blob/67937607ee9f62a71fde6f6cb077a10fb6141c83/tests/sqlalchemy_dialect_compliance/test_dialect_compliance.py#L221-L240).

I'd worked around this for other tests by setting [`preexecute_autoincrement_sequences` to True](https://github.com/googleapis/python-bigquery-sqlalchemy/blob/67937607ee9f62a71fde6f6cb077a10fb6141c83/tests/sqlalchemy_dialect_compliance/conftest.py) and providing [`get_insert_default`](https://github.com/googleapis/python-bigquery-sqlalchemy/blob/67937607ee9f62a71fde6f6cb077a10fb6141c83/pybigquery/sqlalchemy_bigquery.py#L148-L153), but that didn't work here. (And really shouldn't have been necessary in the first place.)

If a test isn't testing primary-key generation, it shouldn't use primary keys or should provide values for them.

**Comment by jimfulton** [comment]
Happy to provide a PR for this. Just ask. :)

**Comment by jimfulton** [comment]
I wouldn't want to skip `RowCountTest` just because BigQuery doesn't do auto-increment.  This test has nothing to do with auto-increment.  Getting it running showed me that BigQuery doesn't correctly handle executemany row counts. :)

**Comment by zzzeek** [comment]
So I can provide for two answers to this.

First one, tests like RowCountTest where we dont care about PKs, absolutely, we can accept PRs etc. for that.   In particular I think it's best if the Column() that's the "pk" includes autoincrement=False; this will allow databases like SQL Server to not even include the "IDENTITY" directive which actually interferes with the ability to INSERT new PK values directly.      We can do that to fix the majority of this issue now.

Bigger picture, a lot of tests in the suite that do continue to generate PK values are using things like sequences to work on databases that don't have an intrinsic "autoincrement" kind of feature.   Oracle is another database that we test which also has this same limitation, that there is no inherent way in which it generates new PK values.   In SQLAlchemy we use a sequence that is at the Oracle level separate from the table itself in order to generate these PKs.

the way Oracle passes the suite tests is that they are using test-specific funcitons to generate Table and Column objects: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/testing/schema.py#L85 

where above, you can see that there's hardcoding of dialect names like Oracle and Firebird where a Sequence has to be added to a pk Column automatically.

What we should do here, eventually or sooner if we care, so that third party dialects with similar restrictions can take advantage of this system is generalize what we see in sqlalchemy/testing/schema.py.      The place that we allow for generalizing of test suite behaviors is in a series of modules known as "provisioning", such as Oracle's which is at https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/oracle/provision.py .

I can propose here that we take the special "test_needs_autoincrement" etc. directives we see in sqlalchemy/testing/schema.py, in the areas where we are hardcoding to specific databases like mysql, mariadb, Oracle, Firebird, etc., we instead consult among new functions that would be added to the provisioning API - the existing provisioning functions available can be seen at https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/testing/provision.py .    

Concretely, what this would mean for BigQuery would be in your SQLAlchemy dialect, you would implement the provision.py file and accommodate for the case such as a Column that needs to produce new primary key values on INSERT.   This could be something as homegrown as you are using itertools.count() inside your test suite which would be linked as a Python-side default generator for tables.

certainly for the moment there's less cognitive load to just removing the use of autoincrement for suites where it doesn't matter.

**Comment by CaselIT** [comment]
> I wouldn't want to skip `RowCountTest` just because BigQuery doesn't do auto-increment. This test has nothing to do with auto-increment. Getting it running showed me that BigQuery doesn't correctly handle `executemany` row counts. :)

I probably expressed myself poorly. I agree with you, I just mentioned that in some cases where we do test the autoincrement we may be missing an autoincrement requirement.

Using the provisioning system to get the proper columns would be useful I think mike. We may be also use it to provide further customization to the suite tests that way.

**Comment by sqla-tester** [comment]
**Jim Fulton** has proposed a fix for this issue in the **master** branch:

**Provide primary key values for data in tests that aren't about primary keys.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2830
