### ISSUE TITLE
do ORM resolution for non-ORM statements where there is still a plugin subject?

### ISSUE THREAD

**Issue by ave-satan** [sqlalchemy/sqlalchemy#6484]
ORM-enabled INSERT in 2.0 style doesn't work when I try to configure `binds` on `session` with my declarative base. 
It only works when I explicitly set `binds` for ORM models, but this is not a desired behavior for me.
There is a [section in docs](https://docs.sqlalchemy.org/en/14/orm/session_api.html#sqlalchemy.orm.Session.params.binds) which makes me assume it should be able to bind an engine to a declarative base, though.

Strangely enough it fails only for insert statements, updates and deletes execute almost fine as you can see in the code example provided below. However there is an odd behavior for updates and deletes as well.

**To Reproduce**
```py
from sqlalchemy import create_engine, insert, update, Column, Integer, Text
from sqlalchemy.orm import declarative_base, sessionmaker

engine = create_engine('postgresql://localhost', future=True)
DeclarativeBase = declarative_base()


class Test(DeclarativeBase):
    __tablename__ = 'test'

    id = Column(Integer(), primary_key=True, autoincrement=True)
    val = Column(Text())


Session = sessionmaker(binds={
    DeclarativeBase: engine,
})

session = Session()
insert_stmt = insert(Test).values(val='123')
# sqlalchemy.exc.UnboundExecutionError: Could not locate a bind configured on SQL expression or this Session.
print(session.get_bind(clause=insert_stmt))
# same exception here
session.execute(insert_stmt)

session = Session()
update_stmt = update(Test).values(val='123')
# sqlalchemy.exc.UnboundExecutionError: Could not locate a bind configured on SQL expression or this Session.
print(session.get_bind(clause=update_stmt))
# but this works fine some reason
session.execute(update_stmt)

# explicitly bind model to engine
Session = sessionmaker(binds={
    DeclarativeBase: engine,
    Test: engine,
})

session = Session()
insert_stmt = insert(Test).values(val='123')
# and now it works
print(session.get_bind(clause=insert_stmt))  # Engine(postgresql://localhost)
session.execute(insert_stmt)
```

**Error**
```
Traceback (most recent call last):
  File "/home/ave_satan/projects/test/1.py", line 23, in <module>
    print(session.get_bind(clause=insert_stmt))
  File "/home/ave_satan/.pyenv/versions/test/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2058, in get_bind
    raise sa_exc.UnboundExecutionError(
sqlalchemy.exc.UnboundExecutionError: Could not locate a bind configured on SQL expression or this Session.
```

**Versions:**
 - OS: Ubuntu 20.04.2 LTS
 - Python: 3.9.2
 - SQLAlchemy: 1.4.15

**Comment by zzzeek** [comment]
The issue is that there is no "ORM-enabled INSERT" feature right now.  There's ORM enabled SELECT, UPDATE and DELETE right now.    A special exception would need to be added to support insert:

1. the statement insert(Test) is not considered from an ORM perspective, as the ORM does not have any hooks to intercept insert() objects directly.  So the "binds" that contain mapped classes and superclasses are not considered.
2. the update(Test) statement as of 1.4 *is* considered from an ORM perspective, so the binds dictionary with minimal class information is sufficient here.
3. When the "Test" class itself is present in the "binds" dictionary, the Session does some extra steps which is to extract the mapped tables from the Test mapping, and additonally add those to the "binds" as well.    So when this is done, the parameter  "clause=insert_stmt" passed to get_bind() is suddenly meaningful, because it is going to match the insert_stmt to the tables, that is, not using any ORM classes to make this connection.

this is why insert(Test) does not behave like update(Test) right now and also why the binds dictionary is producing that effect.

A solution to this would be to add rudimentary ORM bind matching to all statements even if they don't have an explicit ORM usage path right now.   but as we've had lots of backwards incompatible changes already that people are adjusting towards, im hesitant to jump into this one without being very careful, although the fix should be straightforward since statements now collect information on their primary ORM entity in most cases including insert().

what you can do right now to have the bind that you want is to pass them separately using bind_arguments:

    insert_stmt = insert(Test).values(val="123")
    session.execute(insert_stmt, bind_arguments={"mapper":  Test})

This can be generalized in the way I'd probably do this internally, using the following private API that is not guaranteed to remain stable:

    session.execute(insert_stmt, bind_arguments={"mapper":  insert_stmt._propagate_attrs.get("plugin_subject", None)})

the same thing can be done using a custom get_bind() implementation such as in the example at https://docs.sqlalchemy.org/en/14/orm/persistence_techniques.html#session-partitioning .

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Consult plugin_subject for non-ORM enabled stmts in get_bind()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2826
