### ISSUE TITLE
SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery

### ISSUE THREAD

**Issue by mkmoisen** [sqlalchemy/sqlalchemy#6491]
**Describe the bug**
I believe this warning should be removed, and users should never have to call scalar_subquery directly:

    SAWarning: implicitly coercing SELECT object to scalar subquery; 
    please use the .scalar_subquery() method to produce a scalar subquery.

In SQL the following is totally legal and ordinary:

    SELECT foo.*
    FROM foo
    WHERE foo.bar_id = (
        SELECT bar.id
        FROM bar
        WHERE bar.name = 'baz'
    )

Translating that into SQLAlchemy Core results in a very intuitive syntax and a 1:1 mapping between SQL and python APIs:

    select(foo).where(foo.c.bar_id == select(bar.c.id).where(bar.c.name == 'baz'))

However, as of 1.4 this now raises a warning:

    SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.

Would it be possible if this warning could be removed, and the current syntax could be maintained? I assume this warning implies that the current syntax will be deprecated.

Making us add `scalar_subquery()` is one more mental block that clutters up the code:

    select(foo).where(foo.c.bar_id == select(bar.c.id).where(bar.c.name == 'baz').scalar_subquery())

In SQL I don't have to inform the query that my subquery should return a scalar subquery. It just works. If my subquery has a bug and returns more than one row, the query will fail explaining that more than one row was found.

SQLAlchemy Core is really great because it generally maps 1:1 with SQL. I think making us add scalar_subquery() would detract from this.

**To Reproduce**
Provide your [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example
here.

```py
from sqlalchemy import table, column, Integer, select

foo = table('foo', column('id'), column('bar_id'))
bar = table('bar', column('id'), column('name'))

select(foo).where(foo.c.bar_id == select(bar.c.id).where(bar.c.name == 'baz'))
```

**Error**
Provide the complete text of any errors received **including the complete
stack trace**.   If the message is a warning, run your program with the
``-Werror`` flag:   ``python -Werror myprogram.py``

```
# Copy complete stack trace and error message here, including SQL log output
if applicable.
>>> select(foo).where(foo.c.bar_id == select(bar.c.id).where(bar.c.name == 'baz'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/app-root/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 360, in __eq__
    return self.operate(eq, other)
  File "/opt/app-root/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 847, in operate
    return op(self.comparator, *other, **kwargs)
  File "/opt/app-root/lib/python3.9/site-packages/sqlalchemy/sql/operators.py", line 360, in __eq__
    return self.operate(eq, other)
  File "/opt/app-root/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 76, in operate
    return o[0](self.expr, op, *(other + o[1:]), **kwargs)
  File "/opt/app-root/lib/python3.9/site-packages/sqlalchemy/sql/default_comparator.py", line 97, in _boolean_compare
    obj = coercions.expect(
  File "/opt/app-root/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 200, in expect
    return impl._implicit_coercions(
  File "/opt/app-root/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 319, in _implicit_coercions
    self._warn_for_scalar_subquery_coercion()
  File "/opt/app-root/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 307, in _warn_for_scalar_subquery_coercion
    util.warn(
  File "/opt/app-root/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1621, in warn
    _warnings_warn(msg, exc.SAWarning)
  File "/opt/app-root/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1658, in _warnings_warn
    warnings.warn(message, category, stacklevel=stacklevel + 1)
sqlalchemy.exc.SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
```

**Versions.**
 - OS: Windows and Linux
 - Python: 3.9.5
 - SQLAlchemy: 1.4.15
 - Database: N/A
 - DBAPI: N/A

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there -

The Select object and the ScalarSelect object have completely different semantics and we'd like users to know that they are opting into a scalar subquery.     Select represents a series of columns that can be delivered as zero or more rows, whereas ScalarSelect represents a single column expression that must produce zero or one row.   ScalarSelect is in fact a ColumnElement whereas Select is a FromClause.   In SQLAlchemy 1.4 / 2.0, the new path going forward is the removal of all the various implicit, inconsistent and often surprising decisions that SQLAlchemy makes like so that there are fewer surprises, more explicit statement of intent up front, as much consistency as possible in how things work, and a better understanding on the part of the end user what's going on.

> Making us add scalar_subquery() is one more mental block that clutters up the code:

I disagree completely and I see it as an improvement that makes the user aware what's going on, and it also produces code that is more obvious as to what different elements are as well as their intent.   implicit coercion to scalar subquery would be inconsistent vs. the fact that we are also removing implicit coercion to non-scalar subquery, which is absolutely necessary as users have been confused for many years by this behavior.
    
These design decisions have been in the works fairly publicly for about two years now and we had beta releases for several months starting in november of 2020, and there have been no comments or objections raised during that whole time, so the 1.4/2.0 arch is pretty much baked in at this point especially w.r.t the most fundamental philosophy of "no more implicit decisionmaking".

**Comment by mkmoisen** [comment]
Hi @zzzeek understood, thank you for the explanation.
