### ISSUE TITLE
SimpleUpdateDeleteTest asserts that updates and deletes don't return rows, but in BigQuery, they do.

### ISSUE THREAD

**Issue by jimfulton** [sqlalchemy/sqlalchemy#6506]
Is this assertion really needed?

For the BigQuery dialect-compliance tests, I had to override these tests to remove this assertion.

**Comment by CaselIT** [comment]
Hi,

IIRC it was the only, or one of the only, test that checked that stuff. Would also `assert r.rowcount == 1` breaks in this case?

Out of curiosity what rows are returned?

**Comment by zzzeek** [comment]
the "returns rows" / "does not return rows" thing affects whether or not we close the cursor immediately.   we detect rows being returned using cursor.description, and if present, we don't close the cursor assuming it must be consumed.   Therefore this is a pretty big assumption that UPDATE/DELETE without RETURNING will return an empty cursor.description and the result will be closed immediately.   otherwise the cursor gets left open, which we genreally see as an antipattern that this is not handled in some way.

What is cursor.description equal towards when one does a DELETE from a table without the use of RETURNING ? an entire table row ?

**Comment by jimfulton** [comment]
Well, this is weird. :)

At the db api level, after an update or delete:

- The `description` is the same as it would have been if you did `select * from table`.
- If you fetch rows, you get table rows as they are after the operation.

When I debugged the tests initially, I didn't look closely enough and assumed that the rows returned were the affected rows.

Maybe this is a BigQuery client bug of some kind.  I need to do some digging. I'm going to close this for now.

**Comment by CaselIT** [comment]
Ok, feel free to reopen if needed
