### ISSUE TITLE
sessionmaker context manager is not fully compatible with scoped_session

### ISSUE THREAD

**Issue by helioblast** [sqlalchemy/sqlalchemy#6519]
**Describe the bug**

When using `scoped_session()` to create `Session` objects (e.g., for a threaded app), using the combined context manager `with Session.begin() as session` results in an exception.

**To Reproduce**
```py
from sqlalchemy import Column, Integer, String
from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base, scoped_session, sessionmaker


Base = declarative_base()


class Test(Base):
    __tablename__ = 'test'
    id = Column(Integer, primary_key=True, unique=True, autoincrement=True)
    value = Column(String)


engine = create_engine("sqlite://", future=True)
Base.metadata.create_all(engine)

Session = scoped_session(sessionmaker(bind=engine, future=True))
# Session = sessionmaker(bind=engine, future=True)

with Session.begin() as session:
    session.add(Test(value="foo"))

# with Session() as session:
#     with session.begin():
#         session.add(Test(value="foo"))
```

**Error**

```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
AttributeError: 'SessionTransaction' object has no attribute 'add'
```

The same type of exception occurs regardless of the method called for `session` (e.g., `.get()`, `.execute()`)

**Workarounds**

Replace:
```
with Session.begin() as session:
```
with:
```
with Session() as session:
    with session.begin():
```

Or (if thread support is not required) replace:
```
Session = scoped_session(sessionmaker(bind=engine, future=True))
```
with:
```
Session = sessionmaker(bind=engine, future=True)
```

**Versions**
 - OS: Ubuntu 21.04 (5.11.0-17-generic  x86_64)
 - Python: 3.9.4
 - SQLAlchemy: 1.4.15
 - Database: SQLite 3.34.1
 - DBAPI: pysqlite

**Comment by zzzeek** [comment]
this is a good issue but there is a judgment call to be made as this would require a backwards incompatible change in the middle of the 1.4 series to work, unless we limited the new behavior to very specific conditions which IMO would make it more confusing to understand.     

three common varieties are included below of this pattern, two of them succeed in 1.3 and return a `SessionTransaction`, and not a `Session`.    The most common public API of `SessionTransaction` is the .commit() and .rollback() methods, which are on `Session` also.    So that leaves just some edgier cases, like someone's test suite doing `isinstance(x, SessionTransaction)` or calling upon accessors or methods that are only on `SessionTransaction` such as `prepare()`.  This is all very unlikely but there is still a chance someone's test suite breaks if we just change this.    


```python
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session
from sqlalchemy.orm import sessionmaker

e = create_engine("sqlite://")


def test_case1():
    s = scoped_session(sessionmaker(e))
    # doesn't work in 1.3 due to transaction already begun
    with s.begin() as thing:
        pass

def test_case2():
    # works in 1.3, returns SessionTransaction
    s = scoped_session(sessionmaker(e, autocommit=True))
    with s.begin() as thing:
        pass


def test_case3():
    # works in 1.3, returns SessionTransaction
    s = scoped_session(sessionmaker(e, autocommit=True))
    with s.begin() as thing:
        pass


```


there's also the notion that we'd maybe check if future=True and then only use the new behavior then.   But this would be inconsistent with how plain `Session` works.    At the moment it seems the least impactful change would be to make the change as requested across the board and have it return `Session` instead of `SessionTransaction` with the small chance that some unusual pattern somewhere is impacted.    I often make the unconventional decision that doing so is less distruptful than a long and intricate deprecation path.

**Comment by zzzeek** [comment]
so the more "cautious" way to change would be, if the given Session is not in legacy "autocommit" and the method is not using legacy "subtransactions", then we return the Session, because this is new code.  if either autocommit or subtransactions are in play, then this is definitely legacy code, and we do the old thing.    So in this case, SQLAlchemy is making assumptions that we hope "just work".  but if someone actually has a problem and wants to see what's going on , this would be very confusing to them.

**Comment by CaselIT** [comment]
Personally I think this is working as intended. From the documentation: https://docs.sqlalchemy.org/en/14/orm/contextual.html#implicit-method-access

> The job of the scoped_session is simple; hold onto a Session for all who ask for it. As a means of producing more transparent access to this Session, the scoped_session also includes proxy behavior, meaning that the registry itself can be treated just like a Session directly; when methods are called on this object, they are proxied to the underlying Session being maintained by the registry:

So the scoped session should behave like the session. `session.begin()` returns a `SessionTransaction` so I think it would follow that scoped session would also return a `SessionTransaction`

**Comment by CaselIT** [comment]
I think any change would be best as a next release, so that in can be in the migration notes etc.

Also changed from bug to use case, since the current behaviour is as documented, so there is no bug.

>  however that said it is nice to get at the per-thread session

well you already have it though. With the normal session the code is:
```py
session = my_session_maker()
with session.begin():
  session.add(...)
  ...
```
with a scoped session you have two options:
```py
# same as session maker
session = my_scoped_session()
with session.begin():
  session.add(...)
  ...
# use as proxy
with my_scoped_session.begin():
  my_scoped_session.add(...)
  ...
```

**Comment by zzzeek** [comment]
i had a thought that why would one even be using scoped_session() if they are using context managers for transactions.   The pattern of "some_sessionmaker.begin()" means something completely different than "some_scoped_session.begin()".      the former is a creational pattern that gives you a new Session() right there.  The latter is assumed there is some session attached to a thread local that's already in process and you're using it as a proxy, it would not be generally safe to call "begin()" on it as there is likely already a transaction in progress on it.

really the big pattern here is that scoped_session() is a legacy "thread local" thing and it's not really the way to do things going forward as context/thread locals have proven to be confusing to people as opposed to explicitly passing a context/session into methods that need it.  At most the code that uses a scoped_session() it would get the actual Session from it and assume it's already in a transactional state.

**Comment by helioblast** [comment]
Hmmm... So I guess it's possible I've maybe developed some kind of misunderstanding of `scoped_session()`?

The following is basically what I'm looking to do:
```py
engine = create_engine("sqlite://", future=True)  # or MySQL, Postgres, etc.
Session = scoped_session(sessionmaker(bind=engine, future=True))


class FileWorker(threading.Thread):

    def __init__(self, file_queue):
        self._file_queue = file_queue
        ...

    def _process_file(self, file_path):
        ...

    def _update_db(self, file_data):
        with Session.begin() as session:
            ...
            
        # with Session() as session:
        #     with session.begin():
        #         ...
        
        # try:
        #     session = Session()
        #     ...
        #     session.commit()
        # except:
        #     session.rollback()
        # finally:
        #     session.close()


    def run(self):
        while True:
            # Pull a filepath from the queue as it's populated.
            file_path = self._file_queue.get()
            # Do some work on the file.
            file_data = self._process_file(file_path)
            # Add to the DB.
            result = self._update_db(file_data)


def read_files(file_dir):
    fileworker_threads = some_int
    file_queue = Queue(some_int * 2)

    for i in range(fileworker_threads):
        file_worker = FileWorker(file_queue)
        file_worker.start()

    for file_path in file_dir.iterdir():
        file_queue.put(file_path)

    file_queue.join()


def some_query(value):
    # Some method of setting up/controlling the session as above
    with Session.begin() as session:
        session.execute(
            ...
        )

...
```

(In reality, `Session` is currently defined from`scoped_session()` elsewhere in the app and used by various other functions. Threading was chosen for the worker mainly because the major wait is file I/O, not processing on the file itself.)

So OK, or flawed design or anti-pattern of some sort? Unexpected usage? Maybe it would be better to simply define `Session = sessionmaker(bind=engine, future=True)` in `FileWorker.run()` (where the new thread is started) and go from there (haven't tried, not sure that's valid)?

Thanks (and sorry, didn't meant to turn a possible issue into Stack Overflow).

**Comment by CaselIT** [comment]
> So OK, or flawed design or anti-pattern of some sort? Unexpected usage?

this depends on you preference regarding thread local variables, I personally agree with mike that's probably cleared to pass around the session explicitly, but thread locals are also popular, as evidenced by the popularity of flask.

Regarding your usage I think you are misunderstanding the scoped_session with the sessionmaker. The scoped session acts as a proxy for a session that is local to the current thread, while the sessionmaker is a factory of session. So when you do 
```py
 with Session.begin() as session:
        session.execute(...)
```
you are trying to run execute on a transaction, like you would on a session. The correct usage is the one I mentioned above 
https://github.com/sqlalchemy/sqlalchemy/issues/6519#issuecomment-846087783

**Comment by zzzeek** [comment]
yeah just to clarify, if you just used sessionmaker() and didnt use scoped_session at all, I assume "file_data" is non-ORM records that you're going to be adding into a Session.   so when you say "with Session.begin()", that makes a brand new Session right there which you use, then it commits and closes.    That is I don't see where you are sharing the same Session among different methods without passing it explicitly.

**Comment by zzzeek** [comment]
looking back at this I agree with @CaselIT  that the documented pattern of scoped session is that it's a proxy.  It would be inconsistent for us to make an exception that considers certain methods separately.   The sessionmaker OTOH is not a proxy, so in that case we have the chance for begin() to do something different.

for the original example given, the expected pattern when using a scoped session would be:

```py
with Session.begin():
    Session.add(Test(value="foo"))
```

that is, `Session` is treated like it is already a `sqlalchemy.orm.Session` object.    If we change anything here even for 2.0 I think we're going to have new problems.

**Comment by aalvrz** [comment]
I just stumbled upon this after trying to understand how I should be using sessions when migrating from 1.3 to 1.4. 

My application uses `scoped_session` and I was trying to implement the new 1.4 context manager usage, but what I understand so far from this discussion is that these are two completely different usages? Meaning that you should opt for either of one, but not both. Is this a valid assumption?

**Comment by ggregoire** [comment]
I just stumbled upon this too. Since the session now has a `autobegin` feature, could 

```python
Session = scoped_session(sessionmaker(engine))

def worker_one():
     Session.execute(text("select 1"))

def worker_two():
     Session.execute(text("select 2"))

def main():
    with Session.begin():
        worker_one()
        worker_two()

main()
```

be rewritten

```python
Session = scoped_session(sessionmaker(engine))

def worker_one():
     Session.execute(text("select 1"))

def worker_two():
     Session.execute(text("select 2"))

def main():
    worker_one()
    worker_two()
    Session.commit()
    Session.remove()

main()
```

?

Are they exactly the same? Is one or the other the preferred way to write it?

For instance, `with Session.begin()` called `session.close()` automatically, right? But [the doc about `scoped_session`](https://docs.sqlalchemy.org/en/14/orm/contextual.html#using-thread-local-scope-with-web-applications) says to call `session.remove()` as a requirement. So shouldn't the second piece of code above be the correct way to do it?

**Comment by CaselIT** [comment]
I'm not sure if `Session.begin()` calls `renove` when exiting the context.
The main difference in the two is that if one of the worker functions raises an exception with the context manager version the transaction would be ended with a rollback, while in the other no rollback would be issued

**Comment by CaselIT** [comment]
> I'm not sure if Session.begin() calls renove when exiting the context.

The session is not removed by begin on the scope_session
