### ISSUE TITLE
AsyncSession does not throw an error when committed outside async context manager

### ISSUE THREAD

**Issue by noahkw** [sqlalchemy/sqlalchemy#6523]
**Describe the bug**
When accidentally committing an AsyncSession outside an async context manager, no exception is thrown. This can lead to difficult to debug bugs.

**To Reproduce**

```py
import asyncio

from sqlalchemy import Column, Integer, String, select, delete
from sqlalchemy.orm import declarative_base, sessionmaker
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession


Base = declarative_base()


class Test(Base):
  __tablename__ = 'test'
  id = Column(Integer, primary_key=True, unique=True, autoincrement=True)
  value = Column(String)

engine = create_async_engine("sqlite+aiosqlite://")
Session = sessionmaker(bind=engine, class_=AsyncSession)


async def main():
  async with engine.begin() as conn:
    await conn.run_sync(Base.metadata.create_all)

  async with Session() as session1:
    session1.add(Test(value="foo"))
    await session1.commit()

  async with Session() as session2:
    statement = delete(Test).where(Test.value == "foo")
    await session2.execute(statement)
  
  # accidentally un-indented call to AsyncSession.commit()
  await session2.commit()

  async with Session() as session3:
    statement = select(Test).where(Test.value == "foo")
    (await session3.execute(statement)).one()

asyncio.run(main())
```

**Error**
An error should be thrown when calling `await session2.commit()`, because the session is closed and the changes are not actually committed to the database. Consequently, `(await session3.execute(statement)).one()` does not throw a `NoResultFound` exception, which is unexpected.

**Comment by CaselIT** [comment]
Hi,

I think this is working as expected and documented. The session will re-open itself after a `close()` is called if it's used again, so it's expected that the commit does not raises an error.

Regarding your example, the issue is not that the `commit` is not issued, is that when the context manager exits the session is closed and a rollback is issued in that case. You can see the db interaction by passing `echo=True` to the create engine function.

I agree that in this case example the current behaviour may not the most appropriate one. Maybe we could add a flag to prevent this reopen-after-close behaviour or change this in a future release (for async session only?). @zzzeek what's your opinion?
