### ISSUE TITLE
'NoneType' object has no attribute 'Error' in do_ping

### ISSUE THREAD

**Issue by GergelyKalmar** [sqlalchemy/sqlalchemy#6623]
**Describe the bug**
Connection pool pre-pinging does not work as expected.

**To Reproduce**
I do not have a reproduction code yet (the error appears in a complex application), however, looking at https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/default.py#L687, https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/default.py#L304 and finally https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/default.py#L273 it seems like this is a coding error which appears when the `DefaultDialect` is initialized without a `dbapi` parameter.

**Error**
I'm getting the following error when using pre_ping with https://github.com/aws/amazon-redshift-python-driver and https://github.com/sqlalchemy-redshift/sqlalchemy-redshift:

```
TimeoutError: [Errno 110] Connection timed out
  File "sqlalchemy/engine/default.py", line 560, in do_ping
    cursor.execute(self._dialect_specific_select_one)
  File "redshift_connector/cursor.py", line 175, in execute
    self._c.execute(self, "begin transaction", None)
  File "redshift_connector/core.py", line 1162, in execute
    self._flush()
  File "socket.py", line 604, in write
    return self._sock.send(b)
  File "ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "ssl.py", line 642, in write
    return self._sslobj.write(data)

AttributeError: 'NoneType' object has no attribute 'Error'
  ...
  File "infrastructure/aws/redshift.py", line 62, in query
    connection = self._connection_pool.connect()
  File "sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "sqlalchemy/pool/base.py", line 809, in _checkout
    result = pool._dialect.do_ping(fairy.connection)
  File "sqlalchemy/engine/default.py", line 563, in do_ping
    except self.dbapi.Error as err:
```

**Versions.**
 - OS: CentOS Linux 7
 - Python: 3.6.8
 - SQLAlchemy: 1.3.20
 - Database: AWS Redshift
 - DBAPI: https://github.com/aws/amazon-redshift-python-driver

**Have a nice day!**

**Comment by zzzeek** [comment]
the "dbapi" parameter to DefaultDialect is not required because all dialects produce their own DBAPI using the [dbapi](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/psycopg2.py#L791) method.       this error seems to be fully specific to sqlalchemy-redshift and you should be reporting this stack trace on that tracker first, where they can at least test out the pre_ping feature on an AWS database of their own, we have no access to such an environment here.

**Comment by GergelyKalmar** [comment]
That is fair. However, if it isn't required, then `do_ping` has the potential to throw up (as we can see), which is unlikely what the intention is. (You are making an assumption that `self.dbapi` exists but not checking before using it nor are you requiring it in the constructor.)

I figured I can fix it by providing a `dbapi` parameter to the dialect when creating the queue pool:
```
QueuePool(
    ...
    creator=partial(redshift_connector.connect, **REDSHIFT_CONNECTION_CONFIG),
    dialect=RedshiftDialect(dbapi=redshift_connector),
    **(REDSHIFT_CONNECTION_POOL_CONFIG),
)
```

Regardless, I think this issue would appear with any dialect (when the `dbapi` argument isn't given but pre_ping is used), so it is not quite specific to the Redshift dialect or driver. In fact, `RedshiftDialect` just inherits from `PGDialect` (see https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/master/sqlalchemy_redshift/dialect.py#L403).

**Comment by zzzeek** [comment]
> That is fair. However, if it isn't required, then `do_ping` has the potential to throw up (as we can see), which is unlikely what the intention is. (You are making an assumption that `self.dbapi` exists but not checking before using it nor are you requiring it in the constructor.)

many DefaultDialect methods require that .dbapi is present so it is not practical to check that this parameter is non-None in every case.  If I were to add a "fix" for this, it would simply be if the dialect is being asked to do_ping and dbapi is None, that's simply invalid, the fix would be that we raise an error, "cant call do_ping when .dbapi is not initialized".  That is a nicer looking error message but does not get you any closer to solving your problem nor does it fix whatever is wrong in the redshift dialect.   

Also the fact that you are constructing a QueuePool manually looks to suggest something about your actual usage pattern, which you have not shared here.   

If the issue is in sqlalchemy-redshift as is suspected, the reason dialects like these are third party and not part of SQLAlchemy itself is to spread out the maintenance burden, so I would appreciate it if you can please take this issue to them first, and we will make whatever changes are needed if an unexpected use case is shown to exist.     To continue here, we require that an [MCVE](http://stackoverflow.com/help/mcve) using only SQLAlchemy APIs is produced, illustrating a real-world use case that produces the problem (that is, if you show me a DefaultDialect(dbapi=None) and try to use it by itself, sure, but that's not a real world use case).    The emphasis here is on solving real use cases, not getting bogged down with every possible AttributeError produced by artificial use case.  thanks!



> 
> I figured I can fix it by providing a `dbapi` parameter to the dialect when creating the queue pool:
> 
> ```
> QueuePool(
>     ...
>     creator=partial(redshift_connector.connect, **REDSHIFT_CONNECTION_CONFIG),
>     dialect=RedshiftDialect(dbapi=redshift_connector),
>     **(REDSHIFT_CONNECTION_POOL_CONFIG),
> )
> ```
> 
> Regardless, I think this issue would appear with any dialect (when the `dbapi` argument isn't given but pre_ping is used), so it is not quite specific to the Redshift dialect or driver. In fact, `RedshiftDialect` just inherits from `PGDialect` (see https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/master/sqlalchemy_redshift/dialect.py#L403).

**Comment by zzzeek** [comment]
seems to be an external driver issue
