### ISSUE TITLE
implement  / document the recommended pattern for traditional overriding of get_bind() in terms of AsyncSession

### ISSUE THREAD

**Issue by davidandreoletti** [sqlalchemy/sqlalchemy#6689]
**Describe the bug**
With a subclass of AsyncSession with a custom get_bind() implementation, AsyncSession.get_bind() method will not be called because all AsyncSession methods actually delegate [the "work"](https://github.com/sqlalchemy/sqlalchemy/blob/52effe545fafe80570663d9c462166302efae082/lib/sqlalchemy/ext/asyncio/session.py#L130) to `Session` instance. 

This is breaking the dynamic engine/binding resolution mechanism for system using database shards.

**Workaround**: Override the instantiation of Session with a custom Session object in the AsyncSession's [constructor](https://github.com/sqlalchemy/sqlalchemy/blob/52effe545fafe80570663d9c462166302efae082/lib/sqlalchemy/ext/asyncio/session.py#L79)

**To Reproduce**
``` python
Base = declarative_base()
class RandomTable (Base):
    __tablename__ = "random"
```

``` python
class MyAsyncSession(AsyncSession):
   ...
   def get_bind(mapper=None, clause=None):
       print("Custom binding resolution called")
       ....

``` 

``` python

async def async_main():
    """Main program function."""

    engine = create_async_engine(
        "postgresql+asyncpg://localhost/test"
    )

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    session = sessionmaker(
         expire_on_commit=False, class_=MyAsyncSession
    )

    await session.execute(select(RandomTable)).scalars().all()
    // MyAsyncSession.get_bind is never called and therefore bind resolution heuristics algo fails. See error below.
```

**Error**
```
    File "/Users/davidis/.pyenv/versions/eagleeye/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/session.py", line 143, in execute
    return await greenlet_spawn(
    File "/Users/davidis/.pyenv/versions/eagleeye/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 116, in greenlet_spawn
    result = context.switch(*args, **kwargs)
    File "/Users/davidis/.pyenv/versions/eagleeye/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1677, in execute
    bind = self.get_bind(**bind_arguments)
    File "/Users/davidis/.pyenv/versions/eagleeye/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2094, in get_bind
    raise sa_exc.UnboundExecutionError(
sqlalchemy.exc.UnboundExecutionError: Could not locate a bind configured on mapper mapped class RandomTable->random, SQL expression or this Session.
```

**Versions.**
 - OS:  MacOS 11.2.2
 - Python: Python 3.8.9
 - SQLAlchemy: 1.14.20
 - Database: Postgres
 - DBAPI: asyncpg

**Additional context**

None.

**Have a nice day!**

**Comment by zzzeek** [comment]
I would propose we add "session_class" parameter to ``AsyncSession``, and users who want to override `get_bind()` continue to do so on the traditional `Session` class.  the `AsyncSession` is a proxy to a `Session` only.  Right now the ORM event model is also in terms of `Session` and not `AsyncSession`, so users of `AsyncSession` I think should generally try to be familiar with the fact that it's providing only "async" adaptation of an actual `Session`.

**Comment by zzzeek** [comment]
otherwise, the architecture becomes:

```
   AsyncSession -> proxies -> Session
                           -> injects its own get_bind() into -> Session 
```

The first thing that is awkward is what does AsyncSession.get_bind() return; we would assume AsyncEngine which then means more translation has to go on if AsyncSession were to be injecting it's own get_bind() into the impl Session.

Overall this creates an awkward cycle, and also places the ``Session.get_bind()`` method in a special category that does not apply to any other method, which would be only because it's one particular method that we happen to document as particularly useful to override.   But this wouldn't apply to any other methods, which is unintuitive, and really the whole "get_bind() as subclassable" idea really starts to look like it should all be done using a more modern event hook instead in any case.   longer term I'd rather go towards:

1. make a new event hook on SessionEvents to handle get_bind() use cases
2. document / improve the system by which AsyncSession users use SessionEvents

**Comment by CaselIT** [comment]
I was also thinking about providing a `session_class` to do this. all other solution break the proxy abstraction

**Comment by luisroel91** [comment]
Is there a workaround for this currently? Does setting bind=asynengine still fix this?
