### ISSUE TITLE
delete() with joined table inheritance (JTI) issues bad DELETE...USING statement that deletes all rows in the child table

### ISSUE THREAD

**Issue by nlevitt** [sqlalchemy/sqlalchemy#6743]
**Describe the bug**

delete() with joined table inheritance (JTI) issues bad DELETE...USING statement that deletes all rows in the table with postgresql.

**To Reproduce**

```py
from sqlalchemy import Column, Integer, ForeignKey, create_engine, String
from sqlalchemy.orm import declarative_base, sessionmaker

# import logging
# logging.basicConfig()
# logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)

Base = declarative_base()

class Employee(Base):
    __tablename__ = 'employee'
    id = Column(Integer, primary_key=True)
    name = Column(String(50))
    type = Column(String(50))

    __mapper_args__ = {
        'polymorphic_identity':'employee',
        'polymorphic_on':type
    }

    def __repr__(self):
        return "<Employee id={!r} type={!r} name={!r}>".format(self.id, self.type, self.name)

class Engineer(Employee):
    __tablename__ = 'engineer'
    id = Column(Integer, ForeignKey('employee.id', ondelete='CASCADE'), primary_key=True)

    __mapper_args__ = {
        'polymorphic_identity':'engineer',
    }


db = create_engine("postgresql://localhost:5434/")
Base.metadata.create_all(db)

session = sessionmaker(db)()
session.add(Engineer(name='Alice'))
session.add(Engineer(name='Bob'))
session.commit()

print("engineers: {}".format(session.query(Engineer).all()))
print("engineers named Alice: {}".format(session.query(Engineer).filter(Engineer.name == "Alice").all()))
print("deleting engineers named Alice")
session.query(Engineer).filter(Engineer.name == "Alice").delete()
print("engineers: {}".format(session.query(Engineer).all()))
session.commit()
```

**Error**

Output of the above program:
```
engineers: [<Employee id=1 type='engineer' name='Alice'>, <Employee id=2 type='engineer' name='Bob'>]
engineers named Alice: [<Employee id=1 type='engineer' name='Alice'>]
deleting engineers named Alice
engineers: []
```

SQL statement logging reveals the bad query to be:
```
INFO:sqlalchemy.engine.Engine:DELETE FROM engineer USING employee WHERE employee.name = %(name_1)s
INFO:sqlalchemy.engine.Engine:[generated in 0.00011s] {'name_1': 'Alice'}
```
This deletes all rows in the `engineer` table (and none in the `employee` table).

**Versions.**
 - OS: macOS 10.15.7
 - Python: Python 3.8.2
 - SQLAlchemy: 1.4.20
 - Database: Postgresql 13
 - DBAPI: psycopg2

**Additional context**

Seems pretty dangerous to be deleting extraneous data.

https://github.com/sqlalchemy/sqlalchemy/issues/6177 is a similar report, but in that case the database rejected the SQL. On https://github.com/sqlalchemy/sqlalchemy/discussions/6178 @zzzeek wrote:

> For this reason, ORM-enabled UPDATE and DELETE of multiple rows are explicitly not supported for joined-table inheritance setups, and this is documented in the big pink dragon box at https://docs.sqlalchemy.org/en/14/orm/session_basics.html#orm-expression-update-delete :
> > ORM-enabled UPDATEs and DELETEs do not handle joined table inheritance automatically. If the operation is against multiple tables, typically individual UPDATE / DELETE statements against the individual tables should be used. Some databases support multiple table UPDATEs. Similar guidelines as those detailed at Multiple Table Updates may be applied.

and

> We usually have to do something more sophisticated than "if with_polymorphic is not None: raise", mappings can be against any kinds of selectables which may or may not work. The database itself is the best authority on what SQL works and what doesn't so in the absense of a really well thought out plan for everything that will definitely not work and everything that might work, we just let the database do it.

But it seems to me that "if with_polymorphic is not None: raise" might be the best solution. 

**Have a nice day!**

**Comment by zzzeek** [comment]
> **Describe the bug**
> 
> delete() with joined table inheritance (JTI) issues bad DELETE...USING statement that deletes all rows in the table with postgresql.

as you noted in the docs, this is expected right now as joined table inheritance is not supported with query.update() or query.delete() right now.  it's very clearly noted.   It would be nice if this all worked someday, and maybe that will happen (like in a 2.1 or 2.2 type of thing), however it would be lots of effort and complexity (especially that it would need to emit multiple DELETE statements for separate tables) for a feature that isn't that critical.    


> 
> Seems pretty dangerous to be deleting extraneous data.

hard disagree on "dangerous", this is no more "dangerous" than any other query.delete() that might be written.  The above code will run the same structure every time and is fully deterministic.      "dangerous" only applies to things where an action that performs a particular result during development and testing suddenly does the wrong thing in response to unexpected runtime input or distant effects from other parts of the program.  This example is not "dangerous" as long as you don't have programmers writing arbitrary python code involving query.delete(), not testing it at all, then sticking it straight on production.      

> But it seems to me that "if with_polymorphic is not None: raise" might be the best solution.

"with_polymorprhic" is not necessary in order to have joined table inheritance and it isn't used in your example above.




> 
> **Have a nice day!**

**Comment by nlevitt** [comment]
> it's very clearly noted. It would be nice if this all worked someday, and maybe that will happen

I'm just requesting that for now sqlalchemy raise an exception telling you it's not supported, so people don't shoot themselves in the foot. I can't say that I've carefully read and grokked the documentation for every sqlalchemy method I've used. That seems like a high bar.

> This example is not "dangerous" as long as you don't have programmers writing arbitrary python code involving query.delete(), not testing it at all, then sticking it straight on production.

Realistically not all code that runs against important data goes through rigorous testing. For example you might be using sqlalchemy in a python shell to fix some urgent issue for a customer.

> "with_polymorprhic" is not necessary in order to have joined table inheritance and it isn't used in your example above.

Ah my bad, I kind of glossed over that and assumed it was shorthand for "uses JTI"

**Comment by zzzeek** [comment]
the problem is I dont want to break query.update() / delete() for people that are using it right now with various inheritance situations in such a way that it is working for them.  the methods will work with single table inheritance, concrete inheritnace, and also in some degree of cases for joined inheritatnce too.    writing a whole set of logic to guess when the user might be stepping into areas that we can't be sure will be 100% intuitive is just as hard as implementing the whole feature.   unfortunately.   that's why it's documented and does not have logic that tries to guess if someone is veering into unsupported areas.   

> For example you might be using sqlalchemy in a python shell to fix some urgent issue for a customer.

it would be super extreme to write straight Python code on the fly to write CRUD operations into a live production database without attempting to test on sample data, and even then to automatically commit the transaction without checking what SQL was emitted.   This would be an unreasonably high bar for a tool like SQLAlchemy to achieve within the ORM.
