### ISSUE TITLE
Add count example to the 2.0 migration table

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6794]
We should add a count example to the table in the 2.0 migration https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-orm-usage

Something like `session.query(User).count()` -> `session.execute(sa.select(sa.func.count('*')).select_from(User)).scalar()` or `session.execute(sa.select(sa.func.count(User.id))).scalar()`

Mike which one do you prefer?

**Comment by zzzeek** [comment]
`func.count()` does the star automatically, so it should be:

```py
count = session.scalar(select(func.count()).select_from(User))
```

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Add count example to 2.0 migration table** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2976

**Comment by yonoss** [comment]
Is it possible to have the count method at the result set level?  With the proposed approached it seems to me that you have to have a dedicated select to get the count. That was not the case with the query.count(). What I mean is that with the query approach, you could have used the same query to get the count or to get the whole result set, etc

**Comment by CaselIT** [comment]
Hi,

I'm sure mike already replied to the reasoning for not having a select.count() method, but I cannot find it at the moment.
This has some explanation of the rationale https://github.com/sqlalchemy/sqlalchemy/discussions/6334

>Is it possible to have the count method at the result set level?

The result set represents the result of a query that has already run, so count cannot be attached there, since a result set does not run queries. 

>That was not the case with the query.count(). What I mean is that with the query approach, you could have used the same query to get the count or to get the whole result set, etc

you can to the same thing also for v2 orm style queries. I agree that it's less convenient than `query.count()`
```py
my_select = select(...)
count_select = select(func.count()).select_from(my_select.subquery())
```

**Comment by zzzeek** [comment]
the problem with count is that there are at least two different interpretations of what "count" means, and it is not obvious with a method like query.count() which of the two interpretations should be taken.   it turns out that this interpretation is very difficult to automate, as we were doing so for many years and kept having more and more bugs reported, for years, where this interpretation continued to fail, until we removed this decision making process from query.count() and hardcoded it to use just one of these two interpretations in all cases, one which returns a value that people expect, but which does so using more expensive SQL that continues to generate complaints.

the two interpretations of count() are:

1. replace the columns of a SELECT with a single call to "COUNT('*')"


that is:


    SELECT a, b, c FROM table

becomes

    SELECT count(*) FROM table

easy enough.    

However, it breaks in lots of cases, such as:

    SELECT a, b, c FROM table LIMIT 3

uh oh, we can't just add count(*) to that:

    SELECT count(*) FROM table LIMIT 3

will simply return the number of rows in "table" - user will post a bug, "LIMIT 3 is ignored, the answer should be 3"

the "expected" query in the above case is:

   SELECT count(*) FROM (SELECT a, b, c FROM table LIMIT 3)

all kinds of similar things happen with issues like DISTINCT, other aggregate functions, etc.

so for a long time Query would guess which form was more appropriate, and for years and years it kept guessing wrong.  so eventually we made it do just the subquery form, which is unreasonably expensive in many scenarios.

2.0 takes Guido's advice of "In the face of ambiguity, refuse the temptation to guess." and makes this choice of SQL form an explicit choice.  when the user has to type out `select(func.count()).select_from(table)`, there is litle to no chance they are going to do something like add "limit(3)" or "distinct()" and then be surprised that they dont get the count the expect.  we have the user write SQL, it's transparent and they know whats going on.
