### ISSUE TITLE
Using limit with joinedload makes prefix_with appear in a subquery

### ISSUE THREAD

**Issue by huntfx** [sqlalchemy/sqlalchemy#6811]
**Background**
I'm adding an optional timeout to my queries using [this](https://stackoverflow.com/a/62630542/2403000) method:

```py
if timeout is not None:
    stmt = stmt.prefix_with(f'/*+ MAX_EXECUTION_TIME({int(timeout * 1000)}) */', dialect='mysql')
```

**Describe the bug**

If using both `limit` and `joinedload`, then anything added via `prefix_with` will appear in a subquery, and not in the main query.
With the above example, it causes the `MAX_EXECUTION_TIME` parameter to be ignored.

**To Reproduce**

```py
from sqlalchemy import select, Column, Integer, ForeignKey
from sqlalchemy.orm import relationship, joinedload
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Parent(Base):
    __tablename__ = 'parent'
    id = Column(Integer, primary_key=True)
    children = relationship("Child")

class Child(Base):
    __tablename__ = 'child'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('parent.id'))


stmt = select(Parent).options(joinedload(Parent.children)).limit(50)
print(stmt.prefix_with('>> TEST <<'))
```

**Actual**

```sql
SELECT anon_1.id, child_1.id AS id_1, child_1.parent_id
FROM (SELECT >> TEST << parent.id AS id
FROM parent
 LIMIT :param_1) AS anon_1 LEFT OUTER JOIN child AS child_1 ON anon_1.id = child_1.parent_id
```

**Expected**
```sql
SELECT >> TEST << anon_1.id, child_1.id AS id_1, child_1.parent_id
FROM (SELECT parent.id AS id
FROM parent
 LIMIT :param_1) AS anon_1 LEFT OUTER JOIN child AS child_1 ON anon_1.id = child_1.parent_id
```

**Versions.**
 - OS: Windows 10
 - Python: 3.7.9
 - SQLAlchemy: 1.4.15
 - Database: MySQL
 - DBAPI: mysqlclient

**Comment by CaselIT** [comment]
Hi,

I think this is working as expected. SQLAlchemy cannot assume that the with_prefix options can be transferred to the outer query since these are user defined and may only be valid if applied to the inner select.

You can change the loader option to something else, like selectinload, to avoid the change to the query

**Comment by huntfx** [comment]
To counter that point, would it make sense to put it on the outer query if the select was done on a single ORM model, since the entire statement is all automatically generated at that point?

For example:
```py
# Put it on the outer query
stmt = select(Child)  

# Keep it in the inner query
stmt = select(Child.id, Child.parent_id)
```

Alternatively, something like `.with_prefix(xyz, force_outer=True)` could be nice.

I gave my code a quick test with `selectinload` and it's about 3x slower, but it also doesn't have the prefix applied, so that way doesn't work with the execution time limit. I had a play with manually reconstructing what the ORM does, so if it is indeed expected behaviour I can at least work around this (after I figure out how to fix the joins)

```py
# Old
stmt = select(Info).options(
    lazyload('*'),
    joinedload(Info.link).joinedload(Link.data),
).limit(50)
stmt = stmt.prefix_with(f'/*+ MAX_EXECUTION_TIME(1000) */', dialect='mysql')

# New
stmt = select(
    Info.id,
    Info.start_date,
    Info.end_date,
).limit(50)
subquery = stmt.subquery()
stmt = select(
    subquery.c.id,
    subquery.c.start_date,
    subquery.c.end_date,
    Data.key,
    Data.value,
).outerjoin(Link, Link.info_id == subquery.c.id).join(Data)  # This bit needs fixing
stmt = stmt.prefix_with(f'/*+ MAX_EXECUTION_TIME(1000) */', dialect='mysql')
```

**Comment by zzzeek** [comment]
trying to understand the use case, "selectinload is 3x slower", OK but that's  query that completed successfully.  the max_execution_time thing from everything I can see will cause your query to raise an error, and that's the only difference.  so is that the behavior you're looking for?

From a "fast/slow" perspective, not including pre-emptive query timeouts, selectinload emits a query that was tailor made for MySQL's optimizers, whereas joinedload(), especially with LIMIT, emits a query that is basically the worst case scenario for MySQL.    "selectinload"s main customer is MySQL. 

So overall if your main thing is, "here are some rows, but if it takes too long, then i dont want them and just abort", I'd just emit a SELECT for those rows directly in the same way selectinload works, but just run it separately, that is, `select(Child).where(Child.id.in_([obj.id for obj in my_obj])).prefix_with("max exec time thing")`.    if you want to knit the results from this query back to your top level objects, there used to be a recipe for this that seems to not be there....but the idea is to match the incoming rows back to the primary keys and use [set_committed_value](https://docs.sqlalchemy.org/en/14/orm/session_api.html?highlight=set_committed_value#sqlalchemy.orm.attributes.set_committed_value) to establish the collections on the parent objects, I can write this out if it interests you.

There's other ways to make this happen too depending on what we are going for:

1. any joinedload() can be rewritten, pretty easily in fact, using join() and contains_eager().  to get exactly what you asked for at the top I would just use that approach.    contains_eager() is documented at https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html?highlight=contains_eager#contains-eager and is generally how you "drop down" to more explicit control of a joinedload situation as is the case here.
2. to affect how secondary ORM queries run like that of lazyload and selectinload there are ways to use the [do_orm_execute](https://docs.sqlalchemy.org/en/14/orm/events.html?highlight=do_orm_execute#sqlalchemy.orm.SessionEvents.do_orm_execute) to intercept and modify these 

re: the option itself, some kind of "apply to the toplevel" thing seems like what would involve this most directly but I am hesitant, as I am in most cases, to just shove more arbitrary flags and switches into things.    The case where the user doesn't actually have direct access to the "top level" is really just this one quite narrow use case of joinedload() with limit(), which is already a case that we are trying to discourage.    The issue here is revealing that meaning of "the top level" might not be as clear as we think; what you really want to do is apply a SQL hint to **the relationship load**.   that is, you might want this hint applied to selectinload, or lazyload, or anything else.   Then it starts to look like what you *really* want might be something like:

```
select(...).options(selectinload(Foo.bar).options(select_prefix_with="my hint"))
```

that would almost seem like the better option here.

but that's a lot of API to add for a very unusual use case, so there's not a lot of momentum for that at the moment (but as the laws of two implies, we might get another request for this same thing later today).     

right now I'd try going with "use contains_eager()" or "write the SELECT IN query explicitly".

I sort of consider this issue to be a discussion for now because theres' many different ways to accommodate the use case here so it's important to pin point the thing that you *really* need to do.

**Comment by huntfx** [comment]
Thanks as always for the detailed reply. I understand what you mean about being hesitant about implementing anything, though for the record - not that I need it anymore after your help - I do like the syntax you proposed with the `select_prefix_with` idea.

> trying to understand the use case,

I've built an API for use internally at work. For each endpoint I was setting a maximum limit, but it was completely arbitrary and got in the way considering it's just my team who will ever need to access it. I've now removed the limit, but I'd like to use timeouts as a safeguard to prevent any rogue queries from running for hours, since simply closing the page won't stop the query.

> "selectinload is 3x slower"

Forget what I said about it being 3x slower, I gave it another try with a limit of 5000 instead of 50, and it's nearly 2x faster. I'm going to use your suggestion of writing the query manually and merging the results.

> any joinedload() can be rewritten, pretty easily in fact, using join() and contains_eager(). 

Gave that a quick try, it still resulted with the prefix being added to the inner query. I like the idea of `contains_eager` though, hopefully I'll find a use for it in the future.

> which is already a case that we are trying to discourage

Is this just what you were referring to about `selectinload` being a lot more optimised? I'm guessing `joinedload` is a fine for fetching a single record, but `selectinload` is preferred for fetching many?

-------

From having `echo=True` I saw you were chunking the results in sizes of 500, so I added that into my code.

I found that using `set_committed_value` on the models was about 50% slower (2.1 seconds from 1.4 when just using the ORM), but by manually tailoring the queries to what I needed, it dropped it back down to 1.2 seconds.

I may as well paste the code for the sake of if anyone else comes across this later

```py
chunk_size = 500

def chunks(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i + n]

def prepare_stmt(stmt):
    return stmt.options(lazyload('*')).prefix_with(f'/*+ MAX_EXECUTION_TIME(1000) */', dialect='mysql')
```

With models (2.1s):

```py
# Query SessionInfo
stmt = select(SessionInfo).limit(5000)
result = session.execute(prepare_stmt(stmt))
infos = {info.id: info for info in result.scalars()}

# Query SessionLink
info_links = defaultdict(list)
data_links = defaultdict(list)
for chunk in chunks(tuple(infos.keys()), chunk_size):
    stmt = select(SessionLink).where(SessionLink.info_id.in_(chunk))
    result = session.execute(prepare_stmt(stmt))

    for link in result.scalars():
        info_links[link.info_id].append(link)
        data_links[link.data_id].append(link)

# Query SessionData
datas = {}
for chunk in chunks(tuple(data_links.keys()), chunk_size):
    stmt = select(SessionData).where(SessionData.id.in_(chunk))
    result = session.execute(prepare_stmt(stmt))
    datas.update({data.id: data for data in result.scalars()})

# Set values
for info_id, children in info_links.items():
    set_committed_value(infos[info_id], 'link', children)
for data_id, children in data_links.items():
    set_committed_value(datas[data_id], 'link', children)

result = list(infos.values())
print(result[0].data['username'])
```

Without models (1.2s):
```py
# Query SessionInfo
stmt = select(SessionInfo.id, SessionInfo.start_date, SessionInfo.end_date).limit(5000)
result = session.execute(prepare_stmt(stmt))
infos = {id: [start_date, end_date, {}] for id, start_date, end_date in result.fetchall()}

# Query SessionLink
info_links = defaultdict(list)
data_links = set()
for chunk in chunks(tuple(infos.keys()), chunk_size):
    stmt = select(SessionLink.info_id, SessionLink.data_id).where(SessionLink.info_id.in_(chunk))
    result = session.execute(prepare_stmt(stmt))

    for info_id, data_id in result.fetchall():
        info_links[info_id].append(data_id)
        data_links.add(data_id)

# Query SessionData
datas = {}
for chunk in chunks(tuple(data_links), chunk_size):
    stmt = select(SessionData.id, SessionData.key, SessionData.value).where(SessionData.id.in_(chunk))
    result = session.execute(prepare_stmt(stmt))
    datas.update({id: (key, value) for id, key, value in result.fetchall()})

# Match values
for info_id, info_data in infos.items():
    data_ids = info_links[info_id]
    data = map(datas.__getitem__, data_ids)
    info_data[2].update({k: v for k, v in data})
```

**Comment by zzzeek** [comment]
joinedload for collections that can be of zero length means you have at the very least a LEFT OUTER JOIN, which is bad, then any of the limit/offset use cases here it has to do the subquery thing, which is also bad, then yes it gets N*M rows back which include a lot of repeated columns for the parent object.    selectinload uses usually no joins, no subqueries, and returns the miminum amount of data.

in this case the contains_eager() equivalent to the jionedload() is

```py
stmt = select(Parent).limit(50).subquery()

subq = aliased(Parent, stmt)

stmt = (
    select(subq)
    .join(subq.children)
    .options(contains_eager(subq.children))
    .prefix_with(">> TEST <<")
)
print(stmt)
```

**Comment by CaselIT** [comment]
From my experience the joinedload is better only if the network latency to the db is larger that the db execution time, usually that's the case for collections with a low number of children (say less than 50) and where the parent data is not physically large  (so int/dates are probably ok, unbounded text is not) so that its replication does not have adverse effects on transmission time.

All in all selectinload is probably a safer bet unless tests for a specific case show otherwise

**Comment by huntfx** [comment]
Oh, that actually makes perfect sense now haha.
An API we rely on at work has a very high network latency (roughly 50ms to do anything), so fetching everything in a single query was the way to go. I then just sort of assumed that same method was the best for all databases, and didn't give it a second thought until now.

Thanks a lot both for the replies anyway, I've learned a lot. That original query is now 7x faster in some cases, and I have a couple of other heavily-joined queries which I'm looking forward to having a play with. The timeout is now working correctly on everything too.

I'll give this a close now, really appreciate all the help :)
