### ISSUE TITLE
add loader options to session.merge, asyncsession.merge

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6955]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/6953

as mentioned in the linked discussion, `session.get()` allows for loader options, which is new as "get()" is historically part of `Query`.  These loader options should be possible for `merge()` also.   There's part of a PR in the linked discussion for this,should also be added to asyncsession, needs some docstrings and some tests.

**Comment by daniel-stoneuk** [comment]
I've been having a look into this and it seems like the options pass through is working well, so I've started to write tests for the PR which I'll make soon. I have noticed some interesting points in the meantime.

If the `.merge` call is made with an identity that already exists, there is no problem eagerly loading relationships. Assuming the database enforces foreign key constraints, we can be sure that once the `.merge` is performed, either:

a) A `.get` was made with loader options, and the existing relationship collection records have been eagerly loaded
b) The object has been added to the session, and the relationship collection is assumed to be empty (due to the foreign key constraint)

While testing, I noticed that if a flush is performed after the add operation, the relationship collection will be lazily loaded. This is the same with a normal `.add`, in the following code snippet:

```python
async with async_session() as session:
    async with session.begin():
        session.add_all(
            [
                A(bs=[B(), B()], data="a1"),
                A(bs=[B()], data="a2"),
                A(bs=[B(), B()], data="a3"),
            ]
        )

    a4 = A(
        data="a4 new"
    )
    session.add(a4)
    await session.flush()

    print(a4.id) # 4
    print(a4.data) # a4 updated
    for b in a4.bs: # blocking call
        print(b)

    await session.commit()
```

I suppose, since I haven't defined a list of `bs` in `a4`, the ORM will mark `bs` as expired* on flush. Is there a way to change the loading strategy of relationships for an instance being added to the session? 

*I'm not sure if this is the right terminology here.

For my use-case, this PR is still a valid and useful fix and the above discovery has prompted me to move the `session.flush()` to a better location.

I don't have extensive experience with SQLAlchemy, so please forgive me if I've missed something obvious! Thanks.

**Comment by zzzeek** [comment]
> I suppose, since I haven't defined a list of `bs` in `a4`, the ORM will mark `bs` as expired* on flush. Is there a way to change the loading strategy of relationships for an instance being added to the session?

there are not-currently-public ways of establishing particular loader strategies there but there's no query being emitted where these strategies would have a chance to be emitted.   i guess you would want some kind of "load" to occur within the flush(), as that's already awaitable.   there's ways to add logic to the flush routine by using an event such as [after_flush_postexec](https://docs.sqlalchemy.org/en/14/orm/events.html?highlight=after_flush_postexec#sqlalchemy.orm.SessionEvents.after_flush_postexec) where you could add blocking code to load unloaded relationships.

overall the best strategy is to set an empty list on `a4 = A(bs=[])`.

> 
> I don't have extensive experience with SQLAlchemy, so please forgive me if I've missed something obvious! Thanks.

you're following along way better than the vast majority of newcomers and not-so-newcomers.

**Comment by daniel-stoneuk** [comment]
Cheers, setting the empty list makes a lot of sense. Thanks again for the help.

**Comment by sqla-tester** [comment]
**Daniel Stone** has proposed a fix for this issue in the **master** branch:

**Added loader options to session.merge, asyncsession.merge** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3030
