### ISSUE TITLE
py3 dep required for py2 install

### ISSUE THREAD

**Issue by tucked** [sqlalchemy/sqlalchemy#7010]
### Describe the bug

https://github.com/sqlalchemy/sqlalchemy/commit/b2f2bf1acc5799221981d30c2bf9ed29d5ca6312 requires `pg8000 >= 1.16.6`  which does not support Python 2, yet the package claims support for Python 2.7:
https://github.com/sqlalchemy/sqlalchemy/blob/6dbcb792eb60d4e084f0d1252882a0cbad4bc673/setup.cfg#L37

### To Reproduce

```python
`python2 -m pip install SQLAlchemy` then try to use the `postgresql` dialect.
```

### Error

```
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/create.py", line 561, in create_engine
    dialect = dialect_cls(**dialect_args)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/dialects/postgresql/pg8000.py", line 395, in __init__
    raise NotImplementedError("pg8000 1.16.6 or greater is required")
NotImplementedError: pg8000 1.16.6 or greater is required
```

### Versions

- OS: OneFS (but any should do)
- Python: 2.7.18
- SQLAlchemy: 1.4.23
- Database: postgresql
- DBAPI: pg8000

**Comment by zzzeek** [comment]
pg8000 has dropped Python 2 support, so you can't use the SQLAlchemy pg8000 dialect in version 1.4 with Python 2.    You can certainly install SQLAlchemy on Python 2 however, you just would have to use a different postgresql driver namely psycopg2.

**Comment by zzzeek** [comment]
if you could indicate the behavior you'd expect we can describe what can be done.

**Comment by tucked** [comment]
Since this package claims support for Python2, I would expect to be able to use it with Python2, but this manually bans any Python2-supporting version of `pg8000` (_after_ install time).

This isn't really a blocking issue for us AFAIK, so it's fine to leave it closed... It just seems incorrect.

**Comment by zzzeek** [comment]
We can unban pg8000 but the pg8000 dialect won't work. It uses new apis that are not in the older pg8000 version.  Because sqlalchemy supports only a minimum version of pg8000, it can't work on python 2.

**Comment by zzzeek** [comment]
Like I don't understand what you would consider "correct" here besides having a backported dialect available.  Non-compatibility with old libraries might be a problem but I'm not seeing the "incorrect" part of that.

**Comment by tucked** [comment]
> It uses new apis that are not in the older pg8000 version.

This is exactly the issue, isn't it? [`pg8000` dropped support for py2 in 1.13.0.](https://github.com/tlocke/pg8000/commit/20634912d155ea4fd0c80e672ae9aa5b2c2a48ac#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7)... So, 1.12.x is the latest usable version for a downstream wanting to support Python 3 _and_ 2 (e.g. `sqlalchemy`). Using any APIs from later versions breaks Python 2 compat.

**Comment by CaselIT** [comment]
> 
> 
> > It uses new apis that are not in the older pg8000 version.
> 
> This is exactly the issue, isn't it? [`pg8000` dropped support for py2 in 1.13.0.](https://github.com/tlocke/pg8000/commit/20634912d155ea4fd0c80e672ae9aa5b2c2a48ac#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7)... So, 1.12.x is the latest usable version for a downstream wanting to support Python 3 _and_ 2 (e.g. `sqlalchemy`). Using any APIs from later versions breaks Python 2 compat.

Sorry but that does not make any sense. It would prevent using any driver that is py3k only.

As mentioned SQLAlchemy does support python2, but not all driver support it.

If you need to use pg8000 with python2 you can use the 1.3 series

**Comment by zzzeek** [comment]
> > It uses new apis that are not in the older pg8000 version.
> 
> This is exactly the issue, isn't it? [`pg8000` dropped support for py2 in 1.13.0.](https://github.com/tlocke/pg8000/commit/20634912d155ea4fd0c80e672ae9aa5b2c2a48ac#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7)... So, 1.12.x is the latest usable version for a downstream wanting to support Python 3 _and_ 2 (e.g. `sqlalchemy`). Using any APIs from later versions breaks Python 2 compat.

it's more than that because I worked with @tlocke to get everything in pg8000 working very well with 1.4.  Previously, in 4bd4bae5c1132e1ca, I began noting that pg8000 was not really supported any longer because it had too many non-working cases. Then Tony came along to do the 1.16 refactor which changed alot about the driver including adding setinputsizes() and all that, and he did most of the work porting the dialect over with commits such as 06f1929b866abc2af0ff5c838e4 and others.  We tried to keep the dialect somewhat "conditional", such as not calling setinputsizes() if we are on a pre 1.16 version, but then b2f2bf1acc5799221981d30 came along and it simply was not worth the effort to keep dragging along older pg8000 versions for the SQLAlchemy 1.4 series, which is meant as a transitional version for the 2.0 series that is Python 3 only.   Python 2 is now [extremely unpopular](https://pypistats.org/packages/sqlalchemy) (note on any given day there are around 25 times more downloads for Python 3 versions that Python 2),  pg8000 itself was a very little used driver.     SQLAlchemy is taking a super extra long time to be done with Python 2 but the world has moved on, it's basically the primary goal now to get SQLAlchemy 2 out and be done with Python 2 for good.

**Comment by tucked** [comment]
Yes, dropping py2 (in `python_requires`) would be the most sensible remedy IMO.

> It would prevent using any driver that is py3k only.

That's what it means to support py2...

> If you need to use pg8000 with python2 you can use the 1.3 series

This is the way. "One of our upstreams dropped support for py2. We want to continue supporting the latest releases, so we are also dropping py2 support (but you can continue using the previous release, of course)."

I understand the goal (essentially "partial" or "conditional" support). It just isn't really a feature of Python packaging, unfortunately. That's why this issue caused a problem... Something on Python2 was using `sqlalchemy`+`pg8000`, and it all worked fine. Then, `sqlalchemy` dropped py2 support for `pg8000` without removing py2 from `python_requires`. So `pip` (correctly) grabs the old `pg8000` but (incorrectly) grabs the newer `sqlalchemy`, which appears to work at install time but breaks at runtime.

**Comment by zzzeek** [comment]
> Yes, dropping py2 (in `python_requires`) would be the most sensible remedy IMO.

that would be entirely unreasonable.   we were not ready to drop support for Python 2.  some optional libraries were.  there's nothing wrong with that.    We also have a whole asyncio extension that naturally only works on Python3 only.  
> 
> > It would prevent using any driver that is py3k only.
> 
> That's what it means to support py2...

we have supported a few python 3 only drivers for many years while we suppored python 2 and 3 at the same time, such as pypostgresql.  there is nothing unusual about this.

> 
> > If you need to use pg8000 with python2 you can use the 1.3 series
> 
> This is the way. "One of our upstreams dropped support for py2. We want to continue supporting the latest releases, so we are also dropping py2 support (but you can continue using the previous release, of course)."

we were not ready to drop python 2 support.  having one single driver that is not widely used and is also very buggy (as it was) hold up an entire major release series is not reasonable for our project.

> 
> I understand the goal (essentially "partial" or "conditional" support). It just isn't really a feature of Python packaging, unfortunately. 
> That's why this issue caused a problem... Something on Python2 was using `sqlalchemy`+`pg8000`, and it all worked fine. Then, `sqlalchemy` dropped py2 support for `pg8000` without removing py2 from `python_requires`. 

our 1.3 -> 1.4 are treated as "major" releases with some backwards compatible changes, like removing deprecated APIs and drivers.  that's why we have the [migration guide](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html).   you absolutely should always have SQLAlchemy pinned on the second digit in your requirements.txt files.   100% migration from 1.3 to 1.4 is not expected.    we drop support for drivers *entirely* sometimes, such as the above mentioned pypostgresql.    


> So `pip` (correctly) grabs the old `pg8000` but (incorrectly) grabs the newer `sqlalchemy`, which appears to work at install time but breaks at runtime.

the issue is that SQLAlchemy removes old APIs and drivers for "minor" releases which are around yearly or more.  This is described at https://www.sqlalchemy.org/download.html#versions.     

i am very sorry you were inconvenienced, however please pin your SQLAlchemy versions on the second digit as a 1.x->1.y migration will never be expected to be 100% backwards compatrible.

**Comment by zzzeek** [comment]
here's an "incorrect" thing, is the pg8000 change is not in the migration guide.  will add that now.

**Comment by zzzeek** [comment]
also incorrect is that the changelog for the pg8000 change details changes to the driver itself, not the SQLAlchemy dialect, leading to misleading paragraphs about new features that aren't actually there.

**Comment by CaselIT** [comment]
I feel like we are going in circles.
We obviously don't agree on what py2 supports means, so I don't think there is much left to discuss.

As mike said, sorry if that's impacted you. I don't think there is a way of telling pip that 1.4 requires a particular version of pg8000 without making it a required dependency, so I don't think there is an automatic way of solving this.
Your options are to pin sqlalchemy to 1.3.x or change driver or migrate to python 3
