### ISSUE TITLE
Inspector.has_table does not reflect views in oracle, mssql

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7161]
Inspector.has_table does not reflect views in oracle, mssql

It does instead reflect views in postgres. I've not tested it in mysql/mariadb but I think it does.

Docs would also need to be updated

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**The ``has_table`` method now also checks views** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3127

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**The ``has_table`` method now also checks views** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3138

**Comment by CaselIT** [comment]
@zzzeek do you think it makes sense to add the flag `include_views=True` to `has_table`?

this would require an explicit change to 3rd party dialects though.

**Comment by zzzeek** [comment]
id rather have had "has_view()" but now we're in backwards incompatible territory.  plus for efficiency checking for both at the same time is needed.

i think for the moment because Table(autoload) implies views also as does get_columns() (that works for all dialects,right) then has_table() has to do tables and views on all backends.  this also might nullify my concern about table permissions on Oracle.  but it's still late in 1.4.x for a behavioral change like that.

**Comment by CaselIT** [comment]
ok, let's target v2. The change should be done, but it should wait until we start the 2_0 branch (or move 1.4 to the 1_4 branch)
