### ISSUE TITLE
Uniform behavior of dialect reflection functions

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7334]
The reflection function in the dialects behave in different ways for what concerns missing tables.
For example postgresql raises `NoSuchTableError`, while sqlite, oracle ignore it and return empty dict/list.

I don't have an absolute preference here, probably raising `NoSuchTableError` may be nicer as interface.

there may be other cases what have similar discrepancies.

**Comment by zzzeek** [comment]
I dont think it's feasible for many dialects to raise NoSuchTableError as that implies they need to run additional queries to check whether the given table name exists.  for example if querying constraints for a table, the PG dialect always has to call get_table_oid() which is why it has a clean spot to raise NST.   another dialect that just SELECTs from a "constraints" table "where tablename=:name" would not be able to tell from that query alone if table X has no constraints or if it doesn't exist.

at the moment therefore I think the contract of these methods like get_columns(), get_constraints() etc. is that the given table name is expected to exist, and behavior if name is not present is undefined.  get_columns() is the one spot that we seem to be using as a "check if the table exists also" kind of point as we assume (wrongly) that all tables that exist have inspectable columns.

**Comment by CaselIT** [comment]
That's what I thought.

Regarding get_colums, reflect_table now checks if a table exists if no columns were reflected, so that should not be a problem.

Should pg (and all dialects) also default at not raising errors?
Maybe we could just require that a falsy value be returned, since that's what it's most likely to be already returned if no error is raised?

**Comment by zzzeek** [comment]
i think PG's get_table_oid() should keep raising but the methods that call upon it for other reasons should likely catch that error and return something.

**Comment by CaselIT** [comment]
Makes sense. With the multi reflect that method is bo longer called, so we can avoid raising.

So let's standardize on falsely value if the table is bot found

**Comment by CaselIT** [comment]
This was mostly done in the #4379
