### ISSUE TITLE
Tables with the same name (in different schemas) doesn't schema-qualifiy or disambiguate the local table name

### ISSUE THREAD

**Issue by DanCardin** [sqlalchemy/sqlalchemy#7471]
### note to users

a fix here is targeted at 2.0.  for a decent engine-level configuration to work around this on PostgreSQL, MySQL/MariaDB, SQLite for 1.4/1.3, see https://github.com/sqlalchemy/sqlalchemy/issues/7471#issuecomment-997207701 

### Describe the bug

When you have

* two tables with the same name
* one of those tables lives in the public schema
* the other is some other schema
* and both tables show up in a join on a query

the public one does not qualify itself, and becomes ambiguous in the query

I would ideally want this to qualify the query with `public.` (either through the dialect's default schema or i guess perhaps this relates to the search_path), or else for sqlalchemy to realize this is about to happen and internally alias the ambiguous table

### To Reproduce

```python
from sqlalchemy import Column, create_engine, ForeignKey, Integer
from sqlalchemy.engine.url import URL
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm.session import sessionmaker

Base = declarative_base()


class Foo(Base):
    __tablename__ = "foo"
    __table_args__ = dict(schema="foo")

    id = Column(Integer, primary_key=True)


class Bar(Base):
    __tablename__ = "foo"

    id = Column(ForeignKey("foo.foo.id"), primary_key=True)

    foo = relationship("Foo", uselist=False)


engine = create_engine(
    URL(
        host="localhost",
        drivername="postgresql+psycopg2",
        username="user",
        password="password",
        database="postgres",
        port="5532",
    )
)


engine.execute("drop schema if exists foo cascade")
engine.execute("create schema foo")
Base.metadata.create_all(engine)
Session = sessionmaker()
session = Session(bind=engine)

session.query(Bar).join(Foo).all()
```

### Error

```
/foo/meow.py:26: SADeprecationWarning: Calling URL() directly is deprecated and will be disabled in a future release.  The public constructor for URL is now the URL.create() method.
  URL(
Traceback (most recent call last):
  File "/foo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/foo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.AmbiguousAlias: table reference "foo" is ambiguous
LINE 2: FROM foo JOIN foo.foo ON foo.foo.id = foo.id
                                              ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/foo/meow.py", line 43, in <module>
    session.query(Bar).join(Foo).all()
  File "/foo/.venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2759, in all
    return self._iter().all()
  File "/foo/.venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/foo/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/foo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/foo/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/foo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/foo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/foo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/foo/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/foo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/foo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.AmbiguousAlias) table reference "foo" is ambiguous
LINE 2: FROM foo JOIN foo.foo ON foo.foo.id = foo.id
                                              ^

[SQL: SELECT foo.id AS foo_id
FROM foo JOIN foo.foo ON foo.foo.id = foo.id]
``` 

### Versions

- Python: 3.7+
- SQLAlchemy: 1.3+
- Database: postgres
- DBAPI: psycopg2

**Comment by zzzeek** [comment]
confirmed PostgreSQL doesn't want to assume "public" for the non-qualified table, which is unfortunate.

this is a very unusual use case and you certainly can schema-qualify tables as public, just set up the mapping as such and your MCVE (works perfectly, thanks) works fine

```py
from sqlalchemy import Column, create_engine, ForeignKey, Integer
from sqlalchemy.engine.url import URL
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm.session import sessionmaker

Base = declarative_base()


class Foo(Base):
    __tablename__ = "foo"
    __table_args__ = dict(schema="foo")

    id = Column(Integer, primary_key=True)


class Bar(Base):
    __tablename__ = "foo"
    __table_args__ = dict(schema="public")

    id = Column(ForeignKey("foo.foo.id"), primary_key=True)

    foo = relationship("Foo", uselist=False)


engine = create_engine(
    "postgresql://scott:tiger@localhost/test", echo='debug'
)


engine.execute("drop schema if exists foo cascade")
engine.execute("create schema foo")
Base.metadata.create_all(engine)
Session = sessionmaker()
session = Session(bind=engine)

session.query(Bar).join(Foo).all()
```

**Comment by zzzeek** [comment]
Okey doke mysql has the same problem

```py
from sqlalchemy import Column, create_engine, ForeignKey, Integer
from sqlalchemy.engine.url import URL
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm.session import sessionmaker

Base = declarative_base()


class Foo(Base):
    __tablename__ = "foo"
    __table_args__ = dict(schema="foo")

    id = Column(Integer, primary_key=True)


class Bar(Base):
    __tablename__ = "foo"
    
    # same issue on MySQL if this is not present
    #__table_args__ = dict(schema="test")

    id = Column(ForeignKey("foo.foo.id"), primary_key=True)

    foo = relationship("Foo", uselist=False)



#engine = create_engine("postgresql://scott:tiger@localhost/test", echo='debug')
#with engine.begin() as conn:
#    conn.execute("drop schema if exists foo cascade")
 #   conn.execute("create schema foo")

engine = create_engine("mysql://scott:tiger@localhost/test", echo='debug')
with engine.begin() as conn:
    conn.execute("create database if not exists foo")
Base.metadata.create_all(engine)
Session = sessionmaker()
session = Session(bind=engine)

session.query(Bar).join(Foo).all()
```

**Comment by CaselIT** [comment]
I think this is uncommon enough that the solution could be to qualify the schema in both tables

**Comment by zzzeek** [comment]
good news, the behavior can be reproduced with any schema name, it's just the two tables in same schema that have the problem, which eases testing burden.   can target this sooner as a result.

**Comment by zzzeek** [comment]
this is a weird one because this issue has existed literally for 16 years, and while we have had a lot of funny name-conflict kinds of issues reported, never this one.   so we would assume this is *extremely* unlikely.

but from there it's all somewhat bad news.  The workaround of schema-qualifying the table is not database agnostic, because the "default schema name" is different for every database.   The upcoming gerrit illustrates a fix for this problem, which adds a small expense to the compilation of statements in order to track these names up front to identfy conflicts; we have to add this as a separate step because we render columns clauses and WHERE clauses before we render FROM clauses.    We do already have a scan for "FROM" objects up front for SELECT / UPDATE / DELETE but it has to traverse joins for this; it's negligible overhead and it's cached.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**track item schema names to identify name collisions w/ default schema** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3412

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**track item schema names to identify name collisions w/ default schema** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3413

**Comment by zzzeek** [comment]
the overhead is really small but the ratio of CPU cycles to actual need is still going to be extremely massive

**Comment by zzzeek** [comment]
alrighty:

works for PG, MySQL and SQLite.

SQL Server: "sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]The objects "test_schema.some_table" and "some_table" in the FROM clause have the same exposed names. Use correlation names to distinguish them. (1013) (SQLExecDirectW)')"   forget it.   we're not doing that

Oracle: it's having some problem creating the tables, need to check if Oracle has a restriction on cross-schema FKs which it shouldnt

**Comment by zzzeek** [comment]
don't know the syntax for Oracle because I dont know what the "implicit" schema name is.  the default schema name is the username for that DB but we can't qualify with that.

so for now this is a fix for the OSS backends only, Oracle/SQL Server are excluded.  PostgreSQL is the only database where people really use schemas a lot.

**Comment by zzzeek** [comment]
well anyway, SQL Server's error message leads us to the other workaround here, which is just use an alias:

```py
f1 = aliased(Foo)

session.query(Bar).join(f1).all()
```

automatically aliasing that is a huge rabbit hole that we've been actually trying to pull out of in 2.0.

overall the best fix for this issue is to just not name your tables that way.

**Comment by zzzeek** [comment]
oh the fix also won't work reliably for PostgreSQL if you have multiple entries in search_path and the table is not against the first entry.   we get search_path from current_schema().  "current_schema returns the name of the schema that is first in the search path (or a null value if the search path is empty). This is the schema that will be used for any tables or other named objects that are created without specifying a target schema."

**Comment by zzzeek** [comment]
to add automatic aliasing into the compiler, rather than at the SQL construction level which is where we've historically done this (the whole adapt() thing), is somewhat doable but it would add a burden to all table rendering everywhere, that this additional context has to be passed through and checked in the same way we do for columns etc., it would be all over the place.  doesn't feel worth it yet though it would be more consistent for how we alias same-named columns.

**Comment by DanCardin** [comment]
For what it's worth, we went to go qualify it first. Although I think we were qualifying the foreign key, i dont recall if we also qualified the table, i can try to check later. But we noticed a similar issue to https://stackoverflow.com/questions/53523529/alembic-revision-autogenerate-produces-redundant-foreign-key-migrations, wherein alembic would start autogenerating a drop/create index statement that you couldn't resolve.

**Comment by zzzeek** [comment]
the alembic thing is a completely different issue and they are needing to configure their autogenerate correctly, that has nothing to do with the issue here of a statement with two same-named tables.

Since the schema qualify fix does not work on SQL Server or Oracle and probably other database, and additionally wont work with PostgreSQL multiple search path tokens, and also that we do similar aliasing with columns in any case, I think it's more appropriate that this uses an anomized alias name in the SQL statement as we can in fact do that here now that I looked.   the one thing I can see going wrong is if we have an alias name like "mytable_1" and there's also a table named "mytable_1" that's used in the statement explicitly, we aren't checking for that right now, but in fact that potential bug isn't new at all as that would already happen with any anonymous alias() construct anyway.

the bad news here is that I think this should be targeted at 2.0 and not 1.4 as 1.4 is already up to 1.4.29 and there's a chance this behavioral change will cause regressions.  so for the time being you'll need to stick with workarounds of using "public" schema or using aliases for that table.

**Comment by DanCardin** [comment]
As suggested, the only update I make to the MCVE is:
```python
class Bar(Base):
    __tablename__ = "foo"
    __table_args__ = dict(schema="public")
```

Can you explain what's wrong with the following setup then? (and perhaps, i should bring this to alembic, but it's related to this overall issue regardless, i think)

I just quickly ran `alembic init` against this, with just 2 changes:
* update the alembic.ini to point at the database
* update env.py to set `context.configure(connection=connection, target_metadata=target_metadata, include_schemas=True)`

First revision:
```
def upgrade():
    op.execute("create schema foo") # manually added this, obviously
    op.create_table("foo", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id"), schema="foo")
    op.create_table(
        "foo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["foo.foo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
```
looks great!

from then on, every subsequent autogenerate will generate:
```
def upgrade():
    op.drop_constraint('foo_id_fkey', 'foo', type_='foreignkey')
    op.create_foreign_key(None, 'foo', 'foo', ['id'], ['id'], source_schema='public', referent_schema='foo')
```

**Comment by zzzeek** [comment]
OK the problem with Alembic and "public" is because of how SQLAlchemy implements table reflection, where it considers the default schema on the database connection, in this case the value of `current_schema()` which is `public`, to be special .   so when tables are reflected that have foreign keys to other tables in "public", things can get confusing.  I've recently updated the docs to be extremely in-depth on this issue which you can see here: https://docs.sqlalchemy.org/en/14/core/reflection.html#interaction-of-schema-qualified-reflection-with-the-default-schema  .

now if your alembic setup is working fine, then that's great, this is only autogenerate, it's not something you run in "production".

I would add that another way to get the "public" schema in your application without it being in your table metadata is to use the [schema_translate_map](https://docs.sqlalchemy.org/en/14/core/connections.html#schema-translating) feature, and in fact you might like this a lot better because it's essentially an engine option.  We can write your program above as:

```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm.session import sessionmaker

Base = declarative_base()


class Foo(Base):
    __tablename__ = "foo"
    __table_args__ = dict(schema="foo")

    id = Column(Integer, primary_key=True)


class Bar(Base):
    __tablename__ = "foo"

    id = Column(ForeignKey("foo.foo.id"), primary_key=True)

    foo = relationship("Foo", uselist=False)


engine = create_engine(
    "postgresql://scott:tiger@localhost/test",
    echo="debug",
    execution_options={"schema_translate_map": {None: "public"}},
)
with engine.begin() as conn:
    conn.execute(text("drop schema if exists foo cascade"))
    conn.execute(text("create schema foo"))

Base.metadata.create_all(engine)
Session = sessionmaker()
session = Session(bind=engine)

session.query(Bar).join(Foo).all()
```

I think that's likely your best option here, that way you can change that schema name if you wanted to run on another kind of database or schema structure, and you also can use Alembic in plain vanilla mode without the chance of foreign key constraints coming out wrong.

**Comment by DanCardin** [comment]
We run [pytest-alembic](https://github.com/schireson/pytest-alembic) which, for better or worse, asserts that our autogenerate remains empty

But can confirm that `schema_translate_map` at least seems to work with the test case, including appeasing alembic's autogenerate. So that seems like the solution for now, thanks!

**Comment by zzzeek** [comment]
> We run [pytest-alembic](https://github.com/schireson/pytest-alembic) which, for better or worse, asserts that our autogenerate remains empty (plus it'd otherwise be an annoyance we'd have to ignore/remove every time)

it's gotten as far as a legit pytest plugin now huh.   a cautionary tale to anyone who wants to write some code that will "save some typing for developers" :)

> 
> But can confirm that `schema_translate_map` at least seems to work with the test case, including appeasing alembic's autogenerate. So that seems like the solution for now, thanks!

ok great.  schema translate map has been a tricky feature to get right so let me know if it screws anything up
