### ISSUE TITLE
ensure sessionmaker is generic with returned session type for 2.0

### ISSUE THREAD

**Issue by devRMA** [sqlalchemy/sqlalchemy#7656]
### Describe the bug

I'm not able to statically type my code that returns a sessionmaker

### To Reproduce

```python
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession
from sqlalchemy.orm import sessionmaker

def session_factory(engine: AsyncEngine) -> sessionmaker[AsyncSession]:
    return sessionmaker(engine, class_=AsyncSession)

def foo(session: sessionmaker[AsyncSession]):
    ...
```

### Error

```python
Traceback (most recent call last):
  File "issue.py", line 4, in <module>
    def session_factory(engine: AsyncEngine) -> sessionmaker[AsyncSession]:
TypeError: 'type' object is not subscriptable
``` 

### Versions

- OS: Linux (Manjaro)
- Python: 3.10.2
- SQLAlchemy: 1.4.29
- Database: PostgreSQL 14.1
- DBAPI: Asyncpg 0.25.0

### Additional context

I'm using the mypy plugin, and I think the error occurs because in the [plugin](https://github.com/sqlalchemy/sqlalchemy2-stubs/blob/main/sqlalchemy-stubs/orm/session.pyi#L481) the class was typed inheriting from Generic, allowing the use of ``sessionmaker[AsyncSession]`` but in the [code](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/orm/session.py#L3803) there is no this inheritance.

I would like to know if there's a way I can do the typing in my code, or if I'll only be able to, when the sessionmaker class does the Generic inheritance

**Comment by zzzeek** [comment]
its news to me that sessionmaker() was typed as generic.   PRs welcome against the 1.4 branch, or we will get to this in 2.0 which will not use the stubs.  a 1.4 PR can't use Generic since it supports Python 2, it can only use ``__class_getitem__``.

**Comment by devRMA** [comment]
I got a way to do the type hinting without getting error.
This was my solution:
```py
from typing import TYPE_CHECKING, TypeAlias
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession
from sqlalchemy.orm import sessionmaker

if TYPE_CHECKING:
    TSession: TypeAlias = sessionmaker[AsyncSession]
else:
    # anything that doesn't raise a exception
    TSession: TypeAlias = AsyncSession


def session_factory(engine: AsyncEngine) -> TSession:
    return sessionmaker(engine, class_=AsyncSession)


def foo(session: TSession):
    ...
```

**Comment by AlexanderPodorov** [comment]
@devRMA , I've faced with the same issue.
And I solved it by adding:
```python
from __future__ import annotations
```
I have no idea why it solves the problem.

**Comment by zzzeek** [comment]
yeah that's because the code that says `-> sessionmaker[AsyncSession]:` is not run at all when the Python interpreter runs.     Everyone should have `from __future__ import annotations` in all their Python files as it will be standard I think in Python 3.11 and it significantly reduces the amount of work the interpreter does on startup.

**Comment by AlexanderPodorov** [comment]
@zzzeek , thank you for all your work around SQLAlchemy and Alembic!
BTW, it's declared as generic in `sqlalchemy2-stubs`:
```python
class sessionmaker(_SessionClassMethods, Generic[_TSessionMakerType]):
```

**Comment by zzzeek** [comment]
as there was no way for the `sessionmaker.begin()` method to become async for the AsyncSession, 2.0 now has it's own [async_sessionmaker](https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html?highlight=async_sessionmaker#sqlalchemy.ext.asyncio.async_sessionmaker) class that is used for asyncio, mostly solving the issue here.

however, as sessionmaker /async_sessionmaker do allow for a class to be passed in, we should still make these two classes generic, right now it's hardcoded on the "class_" attribute.

**Comment by zzzeek** [comment]
also AsyncSession is not a subclass of Session so that was another awkward thing about using sessionmaker

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**establish sessionmaker and async_sessionmaker as generic** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3868
