### ISSUE TITLE
Docs: AsyncSession proxy example is confusing

### ISSUE THREAD

**Issue by dimaqq** [sqlalchemy/sqlalchemy#7671]
### Describe the bug

Docs at https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#using-asyncio-scoped-session

```py
from sqlalchemy.ext.asyncio import AsyncSession

async_session_factory = sessionmaker(some_async_engine, class_=_AsyncSession)
# -------------------------------------------------------------^^^^^^^^^^^^^
# what is **_A** _AsyncSession ?

AsyncSession = async_scoped_session(async_session_factory, scopefunc=current_task)
# ^^^^^^^^^^----
# is the import shadowed now?

some_async_session = AsyncSession()
```

Was the intention to `import A as _A`?

Or is the whole point that once the "task scope" is set up, the global, importable `AsyncSession` can be used directly?

### To Reproduce

```python
Docs only
```

### Error

Docs only

### Versions

Docs for v 1.4

**Comment by dimaqq** [comment]
The intention is clear then.

It’s probably not the best ti recommend to shadow a library api name though, is it?

**Comment by zzzeek** [comment]
sure, I dont really like "scoped session" at all very much in any case.   

if we change the convention here we have to change it [here](https://docs.sqlalchemy.org/en/14/orm/contextual.html?highlight=scoped_session#unitofwork-contextual) also , because Session is also a SQLAlchemy name.

suggestions / PRs ?
