### ISSUE TITLE
emit a warning for returning + executemany, take driver into account, etc.

### ISSUE THREAD

**Issue by Apakottur** [sqlalchemy/sqlalchemy#7907]
### Describe the bug

I am unable to get any results from the `RETURNING` clause of postgres when using bulk inserts with SQLA core.
I am using the `asyncpg` driver.

I was following the [examples in the documentation](https://docs.sqlalchemy.org/en/14/tutorial/data_insert.html#insert-usually-generates-the-values-clause-automatically) when I encountered the issue.

### To Reproduce
The following works:

```python
result = await session.execute(
    insert(Actor)
    .values(
        [
            {"id": 1, "name": "first"},
            {"id": 2, "name": "second"},
        ]
    )
    .returning(Actor.id),
)
assert result.scalars().all() == [1, 2]
```

But the following doesn't:
```python
result = await session.execute(
    insert(Actor).returning(Actor.id),
    [
        {"id": 3, "name": "first"},
        {"id": 4, "name": "second"},
    ],
)
assert result.scalars().all() == [3, 4]  # Fails!
```

The resulting DB queries seem to be equivalent. The latter is the syntax used in the docs, but maybe I am missing something?

### Error

```sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.```

### Versions

- OS: Ubuntu 22.04
- Python: 3.10.3
- SQLAlchemy: 1.4.34
- Database: Postgres
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): postgresql+asyncpg

### Additional context

The full reproducible example can be found in:
https://gist.github.com/Apakottur/38cc038bfbf37563bcea33aab1dbbea7

**Comment by zzzeek** [comment]
this is expected.   I agree it's difficult to make clear why though, and perhaps this should be raising an error, though it has not done so for many years.

Basically if you do this with a DBAPI:

```py
   cursor.executemany(
        "INSERT INTO table (id) VALUES (%(id)s) RETURNING id",
        [{"id": 1}, {"id": 2}, {"id": 3}]
   )
   rows = cursor.fetchall()
```

you will get nothing back.  This is because executemany() does not define any return value.  There is in fact no DBAPI that supports rows being returned after cursor.executemany.     The difference in the two examples you have is that one of them is using a single INSERT statement executed just once, and the other is using an INSERT statement executed multiple times, once for each parameter set.  

asyncpg is not a DBAPI but the method we use here for asyncpg is [executemany()](https://magicstack.github.io/asyncpg/current/api/index.html#asyncpg.connection.Connection.executemany), where we can see, "This method discards the results of the operations." 

So, that is the situation.  we can at least make this emit a warning when we know that returning is present and executemany is used.  Though it gets a little tricky at the moment because right now for just **one** particular driver (psycopg2) we do have an "execution helper" that is rewriting an INSERT to be in the single VALUES form, gathering up the results, and returning them all in a result.  This is currently a special case that was discussed most recently in the change notes at https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#orm-batch-inserts-with-psycopg2-now-batch-statements-with-returning-in-most-cases .

There was a tentative plan to generalize this behavior to the other drivers including asyncpg, but my most recent thinking has been that we should keep the above pattern explicit as I wrote at https://github.com/sqlalchemy/sqlalchemy/issues/6047#issuecomment-1081968916 .

I think we likely should see if we can add a warning for executemany() + returning but otherwise allow it to pass.

**Comment by Apakottur** [comment]
Thanks for the thorough answer.

Overall I am getting the impression that there's only downsides to using `executemany` when `.values` is applicable.

In our case we switched to always using `insert.values` and `insert.values.returning` for bulk operations, which seems to work faster and lets us retrieve the results of `RETURNING`.

**Comment by zzzeek** [comment]
as it turns out the majority of work for 2.0 besides typing are things involving RETURNING.   so this is added to the list

**Comment by zzzeek** [comment]
also update that we've gone with having executemany() style exections rewrite themselves into INSERT.. VALUES () () () so basically every backend other than plain mysql will support RETURNING with executemany.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**implement batched INSERT..VALUES () () for executemany** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4001

**Comment by zzzeek** [comment]
so short answer here is your original example will work in both forms now, as the ORM will use the new "insertmanyvalues", as long as you aren't using MySQL.   But additionally, if you were on a dialect that supported RETURNING but not the "insertmanyvalues" part, the error looks like: "sqlalchemy.exc.InvalidRequestError: Can't use explicit RETURNING for bulk INSERT operation with XYZ backend; executemany is not supported with RETURNING".   so should be covered

**Comment by FyZzyss** [comment]
https://github.com/MagicStack/asyncpg/issues/137 may be this can help?

**Comment by zzzeek** [comment]
> [MagicStack/asyncpg#137](https://github.com/MagicStack/asyncpg/issues/137) may be this can help? It seems that we need to use `.fetch` instead `executemany`

that's more or less the same thing we are doing now, it's just they are using a more awkward syntax (SELECT unnest).  We're good on this one.
