### ISSUE TITLE
convenience "multi" selector for Table.c ?  

### ISSUE THREAD

**Issue by frbelotto** [sqlalchemy/sqlalchemy#8285]
### Describe the use case

When executing a select() method selecting specific columns, choosing several columns is not really "fast". You must specify the table_name.c.Column_name several times in a single select.

I wonder if wouldn't be able/capable of running a multiple column select fast by inserting a list of column

### Databases / Backends / Drivers targeted

Any compatible?

### Example Use

`select(table_name.column['a','b','c'])`
Instead of 
`select(table_name.c.a, table_name.c.b, table_name.c.c)`
for example

### Additional context

I´ve searched across several docs trying to really understand a easier way to select several columns, but unsuccessful.
I am sorry if this is not the right way to ask for this or if I´ve misunderstood any docs regarding this situation.

Best regards,

**Comment by zzzeek** [comment]
interesting idea for a use pattern we've had since 2005.

note that `select(table_name.column['a','b','c'])` is not valid Python syntax, so that wouldn't work.

we can certainly add a method to ColumnCollection like  ``mytable.c.cols('a', 'b', 'c')`` or even make ColumnCollection a callable, where it would be ``mytable.c('a', 'b', 'c')``.

we've gone for 17 years without another reason to add ``__call__()`` to ColumnCollection so might not be that risky.

alternatively we could add just another accessor to FromClause, but "columns" is the best name and that's already the ColumnCollection.   points again to adding ``__call__()``.

**Comment by zzzeek** [comment]
cc @CaselIT @jvanasco thoughts?

**Comment by zzzeek** [comment]
oh plus it would also have to be expanded in some way - if it just returned a Tuple, then you'd need to say

```
select(*table_name.columns('a','b', 'c'))
```

otherwise, it would need to return some new object that's similar to a Bundle in the ORM that expands out to those three columns, which becomes a much bigger deal.

**Comment by frbelotto** [comment]
> interesting idea for a use pattern we've had since 2005.
> 
> note that `select(table_name.column['a','b','c'])` is not valid Python syntax, so that wouldn't work.`.

Sorry if I misunderstood something, but what do you mean of not valid in Python syntax?

I got this ideia from some select that I use like the statement bellow:
`
stmt = select (chicago_schools.columns['Name of School'], chicago_schools.columns['Location']).where(chicago_schools.columns['Name of School'].contains('Charles')).limit(10)`

Would so much easier and cleaner if i could avoid repeating the "chicago_schools." over and over again lol.

**Comment by zzzeek** [comment]
> > interesting idea for a use pattern we've had since 2005.
> > note that `select(table_name.column['a','b','c'])` is not valid Python syntax, so that wouldn't work.`.
> 
> Sorry if I misunderstood something, but what do you mean of not valid in Python syntax?

oh my mistake, apparently that sends a tuple onto `__getitem__`, so sure, possibly a better place to put it as these are strings.

> 
> I got this ideia from some select that I use like the statement bellow: ` stmt = select (chicago_schools.columns['Name of School'], chicago_schools.columns['Location']).where(chicago_schools.columns['Name of School'].contains('Charles')).limit(10)`
> 
> Would so much easier and cleaner if i could avoid repeating the "chicago_schools." over and over again lol. Obs: I don´t think that this easy way would be applied to "where" or other kind of clauses. But at select it would be ok.

most people use the ORM where none of this syntax would apply and also people assign table.c to a variable, so you could say `select(x.a, x.b, x.c)`.

**Comment by zzzeek** [comment]
anyway the syntax `t.c['a', 'b', 'c']` should return an object that is mostly itself like a ColumnCollection (preferably directly a ColumnCollection subclass), which already behaves like a tuple in 1.4 (includes iterator delivering the columns, integer indexed access).   the given columns would be transferred to its namespace, that is, with `x = t.c['a', 'b', 'c']` one can access  `x.a;  x.b; x.c`.  

finally it would somehow have to expand itself when passed to a select() or other places in some way, or deliver itself in such a way that it's treated like a Table.  it wouldn't be able to support typing, the same way `select(table)` doesn't give you typing support either.   that is it mostly should act like Table, which implies maybe it is itself a selectable of some kind.   this also suggests just saying `select(table.c)` should act like saying `select(table)` also, which instead implies maybe all the places that we look for "selectables" in column lists we also look for "column collection thing".

the first part is simple the second part requires changing code in a lot of places and adding a lot of tests, the kind of code changes that dont get tested much for many years because nobody knows about the feature.  this feature is unlikely to be widely used because nobody has asked for it before.

**Comment by CaselIT** [comment]
> cc @CaselIT @jvanasco thoughts?

Note that the orm buntle works also with core and it seems to mostly do what the seek, so maybe it could be re-used for this.
Otherwise creating a new construct is probably not worth it, like you mentioned

**Comment by jvanasco** [comment]
> most people use the ORM where none of this syntax would apply and also people assign table.c to a variable, so you could say select(x.a, x.b, x.c).

I actually avoid this design pattern and the goal of this PR as much as possible.  I think 10 years ago I would have loved this as a feature, today I am the opposite.

While it's useful/agile in small temporal projects, I find it ends up being a maintenance nightmare in larger or long-maintained projects, as it requires a lot more work to identify and differentiate columns when the schema changes.

**Comment by frbelotto** [comment]
Got it. It seems not worth to work on.
Thanks anyway.

I am using sqla just as a thin abstraction layer of sql, that why I choose not to try the ORM.

I am closing it now.

**Comment by frbelotto** [comment]
.

**Comment by CaselIT** [comment]
note that if we get this "for free" by reusing bundle it could be something to consider, so maybe it could stay open.
@zzzeek any reason why bundle would not work?

**Comment by zzzeek** [comment]
I had a lot of reasons why bundle would not work and they all seem to be incorrect :)   amazingly it works in Core completely, and even gets the correct column descriptions, looks like I must have added functionality for all of this to Core.

I still wonder if `table.c['a', 'b', 'c']` should return an object that is directly the "c" collection already, but it really doesn't matter since people just want to pass this through to `select()`.

I would propose we make a Core-only superclass for Bundle that does not include a "name" field, and in an ORM context would not produce "nesting" in the result set (ah that still requires some new code in orm context).

certainly though I think the idea fills in a bit of an empty spot in the API still.

**Comment by zzzeek** [comment]
```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import select
from sqlalchemy import Table
from sqlalchemy.orm import Bundle

t = Table(
    "t",
    MetaData(),
    Column("a", Integer),
    Column("b", Integer),
    Column("c", Integer),
)

b = Bundle("mybundle", t.c.a, t.c.b, t.c.c)

stmt = select(b)
print(stmt)

# it gets all the correct result columns somehow
print(stmt.compile()._result_columns)

e = create_engine("sqlite://", echo="debug")
t.create(e)

with e.connect() as conn:
    result = conn.execute(stmt)
    print(result.keys())

```

**Comment by CaselIT** [comment]
Suggestion on what to call the core bundle? `ColumnBundle`?

**Comment by zzzeek** [comment]
the "bundle" part of it implies the way the ORM returns it as a nested result, so I wouldnt want the word "bundle" in it.

i just pdbed a little to see how the above works, and we can't use that implementation as is; the Bundle object includes ORM annotations so the reason why the SELECT we see looks correct is because full blown ORM compilation just happened and created a new select() object with the individual columns.   for Core only, that can't happen, so we are back to the beginning where this would be a new thing that has to be created from scratch.

**Comment by zzzeek** [comment]
I have a feeling everything here already works, one moment

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**implement tuple-slices from .c collections** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4011

**Comment by frbelotto** [comment]
Mike,
Just a comment from where my question really started.

I have Sqla codes where I use table.c.columname, but other I use table.column['column_name'].

That were the case where I thought that, that a list, why not pass several itens together?

**Comment by zzzeek** [comment]
yeah I know!

**Comment by zzzeek** [comment]
this was a great idea and you should know it is **extremely** unusual we get ideas that we just put right in like this, good call.

**Comment by frbelotto** [comment]
Thanks man

**Comment by zzzeek** [comment]
somehow we didnt add slice access here, which is very strange, doing that now.

**Comment by CaselIT** [comment]
I don't remember, does the `.c` collection support int index access?

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**support slice access for .c** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4580

**Comment by zzzeek** [comment]
> I don't remember, does the `.c` collection support int index access?

yeah big time in 2.0
