### ISSUE TITLE
Incorrect documentation for pymssql dialect

### ISSUE THREAD

**Issue by cwegener** [sqlalchemy/sqlalchemy#8337]
### Describe the bug

The current SQLAlchemy documentation website for version 1.4 has incorrect information about the maintainer status of the `pymssql` project.

The documentation reads:
> pymssql is currently unmaintained

This is not correct.  `pymssql` is fully maintained (in fact it was never unmaintained, there simply have been public discussion about the discontinuation of the project, but that never came to be) [source](https://github.com/pymssql/pymssql/issues/668)

Quite to the contrary, Randy the long-time maintainer was very *opposed* to the project becoming unmaintained as expressed in the above Github discussion, hence he floated the idea of discontinuing the project in order to *prevent* it from becoming unmaintained!

### To Reproduce

```python
Go to https://docs.sqlalchemy.org/en/14/dialects/mssql.html#module-sqlalchemy.dialects.mssql.pymssql and read the following paragraph:

> Modern versions of this driver worked very well with SQL Server and FreeTDS from Linux and were highly recommended. However, pymssql is currently unmaintained and has fallen behind the progress of the Microsoft ODBC driver in its support for newer features of SQL Server. The latest official release of pymssql at the time of this document is version 2.1.4 (August, 2018) and it lacks support for[...]

Then go to https://github.com/pymssql/pymssql/issues/668 and read the discussion thread.
```

### Error

> pymssql is currently unmaintained

### Versions

- OS: Any
- Python: Any
- SQLAlchemy: 1.4
- Database: SQL Server
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pymssql

**Comment by zzzeek** [comment]
no need for an issue, please send a PR, thanks.

**Comment by zzzeek** [comment]
> Quite to the contrary, Randy the long-time maintainer was very _opposed_ to the project becoming unmaintained as expressed in the above Github discussion, hence he floated the idea of discontinuing the project in order to _prevent_ it from becoming unmaintained!

Sure, I was in those discussions, but as far as the term "unmaintained", Randy did not in fact "discontinue" the project and he very clearly had little to no resources to attend to it, it continued to be available for download, people continued using it, and the project did not see a release for two years.     So the documentation was accurate at that time that the project was effectively, if not in actuality, unmaintained.   The paragraph in question just to be cautious includes an "at the time of this writing, August, 2018".   Also I'm skeptical of what "discontinued" means anyway, unless he means removing it from pypi which I think would have been highly unethical considering the widespread production use of this library.

that said, in 2020 it looks like releases started up again, so that's great, thanks for the heads up.
