### ISSUE TITLE
change URL documentation  / error message to no longer refer to URLs as RFC1738, only "generally similar to RFC1738 with the following exceptions"

### ISSUE THREAD

**Issue by wesley-smith** [sqlalchemy/sqlalchemy#8519]
### Describe the bug

RFC 1738 [defines](https://datatracker.ietf.org/doc/html/rfc1738#section-5) the syntax for a valid URL scheme as:

```
; the scheme is in lower case; interpreters should use case-ignore
scheme         = 1*[ lowalpha | digit | "+" | "-" | "." ]
```

The SQLAlchemy URL [regex](https://github.com/sqlalchemy/sqlalchemy/blob/de173b600b0d3747bcf1941e3027598c66da33ac/lib/sqlalchemy/engine/url.py#L838), on the other hand, searches for the character set: `[ lowalpha | digit | "+" | "_" ]`. This differs from the standard by the inclusion of the `_` character and exclusion of the `-` and `.` characters from the allowed set.

### To Reproduce

```python
rfc1738_url = 'some-scheme://user:pass@host/path'
sqla_url = 'some_scheme://user:pass@host/path'

# Comparison to urlparse as a standard-compliant reference implementation
from urllib.parse import urlparse
urlparse(rfc1738_url)
# ParseResult(scheme='some-scheme', netloc='user:pass@host', path='/path', params='', query='', fragment='')
urlparse(sqla_url)
# parsing fails due to the '_' in the scheme
# ParseResult(scheme='', netloc='', path='some_scheme://user:pass@host/path', params='', query='', fragment='')

from sqlalchemy.engine.url import make_url
make_url(sqla_url)
# some_scheme://user:***@host/path
make_url(rfc1738_url)
# produces error below
```

### Error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 725, in make_url
    return _parse_rfc1738_args(name_or_url)
  File ".../lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 786, in _parse_rfc1738_args
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'some-scheme://user:pass@host/path'
``` 

### Versions

Encountered in versions:
- Python: 3.6.9, 3.8.10
- SQLAlchemy: 1.3.13, 1.4.41

### Additional context

Our team is attempting to use the `redshift+redshift_connector` dialect as supported by the [`sqlalchemy-redshift` package](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift). We also need our DB URLs to be in a format that can be parsed by other tools such as `urlparse`.

Given the fact that SQLAlchemy's parser supports `_` but not `-`, whereas `urlparse` supports the opposite, we cannot configure our DB URLs today in such a way that will satisfy both tools.

**Comment by CaselIT** [comment]
Hi,

> from the standard by the inclusion of the _ character and exclusion of the - and . characters from the allowed set.

the scheme is resolved to a python module. The characters `-` and `.` are not legal python module names, so sqlalchemy does not accept them. `_` is include since it's legal as a python module name.

Allowing additional character would imply that sqlalchemy would have to guess what's the module name for a particular scheme, and that seems like a worse system, so I don't think this is likely to be fixed. cc @zzzeek

**Comment by zzzeek** [comment]
there's no explicit "_" in the regex for SQLAlchemy's URL parser, it's using `\w` which apparently [matches underscore also](https://docs.python.org/3/library/re.html) however there was no intention behind this.   none of [our included dialects](https://docs.sqlalchemy.org/en/14/dialects/index.html#included-dialects) use underscores or dashes in the driver name and there is precedent that the driver names that are "XYZ Connector" use just one word, no underscores: https://docs.sqlalchemy.org/en/14/dialects/mysql.html#module-sqlalchemy.dialects.mysql.mysqlconnector and mariadbconnector, the latter of which alarmingly seems to be omitted from our current published docs due to a missing autodoc entry, am adding that now.     

so another way this change could be made would be that the sqlalchemy_redshift dialect should use the name "redshiftconnector" instead of "redshift_connector".   I dont think that's a great idea either, but just some background that we don't really have the underscore on this end for that kind of name.

Anyway, the bug report as written is impossible to fix.   We can never lose the "_" from our URL parsing scheme since third party dialects make [wide use](https://docs.sqlalchemy.org/en/14/dialects/index.html#external-dialects) of it, and even if we said that we'd accept dashes and translate them to underscores when we look up modules, there are still likely millions of configuration files that have underscores in their SQLAlchemy URLs as a result.     When we do change anything whatsoever about our URL, it [causes](https://github.com/sqlalchemy/sqlalchemy/issues?q=is%3Aissue+label%3A%22%40+%28or+other+chars%29+in+password%22+) a [debacle](https://github.com/sqlalchemy/sqlalchemy/issues/6083).  So dropping the "_", definitely not worth it.  So SQLAlchemy's URL parsing will always "differ from RFC1738", and if that is the actual issue being reported here, it's a "can't fix".       

Beyond that, it's ambiguous what SQLAlchemy would do with dashes or periods in the "scheme" in any case.  as @CaselIT mentions, these are module names.    Having the regex accept dashes and periods wouldn't actually change the problem you have, the dash is not part of the module name for `redshift_connector`.   Do we come up with a translation system that turns dashes into underscores when looking up module names, and what do we do with periods?    maybe, but why are we doing that?  the underscore can be used directly and this is explicit.  adding implicit, hidden behaviors is usually not a good idea unless there's a good reason for it.

That leaves us with just the additional context provided:

> We also need our DB URLs to be in a format that can be parsed by other tools such as urlparse.

That part.       If I had to solve that problem given that constraint, I would store URLs with dashes only in whatever this "urlparse-only" system is, and then I'd replace calls to `create_engine()` with something equivalent to `create_engine(url.replace("-", "_"))`.   That would be your solution given the constraint you've stated.   

however, I would need to know what the reason is for such a constraint.  SQLAlchemy URLs are meaningful only to SQLAlchemy's create_engine() call, and nothing else.  There's no reason I can think of that they need to be compliant with urlparse().     It's from understanding that where I would be someday saying, "OK, we need to support a dash here that translates to an underscore character".    I wouldn't call that "providing RFC1738 compliance" because full compliance means we just use urlparse() directly. 

Instead, it would be, and this is I believe what's actually being asked for, "ensure any SQLAlchemy URL can be provided in an alternative form that is also parseable by Python's urlparse(), substituting dashes (and periods?) for underscores when determining the module name".     That's the ask.   So i ask, why?

**Comment by CaselIT** [comment]
Thanks for the clarification.
I remain unconvinced that the pro outweigh the cons for this feature, since it's the first time this has been raised.
That said I'm not against it if someone whats to implement it.

**Comment by zzzeek** [comment]
> 
> If you chose to add this support, my thoughts on the proposed translations are as follows. `.` characters could be left as-is and would be expected to resolve to nested modules in a Python package hierarchy. 

that would be a significant implementation detail that I fear would be seen as encouraging of that particular pattern, without any rationale for why URLs should be pointing to nested modules.  The URLs are ultimately based on setuptools entrypoints, and not arbitrary filesystem traversal, so im not really sure that's very feasible.  it would appear to allow only that URL resolution and naming would be more complicated.    


> `-` characters could be changed to `_` to provide the necessary module mapping you mention. 

well again, after many years of doing this, I really don't add *any* arbitrary feature without knowing exactly what problem it intends to solve.    

> Personally I think that is a natural character mapping, although it's unclear to me where the boundary between pre- and post-translation would be defined. I'd think the scheme in that case should always appear un-translated to the user, but the engine would need to translate to find the dialect accordingly.

if implemented, it would just keep the dash in the name and we'd translate to underscore for the setuptools entrypoint name.   implementation is not hard at all here.  it's the "why" part.   If here we say, "dashes were added because someone wanted urlparse() to work".   Well from there, and this has already happened, people then ask, "SQLAlchemy should also accept URLs in the identical form that are passed to [libpq connection uris](https://www.postgresql.org/docs/current/libpq-connect.html#id-1.7.3.8.3.6)", including their particular means of multi-host configuration (they describe their URI format as "URIs generally follow [RFC 3986](https://tools.ietf.org/html/rfc3986), except that multi-host connection strings are allowed as further described below.").   After all, we actually connect to PostgreSQL (whereas we don't connect to https:// websites...) so isn't supporting libpq's syntax *more* of a priority than supporting urlparse?   This is basically where I don't want to go.  We have our URL format, it is now officially **not** RFC1738 , it's our own thing and we really dont want to have to chase after many other formats, of which urlparse is only one.    Adding your dash is not the problem.  It's adding the next half dozen URI/URL pet features that everyone will want, none of which have anything to do with what create_engine() accepts.  While all the while, people can write whatever parser they want and simply provide a completed [URL](https://docs.sqlalchemy.org/en/14/core/engines.html?highlight=url#sqlalchemy.engine.URL) object to create_engine(), and that will work fine.       Like, there is not even any technical barrier to people using any URL format they want.  They just want *us* to do it.   




> 
> Finally, I'll highlight the error message that called my attention to this discrepancy:
> 
> ```
> sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'some-scheme://user:pass@host/path'

By a wide margin I will adjust that error message, there's no need that RFC should be mentioned there.

> ```
> 
> Clearly, that string is an RFC1738 URL. At the very least, the documentation for this excellent tool could be improved by stating that the SQLAlchemy's expected DB URL syntax is different from generic RFC1738 URLs in a few key ways.

absoutely, as we can see in PGs docs they use the phrase "URIs generally follow [RFC 3986](https://tools.ietf.org/html/rfc3986), except that multi-host connection strings are allowed as further described below.".

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**change verbiage stating exact compliance with RFC-1738** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4084

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**change verbiage stating exact compliance with RFC-1738** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4085

**Comment by wesley-smith** [comment]
Thanks all for the support!
