### ISSUE TITLE
Oracle and Limit with Textual Query results in Wrong SQL

### ISSUE THREAD

**Issue by mkmoisen** [sqlalchemy/sqlalchemy#8585]
### Describe the bug

Using Oracle and a `.limit` on a textual query such as `select(text('*')).select_from(text('foo')).limit(10)` results in an incorrect query.

### To Reproduce

```python
from sqlalchemy import select, text
from sqlalchemy.dialects import oracle

sel = select(text('*')).select_from(text('foo')).limit(10)

print(sel.compile(dialect=oracle.dialect()))
```

Results in:

```
SELECT  FROM DUAL
WHERE ROWNUM <= __[POSTCOMPILE_param_1]
```

Another example:

```
sel = select(text('select * from foo')).limit(10)
print(sel.compile(dialect=oracle.dialect()))
```

Results in:

```
SELECT  FROM DUAL
WHERE ROWNUM <= __[POSTCOMPILE_param_1]
```

The above queries work fine on postgresql.

### Error

```
SELECT  FROM DUAL
WHERE ROWNUM <= __[POSTCOMPILE_param_1]
``` 

### Versions

- OS: Windows, Unix
- Python: 3.9
- SQLAlchemy: 1.4.36
- Database: Oracle
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): N/A

**Comment by zzzeek** [comment]
hi - 

this is not exactly a "bug" as a known limitation in the 1.x series of SQLAlchemy, as LIMIT/OFFSET for Oracle are emulated using query rewriting, which is not implemented for arbitrary textual elements as SQLAlchemy cannot interpret these intelligently.  A "fix" for the 1.x series here would only be that an informative exception message is raised in this case, which would be complicated to implement while avoiding false positives so I am "wontfix" on that part.

in 2.x, the Oracle dialect now supports Oracle's FETCH FIRST syntax and your query as written (noting, there is a much better way to write it, see below) will interpret appropriately:

```sql
SELECT * 
FROM foo
 FETCH FIRST __[POSTCOMPILE_param_1] ROWS ONLY
```

For compatibility on all versions, the query to be written in a way that SQLAlchemy can interpret it, which is to use literal_column('*') instead of text() so that SQLAlchemy knows this is a single column expression:

```py
from sqlalchemy import select, text, literal_column
from sqlalchemy.dialects import oracle

stmt = select(literal_column('*')).select_from(text('foo'))
print(stmt.compile(dialect=oracle.dialect()))

stmt = stmt.limit(10)

print(stmt.compile(dialect=oracle.dialect()))

```


the overall issue was fixed in 2.x by #8221.

**Comment by CaselIT** [comment]
Fetch can be used also on 1.4 if your oracle version supports it.
```py
stmp = sa.select(sa.text('*')).select_from(sa.text('foo')).fetch(10)
```
compiles to
```
SELECT *
FROM foo
 FETCH FIRST :param_1 ROWS ONLY
```
