### ISSUE TITLE
Wrong return type when using SQL functions

### ISSUE THREAD

**Issue by emontnemery** [sqlalchemy/sqlalchemy#9127]
### Describe the bug

Type checkers error when using SQL functions in a SELECT, for example when using `COUNT` as in the example below, the inferred type of the column is a `Callable[[Any], int]`, not `int`.

### To Reproduce

```python
class Base(DeclarativeBase):
    ...

class MyTable(Base):
    idx: Mapped[int]

def select_count(session: Session) -> int:
    sel = select(func.count(MyTable.idx))
    res = session.execute(sel).all()
    if res:
        return res[0].count
    return -1
```

### Error

mypy --strict test.py
```
db_schema.py:22: error: Incompatible return value type (got "Callable[[Any], int]", expected "int")  [return-value]
``` 

pyright test.py
```
error: Expression of type "(value: Any) -> int" cannot be assigned to return type "int"
```

### Versions

- OS:
- Python: 3.9
- SQLAlchemy: 2.0.0rc3
- Database:
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by zzzeek** [comment]
So this seems initially like a "wont/cantfix", because first off, we don't have any typing for attributes on `Row` - even though `Row` acts like a named tuple, we can't actually dynamically type a named tuple.   As the docs mention, the best way to get typed members is to [unpack](https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#sql-expression-statement-result-set-typing) :


```py
def select_count(session: Session) -> int:
    sel = select(func.count(MyTable.idx))
    res = session.execute(sel).all()
    if res:
        my_count, = res[0]
    return -1

```

the next issue is that tuples have a "count" method, so we can't dynamically determine that "count" here should be a named element and not the method on tuple.   That's the reason "count" has that problem.  I dont see a way to solve that right now (suggestions always welcome).

finally, this is the part we could fix is to apply return types for all the known types that we implement, like count.   That is, you can do `from sqlalchemy.sql.functions import count` and use that directly and it would know about `int`, but right now it doesn't know that `func.count()` is the same thing.

**Comment by zzzeek** [comment]
OK for specific functions having types from func, I added #9129.

For the issue here, I don't have a fix, other than document a bit more.    Reopen if you have ideas thanks!
