### ISSUE TITLE
After upgrade new objects does not added to session when linked with exists objects

### ISSUE THREAD

**Issue by mrquokka** [sqlalchemy/sqlalchemy#9230]
### Describe the bug

After upgrade from 1.4 version to 2.0.1 - links with exists objects does not add objects to session

### To Reproduce

```python
a = MyCls1()
session.add(a)
session.commit()
a = session.query(MyCls1).first()
b = MyCls2(link = a)
session.commit()
```

### Error

No objects in db

### Versions

- OS:
- Python:
- SQLAlchemy:
- Database:
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by zzzeek** [comment]
hi there -

this issue does not explain what the issue is nor does it illustrate any example, so unfortunately we cannot act upon this request.

please reopen this with a proper [MCVE](http://stackoverflow.com/help/mcve), for examples please see https://github.com/sqlalchemy/sqlalchemy/issues?q=is%3Aissue+label%3A%22great+mcve%22 .

if you are unable to provide an MCVE, please open a [discussion](https://github.com/sqlalchemy/sqlalchemy/discussions).

**Comment by zzzeek** [comment]
you are likely seeing this:  https://docs.sqlalchemy.org/en/20/changelog/migration_14.html#change-5150

add the object to the session

   session.add(b)

**Comment by mrquokka** [comment]
Thanks :( But why? :)

**Comment by zzzeek** [comment]
why...do you need to call .add() or why was the change made?

the explanation at https://docs.sqlalchemy.org/en/20/changelog/migration_14.html#change-5150 illustrates what the change is, and also that we had a lot of confusion over a.b = b adding "a" to the Session unexpectedly.

**Comment by mrquokka** [comment]
> why...do you need to call .add() or why was the change made?
> 
> the explanation at https://docs.sqlalchemy.org/en/20/changelog/migration_14.html#change-5150 illustrates what the change is, and also that we had a lot of confusion over a.b = b adding "a" to the Session unexpectedly.

That's okay, but when already maked big project, need to check all project + scripts that is works normally after upgrade. Anyway thank you for your work)

**Comment by zzzeek** [comment]
there should be warnings for the old behavior when you run SQLAlchemy 1.4 with SQLALCHEMY_WARN_20 turned on
