### ISSUE TITLE
column ordering hint for mapped_column

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9297]
noted in #9294 and now in the whats new notes in 037884edaef8638c7128ad13cc51 , we can add a new indicator to ``mapped_column()`` specifically that tells Declarative how to order columns when creating Table.

Why mapped_column()?  Because this is ORM specific.   Column / Table has no "sorting", the order is the order in which Column objects are placed into the Table.

Propose ``mapped_column.sort_order``, ~~which accepts any object type and uses it to apply ``sorted()``.   Users can specify integers, strings, floats, or any custom Python object that has an ``__lt__()`` method, so that any scheme can be created.~~ which is an int value. By default all columns have the value of 0

Declarative would record this sort order and apply it specifically within the `_setup_table()` method.

**Comment by zzzeek** [comment]
cc @CaselIT

**Comment by CaselIT** [comment]
makes sense to me. Not sure if sort priority would be a better name or not. The proposed sort order is clear enough though.

> Propose mapped_column.sort_order, which accepts any object type and uses it to apply sorted(). Users can specify integers, strings, floats, or any custom Python object that has an __lt__() method, so that any scheme can be created.

I'm not sure we need this complication. I think a plain int can work so we can specify that by default all columns have a value of 0.

Do you have an use case for allowing any type to be there? I think it will complicate things since if an used use in one column `sort_order` then all columns require one, otherwise you get errors like `TypeError: '<' not supported between instances of 'int' and 'NoneType'` and similar

**Comment by zzzeek** [comment]
yeah I guess I wasn't thinking straight, i was thinking more like a function that can look at two columns and would know that A should be before B.   but i think 99% of the time people jut want their primary keys at the top

**Comment by CaselIT** [comment]
Ok, let's go with int and do something more complex if we need to then

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Allow custom sorting of column in the ORM.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4455
