### ISSUE TITLE
warn or load for session.refresh([attrname]) where attrname is lazy loaded

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9298]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9287

warn would be "safer" here but if someone is really putting that attribute name in the list, we can just load it, both approaches illustrated below

```diff
diff --git a/lib/sqlalchemy/orm/strategies.py b/lib/sqlalchemy/orm/strategies.py
index af63b9f6eb..c97ff7e5a9 100644
--- a/lib/sqlalchemy/orm/strategies.py
+++ b/lib/sqlalchemy/orm/strategies.py
@@ -1143,6 +1143,32 @@ class LazyLoader(
     ):
         key = self.key
 
+        # TODO: only warn if session.refresh() were used.  session.refresh()
+        # would need to send through a new boolean "warn_for_not_refreshed".
+        if (
+            context.query._compile_options._only_load_props
+            and self.key in context.query._compile_options._only_load_props
+            # and is_a_session_refresh_operation
+        ):
+
+            # choice A: warn
+            util.warn(f"lazy loader {self} cannot refresh property {self.key}")
+
+            # choice B: load it
+            return self.parent_property._get_strategy(
+                (("lazy", "immediate"),)
+            ).create_row_processor(
+                context,
+                query_entity,
+                path,
+                loadopt,
+                mapper,
+                result,
+                adapter,
+                populators,
+            )
+
+
         if not self.is_class_level or (loadopt and loadopt._extra_criteria):
             # we are not the primary manager for this attribute
             # on this class - set up a

```

**Comment by zzzeek** [comment]
let's load, this will be very useful for the asyncio use case

**Comment by CaselIT** [comment]
makes sense to me. Indeed for asyncio it would make sense to load

**Comment by pankajkumar229** [comment]
I would like to use this method if it can be backported to sqlalchemy 1.4.46. The other method needs some code refactoring that makes the code look ugly for us.

**Comment by CaselIT** [comment]
@zzzeek is it feasible to backport to 1.4?

**Comment by pankajkumar229** [comment]
Hi Mike and Federico, 

Thanks so much for all your help and I am really sorry for all the doubts on the framework. I found the bug in our usage of run_sync. We were somehow using append on a list which we thought was a local variable. But it was actually a class member variable. This caused repeats on the number of arguments. The first one was ('courses', 'courses_taught'). In the second call, the list of argument became ('courses', 'courses_taught', 'courses', 'courses_taught') and kept increasing. This caused run_sync loop to go forever. We have fixed it since and I reverted back to async_scoped_session, things work well. 

We have been doing a large refactor and sometimes running into bugs that are hard to pinpoint. 

We would not be needing this backport.

Many Thanks,

**Comment by zzzeek** [comment]
> @zzzeek is it feasible to backport to 1.4?

from a technical standpoint it's not difficult but behaviorally it's a big change and also would not be consistent with the behavior of refresh() in 1.4.   refresh was highly modified for 2.0.  1.4 should be as behaviorally frozen as possible
