### ISSUE TITLE
`KEY_OBJECTS_ONLY` global variable can be declared as int in resultproxy.pyx

### ISSUE THREAD

**Issue by matusvalo** [sqlalchemy/sqlalchemy#9343]
### Describe the bug

Global variable `KEY_OBJECTS_ONLY` is declared as python variable in  resultproxy.pyx. This causes suboptimal comparison in line: https://github.com/sqlalchemy/sqlalchemy/blob/fc57bafbae9d67b7ce95e26c939ca957c366b0f7/lib/sqlalchemy/cyextension/resultproxy.pyx#L79

This line is translated to following C code:

![image](https://user-images.githubusercontent.com/827060/220471541-f93762d7-eb71-4a47-a95b-67e9a5c6dd23.png)

Declaring the variable as `int` this can be further optimised to simple C comparision.

### SQLAlchemy Version in Use

master

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

3.9

### Operating system

OSX

### To Reproduce

```python
N/A
```

### Error

N/A

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting. I remember I considered it, but I don't remember why I did not actually implement it like that.
Maybe it was to allow setting that value from python?

But then again we import the constant from the cython file here, so it should not be a problem
https://github.com/sqlalchemy/sqlalchemy/blob/fc57bafbae9d67b7ce95e26c939ca957c366b0f7/lib/sqlalchemy/engine/row.py#L35-L42

Feel free to take a look also to the other cython parts to see if you have suggestions, since neither me that originally wrote that code, nor mike that reviewed it are overly expect in cython. Thanks!

**Comment by matusvalo** [comment]
> Maybe it was to allow setting that value from python?

I was considering this option. I am not an expert in internals of SQLAlchemy though. I did just quick grep and I was not able to find any place where this variable is replaced. Is it possible to set it somewhere outside the code of SqlAlchemy (plugin or user code)?

**Comment by sqla-tester** [comment]
**Matus Valo** has proposed a fix for this issue in the **main** branch:

**Declare KEY_OBJECTS_ONLY as cdef variable** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4461

**Comment by CaselIT** [comment]
> > Maybe it was to allow setting that value from python?
> 
> I was considering this option. I am not an expert in internals of SQLAlchemy though. I did just quick grep and I was not able to find any place where this variable is replaced. Is it possible to set it somewhere outside the code of SqlAlchemy (plugin or user code)?

I don't think anyone is changing it to something else, and if they are that's an unsupported usage, since it would break multiple assumptions in sqlalchemy

**Comment by sqla-tester** [comment]
**Matus Valo** has proposed a fix for this issue in the **main** branch:

**Declare KEY_OBJECTS_ONLY as cdef variable** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4461
