### ISSUE TITLE
type conversions break identity map

### ISSUE THREAD

**Issue by nioncode** [sqlalchemy/sqlalchemy#9573]
### Describe the bug

When inserting objects with attributes that do not match the exact type specified in the column (e.g. initializing a `Uuid` column with a `str`), the identity map breaks and you will have multiple instances of the same object in memory that do not sync their changes.

In the attached sample code, it will print `1.1: fail` (because the identity check fails) and `1.2.: fail` (to show that changes to one object does not sync to the other). The rest of the sample code just shows that it works correctly if you either initialize the `Uuid` column with a `UUID` object or if you don't use an `Uuid` column, but a `Text` column instead.

It seems like that as soon as there are type conversions involved, then the identity map breaks.

### SQLAlchemy Version in Use

2.0.4

### DBAPI (i.e. the database driver)

pg8000

### Database Vendor and Major Version

PostgreSQL 14

### Python Version

3.9.13

### Operating system

Linux

### To Reproduce

```python
import uuid

from sqlalchemy import (
    Column,
    Text,
    create_engine,
    String,
    Uuid,
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class Node(Base):
    __tablename__ = "nodes"
    id = Column(String, primary_key=True)
    label = Column(Text)


class NodeUuid(Base):
    __tablename__ = "nodes_uuid"
    id = Column(Uuid, primary_key=True)
    label = Column(Text)


def main():
    engine = create_engine("postgresql+pg8000://postgres@localhost:5432")
    Base.metadata.create_all(bind=engine, checkfirst=True)
    session = Session(bind=engine)

    for existing in session.query(NodeUuid).all():
        session.delete(existing)
        session.commit()
    for existing in session.query(Node).all():
        session.delete(existing)
        session.commit()

    node = NodeUuid(id="0" * 32, label="foo")
    session.add(node)
    session.commit()

    c = session.query(NodeUuid).first()
    assert c.id == node.id
    assert c.label == node.label
    # This will fail.
    if c == node:
        print("1.1: pass")
    else:
        print("1.1: fail")
    node.label = "hello"
    # This will fail.
    if c.label == node.label:
        print("1.2: pass")
    else:
        print("1.2: fail")
    session.delete(node)
    session.commit()

    # Creating the node with id=uuid.UUID() works.
    node = NodeUuid(id=uuid.UUID("0" * 32), label="foo")
    session.add(node)
    session.commit()

    n = session.query(NodeUuid).first()
    assert n.id == node.id
    assert n.label == node.label
    assert n == node
    node.label = "hello"
    assert n.label == node.label
    session.delete(node)
    session.commit()

    # Creating a node with string works.
    node = Node(id="0" * 32, label="foo")
    session.add(node)
    session.commit()

    n = session.query(Node).first()
    assert n.id == node.id
    assert n.label == node.label
    assert n == node
    node.label = "hello"
    assert n.label == node.label
    session.delete(node)
    session.commit()


if __name__ == "__main__":
    main()
```

### Error

```
1.1: fail
1.2: fail
```

**Comment by zzzeek** [comment]
this is normal.  The Uuid datatype in its default configuration should be passed Python uuid objects, not strings.    The docs for Uuid should clarify this as it's not clearly stated.

if you'd like to use string uuids, set the [as_uuid](https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Uuid.params.as_uuid) parameter to False.

**Comment by nioncode** [comment]
I tried this as well, but setting `as_uuid=False` does not fix the initial problem (but it breaks passing in uuid objects so the other tests in the repro fail as well).

This is also not just happening for uuid. The same happens if you have a `Text` column and provide an `int` as initializer. Probably this happens for all types that are coalesced into another type automatically. @zzzeek is this really how this is supposed to work?

It seems like either the initializer should reject invalid types early on or the identity map should be fixed somehow. Otherwise this leads to hard to debug issues and silent bugs.

```python
#!/usr/bin/env python3

from sqlalchemy import (
    Column,
    Text,
    create_engine,
    String,
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class Node(Base):
    __tablename__ = "nodes"
    id = Column(Text, primary_key=True)
    label = Column(Text)


def main():
    engine = create_engine("postgresql+pg8000://postgres@localhost:5432")
    Base.metadata.create_all(bind=engine, checkfirst=True)
    session = Session(bind=engine)

    for existing in session.query(Node).all():
        session.delete(existing)
        session.commit()

    node = Node(id=1, label="foo")
    session.add(node)
    session.commit()

    c = session.query(Node).first()
    assert c.id == node.id
    assert c.label == node.label
    # This will fail.
    if c == node:
        print("1.1: pass")
    else:
        print("1.1: fail")
    node.label = "hello"
    # This will fail.
    if c.label == node.label:
        print("1.2: pass")
    else:
        print("1.2: fail")
    session.delete(node)
    session.commit()

    # Creating a node with string works.
    node = Node(id="1", label="foo")
    session.add(node)
    session.commit()

    n = session.query(Node).first()
    assert n.id == node.id
    assert n.label == node.label
    assert n == node
    node.label = "hello"
    assert n.label == node.label
    session.delete(node)
    session.commit()


if __name__ == "__main__":
    main()
```

**Comment by zzzeek** [comment]
> I tried this as well, but setting `as_uuid=False` does not fix the initial problem (but it breaks passing in uuid objects so the other tests in the repro fail as well).

you have to work with one type or the other, ORM objects expect a fully consistent Python type for attributes whether they are set from the Python side or they are delivered from the database side.   This is not that unusual of a requirement.

 
> This is also not just happening for uuid. The same happens if you have a `Text` column and provide an `int` as initializer. 

Why would you use a `Text` column with an integer value?    There's no valid reason to do something like that and most databases would reject it.

> Probably this happens for all types that are coalesced into another type automatically. 

types that "coalesce" into other types do this so that the value passed to the database is of a particular type expected by the database.   those types will then include a "result processor" that converts back to the Python-side type.    So the Python side sees only one datatype, the database sees only another.   

> @zzzeek is this really how this is supposed to work?

absolutely!

> It seems like either the initializer should reject invalid types early on 

The initializer itself in the ORM is under your own control, and you can also use [validates](https://docs.sqlalchemy.org/en/20/orm/mapped_attributes.html#sqlalchemy.orm.validates) rules for specific ORM mapped attributes.  

Otherwise, the type object itself can be made to reject invalid types, which would make the issue apparent here as well as soon as an INSERT occurs.  Some type objects do this while others dont, depends on case.   We haven't had any complaints about UUID datatypes not doing this check but it could be added as an optional feature.


> or the identity map should be fixed somehow. 

The identity map is not "broken".   it's a Python mapping, and uses hash values + `__eq__()` just like any other mapping.   There's no Python dictionary that would report True for `"1" in {1: 'hi'}` unless it itself embedded type conversion functions, which would not be the correct place for such a thing to be happening here.



> Otherwise this leads to hard to debug issues and silent bugs.

point taken for the type-level validation, for most datatypes there's not much controversy but Uuid I can see can be prone to this mistake.

**Comment by nioncode** [comment]
> Why would you use a Text column with an integer value? There's no valid reason to do something like that and most databases would reject it.

I just wanted to check if this only happens to the uuid type to all types. But in practice, the actual values might come from other methods and with python being a not strongly typed language, it might not be immediately clear (to the reader/writer of the source code) what type a variable has the moment it gets used to initialize a table object.

> Otherwise, the type object itself can be made to reject invalid types, which would make the issue apparent here as well as soon as an INSERT occurs. Some type objects do this while others dont, depends on case.

I'm actually surprised that this is the case. I was expecting that there will be some assertions on the passed types and was surprised that I can just pass an `int` to a `Text` column without any errors. Seems like I have to add something like this to all of my fields:
```python
    @validates('id')
    def validate_str_type(self, key, value):
        if not isinstance(value, str):
            raise ValueError(f"{key} must be set to a str, not to {type(value)}")
        return value
```
Is there a reason why SQLAlchemy is not stricter with the accepted types here? It seems weird that you can pass in kind of arbitrary types that are then converted (by the ORM and/or by the database driver and/or by the database itself) and might end up as completely different fields in the database.

I was under the impression that the following will always be true:
```
obj = Table(field=whatever_value)
session.add(obj)
session.commit()
assert session.query(Table).first() == obj
```
But apparently, this will not always be the case. Probably I am just expecting too much and this is perfectly reasonable, but at least this was not clear to me. Is there some description about what kind of guarantees SQLAlchemy gives with regards to types / type conversions / identities and so on? Maybe I just did not find the correct place in the documentation where this is discussed.

**Comment by zzzeek** [comment]
> 
> I just wanted to check if this only happens to the uuid type to all types. But in practice, the actual values might come from other methods and with python being a not strongly typed language, it might not be immediately clear (to the reader/writer of the source code) what type a variable has the moment it gets used to initialize a table object.

Python is a strongly typed language, what you are thinking of is that it's not *statically* typed.     In modern use we are all using pep-484 typings to a greater or lesser degree which can find typing issues like these using static analysis.   I would recommend moving towards type annotations to document and lint the expected types of variables and attributes; SQLAlchemy 2.0 now has very strong support for this.


> I'm actually surprised that this is the case. I was expecting that there will be some assertions on the passed types and was surprised that I can just pass an `int` to a `Text` column without any errors. 

isinstance() checks, like all Python functions, have measurable overhead and if you consider a program that wants to bulk insert 10000 rows with 50 columns each, by not forcing "isinstance()" checks into all the types, since in the vast majority of cases the database backend will reject illegal types in any case, we save half a million function calls for that operation alone.    static type checking is vastly more efficient and self-documenting.


> 
> ```python
>     @validates('id')
>     def validate_str_type(self, key, value):
>         if not isinstance(value, str):
>             raise ValueError(f"{key} must be set to a str, not to {type(value)}")
>         return value
> ```

I probably wouldn't do that.    Add type annotations and use mypy in your CI is a better overall solution.

 
> Is there a reason why SQLAlchemy is not stricter with the accepted types here? 

1. quality databases such as PostgreSQL reject invalid data in any case
2. isinstance() checks are wasteful
3. many users do in fact want the full range of datatypes accepted by the database itself to be allowed, such as the string/uuid issue we see here.

> It seems weird that you can pass in kind of arbitrary types that are then converted (by the ORM and/or by the database driver and/or by the database itself) and might end up as completely different fields in the database.

Datatypes have to work that way, because the backend database as well as the database driver itself often does not support the Python representation of an object directly. There are many examples, including datetime objects for SQLite, UUID objects for most backends, JSON structures, arrays, ENUMs, intervals, for a long time Python Unicode objects had to be converted, this conversion is not "the Python type wrong", it's for the purposes of data marshalling.   The Python side type should be fixed.    Here we are looking at an edge case of a particular datatype that happens to accept two different Python representations, which is not the usual case for most datatypes.


> But apparently, this will not always be the case. Probably I am just expecting too much and this is perfectly reasonable, but at least this was not clear to me. 

As mentioned, this kind of case is somewhat idiosyncratic to the uuid datatype and we would support adding a parameter to add data validation to it.     Datatypes that are subject to this kind of thing like Enum include client-side data validation so it would not be controversial in this case.

Additionally, you can add data validation to any SQLAlchemy type using TypeDecorator, see the recipes at https://docs.sqlalchemy.org/en/20/core/custom_types.html#typedecorator-recipes where you can add simple isinstance() checks to any `process_bind_param()` method.


> Is there some description about what kind of guarantees SQLAlchemy gives with regards to types / type conversions / identities and so on? 

SQLAlchemy types generally don't have guarantees like this, in most cases the backend database rejects invalid types.  Most SQLAlchemy datatypes are pass-through for the performance reasons indicated above.

> 
> EDIT: however, it is still weird that `as_uuid=False` does not work:

for issues like these you want to turn on echo='debug' to see what the database driver is returning:

```
INSERT INTO nodes_uuid (id, label) VALUES (%s, %s::VARCHAR)
2023-03-31 14:23:40,684 INFO sqlalchemy.engine.Engine [generated in 0.00013s] ('00000000000000000000000000000000', 'foo')
2023-03-31 14:23:40,685 INFO sqlalchemy.engine.Engine COMMIT
2023-03-31 14:23:40,687 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-03-31 14:23:40,688 INFO sqlalchemy.engine.Engine SELECT nodes_uuid.id AS nodes_uuid_id, nodes_uuid.label AS nodes_uuid_label 
FROM nodes_uuid 
 LIMIT %s::INTEGER
2023-03-31 14:23:40,688 INFO sqlalchemy.engine.Engine [generated in 0.00011s] (1,)
2023-03-31 14:23:40,689 DEBUG sqlalchemy.engine.Engine Col ('nodes_uuid_id', 'nodes_uuid_label')
2023-03-31 14:23:40,689 DEBUG sqlalchemy.engine.Engine Row ('00000000-0000-0000-0000-000000000000', 'foo')

```

the string representation used for UUID is the str value of the Python uuid object (note this is being returned by pg8000 itself, psycopg2 etc. all do the same thing, this is not SQLAlchemy's decision), which will add the dashes:

```py
>>> str(uuid.UUID('00000000000000000000000000000000'))
'00000000-0000-0000-0000-000000000000'

```


There's really an overarching theme here which is that you want to use the right datatypes for things, despite Python not being intrinsically statically typed; you want to use ints (not strings) with ints, Decimals (not strings) with numerics, datetimes (not strings) with dates, etc., this is normal in the Python world.    pep-484 typing is the general solution to adding static analysis for these typing issues.
