### ISSUE TITLE
Consider extracting a collections package so that sqlalchemy builtin collections can be used in other projects

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9741]
The main things are immutabledict and orderedset, but maybe most of the general collection classes could be moved to this 3rd party package. 

primary motivator are some other sqlalchemy/sqlalchemyorg projects that may benefit from such a package, but other users may more easily adopt them if they were in a separate package

main thing to decide is the name of such a package

**Comment by jvanasco** [comment]
IMHO, I wouldn't want to see a new package of "collections", because that seems too limiting in it's use.

I think it would be better, even if only starting with "collections", to make the package have a name that is more open to various uses of these "basic" elements that can be repurposed for other uses. 

So perhaps something like:

* alchemy_basics
* basic_alchemy

`from alchemy_basics.collections import immutabledict`

or a namespace inspired by these words?

magic sorcery wizardry conjurer diviner enchanter amulets thaumaturgy talisman

**Comment by CaselIT** [comment]
I agree that maybe it's better to have a more general name than just collections.
Keeping in the alchemy theme, we have `alembic`, so why not `crucible`?

There is already a python package called crucible, but it seems unmaintained (last release 2011) so maybe there is the change of getting it https://pypi.org/project/crucible/. The uploader seems to be active on github so we could ask here even https://github.com/tebeka

**Comment by zzzeek** [comment]
crucible sounds too much like Arthur Miller's famous play to me...

**Comment by jvanasco** [comment]
I’m trying to think of other things that alchemists use. “materials” is taken. Wizards have bags and magical sacks. My wife has a lot of crystals.

looking for synonyms isn’t working well, because I’m getting lots of references to “black magic” and “dark arts” which won’t work well for D&I concerns.

**Comment by CaselIT** [comment]
> crucible sounds too much like Arthur Miller's famous play to me...

well that should not cause too much confusion. but as you prefer

Wikipedia has this to say https://en.wikipedia.org/wiki/Category:Alchemical_tools

`pestle` is another option, but it doesn't sound too good :)
`snow_globe` is better, maybe still not great

there is always the option to use the boring `alchemy_tools`/`alchemist_tools` so make it clear it's from sqlalchemy

**Comment by zzzeek** [comment]
personally I dont think trying to come up with clever alchemy names works with this one, but I will defer to the group since this project is kind of...not mine :)

**Comment by zzzeek** [comment]
I'm not opposed to this but mostly it seems like a distraction to the project for the moment and I proposed it moves to "blue sky discussion"

**Comment by CaselIT** [comment]
I agree, there doesn't seem to be much interest to this, so maybe we can just close.

If a use case cames up we can reopen

**Comment by jvanasco** [comment]
Two things:

1- I am willing to immediately do the grunt work on this (packaging, prs, setup GitHub repo) if the idea is amendable

2- the motivation is that many SQLAlchemy classes seem like a glue layer between SqlAlchemy and variations of “collections” or other objects.  I see a utility - especially in testing and mocking - to better generalize these objects and push end-users into adopting these classes even when not using SqlAlchemy.

**Comment by CaselIT** [comment]
That was my initial reasoning as well, but I'm not sure how much of an use case would it be, or interest in something like this.

Overall the main general collections that are general purpose are immutable dict and ordered set. There is also identity set, but I'm not sure how common its usage would be.

Regarding packaging, from a discoverability point of view, maybe having a different package per collection could be an option, so two packages immutabledict and something like orderedset (there is already one packaged called orderedset)

It could probably be moved to bluesky, but I'm not sure how large the use case would be
