### ISSUE TITLE
enum name not transferred in declarative map feature

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9963]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9962

```py
from __future__ import annotations

import enum

import sqlalchemy
from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column


class Status(enum.Enum):
    PENDING = "pending"
    RECEIVED = "received"
    COMPLETED = "completed"


class Base(DeclarativeBase):
    type_annotation_map = {
        Status: sqlalchemy.Enum(
            "pending", "received", "completed", name="esx_status"
        )
    }


class SomeClass(Base):
    __tablename__ = "some_table"

    id: Mapped[int] = mapped_column(primary_key=True)
    status: Mapped[Status]


e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

```

output

    sqlalchemy.exc.CompileError: PostgreSQL ENUM type requires a name.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**default Enum name to None and don't remove given name** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4747

**Comment by Daverball** [comment]
@zzzeek Is it possible this change broke mapping enums derived from `enum.Enum` directly, without adding an explicit entry into the type annotation map? I have been getting the exact error this was trying to avoid since upgrading and it was working fine before as far as I can tell.

Having to add an explicit entry for each enum type seems a bit cumbersome. There's a good chance each enum type will only be used in one table, so if I have to create an entry into the type annotation map, I might as well pass in the `sqlalchemy.Enum` type into `mapped_column`, I just move the code from one place to another.

It also causes circular dependency issues unless the enum definition is moved outside the file that defined the model, which is trying to use the enum, since the base class needs to import the enum and the model needs to import the base class.

**Comment by zzzeek** [comment]
> @zzzeek Is it possible this change broke mapping enums derived from `enum.Enum` directly, without adding an explicit entry into the type annotation map? 

it wasn't planned and we added new tests, the old tests continue to pass, so please create a succinct [MCVE](http://stackoverflow.com/help/mcve) (like the example at the top here) and open a new issue.

> I have been getting the exact error this was trying to avoid since upgrading and it was working fine before as far as I can tell.

strange

> 
> Having to add an explicit entry for each enum type seems a bit cumbersome. 

there is no such requirement, see docs at https://docs.sqlalchemy.org/en/20/orm/declarative_tables.html#using-python-enum-or-pep-586-literal-types-in-the-type-map  , the feature is automatic by default.  the issue here was someone who wanted a specific name for their enum.

**Comment by Daverball** [comment]
It looks like using the `sqlalchemy.Enum` constructor in `mapped_column` fails too if there's no explicit entry in the type annotation map. (unless i set the name manually)

**Comment by Daverball** [comment]
But I will open an issue for this.

**Comment by Daverball** [comment]
It looks like it only affected a specific enum type, here's the issue with the repro: https://github.com/sqlalchemy/sqlalchemy/issues/10030
